### ISSUE TITLE
LYWSD02 Set time

### ISSUE THREAD

**Issue by toben1997** [custom-components/ble_monitor#100]
Is it possible to set the time somehow on the LYWSD02 with home assistant?

**Comment by Ernst79** [comment]
At the moment, no, this is not possible. I’ll leave the issue open, but I don’t expect this to be implemented soon.

**Comment by Magalex2x14** [comment]
The problem echoes #18.
As I wrote there, the possibility of a direct connection to a device at this stage of component development is not realizable but is taken into account during further development. @Ernst79, maybe close it for now?

**Comment by Ernst79** [comment]
Yes, I don’t think we aim to make this happen in the near future. For now, we keep it passive.
