### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tempus2016** [custom-components/ble_monitor#1004]
### What happened?

Trying to add a Xiaomi temperature sensor but I am unable to get it to show correctly.  If I use this Xiaomi BLE integration, it shows me only the signal strength, no other sensors.  If I use the BLE integration from HACS, it shows me a few more sensors but the temp & humidity are minus values.  HA Bluetooth does not pick up the sensors at all.

Sensors: https://www.aliexpress.com/item/1005002012495689.html?spm=a2g0o.order_list.0.0.27d31802vS5dJV

Xiaomi Integration
<img width="1239" alt="Screenshot 2022-09-03 at 13 39 51" src="https://user-images.githubusercontent.com/40920327/188270776-2e29f12c-ad4c-4b3f-aaf3-f97fc3c17a74.png">

BLE Integration (HACS)
<img width="1239" alt="Screenshot 2022-09-03 at 13 39 42" src="https://user-images.githubusercontent.com/40920327/188270783-f5126161-ee7e-433f-9a85-b02f5062916b.png">

**Comment by tempus2016** [comment]
It appears to have started reporting information using the Xaomi integration.  Not sure what changed, but it's working now.

**Comment by Ernst79** [comment]
The xiaomi sensor is quite slow, can take up to 10 minutes, before it is being recognized. The iBeacon sensor is a different sensor, that is not the Xiaomi sensor. Also not that BLE monitor and the HA integration won’t work nicely together, enable active scan in BLE monitor if you want both integrations at the same time.
