### ISSUE TITLE
[Bug]: No module named 'pyric'

### ISSUE THREAD

**Issue by toledobastos** [custom-components/ble_monitor#1005]
### What happened?

After updating Home Assistant Core to 2022.8.6 on Ubuntu the integration no longer works. Refreshing (F5), removing and reinstalling, and reinstalling HACS don't fix the problem. After reinstalling the integration on HACS, rebooting, and trying to add it via Settings > Devices & Services I get the following error:

"This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant."

If I try to configure blm_monitor directly on configuration.yaml I get this error instead:

Configuration invalid! Component error: ble_monitor - No module named 'pyric'

**Comment by Ernst79** [comment]
It looks like it didn’t install the dependency pyric. Pyric is in the manifest.json, so it should be installed automagically during the installation. Try to reinstall ble monitor to see if it was just an accident that it didn’t install pyric, otherwise, try to install it manually.

**Comment by toledobastos** [comment]
Yup that seems to be the case. I tried reinstalling ble monitor a dozen times, to no avail. I also tried to manually install pyric but snaps are read-only, so you can only see what's in /snap/home-assistant-snap/XXX/lib/pythonXXX/site-packages/ but you can't do anything about it.

**Comment by toledobastos** [comment]
Found a workaround if anyone hits this snag. It seems that the snap Python VENV sys.path reads from /root/snap/home-assistant-snap/XXX/.local/lib/pythonXXX/site-packages, so copying pyric from site-packages in my system enviroment to that site-packages did the trick. The problem disappeared altogether.

**Comment by Ernst79** [comment]
Great. Good to hear

**Comment by Ernst79** [comment]
I'm afraid there isn't much I can do on the BLE monitor side. I guess this should be solved in the home-assistant-snap side, isn't it?

**Comment by toledobastos** [comment]
I think so. The integration seems to be working fine on HA Docker. It's the last releases of HA Core on snap that have this problem. The workaround I mentioned above seems to do the trick, but obviously this needs to be addressed in future HA Core releases. I wrote to the snap maintainer and hopefully he'll look into it. You can close this issue seeing it's not caused by the BLE monitor integration.

**Comment by Ernst79** [comment]
OK, thanks. I'll keep an eye on the other issue, if needed we can add it to the FAQ later
