### ISSUE TITLE
Update frequency of HHCCJCY01

### ISSUE THREAD

**Issue by Olen** [custom-components/ble_monitor#101]
I see from the docs that the HHCCJCY01 are updated once a minute.  This also matches what I see in the GUI, where most of the time, the sensors are reported with "last median of 1" (and occasionally "last median of 2".
However, both when using the app, and when dumping the BT packets, i can see that the data is received by my HA-server much more frequently than once a minute.
Is there a reason this integration does not update more frequently?

My main problem is not that it is a slight delay in the data, that is fine, but the problem is that even with "use_median: true" in the config, the graphs are very "spikey" with the default period of 60 seconds, and one single "off" measurement will cause problems. 
I am trying to solve it by using a longer period, but that will of course give even longre delays before changes are detected.  
But since the numbers are coming in more frequently than once a minute, it seems strange that the integration is not reading them.

Here is an example where I have filtered out one single mac address, and just showing the timestamps and service data:

```
> HCI Event: LE Meta Event (0x3e) plen 40        #10 2020-07-28 16:49:16.513480
        Service Data (UUID 0xfe95): 712098009c1cf988caea800d041002f100
> HCI Event: LE Meta Event (0x3e) plen 41       #137 2020-07-28 16:49:20.451552
        Service Data (UUID 0xfe95): 712098009d1cf988caea800d071003ca0100
> HCI Event: LE Meta Event (0x3e) plen 41       #163 2020-07-28 16:49:21.454570
        Service Data (UUID 0xfe95): 712098009d1cf988caea800d071003ca0100
> HCI Event: LE Meta Event (0x3e) plen 41       #215 2020-07-28 16:49:23.468576
        Service Data (UUID 0xfe95): 712098009d1cf988caea800d071003ca0100
> HCI Event: LE Meta Event (0x3e) plen 41       #216 2020-07-28 16:49:23.469562
        Service Data (UUID 0xfe95): 712098009d1cf988caea800d071003ca0100
> HCI Event: LE Meta Event (0x3e) plen 41       #248 2020-07-28 16:49:24.471563
        Service Data (UUID 0xfe95): 712098009d1cf988caea800d071003ca0100
> HCI Event: LE Meta Event (0x3e) plen 41       #276 2020-07-28 16:49:25.476599
        Service Data (UUID 0xfe95): 712098009d1cf988caea800d071003ca0100
> HCI Event: LE Meta Event (0x3e) plen 41       #299 2020-07-28 16:49:26.480610
        Service Data (UUID 0xfe95): 712098009d1cf988caea800d071003ca0100
> HCI Event: LE Meta Event (0x3e) plen 41       #329 2020-07-28 16:49:27.483633
        Service Data (UUID 0xfe95): 712098009d1cf988caea800d071003ca0100
> HCI Event: LE Meta Event (0x3e) plen 39       #488 2020-07-28 16:49:34.473717
        Service Data (UUID 0xfe95): 712098009e1cf988caea800d08100121
> HCI Event: LE Meta Event (0x3e) plen 39       #544 2020-07-28 16:49:36.479741
        Service Data (UUID 0xfe95): 712098009e1cf988caea800d08100121
> HCI Event: LE Meta Event (0x3e) plen 39       #566 2020-07-28 16:49:37.489699
        Service Data (UUID 0xfe95): 712098009e1cf988caea800d08100121
> HCI Event: LE Meta Event (0x3e) plen 39       #614 2020-07-28 16:49:39.502777
        Service Data (UUID 0xfe95): 712098009e1cf988caea800d08100121
> HCI Event: LE Meta Event (0x3e) plen 40       #805 2020-07-28 16:49:47.488813
        Service Data (UUID 0xfe95): 712098009f1cf988caea800d091002af03
> HCI Event: LE Meta Event (0x3e) plen 40       #838 2020-07-28 16:49:48.492817
        Service Data (UUID 0xfe95): 712098009f1cf988caea800d091002af03
> HCI Event: LE Meta Event (0x3e) plen 40       #872 2020-07-28 16:49:49.493894
        Service Data (UUID 0xfe95): 712098009f1cf988caea800d091002af03
> HCI Event: LE Meta Event (0x3e) plen 40       #909 2020-07-28 16:49:50.480905
        Service Data (UUID 0xfe95): 71209800a01cf988caea800d041002ef00
> HCI Event: LE Meta Event (0x3e) plen 40       #982 2020-07-28 16:49:52.484942
        Service Data (UUID 0xfe95): 71209800a01cf988caea800d041002ef00
> HCI Event: LE Meta Event (0x3e) plen 40      #1094 2020-07-28 16:49:56.506982
        Service Data (UUID 0xfe95): 71209800a01cf988caea800d041002ef00
> HCI Event: LE Meta Event (0x3e) plen 40      #1158 2020-07-28 16:49:58.520999
        Service Data (UUID 0xfe95): 71209800a01cf988caea800d041002ef00
> HCI Event: LE Meta Event (0x3e) plen 41      #1213 2020-07-28 16:50:00.450984
        Service Data (UUID 0xfe95): 71209800a11cf988caea800d071003b90100
> HCI Event: LE Meta Event (0x3e) plen 41      #1237 2020-07-28 16:50:01.452035
        Service Data (UUID 0xfe95): 71209800a11cf988caea800d071003b90100
```

Some of the packets look like they contain the same data, but the information seems to be changed more often than every 60 seconds.

**Comment by Magalex2x14** [comment]
The fact is that, as you correctly noted, the data in these messages is the same. While working on the first versions of this component, I spent a lot of time looking for and studying information about how the exchange protocol is implemented in these sensors. Each piece of payload in the message is accompanied by its own number, which serves as an indicator of the "freshness" of this data. Thus, the protocol implements some redundancy, which increases the stability of data reception in bad conditions. There is no point in averaging the duplicated data - you get the same number in the output. 

Unfortunately, the only way to smooth the graph or increase the resolution through averaging is to lengthen the period... Can you show exactly which data you get spikes in? Is this some kind of erroneous data, or is this true measurement that you would like to smooth out a little before using it again (highlight a trend). The fact is that once upon a time I had to deal with sensors that send incorrect data, but this data went far beyond the measurement range of the sensor, and could be easily filtered out.

**Comment by Magalex2x14** [comment]
Describe in more detail what problem you are trying to solve, relying on the data from this sensor, and we will think about it together. One of the main tasks of our component is to obtain truthful data from the sensor without distortion, and further processing of this data must be carried out in accordance with the problem being solved, and this can already be implemented using the means of both HA itself and other components.

**Comment by Magalex2x14** [comment]
For example, look towards the[ filter platform](https://www.home-assistant.io/integrations/filter/).

**Comment by Magalex2x14** [comment]
I'm closing it for now, because as I wrote above, the protocol assumes multiple sending of the same data for reliability, this is not actually measured data, but a repetition. Feel free to reopen if you still have any questions.
