### ISSUE TITLE
Problem with ""Failed to start Bluetooth: adapter 'hci0' not found" again after last patch

### ISSUE THREAD

**Issue by rubendediegomartinez** [custom-components/ble_monitor#1013]
Hi,
Problem with ""Failed to start Bluetooth: adapter 'hci0' not found" reappears after the latest patch.
Everything works fine until the installation of the latest patch this morning

My platform:

HA OS over Virtual Box in Windows 11.

Any suggestion?

Regards.

**Comment by rubendediegomartinez** [comment]
I did it. The result is the same. Some times HA informs to me that can't find adapter...
Probably problems are in my platform, or in HA OS, but some thing is not too reliable.
Best regards

**Comment by rubendediegomartinez** [comment]
Unfortunately it is. But VM offers some other advantages.
I'll inform of the solution, if exists.... ;-)
BR

**Comment by Ernst79** [comment]
Did you have had any luck finding a solution?

**Comment by Ernst79** [comment]
There hasn't been any activity in this issue. We are closing it, to keep the issue tracker clean. Feel free to reopen if the problem still exists.
