### ISSUE TITLE
[Bug]: All sensors stopped updating

### ISSUE THREAD

**Issue by Stooovie** [custom-components/ble_monitor#1014]
### What happened?

None of my three Xiaomi lywsd03mmc sensors update anymore. The hardware is fine and updating, batteries are recent, it all worked until last few days, probably around the current BLE monitor update. I don't think it's caused by the latest HA 2022.9 update.

Setup: HAOS running on RPi4, built-in Bluetooth. I also have a Xiaomi Aqara Hub that I use for Bluetooth Mesh devices but not for plain BT and BLE devices.

![Screenshot 2022-09-08 at 8 15 56](https://user-images.githubusercontent.com/10572373/189048242-e30911f9-0cb0-4604-b47c-5d132779ba0a.jpg)

### Sensor type

lywsd03mmc

### Relevant log output

```shell
Here's the entire log, I don't know what's relevant.

https://0x0.st/of2o.log
```

**Comment by Ernst79** [comment]
hmmm, strange, I scanned through you logs, but I don't see any incoming BLE message from these devices, only from the iBeacons. Can you do the following. Enable the option "report unknown advertisements to the HA log" in the BLE monitor options, restart and post a new log after a few minutes? I want to check if messages arrive. 

Another option can be to switch the advertisement format to BTHome in the firmware (connect with the [pvvx webtool](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html), update firmware to 3.8 and use BTHome as advertisement format (in 3.7 it is called HA BLE).

**Comment by Stooovie** [comment]
You mean this? The units use WTC firmware. And do I leave the "Devices" empty? Sorry, the UI is a bit unclear. Thank you!
![6664256F-11B5-4B68-B426-B746BB4C707C](https://user-images.githubusercontent.com/10572373/189064462-8003ded6-b9d1-47f8-be94-5ed414290bfc.jpeg)

**Comment by Ernst79** [comment]
You can set Report unknown BLE advertisments to the HA log to Other. That should pick up all advertisements. Under devices, you can select one of the MAC addresses of the failing devices, to keep the log somewhat more limited.

**Comment by Stooovie** [comment]
Here's the new [log file](https://0x0.st/offM.log.zip). Even after changing the FW to BTHome, nothing is coming through... Any other ideas?

**Comment by Stooovie** [comment]
For some reason I had to remove the devices from the integration and re-add from scratch. Working now.

**Comment by Ernst79** [comment]
Great, 

BTW, BTHome also works in HA 2022.9 with a new Home Assistant Integration.
