### ISSUE TITLE
[Documentation] request new sensor

### ISSUE THREAD

**Issue by goosvorbook** [custom-components/ble_monitor#1020]
Hi All, 

The [documentation for a new sensor reques](https://custom-components.github.io/ble_monitor/sensor_request)t still points towards [this github](https://github.com/custom-components/ble_monitor/issues) .
Since this custom component is being phased out in favor of the core Home Assistant bluetooth integration, wouldn't it make sense to redirect users looking for a new integration towards the [new integration github](https://github.com/Bluetooth-Devices)?

**Comment by Ernst79** [comment]
I think the new integration github should get its own "request new sensor" How To, as people will need to use the Bluetooth integration of HA if they use the new integrations. Maybe I can add an extra possibility to explain how to get the data with the new Bluetooth integration, as a intermediate step/solution. 

Anyway, I will add the new sensors to both BLE monitor and the new BLE integrations in the meantime.
