### ISSUE TITLE
[Bug]: create_bt_socket is giving an AttributeError

### ISSUE THREAD

**Issue by kpblca** [custom-components/ble_monitor#1025]
### What happened?

Hi 

Im using 2022.9 last version of HomeAssistant and last version of BLE Monitor 10.3.0

Have such traceback in the logs (see below).

As the result integration dont work and all my BLE devices is not updated in HA.

### Relevant log output

Logger: root
Source: custom_components/ble_monitor/__init__.py:709
Integration: Passive BLE monitor (documentation, issues)
First occurred: 07:08:11 (8 occurrences)
Last logged: 07:11:28

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 709, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
AttributeError: module 'aioblescan' has no attribute 'create_bt_socket' `

**Comment by Ernst79** [comment]
That looks like there is an issue with your Bluetooth hardware. Are you using the Bluetooth integration of home assistant as well?

**Comment by kpblca** [comment]
No, I dont use Bluetooth integration in HomeAsssitant (all discovered Bluetooth adapters and devices in HA's "Integration" panel I have marked as "ignored"). 

To specify the situation, the issue was invoked when I made upgrade using 1 reboot:
- BLE Monitoring from 10.2.0 -> 10.3.0 
- HomeAssistant from 2022.9.4 upto 2022.9.6

Before that update the BLE Monitoring worked well and gathered data from remote ble sensors.

**Comment by Ernst79** [comment]
Did you do a full system restart (not only HA, but the entire system). Sometimes, it got stuck after a HA Os update for example.

**Comment by kpblca** [comment]
I have checked that in the docker container with hassio installed the aioblescan of last version 0.2.13

I have tried without result: 
- do full restart of my rassberry pi with homeassistant
- downgrade of BLE Monitoring down to 10.2.0 and 10.1.0 
- pip3 uninstall and reinstall of `aioblescan` library in the docker container with homeassistant 

Helped only full uninstall & install of BLE Monitoring. After re-installing the issue had gone away and me doing re-adding of my BLE devices successfully.

**Comment by Ernst79** [comment]
Hmm, strange. But good that it is solved. I’ll keep an eye on users reporting similar issues, but for now, i assume we can close this issue.
