### ISSUE TITLE
Add Philips Sonicare

### ISSUE THREAD

**Issue by u20p17** [custom-components/ble_monitor#1036]
### Sensor Description

Philips Sonicare Toothbrush

### Additional information

product link:  [link](https://www.philips.at/c-e/pe/elektrische-zahnbuersten/diamondclean?utm_id=71700000090643832&origin=7_700000001545808_71700000090643832_58700007676858898_43700071020444632&gclid=CjwKCAjwqJSaBhBUEiwAg5W9p4jim62Skd0pHaa1ycumAT1FaSSaRSZCmJ_m61tMkY18EhIMmQxX5RoCpfIQAvD_BwE&gclsrc=aw.ds#triggername=colorpicker_white%2Chero_main%2Ccolors_one%2Ccolorstwo_two%2Ccolorsthree_three)

It looks like there are [python bindings](https://github.com/joushx/python-sonicare) available for the Philips toothbrush.

**Comment by Ernst79** [comment]
This toothbrush uses an active connection to get the data. This is not possible with BLE monitor. It will probably be easier to develop an official HA Bluetooth integration for this. 

Unfortunately, it won't be possible to add it to BLE monitor.
