### ISSUE TITLE
Xiaomi HOTO kitchen scale integration

### ISSUE THREAD

**Issue by davideZavattero** [custom-components/ble_monitor#1040]
Sensor Description
(Xiaomi) Hoto Smart Kitchen Scale

Additional information
Mac address B4:60:ED:95:02:01 . Logs extracted via home assistant.

i put on the scale a weight of 631.4g

Thanks for the support

[xiaomi hoto scale_log.txt](https://github.com/custom-components/ble_monitor/files/9803356/xiaomi.hoto.scale_log.txt)

**Comment by Ernst79** [comment]
Hi, sorry I didn't got back to you sooner. The data contains the same message over and over 

`0f1695fe3058801101010295ed60b408`

After parsing it, is reports 

``` 
mesh device 0
included mac 1
b460ed950201
device_id 4480
QWCFC001
object_include 0
```

The object_include = 0 means that there is no data in the package, which makes sense, as all messages are the same. Sometimes, it will report data after you connect it to MiHome. Did you do/try that?

**Comment by Ernst79** [comment]
Feel free to reopen the issue if you have more data
