### ISSUE TITLE
[Bug]: Bluetooth Adapter not available

### ISSUE THREAD

**Issue by derbohmann** [custom-components/ble_monitor#1047]
### What happened?

Yesterday I set up this addon with my Xiaomi Thermometers. Everything was working finde I could choose the bluetooth adapter and could setup all by thermometers. Today however I can't get it to work.

I'm running Home Assistant in a Docker Container on a Raspberry Pi 3B+. The default Bluetooth integration recognizes the integrated bluetooth adapter like a charm. This integration somehow doesn't anymore.

What I changed today was the network of the docker container from host to custom network. But I don't know how this would affect this integration.

**Comment by Ernst79** [comment]
I don't have docker myself, so can't help you with that. But make sure the Bluetooth dongle is available within the docker environment. Also running the Bluetooth integration and BLE monitor at the same time can cause issues, although the dongle in most cases should be recognized in both integrations. Any error messages during startup of HA?

**Comment by derbohmann** [comment]
There were no log entries during startup and the bluetooth dongle was available in the docker environment.
I ended up flashing the Xiaomi Thermostats again and use the BTHome Integration instead.
Before I did that I tried completely removing the Passive BLE Integration. Restarting HA and HA Container. Then reinstall it. But it still wasn't working for me, even after multiple tries. So I gave up.

**Comment by Ernst79** [comment]
Ok. I'll close the issue for now. In case you want to further investigate what is going on, let me know.
