### ISSUE TITLE
Request to add VSON airbox BLE sensor 

### ISSUE THREAD

**Issue by adekloet** [custom-components/ble_monitor#1056]
Hi,

Is it possible to add the VSON Airbox quality sensor? I will add the BLE raw data and a screenshot of the data received.
Thank you.
Alex

![Screenshot_20221120-193943_VSON](https://user-images.githubusercontent.com/60182504/202920055-af7d2a80-0099-4461-af53-425d922a47a0.jpg)
![Screenshot_20221120-193853_BLE Scanner](https://user-images.githubusercontent.com/60182504/202920056-cb71cf20-da61-42ff-87c9-5934dfc9ec3f.jpg)

**Comment by adekloet** [comment]
![Uploading Screenshot_20221120-194627_BLE Scanner.jpg…]()

**Comment by adekloet** [comment]
![Screenshot_20221120-194627_BLE Scanner](https://user-images.githubusercontent.com/60182504/202920229-c6ef205e-0c29-4fc9-a5e2-f19d068dec73.jpg)

**Comment by Ernst79** [comment]
Not sure, BLE monitor can only receive passive data, which is what you show in the first print screen. I see, the types 01, 03, 09 (2x). 01 = flags, 03 = uuid, 09 = name. 

What you need to find out if you also can see messages of type 16 or FF. These messages contain the data.

**Comment by adekloet** [comment]
Data from a little later with different values for comparison.
![Screenshot_20221120-203738_BLE Scanner](https://user-images.githubusercontent.com/60182504/202922400-59451497-0698-43a5-9ed2-2b3b0d3e281b.jpg)
![Screenshot_20221120-203811_BLE Scanner](https://user-images.githubusercontent.com/60182504/202922403-d18ef12c-d02a-4ddc-aec7-caabb63b0696.jpg)

**Comment by Ernst79** [comment]
Focus on the first printscreen. It is still types 01, 03 and 09 (2x). Unless you find a type 16 or FF, it won't be possible to add. If you won't find type 16 or FF, it probably needs a connection, which is not possible with BLE monitor

**Comment by adekloet** [comment]
Thanks Ernst,

I'll look for that, but haven't seen 16 or FF yet.

Rgds
Alex

**Comment by Ernst79** [comment]
You could try enabling active scan, this sometimes triggers the device to send these packets. 

If that doesn't work, it won't be possible unfortunately.

**Comment by adekloet** [comment]
Seems to need an active connection.
