### ISSUE TITLE
[Bug]: Nie udało się wczytać interfejsu konfiguracji: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by oomichalekoo** [custom-components/ble_monitor#1062]
### What happened?

Nie udało się wczytać interfejsu konfiguracji: {"message":"Invalid handler specified"} i Add sudo for python and components still dont work

**Comment by Ernst79** [comment]
I need more information, show the full errors in the log. Explain what you did and how you install BLE monitor.

**Comment by oomichalekoo** [comment]
Ten błąd pochodzi z niestandardowej integracji.

Logger: homeassistant.loader
Source: custom_components/ble_monitor/bt_helpers.py:35
Integration: Passive BLE monitor (documentation, issues)
First occurred: 14:53:13 (1 occurrences)
Last logged: 14:53:13

Unexpected exception importing platform
custom_components.ble_monitor.config_flow
Traceback (most recent call last):
  File
"/data/data/com.termux/files/usr/lib/python3.10/site-packages/homeassistant/loader.py",
line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File
"/data/data/com.termux/files/usr/lib/python3.10/site-packages/homeassistant/loader.py",
line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File
"/data/data/com.termux/files/usr/lib/python3.10/importlib/__init__.py",
line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in
_call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in
_call_with_frames_removed
  File
"/data/data/com.termux/files/home/AIS/custom_components/ble_monitor/__init__.py",
line 88, in <module>
    from .bt_helpers import (
  File
"/data/data/com.termux/files/home/AIS/custom_components/ble_monitor/bt_helpers.py",
line 162, in <module>
    BT_INTERFACES = hci_get_mac([0, 1, 2, 3])
  File
"/data/data/com.termux/files/home/AIS/custom_components/ble_monitor/bt_helpers.py",
line 88, in hci_get_mac
    btctl = MGMTBluetoothCtl()
  File
"/data/data/com.termux/files/home/AIS/custom_components/ble_monitor/bt_helpers.py",
line 35, in __init__
    idxdata = btmgmt_sync.send('ReadControllerIndexList', None)
  File
"/data/data/com.termux/files/usr/lib/python3.10/site-packages/btsocket/btmgmt_sync.py",
line 22, in send
    sock = btmgmt_socket.open()
  File
"/data/data/com.termux/files/usr/lib/python3.10/site-packages/btsocket/btmgmt_socket.py",
line 42, in open
    ctypes.cdll.LoadLibrary("libc.so.6")
  File "/data/data/com.termux/files/usr/lib/python3.10/ctypes/__init__.py",
line 452, in LoadLibrary
    return self._dlltype(name)
  File "/data/data/com.termux/files/usr/lib/python3.10/ctypes/__init__.py",
line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: library "libc.so.6" not found

pt., 9 gru 2022 o 14:50 Ernst Klamer ***@***.***> napisał(a):

**Comment by oomichalekoo** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:810
First occurred: 14:53:13 (1 occurrences)
Last logged: 14:53:13

Error occurred loading configuration flow for integration ble_monitor:
Exception importing custom_components.ble_monitor.config_flow

pt., 9 gru 2022 o 14:53 Michał ***@***.***> napisał(a):

**Comment by oomichalekoo** [comment]
-

   put in console this

      sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which
python3\``

   -

   and this

      sudo getcap `readlink -f \`which python3\``

   -

   reject me /data/data/com.termux/files/usr/bin/python3.10
cap_net_admin,cap_net_raw=eip

   -

   and add custom components manually



pt., 9 gru 2022 o 14:53 Michał ***@***.***> napisał(a):

**Comment by oomichalekoo** [comment]
I AM using ,esp32 im configuration.yaml i have bluetooth:

pt., 9 gru 2022, 15:11 użytkownik Ernst Klamer ***@***.***>
napisał:

**Comment by Ernst79** [comment]
It still looks like your installation is missing some Bluetooth stuff. 

```
OSError: dlopen failed: library "libc.so.6" not found
```

Not sure, but you might try to disable the Bluetooth adapter in the BLE monitor settings, if you only use ESP32 to forward data to BLE monitor. 
https://custom-components.github.io/ble_monitor/configuration_params#bt_interface

![image](https://user-images.githubusercontent.com/24375847/206722316-73f2c498-a743-4851-951a-2f589f739c4e.png)

BTW. I don't know what sensors you have, but it might be worth to use the core HA integrations in combination with ESPHome Bluetooth Proxy, in stead of BLE monitor.

**Comment by oomichalekoo** [comment]
i cant instal Passive BLE Monitor integration and i cant add ble_monitor: bt_interface:disable becouse is error in configuration.yaml

**Comment by Ernst79** [comment]
What kind of installation do you have? Home Assistant OS?

**Comment by Ernst79** [comment]
There hasn't been any activity in this issue. We are closing it, to keep the issue tracker clean. Feel free to reopen if the problem still exists.
