### ISSUE TITLE
[Bug]: After upload of passive BLE monitor, no integration-card does show up

### ISSUE THREAD

**Issue by michael5411** [custom-components/ble_monitor#1068]
### What happened?

After upload of passive BLE monitor, no integration-card does show up.

I had this working some days ago, but (i thought) I had to delete it and reinstall. Obviously a bad idea.

It`s visible under the "HACS-integration" card. But there does card show up for this integration. Therefore no configuration is possible. Restarts do not help.

I`m using:

Home Assistant 2022.12.3
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221208.0 - latest

and the latest HACs-version.

### Relevant log output

```shell
no error report.
```

**Comment by Ernst79** [comment]
So, If I understand you correct, you have installed it via HACS (check that the folder /custom_components/ble_monitor is on your system, with contect). Next, do a Restart and go to the integrations menu. Add BLE monitor, and that is where you can't find BLE Monitor??

That often is a problem with the browser cache. Try to hit F5 10 times in the browser, to force your browser to update the cache and try again. This often helps

**Comment by michael5411** [comment]
solved - thank you Ernst79
