### ISSUE TITLE
[New Sensor]: Old BlueMaestro Pebble Temperature + Humidity

### ISSUE THREAD

**Issue by dobestler** [custom-components/ble_monitor#1086]
### Sensor Description

BlueMaestro TempHum Pebble (2017)

### Additional information

https://www.facebook.com/BlueMaestroPages/posts/product-update-pebble-environment-monitornumerous-improvements-and-updates-for-t/1506742669400131/

It's an older version.

### BLE advertisements

```shell
2023-01-04 21:52:02.614 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] hci0 (E4:5F:01:XX:XX:XX) [connectable]: FA:67:91:ZZ:ZZ:ZZ AdvertisementData(local_name='Tempo v3', manufacturer_data={307: b'\x01\xcf\x00\xcf\x00\xcf\x00.\xc9\x03\xb2\xd7\x00\x91g\xfa\x07\x00'}, service_uuids=['0000180f-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb'], rssi=-73) match: {'bluemaestro'}


The data is differently arrange compared to the newer BlueMaestro devices. I once wrote a parser in Java for Temp and Humidity. I wasn't interested in the other data :)

        
ByteBuffer bytes = ByteBuffer.wrap(manufacturerData).order(ByteOrder.LITTLE_ENDIAN);
float tempCurrent = ((float) bytes.getShort(3)) / 10.0f; // at index 3
byte humidity = bytes.get(7); // at index 7
```

**Comment by Ernst79** [comment]
I had a look at the data

`cf00cf00cf002ec903b2d7009167fa0700`

`cf00` => `00cf` = 207 --> 20.7 degrees (reported 3x after eachother?)
`2e` => 46 % RH

Is that an correct interpretation?

**Comment by dobestler** [comment]
Looks about right. I found the complete specs of the data:

https://www.alphaomega-electronics.com/en/index.php?controller=attachment&id_attachment=1728

**Comment by Ernst79** [comment]
Looks more like the new format, isn’t it?

**Comment by dobestler** [comment]
You're right. I got mistaken and thought that this pebble device is not sold anymore but turn out it is.

Here is what I know:
`
cf00   cf00     cf00   2e      c903b2d700 9167fa0700
??       temp     ??       hum   ????
           curr                 curr 
`

I think your interpretation of the rest makes sense. I could try and see if the readings make sense compared to other devices showing pressure and dew point.

Here a dump of ADV and Scan Response that might help.
`
            > HCI Event: LE Meta Event (0x3e) plen 31 
                LE Advertising Report (0x02)
                Num reports: 1
                Event type: Connectable undirected - ADV_IND (0x00)
                Address type: Random (0x01)
                Address: FA:67:91:00:D7:B2 (Static)
                Data length: 19
                Name (complete): Tempo v3
                Flags: 0x06
                  LE General Discoverable Mode
                  BR/EDR Not Supported
                16-bit Service UUIDs (partial): 2 entries
                  Battery Service (0x180f)
                  Device Information (0x180a)
                RSSI: -73 dBm (0xb7)
            > HCI Event: LE Meta Event (0x3e) plen 34  
                LE Advertising Report (0x02)
                Num reports: 1
                Event type: Scan response - SCAN_RSP (0x04) 
                Address type: Random (0x01)
                Address: FA:67:91:00:D7:B2 (Static)
                Data length: 22
                Company: Blue Maestro Limited (307)
                  Data: 01f000f000f0002aba03b2d7009167fa0700                 <<<<<<< Data with current measurement values
                RSSI: -81 dBm (0xaf)
`

**Comment by Ernst79** [comment]
If you can get a BLE message and a printscreen from the App, I might be able to match the data. I assume it as an app that shows pressure and dew temperature.

**Comment by dobestler** [comment]
I think there is no blue maestro app anymore that is compatible with this protocol. We'd need the app from 2017 to do this. 

I would be happy with Temp & Humidity already ;)

**Comment by Ernst79** [comment]
The mac address is also in there (reversed per two characters

```
        cf00   cf00     cf00   2e      c903  b2d7009167fa  0700
        ????   temp     ????   hum     ????  mac address   ????

```

I will create an beta update with the following assumption, so you can check if that makes sense with other sensors. 


```
        cf00   cf00     cf00   2e      c903      b2d7009167fa  0700
        ????   temp     ????   hum     pressure  mac address   dew temp

```

**Comment by Ernst79** [comment]
Can you give it a try with 11.3.1-beta (enable beta releases in HACS for BLE monitor to install)

**Comment by dobestler** [comment]
Thanks for the quick fix. I have tested different environments together another device. 

Looks correct except for dew point temp that constantly shows 0.7

Maybe dew point temp is not part of the scan response.

**Comment by Ernst79** [comment]
Done, removed in the final version.
