### ISSUE TITLE
[Bug]:  xiaomi button XMWXKG01LM

### ISSUE THREAD

**Issue by matteos1** [custom-components/ble_monitor#1092]
### What happened?

the button not responding

**Comment by Ernst79** [comment]
I need more info than this. Did it work in the past? In which version did it stop working? Do you have errors in the log?

**Comment by yeaaaaaahh** [comment]
I just upgraded to 11.13.1 and none of my xiaomi zigbee sensors are working (door contact, as well as button).

2023-01-10 09:44:07.842 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)

**Comment by Ernst79** [comment]
This integration is for BLE sensors, not Zigbee. You need to ask at the xiaomi-gateway 3 integration

**Comment by yeaaaaaahh** [comment]
> This integration is for BLE sensors, not Zigbee. You need to ask at the xiaomi-gateway 3 integration

Oh, of course - derp

**Comment by yeaaaaaahh** [comment]
@matteos1, this issue https://github.com/AlexxIT/XiaomiGateway3/issues/921
