### ISSUE TITLE
[Bug]: MiScale V2 catty/jin units

### ISSUE THREAD

**Issue by x11x** [custom-components/ble_monitor#1095]
### What happened?

On my scale (Xiaomi Mi Body Composition 2), catty units is indicated by the 6th bit of the control byte being on (so in your code `control_byte & (1 << 6)` instead of `measunit & (1 << 4)` ([miscale.py line 45](https://github.com/custom-components/ble_monitor/blob/f7a189b6f6892741de7e050bdf5ffd2d96cc4404/custom_components/ble_monitor/ble_parser/miscale.py#L45)].

I have not tested on other models, but I believe Mi Scale 2, etc. (all "V2" models) are the same.

I have not actually run your code (that's why I didn't make a PR), I just found this in my own testing with the device.

I have seen other sources found the same thing:

- https://github.com/wiecosystem/Bluetooth/blob/master/doc/devices/huami.health.scale2.md#advertisement
- https://github.com/foormea/esp32_mi_scale_2/blob/master/esp_sketch/esp_sketch.ino#L283
- https://github.com/oliexdev/openScale/blob/83c2d941ea8ec349c92fba173398c97a5ee45b70/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java#L147

However, I have also noticed many other apps/libraries don't even detect catty units for V2 scales (e.g. https://github.com/esphome/esphome, https://github.com/lolouk44/xiaomi_mi_scale), not sure why. Either because nobody is using catty units (I don't either, I just noticed this while testing different units). Or there is some discrepancy between models or difficulty detecting it.

EDIT: my mistake, oliexdev/openScale actually is detecting catty units the same way as I described above (6th bit of control byte 1), however that code seems to have a bug where they are also using the 6th bit as "isDateInvalid", which has an open [bug report](https://github.com/oliexdev/openScale/issues/907)

### Sensor type

MiScale V2

**Comment by Ernst79** [comment]
Thanks for this in depth investigation!!!

I've fixed it in #1096. I don't think someone actually uses this unit (at least, nobody has complained). Fix will be included in the next release.
