### ISSUE TITLE
[Bug]: almost 700 bogus iBeacon devices. Cleanup_entries service doesn’t help

### ISSUE THREAD

**Issue by Stooovie** [custom-components/ble_monitor#1109]
### What happened?

All of a sudden, I have 657 bogus iBeacon devices with almost 6000 entities showing up. I have five LYWWD3MMC sensors, a Xiaomi Smart Scale, and that’s it. 

This is a new issue, I have been running PBLEM for years without an issue. Currently on latest version  11.4.1, HA 2023.1.7.

The “Passive BLE monitor: cleanup_entries” service doesn’t help, nor does rebooting and reloading the integration. What else? I obviously won't manually remove 650 devices via the integration Config menu. 

I have enabled debugging in the Devices and services HA settings panel but so far I’m not seeing anything. 

Thanks.

**Comment by Ernst79** [comment]
Strange. Looks like some iBeacon device is missing the uuid with data. The uuid should be unique, but I guess there is a sensor  that sends data with a changing uuid. To prevent more sensors to be added, you can disable discovery in the ble monitor options. Maybe the easiest is to write down the Mac addresses of the sensors you want to keep. Remove BLE monitor and restart. The reinstall BLE monitor and disable discovery. Than add the Mac addresses in the devices pull down menu, by selecting add device. Hopefully this will help to get rid off the old devices

**Comment by Stooovie** [comment]
Thank you

**Comment by Ernst79** [comment]
I assume it solved? Otherwise, reopen the issue.

**Comment by Stooovie** [comment]
Running the Clean up dangling BLE entries did work eventually in HA 2023.2.X. It didn't do anything before that. All seems good now.
