### ISSUE TITLE
[Question] Two BT adapters

### ISSUE THREAD

**Issue by szymucha94** [custom-components/ble_monitor#1111]
Hi,
I'd like to know if it's possible to use this integration with two BT adapters. I have one physical adapter connected to server, but one of the sensors is not in range of it. I've added another adapter to HA via usbip, HA found the adapter but this integration didn't allow me to choose both adapter's MACs.
Or maybe is it possible to duplicate this integration and use them separately?

Thanks in advance

**Comment by Ernst79** [comment]
Not sure if that is possible. On startup, ble monitor tries to find all Bluetooth adapters, but I don’t know if it checks usbip. It checks all HCI ports. However you can extend the range with an external ESPhome device with Bluetooth BLE gateway installed on it. This can forward messages from an esp device to HA over WiFi.

https://custom-components.github.io/ble_monitor/parse_data

**Comment by szymucha94** [comment]
This is good, and exactly what I was looking for :)
Currently I'm just dumping packets from whitelisted MACs with hcidump and getting all needed information from these packets with bash, then sending data to HA restapi via curl. My goal is to offload the tablet that is doing that, so this will work perfectly. Thanks!
