### ISSUE TITLE
[New Sensor]: Yieryi BLE-YC01

### ISSUE THREAD

**Issue by pvarman** [custom-components/ble_monitor#1119]
### Sensor Description

Yieryi BLE-YC01 - Pool sensor monitor for water quality

### Additional information

This is a 6 in 1 water quality measuring device similar in construction to Inkbird devices. 

also sold via Amazon by Yinmik -> https://www.amazon.co.uk/Testing-Swimming-Quality-Analyzer-Chlorine/dp/B0B1QP3ZBN/ref=sr_1_21?crid=3PGHPJAJBB7M3&keywords=7+in+1+water+quality+meter+for+pool&qid=1675009544&sprefix=%2Caps%2C129&sr=8-21

I noticed there is another HA thread about getting data out of it, here -> https://community.home-assistant.io/t/pool-monitor-device-yieryi-ble-yc01/418684/16

Would be good if it could be included in this BLE monitor within HA to keep one's system simple.

Logs and a diagnostics dump from Bluetooth 
[Yieryi BLE-YC01 device broadcast capture log.txt](https://github.com/custom-components/ble_monitor/files/10530306/Yieryi.BLE-YC01.device.broadcast.capture.log.txt)
attached.
[config_entry-bluetooth-HomeAssistant-0786cbf6de97e1e6225942aa7317fbb2.json.txt](https://github.com/custom-components/ble_monitor/files/10530292/config_entry-bluetooth-HomeAssistant-0786cbf6de97e1e6225942aa7317fbb2.json.txt)

**Comment by Ernst79** [comment]
According to this post https://community.home-assistant.io/t/pool-monitor-device-yieryi-ble-yc01/418684/12 the device is requiring an active connection, which isn't possible with BLE monitor. That means we can't add it to BLE monitor, as we only listen passively to sensor data.
