### ISSUE TITLE
[Bug]: interference with SwitchBot integration

### ISSUE THREAD

**Issue by ugidj** [custom-components/ble_monitor#1120]
### What happened?

Since I configured "Passive BLE Monitor integration" my Bot SwitchBot (SwitchBot official integration) no longer works properly with this integration. It's possible? Can one interfere with the other? Thank you

**Comment by Ernst79** [comment]
Yes, that is possible. Not sure what switchboard is using, active or passive scanning, or a connection, but using different ways of BLE communication with one Bluetooth adapter can cause this issue. A BLE adapter can only do one thing at the same time. 

One thing you can check is that the HA Bluetooth integration and BLE monitor are using the same scanning mode (both active or both passive). Both integrations have a setting for this. If that doesn’t help, the only thing you can do is using a second BLE adapter, one for BLE monitor and one for the HA Bluetooth integration.

**Comment by schoeberlt** [comment]
@ugidj You can also use BLE Monitor to use Switchbot devices (e.g. temp and humidity), for me it works better than HA integrated bt with switchbot integration. That is, until the updates last week, now I am trying to downgrage.

**Comment by Ernst79** [comment]
I'll have to investigate that. BLE monitor can only receive data (passive or active). but it can't get information by connecting to a device. With connecting, I mean in BLE terms "reading gatt characteristics" by sending some BLE data, and receiving a response. BLE monitor is not able to send data. I will have a look at the official integration which method is uses. Will get back to you a.s.a.p.

**Comment by schoeberlt** [comment]
Sorry if I was a bit vague, I ment of course receiving temperature and humidity data with active scanning from a Switchbot Meter. I suppose that the case in this issue is rather controlling the switchbot bot.
