### ISSUE TITLE
How do you uninstall from HACS 

### ISSUE THREAD

**Issue by Martynhsmith** [custom-components/ble_monitor#1129]
### What happened?

Sorry - I can't see how I should uninstall after moving to HA standard ?

**Comment by Ernst79** [comment]
Just click on the integration in HACS and than click on the three dots, last option should be remove (picture is in Dutch, but you get the hang)

![image](https://user-images.githubusercontent.com/24375847/217863046-675b2e8b-5b2f-4e26-8b21-1f57cef537b6.png)
