### ISSUE TITLE
mitemp_bt module affects xiaomi_aqara integration. Aqara module stops updating sensors

### ISSUE THREAD

**Issue by protei300** [custom-components/ble_monitor#113]
Hello!

Caught a problem with this module. After installing it and successfully connecting 2 BLE sensors via it, my aqara gateway stops sending packets to HA. In a debug there is no errors.. it just send data from round sensors with much slower rate and this causes Lovelace to mark them as not available. 

![изображение](https://user-images.githubusercontent.com/32344207/93218371-a922c680-f759-11ea-8fb2-31d3b9d739d2.png)

Here i marked how temp chart looks like from aqara sensors, After i disable module, it sends data as before without any issue.
There are no errors nor from BLE module, nor from Aqara.

I am using HA 114.4 with hassOS 4.13 on RPI v3 B+

Other things work well, and this module collects data as per documentation each 10 minutes without issues.

**Comment by Ernst79** [comment]
The graph you show, is that a sensor from the xiaomi_aqura integration, or from the mitemp_bt integration?

**Comment by protei300** [comment]
This is from Aqara sensors.... you see there are holes...  missing data... and last part of chart corresponds to time when i switched off BLE module... info starts to go smooth

**Comment by Ernst79** [comment]
Yes, I see, but I don't understand how your Aqara sensors are connected by the xiaomi_aqara component. xiaomi_aqara does not support BLE as far as I know. Can you show your configuration for both xiaomi_aqara en mitemp_bt

**Comment by protei300** [comment]
Aqara sensors connected via  builtin xiaomi_aqara integration component, while BLE sensors using mitemp_bt

Here is a config for mitemp_bt:
 
- platform: mitemp_bt
  encryptors:
    'A4:C1:38:xx:xx:xx': '67fd513760c1d798d05cc7fbxxxxxxxxxx'
    'A4:C1:38:xx:xx:xx': 'f23e6919d566e5890463db33xxxxxxxxx'
  whitelist: True


For xiaomi_aqara i removed it from configuration.yaml and sensors.yaml. I am using built-in component

**Comment by Ernst79** [comment]
To be honest, I have no idea. One possibility that comes to my mind: Aqara is using zigbee connection to the gateway. The gateway also uses WiFi and Bluetooth. Perhaps one of these signals is interfering with the Bluetooth signal of your home assistant device. Try to move one of them to a different place, tomes if that makes a difference.

**Comment by protei300** [comment]
I use Aqara gateway without bluetooth... only zigbee..  Will try to play with settings in configuration, maybe this helps

**Comment by ekarazhas** [comment]
@protei300 do you have any updates on that issue? Looks like I am facing same issue.

**Comment by protei300** [comment]
> @protei300 do you have any updates on that issue? Looks like I am facing same issue.

Nope... i switched it off... sadly... I dont see any errors, its just postpone update requests and thats all

**Comment by Ernst79** [comment]
Could you try HassOs 4.15. There were some changes for Bluetooth in the last two versions. It’s still a guess, as I don’t have this issue myself. I also have xiaomi temperature devices connected via the xiaomi aqara component and ble devices connected via this component, but it’s working fine in my case.

**Comment by protei300** [comment]
> Could you try HassOs 4.15. There were some changes for Bluetooth in the last two versions. It’s still a guess, as I don’t have this issue myself. I also have xiaomi temperature devices connected via the xiaomi aqara component and ble devices connected via this component, but it’s working fine in my case.

Damn error that it cannot fetch update.... gonna try with usb stick update..... This is weird... Before had zero problems with update.

Also now even without mitemp_bt module aqara stops working after a while.... this started after update to 0.116

**Comment by protei300** [comment]
Okey will try thanks! Will let you know

вт, 27 окт. 2020 г., 19:30 Ernst Klamer <notifications@github.com>:

**Comment by Magalex2x14** [comment]
I suggest to close for now, @Ernst79.
@protei300, feel free to reopen if there is any news on this.
