### ISSUE TITLE
[New Sensor]: MMC-W505 Xiaomi Mijia Digital Thermometer

### ISSUE THREAD

**Issue by miguelangel-nubla** [custom-components/ble_monitor#1136]
### Sensor Description

MMC-W505 Xiaomi Mijia Digital Thermometer

### Additional information

[Product link](https://www.banggood.com/XIAOMI-Mijia-MMC-W505-Smart-APP-Bluetooth-4_2-BLE-LCD-Digital-Thermometer-Adult-Baby-Body-Thermometer-Health-Care-Device-reviews-p1667433.html)

![Screenshot_2023-02-20-15-19-05-104_uk co alt236 btlescan](https://user-images.githubusercontent.com/866596/220134482-878a65fc-ef6d-4e07-8671-12b5b10171aa.jpg)

### BLE advertisements

```shell
2023-02-20 15:14:35.510 INFO (Thread-18) [custom_components.ble_monitor.ble_parser] Unknown advertisement received for mac: D0:24:18:53:AB:DBservice data: []manufacturer specific data: []local name: MMC-W505UUID16: None,UUID128: None
2023-02-20 15:16:34.334 INFO (Thread-18) [custom_components.ble_monitor.ble_parser] Unknown advertisement received for mac: D0:24:18:53:AB:DBservice data: []manufacturer specific data: []local name: MMC-W505UUID16: None,UUID128: None
2023-02-20 15:16:45.363 INFO (Thread-18) [custom_components.ble_monitor.ble_parser] Unknown advertisement received for mac: D0:24:18:53:AB:DBservice data: []manufacturer specific data: []local name: MMC-W505UUID16: None,UUID128: None
```

**Comment by vladkozlov69** [comment]
Would be very useful to have support for this device.

**Comment by Ernst79** [comment]
I have had a look. The link you gave seems to suggest that one has to connect to the device to get the data (which isn't possible with BLE monitor). However, I also noticed that the device is sending passive data. 

the general MiBeacon info bytes give the following info
```
MiVer: 2, DevID: 0x391 : MMC-W505, FnCnt: 15, Not bound, Request APP to register and bind, Old version certification, Capability: 0x9, No encryption
```

The data part contains the following information. 
```
payload 0a0002000002
0a00 = body temperature
02 = data length
0000 = data (0)
02 = ???
```

So, it has send body temperature = 0°C, which is of course strange. 
Two questions, 
1. did you connect the sensor to the MiHome App. Sometimes this is needed before it actually starts to send the real data.
2. was the thermometer measuring something. Please try to create another log, during a period in which you are sure it has a (fixed) measurement.

**Comment by miguelangel-nubla** [comment]
The payloads ending in 02 are sent while the temperature is not stable and is being measured.
When the thermometer beeps indicating it has finished it sends a payload ending in 07:
Capture 1:
Thermometer indicated 34.45 °C , the payload 0a00 02 750d 07.
Capture 2:
Thermometer indicated 36.89 °C , the payload 0a00 02 690e 07.
Capture 3:
Thermometer indicated 32.47 °C , the payload 0a00 02 520d 07.
Capture 4:
Thermometer indicated 36.79 °C , the payload 0a00 02 5f0e 07.
Capture 5:
Thermometer indicated 36.92 °C , the payload 0a00 02 6c0e 07.

Attached pcap files:
[caputures_mmc-w505.zip](https://github.com/custom-components/ble_monitor/files/10920238/caputures_mmc-w505.zip)

Captured with Acrylic Bluetooth LE Analyzer. To decode them in Wireshark:
![how-to-decode](https://user-images.githubusercontent.com/866596/223705662-7c332f4d-7e11-4225-8cdd-d068ca8a832c.jpg)

**Comment by Ernst79** [comment]
I have added support for this termometer in 11.8.0. I decided to not use the last byte '07', as this byte is not following the MiBeacon format. So I decided to program it as follows.

If temperature is 0, it will skip the message.
Otherwise, it will report temperature.  

Let me know if it works OK.

**Comment by miguelangel-nubla** [comment]
@Ernst79 working correctly, thank you!
