### ISSUE TITLE
[Bug]: Is there a more concrete timeline for if/when functionality will move in HA core?

### ISSUE THREAD

**Issue by AdrianGarside** [custom-components/ble_monitor#1138]
### What happened?

I just set up esphome to read 4 Xiaomi sensors flashed with the pvvx custom firmware. From experimenting it appears that my Pi in the basement might actually be able to reach them all directly. But even if not, I'm tempted to replace the existing ESPhome device with an esphome bluetooth proxy instead to make future bluetooth additions easier. So I was looking into more native bluetooth integrations and found this HACS component but then the big disclaimer it's being absorbed into HA core gave me pause - is it worth it to try and get this up and running or will it be obsolete soon. Plus I would also first need to update my HA a bit since I'm on 2022.11.2 and I tend to try to not update HA if it's not broken. It's also not clear if HA core will take the custom firmware support?

### Sensor type

LYWSD03MMC/pvvx

**Comment by Ernst79** [comment]
Custom pvvx firmware is already supported by a core HA integration. But you have to set the advertising format to BTHome in the pvvx firmware settings. This isn’t the default. The BTHome integration should than pick up the sensor automatically.

**Comment by AdrianGarside** [comment]
That’s great news and explains why bthome wasn’t finding any of them. Is there any downside to bthome vs this custom component vs esphome?

**Comment by Ernst79** [comment]
No, not really. BLE monitor is using is own BLE collecting mechanism and does some averaging. Core HA integrations dont use averaging, so it updates more often. ESPhome can be helpful if the sensor is out of range, but in that case you can also use the ESP as ESPhome Bluetooth Proxy to forward messages.

**Comment by AdrianGarside** [comment]
Thank you for the super quick answers.

**Comment by AdrianGarside** [comment]
Flipped one of my sensors to broadcast as bthome, upgraded HA to 2023.2.5 and bthome still can't see the sensor :(.
