### ISSUE TITLE
Disable device Model/Manufacturer

### ISSUE THREAD

**Issue by EndermanAPM** [custom-components/ble_monitor#1139]
After installing the addon I made the mistake to leave the "discover new devices" option enabled. Now I have 70ish Apple iBeacon devices added to my HA. Is there any way to bulk remove/disable them and prevent them from showing up again? (No one uses any apple device in our household)

Best regards

**Comment by Ernst79** [comment]
I think the easiest is to remove and reinstall blemonitor. During setup, disable discover and only add the mac of your own sensor (write it down before uninstall)
