### ISSUE TITLE
[New Sensor]: Oras faucet

### ISSUE THREAD

**Issue by bipsendk** [custom-components/ble_monitor#1141]
### Sensor Description

Oras Faucet

### Additional information

washbasin faucet with builtin bluetooth

https://www.oras.com/en/design-lines/oras-electra/washbasin-faucet/6150FZ

The BLE module in this specific model is probably also used in other models.

![image](https://user-images.githubusercontent.com/8531428/221826038-fa3256b6-1841-4b28-b94b-a11dc3e905c2.png)
![image](https://user-images.githubusercontent.com/8531428/221826136-cb3d6205-5480-4dcf-8fa2-4bc91994c96c.png)

The number "2111007935" is the serial number of the faucet

The 0x64 value at offset 14 (index 4 i manufacturer data) (just before the serial number) indicates the battery level in percentage.

### BLE advertisements

```shell
2023-02-28 11:18:56.492 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] bathroom-bluetooth-proxy (c0:49:ef:65:1b:c8) [connectable]: EC:E0:26:98:92:79 AdvertisementData(local_name='ORAS', manufacturer_data={305: b'\x00d\x002111007935\x00    '}, tx_power=-127, rssi=-81) match: set()
```

**Comment by Ernst79** [comment]
support should be added in 11.10.0. Let me know if it works
