### ISSUE TITLE
Add battery level support for Oral B Toothbrush

### ISSUE THREAD

**Issue by sg1888** [custom-components/ble_monitor#1143]
I noticed that HomeAssistant recently added support for the Oral B toothbrush.  I also noticed the HA version includes a battery monitor.   Unfortunately the HA native add-on goes into "unavailable" after brushing is finished.  BLE_monitor is awesome in that it works and doesn't have this limitation!

Seeing as how ble_monitor already supports some features of the OralB toothbrush, It would be great if you could include the battery level functionality into ble_monitor as well.  I believe the code needed to add this feature is available here:

https://github.com/Bluetooth-Devices/oralb-ble/tree/main/src/oralb_ble

Thanks again for your help and support with such an awesome add-on!

**Comment by Ernst79** [comment]
Unfortunately, the battery info is being polled from the device, which means it needs a connection to get this data. This is out of the scope of BLE monitor, as BLE monitor only listens passively. 

However, I would advice you to ask the developer of the oralb integration if he could make the oralb toothbrush a so called "sleepy device". Just open a new issue on the HA core github. @bdraco will know what I mean with a "sleepy device".
