### ISSUE TITLE
[New Sensor]: YZ6045B 

### ISSUE THREAD

**Issue by Kotzende** [custom-components/ble_monitor#1144]
### Additional information

Cheap BLE Sensor from China [https://www.aliexpress.com/item/1005005163856194.html](https://www.aliexpress.com/item/1005005163856194.html)

Description:
The product name：BLE Temperature and humidity meter
APP：qaqa
Temperature range：-50℃~ 70℃
Humidity measurement range：10%~99%RH
The battery：CR2032*1
Temperature resolution：0.1℃
Accuracy of humidity measurement：±5%RH

 
![image](https://user-images.githubusercontent.com/124441290/223400334-1f4ac76a-dc1b-4e7e-b8a4-dc5aabdb8173.png)

### BLE advertisements

```shell
A french guy already decrypted the BLE [https://www.lprp.fr/2022/07/capteur-bluetooth-le-temperature-dans-domoticz-par-reverse-engineering-et-mqtt-auto-discovery-domoticz-et-home-assistant/](url)

"To get to this screen, you have to find the right device (usually LT_xxxx), connect to it, locate the service 0xFFE9 and its notification feature 0xFFE8, click on the little icon on the right to subscribe to notifications, and wait a few seconds to see the value line displayed, which in this example is (0x) AA-AA-A2-00-06-01-10-01-86-10-00-95-55; we are observing well:

AA-AA: the header
A2 : it is the hygrometry
00-06 : the size of the data is 6 bytes
01-10 : 0x0110, that is to say 256 in decimal, to divide by 10 : 25,6° (and that falls well, it is well what my thermometer displays !)
01-86 : 0x0186, that is 390 in decimal, to divide by 10 : 39%.
01 : battery indication ; I suppose that 1 means that the battery indicator is not displayed
00 : we are in degrees Celsius
95 : the checksum (and it is correct)
55 : the footer
We can now read the data and move on!"
```

**Comment by pvvx** [comment]
[Support new Tuya BLE?](https://github.com/custom-components/ble_monitor/issues/1063)
YZ6045B = [CX0726B](https://pvvx.github.io/CX0726B/)

**Comment by Ernst79** [comment]
@Kotzende I think this device uses a connection, to read the characteristics (data),
based on what you describe and what @pvvx says.

Connecting is not possible with BLE monitor. You can check to see if the sensor sends passive data by using this explanation.

https://custom-components.github.io/ble_monitor/sensor_request
