### ISSUE TITLE
BTHome: Add date and time (timestamp) in Unux format in seconds.

### ISSUE THREAD

**Issue by pvvx** [custom-components/ble_monitor#1146]
Add the date and time ([timestamp](https://en.wikipedia.org/wiki/Unix_time)) in Unix format in seconds to BTHome v1 (and v2).
32 bits words - second from 01.01.1970. 
They ask about time synchronization on different models of thermometers.
Also released custom fw for [MJWSD05MMC](https://pvvx.github.io/MJWSD05MMC) (used internal RTC clock).

**Comment by Ernst79** [comment]
Timestamp sensor has been added to BTHome v2.12.0 (both in v1 and v2). Object `0x50` has been reserved for timestamps in unix format, UTC timestamp. 

Home Assistant bthome integration has been updated and is merged in `dev`, will be included in 2023.7.
