### ISSUE TITLE
Qingping air monitor still not able to be added

### ISSUE THREAD

**Issue by uroshj** [custom-components/ble_monitor#1148]
The "normal" or "full" one can not be found.
When will this be available? It is a great device and if the lite one is ther, why not also the normal one?
Thanks!

**Comment by uroshj** [comment]
Curently I can only post product Details here. Will be home on friday evening, then I can check this.
https://www.qingping.co/air-monitor/overview

**Comment by Ernst79** [comment]
Try it with the first method, see "Getting BLE advertisements with the Home Assistant logger"

**Comment by DigiH** [comment]
This device is WiFi only.

https://www.qingping.co/air-monitor/specifications

**Comment by Ernst79** [comment]
BLE monitor is only able to use BLE data, but as @DigiH is saying, this device is using WiFi. So, it can't be included in BLE monitor. 

For further discussion, you can use this topic on the HA forum. 

https://community.home-assistant.io/t/add-support-for-qingping-air-monitor-model-number-cgs1/477959/6

**Comment by vladimir-lisin** [comment]
I've provided some solution at https://community.home-assistant.io/t/add-support-for-qingping-air-monitor-model-number-cgs1/477959/11, please fill free to connect your device ;)
