### ISSUE TITLE
[Bug]: JAALEE Sensor works in its app but does not get discovered

### ISSUE THREAD

**Issue by adekloet** [custom-components/ble_monitor#1155]
### What happened?

Hi,

Maybe a bug or maybe I am missi g something, but my Jaalee temp sensor is working in its app, but does not work in BLE HA, also not in active scanning mode. Is there something I can do to reset the sensor or something to get it discovered?

Thank you
![20230408_125726](https://user-images.githubusercontent.com/60182504/230717585-ab0fc52b-c57f-4b60-9bce-fce78af4a6ce.jpg)

### Sensor type

Jaalee bluetooth temp sensor

### Relevant log output

```shell
Nothing found in HA, it's working in the Jaalee app, and I can see BT Mac and packets in BLE scanner on Andriod.
```

**Comment by Ernst79** [comment]
Can you post some of the BLE messages from the android app?

**Comment by adekloet** [comment]
I think it's this one...

Message raw data:

03039FFE17169FFE000000000000000000000000000000000000000009FFE000B26ECA88D705

**Comment by adekloet** [comment]
![Screenshot_20230408_220116_BLE Scanner](https://user-images.githubusercontent.com/60182504/230740711-5143efe7-210c-4fa4-bedb-349dd5491ad4.jpg)

a screenshot

**Comment by adekloet** [comment]
> fine

Thanks Ernst, I think I found the problem. I think it was in relation to trying to add it with a BLE-gateway. It's a bit confusing. I found your explanation in regards to BT proxies and BLE gateway in another thread. It was a good writeup. Maybe you could add a link on your BLE integration Readme page to such an explanation, just a thought. I needed to find the sensor through the buildin BT on a raspberry pi, once I got that added to BLE I could start using the BLE gateway with an ESP32. (I am still playing with this YAML, as the examples are not very clear, we could use a separate github page with a clear walk through on BLE gateways and an howto add sensors to it. Happy 🐣.
