### ISSUE TITLE
[Bug]: How do I use a 24 bit token?

### ISSUE THREAD

**Issue by zhuayi** [custom-components/ble_monitor#1159]
### What happened?

The token obtained from Xiaomi Smart Door Lock Youth Edition is 24 bit

View URL: https://home.miot-spec.com/spec/loock.lock.v6

How will I use it?

### Sensor type

loock.lock.v6

### Relevant log output

```shell
{'did': '1012155258', 'name': '门锁', 'host': '', 'model': 'loock.lock.v6', 'token': '31594e77949012b62431ee23'}
```

**Comment by Ernst79** [comment]
Hi, 

the “token” is not the key you will need. For this device it is a bit hard to get the key, check this issue. https://github.com/custom-components/ble_monitor/issues/667

As you can see, @rezmus mentioned that it is only possible to extract the bind key with method 4 in the [FAQ](https://custom-components.github.io/ble_monitor/faq#how-to-get-the-mibeacon-v4v5-encryption-key) (Intercepting the MiHome application traffic)

**Comment by zhuayi** [comment]
Thank you for your reply, but that's not the case. The token I obtained through packet capture and database cracking is this 24 bit token. It is normal to use the same method to find tokens from other devices

It is normal for me to use Xiaomi Miot service

Can you try not to limit the number of token bytes?

**Comment by rezmus** [comment]
token is used for active bt connection (out of scope for this project). ble/beacon key is used for passive decrypt of data sent by device.

**Comment by Ernst79** [comment]
See the response of rezmus.
