### ISSUE TITLE
MCCGQ02HL sensors not found apart from battery and rssi

### ISSUE THREAD

**Issue by flodus** [custom-components/ble_monitor#1168]
Hello,

I have been using this integration for a long time with mostly xiaomi sensors and everything works great.

Recently, when I wanted to change the batteries of one of my MCCGQ02HL sensors, I reset it by mistake.
I had to reintegrate it into ble monitor but since then I can't do it anymore.
I recover the device well but I only have the battery and rssi sensors (indicated as unavailable by the way), no more other sensors, open/close, light...
While for all my other MCCGQ02HL sensors it still works.

I wanted to install the official version of the bluetooth addon but cannot find my dongle sena ud100
I thought it was due to a hardware access conflict between ble and the official addon.
So I uninstalled ble to just try the official addon, but still couldn't install it, because it couldn't find the dongle (hci and usb difference maybe...)
I reinstall ble, and there disaster I have to reintegrate all my sensors, but none recovers opening or light sensors, just battery and rssi !!!!
I had to restore my home-assistant to recover everything as before...
So I installed the esphome component miot_mccgq02hl (https://github.com/dentra/esphome-components/tree/master/components/miot_mccgq02hl) on an esp32, and there I retrieve the information from my recalcitrant MCCGQ02HL.
I don't want to use different hardware and different addons... I really like my sena ud100 + ble component couple....

The problem had already been encountered it seems to me, but I don't know if it's with ble monitor or the official integration...
Is there a way to recover my MCCGQ02HL with all its sensors in the ble integration?

BLE 11.11.1
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Interface utilisateur : 20230503.3 - latest

Thank you for your work, and for your support.

**Comment by Ernst79** [comment]
Most likely, the battery change has reset the encryption key. First, try to add it to MiHome again. Next, get the encryption key with one of the method in the FAQ, is has probably changed. Then, change the encryption key in the BLE monitor settings.  Also note that Home Assistant OS 10.0 and 10.1 have a serious  Bluetooth bug at the moment. Try to downgrade to 9.5

**Comment by flodus** [comment]
Thank you for the quick reply !

For the key I already changed it in ble monitor with this app
https://github.com/Maxmudjon/Get_MiHome_devices_token

and I thought the same at first that it was a reset + key problem... but the problem occurred for all the other sensors when reinstalling ble monitor.

For the home-assistant version, I will try, but the problem is not new... I tried to solve it by myself before writing on this issue... I didn't really want to downgrade my version. I think I'll check HA's logs to see when they improve bluetooth, and check back on github if there's no change... I thought using hci will avoid HA's bluetooth issues...

thanks again

**Comment by Ernst79** [comment]
BLE monitor shouldnt be affectie, but using Bluetooth integration might case issues tesulting in a failing Bluetooth dongle. If you post some logs gere, i can check if i see sonething.

**Comment by flodus** [comment]
thanks,

The official bluetooth integration isn't installed on my home-assistant.
Here the logs of ble monitor when i try to configure my MCCGQ02HL  :

`Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:583
Integration: Capteur (documentation, issues)
First occurred: 20:48:03 (17 occurrences)
Last logged: 21:00:23

Error adding entities for domain sensor with platform ble_monitor
Error while setting up ble_monitor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = float(value)  # type:ignore[arg-type]
ValueError: could not convert string to float: 'unavailable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 846, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.ble_battery_e4aaec3705ad has device class battery, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unavailable (<class 'str'>)
`

**Comment by flodus** [comment]
ok I'm really confused... I deleted my device again, I integrated it again, put the ble key... restarted home-assistant... and my MCCGQ02HL was found...
I did not understand anything ! ;)

But it works so I'm good for now! ;) thanks for the support!
