### ISSUE TITLE
[New Sensor]: add another Qingping CGDN1

### ISSUE THREAD

**Issue by hi-pon** [custom-components/ble_monitor#1170]
### Sensor Description

Qingping CGDN1

### Additional information

Hi.
I have a Qingping CGDN1.
It's already supported, but my device ble cannot parse.
So I getted a hcidump, please check it.

MAC: 54:48:E6:8F:91:48
data1
PM2.5: 7
PM10: 7
CO2: 773
Temperature: 31.4 Celcius
Humidity: 35%

data2
PM2.5: 12
PM10: 12
CO2: 8726
Temperature: 30.1 Celcius
Humidity: 40%

### BLE advertisements

```shell
$ sudo hcidump --raw hci
HCI sniffer - Bluetooth packet analyzer ver 5.55
device: hci0 snap_len: 1500 filter: 0x2
< 01 0C 20 02 00 01
> 04 0E 04 01 0C 20 00
< 01 0B 20 07 01 10 00 10 00 00 01
> 04 0E 04 01 0B 20 00
< 01 0C 20 02 01 01
> 04 0E 04 01 0C 20 00
> 04 3E 2B 02 01 00 00 48 91 8F E6 48 54 1F 02 01 06 1B 16 CD
  FD 88 0E 46 91 8F E6 48 54 01 04 39 01 59 01 12 04 07 00 07
  00 13 02 05 03 DF
> 04 3E 27 02 01 04 00 48 91 8F E6 48 54 1B 1A 09 51 69 6E 67
  70 69 6E 67 20 41 69 72 20 4D 6F 6E 69 74 6F 72 20 4C 69 74
  65 E3

-----

$ sudo hcidump --raw hci
HCI sniffer - Bluetooth packet analyzer ver 5.55
device: hci0 snap_len: 1500 filter: 0x2
< 01 0C 20 02 00 01
> 04 0E 04 01 0C 20 00
< 01 0B 20 07 01 10 00 10 00 00 01
> 04 0E 04 01 0B 20 00
< 01 0C 20 02 01 01
> 04 0E 04 01 0C 20 00
> 04 3E 2B 02 01 00 00 48 91 8F E6 48 54 1F 02 01 06 1B 16 CD
  FD 88 0E 46 91 8F E6 48 54 01 04 2A 01 B2 01 12 04 0C 00 0C
  00 13 02 2E 1F E8
> 04 3E 27 02 01 04 00 48 91 8F E6 48 54 1B 1A 09 51 69 6E 67
  70 69 6E 67 20 41 69 72 20 4D 6F 6E 69 74 6F 72 20 4C 69 74
  65 EA
```

**Comment by DigiH** [comment]
Hi @hi-pon,

Just out of curiosity, which firmware version does your CGDN1 have?

It seems that there is just an additional octet added to the relevant encoded data, and when taken into account this is then decodable exactly like the existing CGDN1 implementation. So it would be interesting to know if it is a general firmware change for all devices or a change with a new hardware revision introduction.

From your above dumps I get the following from initial tests - slight deviation on the second dump data, but I'd put that down to minimal reading time differences.

```
{"brand":"Qingping","model":"Air Monitor Lite","model_id":"CGDN1","type":"AIR","tempc":31.3,"tempf":88.34,"hum":34.5,"pm25":7,"pm10":7,"co2":773}
```

```
{"brand":"Qingping","model":"Air Monitor Lite","model_id":"CGDN1","type":"AIR","tempc":29.8,"tempf":85.64,"hum":43.4,"pm25":12,"pm10":12,"co2":7982}
```

**Comment by DigiH** [comment]
@Ernst79, could this be because of a possible extra octet at the end of the encoded data? I'm never that sure with the hcidumps ;) 

@hi-pon - Just out of curiosity, which firmware version does your CGDN1 have?

Otherwise the encoded data looks fine and should be decoded correctly with existing implementations, apart from some slight deviations with the second dump/given data, which I'd put down to minimal reading time differences.

```
{"brand":"Qingping","model":"Air Monitor Lite","model_id":"CGDN1","type":"AIR","tempc":31.3,"tempf":88.34,"hum":34.5,"pm25":7,"pm10":7,"co2":773}
```

```
{"brand":"Qingping","model":"Air Monitor Lite","model_id":"CGDN1","type":"AIR","tempc":29.8,"tempf":85.64,"hum":43.4,"pm25":12,"pm10":12,"co2":7982}
```

**Comment by Ernst79** [comment]
I tried to use the raw data with the parse_data service of BLE monitor. I used your data (first long message). It should just parse fine. Are you sure that the BLE message arrive in HA? Enable debug logging for BLE monitor to find out. 

![image](https://github.com/custom-components/ble_monitor/assets/24375847/b91aaadb-82d1-463b-88bb-3ad88e0c2ac0)

**Comment by hi-pon** [comment]
Hi @Ernst79 
Thankyou for reply and sorry for late responding.
I've resumed this effort.
I tried again and was indeed able to retrieve the values!
