### ISSUE TITLE
After latest update entity card is showing non-rounded value

### ISSUE THREAD

**Issue by fokcuk** [custom-components/ble_monitor#1174]
![image](https://github.com/custom-components/ble_monitor/assets/84503931/a6d83921-6ff5-4cfa-b908-0ba4d47e888b)
After updating to the latest version, HA is not rounding the values on the entity card

**Comment by Ernst79** [comment]
You closed the issue, I assume it is solved?

**Comment by Ernst79** [comment]
No problem. I did make a change with respect to the precision of sensors, but HA should be able to handle this now by itself. BLE monitor will pass on a default precision to HA. Not sure if all custom cards respect that. I only know that the widgets of the android companion app do not respect the default precision, but an issue has been created for that.

**Comment by fokcuk** [comment]
I used the sensor in [lovelace-multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row)
But because it was part of the entity card, I thought that it was due to the BLE monitor update.
lovelace-multiple-entity-row is now using a **format: precision2** option. Once I worked it out, I just closed the issue as it was not BLE monitor that was causing it =)
