### ISSUE TITLE
[Bug]: Shelly BLU Button1 - No button sensor

### ISSUE THREAD

**Issue by andrewjswan** [custom-components/ble_monitor#1185]
### What happened?

I added Shelly BLU to the BLE Monitor as:
```
  - mac: '5C:XX:XX:XX:XX:XX'
    track_device: True
    tracker_scan_interval: 30
    consider_home: 180
    name: 'Shelly BLU'
    reset_timer: 1
```
But the tracker, rssi, and battery sensors appeared. The senor for the button did not appear.
Am I missing something? Or did I do something wrong?

### Sensor type

Button

**Comment by andrewjswan** [comment]
> I'll look into it.

Thank you, I will wait for the decision. Still, so far the BLE Monitor is more convenient than the built-in BT in the HA.

**Comment by andrewjswan** [comment]
@Ernst79 Any news? :)

**Comment by andrewjswan** [comment]
@Ernst79 How are you :)

**Comment by Ernst79** [comment]
@andrewjswan I'm fine :smile Sorry, i have been too busy with a lot of other things. The BLU button is working with the Home Assistant core Bluetooth integration + bthome integration, so I would suggest you try that in the meantime. Holiday period is coming here, so I don't expect to have time shortly. Again, sorry, but time is limited. Of course, any help by others is welcome.

**Comment by andrewjswan** [comment]
I get it, it's a shame. But that's life. I didn't want to customize the built-in, it will only get in the way and find unnecessary entities, but it seems there is no other choice.

**Comment by Ernst79** [comment]
The button sensor is added in 12.6.0 (as well as all other BTHome sensors)

**Comment by andrewjswan** [comment]
Thanks!
