### ISSUE TITLE
[New Sensor]: Air Quality Sensor / RCXAZ / Nobito (Shenzen) Technology

### ISSUE THREAD

**Issue by ge33ek** [custom-components/ble_monitor#1191]
### Sensor Description

Air Quality Sensor by RCXAZ & Nobito (Shenzen) Technology

### Additional information

Available here;

https://www.aliexpress.com/item/1005005473581314.html?spm=a2g0o.order_list.order_list_main.11.21ef1802nmwsfM

Can connect and receive a notify/read stream of data from the device using various Bluetooth Monitor apps, but can't decipher the hex etc. (beyond my skillset) - I can get BLE Monitor to pick up the device and do see active polling once i've plugged in the MAC Address;
2023-06-08 19:36:20.205 INFO (Thread-20) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 3883170eaef4: service data: []manufacturer specific data: [b'\t\xff\xff\xff8\x83\x17\x0e\xae\xf4']local name: XS-AEF4UUID16: 24775,UUID128: None
2023-06-08 19:36:20.644 INFO (Thread-20) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 3883170eaef4: service data: []manufacturer specific data: [b'\t\xff\xff\xff8\x83\x17\x0e\xae\xf4']local name: XS-AEF4UUID16: 24775,UUID128: None

![20230608_094543000_iOS](https://github.com/custom-components/ble_monitor/assets/21974146/ca65602a-72bc-4b60-a2cc-554922a89a25)
![20230608_094211000_iOS](https://github.com/custom-components/ble_monitor/assets/21974146/46c1bfe0-400d-4822-82a9-829638e81a69)
[LBX_LOGS_2023-06-08_20-01.csv](https://github.com/custom-components/ble_monitor/files/11686744/LBX_LOGS_2023-06-08_20-01.csv)

### BLE advertisements

```shell
Attached as CSV using subscription to notify feed in LightBlue
```

**Comment by KittyFort** [comment]
I think RCXAZ might have a family of devices with multiple sensors.

I found this repo for using ESPHome to read from a 5-in-1 BT sensor:
https://github.com/mheistermann/esphome-component-rcxazair

Maybe it'll be helpful for supporting other devicecs from the family, if it's not relevant to the actual 9-in-1 device. I've got the 9-in-1, and it's significantly easier to find.

**Comment by ge33ek** [comment]
> I think RCXAZ might have a family of devices with multiple sensors.
> 
> I found this repo for using ESPHome to read from a 5-in-1 BT sensor: https://github.com/mheistermann/esphome-component-rcxazair
> 
> Maybe it'll be helpful for supporting other devicecs from the family, if it's not relevant to the actual 9-in-1 device. I've got the 9-in-1, and it's significantly easier to find.

Thank you @KittyFort - I built a ESP with ESPHome and added the config file, but couldn't get it to compile - perhaps code it is out sync with latest ESPHome build. In saying that, whilst this would be a step forward, mine is the 9-1 and so i'd really like to try and capture all the properties if possible. Even if i could get it working i'd still be missing a bunch.

**Comment by KittyFort** [comment]
The 5-in-1 and the 9-in-1 share a lot of code - to the point that you can run the 5-in-1 code as-is and get the sensors established in that. I've already tested it with my unit.

I've submitted a PR to fix the build issues on that repo. Fork it or grab a local copy while we see how the PR goes.

I'm looking at the additional sensors, but I don't know what my timeline is for this.

**Comment by KittyFort** [comment]
Build fix PR merged into mainline on the `esphome-component-rcxazair` repo. So you can get 5-in-1 functionality out of it now, @ge33ek. What you'll be missing is the particulate matter sensors.

You'll have to wait for new sensor functionality in a separate PR. I've got some stuff working on it, but it's not complete, has issues and the code for that is filthy. I'll get it into a PR when it's cleaned up.

As far as to how it might relate to this project, the sensor is pretty straightforward:
1. Pair to the device.
2. Listen to the GATT service and characteristic
3. Switch message types based on the first 4 bytes
4. Each message has data from between 1-3 sensors in byte pairs, followed by a lone byte which may be checksum or something.
5. Convert the byte pairs to decimal and you've got a number close to the LCD readout. Any decimal places are implied, so you'll have to math it out.

**Comment by Ernst79** [comment]
Hi guys. As far as I understand, this device uses a connection/pairing to read the characteristics/data. BLE monitor is not supporting connecting to devices. So, I'm closing this issue here. Please continue this discussion here

https://github.com/mheistermann/esphome-component-rcxazair/issues/3

**Comment by daweizhangau** [comment]
Hi guys,

Here is my discovery. 

The Formula: 

checksum = (Σ(byte[i] XOR i) for i=0 to n-1) & 0xFF
(Where index 0 starts at the 0x23 header prefix).

Python Implementation:
```python
def calculate_rcxaz_checksum(payload: bytes) -> int:
    total_sum = 0
    for index, byte_value in enumerate(payload):
        total_sum += byte_value ^ index
    return total_sum & 0xFF
```

BTW, check out this full implementation: https://github.com/daweizhangau/ha-rcxaz-air-quality-ble
