### ISSUE TITLE
[New Sensor]: AT02 grill thermometer

### ISSUE THREAD

**Issue by arcidodo** [custom-components/ble_monitor#1198]
### Sensor Description

AT-02 BBQ Dome Thermometer

### Additional information

https://nl.aliexpress.com/item/1005004235693383.html

i uploaded an Home Assistant log i dont know if this is enough if more info is needed please tell me. 

the advertised name is "AT-02"

![at02](https://github.com/custom-components/ble_monitor/assets/678514/74eca377-b440-4b5e-8518-942ca4675dbb)

**Comment by arcidodo** [comment]
[config_entry-bluetooth-bd3538b338957aad39d69d6e466ec0b5.json.txt](https://github.com/custom-components/ble_monitor/files/11758662/config_entry-bluetooth-bd3538b338957aad39d69d6e466ec0b5.json.txt)

**Comment by syepes** [comment]
Looks like this device requires an active connection, I have tried using `bluetoothctl connect DD:49:AF:6A:D2:BD` on the OS level and it connect but then drops.

`2023-06-20 22:45:15.696 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] BLE-Proxy (4c:75:25:d6:6c:e8) [connectable]: DD:49:AF:6A:D2:BD AdvertisementData(local_name='AT-02', manufacturer_data={53949: b'j\xafI\xdd\x00'}, service_uuids=['0000cee0-0000-1000-8000-00805f9b34fb'], tx_power=-127, rssi=-93) match: set()`

**Comment by andriuskr** [comment]
Anything new on integration of this thermometer ?

**Comment by NiMa08** [comment]
Would also like to know how progress is?

**Comment by NiMa08** [comment]
Anything new?

**Comment by kamermcw** [comment]
Code cracked by https://community.home-assistant.io/t/bbq-grill-thermometer-at-02/584078/5
How do we get it in Homeassistant?

**Comment by Ernst79** [comment]
Unfortunately, BLE monitor is only able to use passive scanning, not active connections. So, that means we can't add it to BLE monitor. ESP Home is able to setup connections to a device, so you could try that. 

https://esphome.io/components/ble_client.html?highlight=ble

I'm closing the issue here, as we can't implement this into BLE monitor. Please continue the discussion in the above mentioned topic.
