### ISSUE TITLE
[Bug]: Sensors stopped reporting after HA update

### ISSUE THREAD

**Issue by Draghmar** [custom-components/ble_monitor#1205]
### What happened?

After updating to HA 2023.7.1 all my sensors stopped reporting. There's log entry related to that (I think). I had BLE Monitor (12.2.1-beta) set up through yaml but I did remove it and tried to use UI - the same result. I have three ATC sensors and one not modified LYWSDCGQ. All of them aren't reporting.

### Sensor type

ATC (Atc1441) and LYWSDCGQ

### Relevant log output

```shell
Logger: homeassistant.components.sensor
Source: custom_components/ble_monitor/sensor.py:450
Integration: Sensor (documentation, issues)
First occurred: 15:16:20 (40 occurrences)
Last logged: 15:16:30

Error adding entities for domain sensor with platform ble_monitor
Error while setting up ble_monitor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/ble_monitor/sensor.py", line 450, in async_added_to_hass
    if old_state.attributes["unit_of_measurement"] in [UnitOfTemperature.CELSIUS, UnitOfTemperature.FAHRENHEIT]:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SensorExtraStoredData' object has no attribute 'attributes'
```

**Comment by Ernst79** [comment]
Did you use UI setup with the Beta version, or with the normal release?

**Comment by Draghmar** [comment]
I didn't touch integration itself. I simply disabled integration, commented yaml, restarted HA, enabled BLE Monitor through UI and...that's it. What interesting was the fact that all sensors were there. Maybe that's because of the restore state set to true?

**Comment by Draghmar** [comment]
Hm...that's kinda weird. I disabled restoring state through the UI and restarted HA. Error is gone and reporting is back. So it looks like that was causing the issue.

**Comment by Ernst79** [comment]
Ok, so it you use the beta version. I made some changes in the restore state function. I think it needs some more testing 😄

**Comment by Ernst79** [comment]
Can you try with 12.2.2-beta? I think it should be fixed with that version
