### ISSUE TITLE
[Bug]: 'Unit of measurement' no longer available

### ISSUE THREAD

**Issue by xelemorf** [custom-components/ble_monitor#1209]
### What happened?

'Unit of measurement' (Home Assistant sensor property) option is missing for the following sensor types since the last two published updates (got the update today and earlier one couple of days ago) on Passive BLE Monitor:
- Humidity: %
- Battery: %
- Rssi: dbi?
- Voltage: V

Unit of measurement is still available for temperature reading: Celsius or Kelvin or Fahrenheit

Using Xiaomi Mi Temperature and Humidity Monitor 2 (LYWSD03MMC) with ATC unencrypted firmware (nothing changed on device level recently)
ATC Firmware details: https://github.com/atc1441/ATC_MiThermometer 

### Sensor type

LYWSD03MMC

**Comment by Ernst79** [comment]
See also #1199 where we are looking into this issue

**Comment by magusagnus** [comment]
I am having the same issue, didn't try to remove and re-add it. I'll try it and tell if it worked for me

**Comment by xelemorf** [comment]
> I am having the same issue, didn't try to remove and re-add it. I'll try it and tell if it worked for me

Removing and re-adding all relevant device integrations fixed the issue indeed, thank you!

**Comment by xelemorf** [comment]
> @xelemorf did you try removing the integration from HA config panel, restarting HA, then adding it again? That solved most of the issues for me, except rssi and power.

Removing and re-adding all relevant device integrations fixed the issue indeed, thank you!

**Comment by tcirstea** [comment]
Just to confirm that the expectations for anyone using LYWSD03MMC and upgrading from past versions:
- Delete the integration and all devices from HA
- Restart HA
- Add devices back

That seems like a significant breaking changes that should be explicitly called out if that's the case.

This is also related to https://github.com/custom-components/ble_monitor/issues/1199
