### ISSUE TITLE
[Bug]: Not restoring old states after restart

### ISSUE THREAD

**Issue by criticallimit** [custom-components/ble_monitor#1210]
### What happened?

After restart of HA old states are not restored, no matter if "restore state after a restart" is set to false or true

![Bildschirmfoto](https://github.com/custom-components/ble_monitor/assets/5613811/bb99be06-43c9-42ee-9e85-86aad34a9fff)

![Bildschirmfoto 1](https://github.com/custom-components/ble_monitor/assets/5613811/aadbc1f7-4600-4815-881e-c300d56e120c)

**Comment by Ernst79** [comment]
Could you try 12.3.2-beta. That version should fix the issue.

**Comment by criticallimit** [comment]
fixed with 12.3.2-beta

thanx
