### ISSUE TITLE
[Bug]: Can not install it on macOS + home assistant

### ISSUE THREAD

**Issue by tpian928** [custom-components/ble_monitor#1211]
### What happened?

The `custom_components/ble_monitor` integration seems to be encountering compatibility issues on macOS. When attempting to load the component, Home Assistant encounters an unexpected exception and fails to import the module. The error log is as follows:

```
ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.ble_monitor
Traceback (most recent call last):
  File ".../homeassistant/loader.py", line 725, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  ...
OSError: dlopen(libc.so.6, 0x0006): tried: 'libc.so.6' (no such file), '/usr/local/lib/libc.so.6' (no such file), '/usr/lib/libc.so.6' (no such file), '/Users/myname/Documents/HomeAssistant/libc.so.6' (no such file)
```

**Comment by Ernst79** [comment]
I think this issue ( 2nd post) largely explains why you get this error

https://github.com/Adam-Langley/pybleno/issues/48

the situation is more or less the same for BLE monitor, we use BluetoothHCI (by using [aioblescan](https://github.com/frawau/aioblescan) to scan for BLE data, which apparently can’t be used on MacOS. There seems to be no easy solution, other than than completely rewrite BLE monitor and use a different mechanism to collect BLE. 

One option can be that we are going to use the Bluetooth integration to collect the data. This would also have the benefit that aioblescan wont interfere with the HA Bluetooth integration, but this would mean a major change, for which I don’t have time in the near future.

**Comment by tpian928** [comment]
Thank you for your reply, I will try other ways to solve it or use docker.
