### ISSUE TITLE
[Bug]: Percentages are incorrectly calculated and displayed

### ISSUE THREAD

**Issue by vsimanin** [custom-components/ble_monitor#1219]
### What happened?

In the statistics card, percentages began to be incorrectly calculated after updating Passive BLE to 12. * The sensor itself correctly reports percentages.  Besides!  The % symbol is no longer displayed after the number.  This applies, for example, to the remaining charge of the device and humidity.  Perhaps this is the key to the solution, i.e.  due to the absence of the % symbol, HA does not divide the reading by 100. Perhaps ...

![Screenshot_2023-08-06-10-25-50-89_c3a231c25ed346e59462e84656a70e50](https://github.com/custom-components/ble_monitor/assets/9263449/54ea1bea-594b-4ccb-855a-174accd1999e)
![Screenshot_2023-08-06-10-27-39-50_c3a231c25ed346e59462e84656a70e50](https://github.com/custom-components/ble_monitor/assets/9263449/58a4fcab-eea5-4282-85e2-06b69348780d)

passive ble vs zigbee sensors
![Screenshot_2023-08-06-10-39-42-67_c3a231c25ed346e59462e84656a70e50](https://github.com/custom-components/ble_monitor/assets/9263449/8d0b8a3f-fe84-4857-a51b-607ce7101a1a)

### Sensor type

humidity, battery level

### Relevant log output

Entity sensor.ble_humidity1 (<class 'custom_components.ble_monitor.sensor.HumiditySensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; expected one of ['%']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.ble_battery_clock1 (<class 'custom_components.ble_monitor.sensor.BatterySensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('battery') it is using; expected one of ['%']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by Ernst79** [comment]
I assume you have installed the latest version? 

Could you try to remove the device and readd it, via the ble monitor configuration?

**Comment by vsimanin** [comment]
> I assume you have installed the latest version?
> 
> Could you try to remove the device and readd it, via the ble monitor configuration?

Yes, and I have all the devices added through integration, and not manually.

**Comment by Ernst79** [comment]
Yes, but can you try to remove one device and re-add it, some people say that this solves the issue

**Comment by Kaibob2** [comment]
I tried removing one device and re-adding it via the ble monitor configuration.
Sadly this doesn't bring back the `unit_of_measurement` aka "%" for `sensor.ble_humidity_xxx` and `sensor.ble_battery`

**Comment by vsimanin** [comment]
Important!  The problem is resolved if you disable the "Restore state on reboot" option in the integration settings.  After use, all sensors have a unit of measurement (% humidity and battery charge)

**Comment by Kaibob2** [comment]
> Important! The problem is resolved if you disable the "Restore state on reboot" option in the integration settings. After use, all sensors have a unit of measurement (% humidity and battery charge)

Confirmed.

**Comment by Ernst79** [comment]
You can enable "Restart state on reboot" afterwards. There is/was some wrong info stored in the HA database (as a result of a earlier BLE monitor version with a bug). 

To Fix:
- Disable "Restart state on reboot"
- Restart 
- Wait a while till sensor data start to be updated again
- Re-enable "Restart state on reboot" again
- Restart again

And it should be fine again. 

See also #1223
