### ISSUE TITLE
[Bug]: Stopped working (integration not loaded), cannot reinstall (Config flow could not be loaded)

### ISSUE THREAD

**Issue by gcf117** [custom-components/ble_monitor#1221]
### What happened?

The integration was working without any problem until a couple of days ago.
Then the devices were missing, and it was marked "not loaded" in the integrations panel.
Removing it was also not working, either in active or disabled status.
I had to manually remove the directory and the /.storage/core.config_entry.
Now, when I try to reinstall it through HACS, I get:
Config flow could not be loaded: {"message":"Invalid handler specified"}
Any suggestions?
Thanks in advance

**Comment by gcf117** [comment]
Forgot to mention: Home Assistant 2023.2.2
Frontend 20230202.0 - latest

**Comment by Ernst79** [comment]
Your HA version is too old. Either update HA or use BLE monitor 11.x.x
(latest release that starts with 11)

Op vr 11 aug. 2023 10:47 schreef gcf117 ***@***.***>:
