### ISSUE TITLE
[Bug]: Entity is using native unit of measurement 'None'

### ISSUE THREAD

**Issue by mate-b** [custom-components/ble_monitor#1223]
### What happened?

Xiaomi temperature and humidity sensors show the error messages attached below related to unit of measurement.

Component version: 12.3.2
Home Assistant version: 2023.8.3
Operating System version: 10.4

### Sensor type

Xiaomi LYWSD03MMC

### Relevant log output

```shell
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:659
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 15:58:40 (32 occurrences)
Last logged: 15:58:40

Entity sensor.ble_rssi_shed_door_sensor (<class 'custom_components.ble_monitor.sensor.MeasuringSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('signal_strength') it is using; expected one of ['dBm', 'dB']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.ble_humidity_shed_temp (<class 'custom_components.ble_monitor.sensor.HumiditySensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; expected one of ['%']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.ble_battery_shed_temp (<class 'custom_components.ble_monitor.sensor.BatterySensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('battery') it is using; expected one of ['%']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.ble_voltage_shed_temp (<class 'custom_components.ble_monitor.sensor.MeasuringSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.ble_rssi_shed_temp (<class 'custom_components.ble_monitor.sensor.MeasuringSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('signal_strength') it is using; expected one of ['dBm', 'dB']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by Ernst79** [comment]
Try to remove the sensor from BLE monitor, restart HA and add it again.

**Comment by mate-b** [comment]
Tried it several times with no luck. The device runs ATC firmware just like my other devices. Those don’t generate this error message.

**Comment by Ernst79** [comment]
Do you restore the state upon restart? This is one of the options of BLE monitor? Can you check this setting?

**Comment by mate-b** [comment]
Yes, the checkbox was checked. I restarted the system without restoring the state and so far so good, no error messages came up. Thank you.

**Comment by Ernst79** [comment]
ok, but it is still a bug, as it should also work with the checkbox checked. 

At least, I now know that it happens during the startup, when it restores the state from the database. It might very well be possible that if you now enable it again, it will still be OK. But I'm not 100% sure. 

I suspect that there was some wrong data in the HA database, which is being restored after a restart, giving the errors you have. It might be cleared now.

**Comment by mate-b** [comment]
I can confirm that states remained correct after enabling the setting and giving it a restart again.

**Comment by mate-b** [comment]
You’re right since some voltage and rssi entities (not only temp/humidity sensors but Xiaomi door sensors as well) produced the same issue. For now, I’m happy with the workaround, thanks again for the help.
