### ISSUE TITLE
[Query] High CPU usage when using Passive BLE

### ISSUE THREAD

**Issue by JIBYC** [custom-components/ble_monitor#1227]
After some testing I've identified that the Passive BLE extension increases the CPU usage on my device by a factor of five. 

Is there anything that can be done to reduce it or identify if there's something not quite right?

**Comment by Ernst79** [comment]
I’m not sure what I can do to fix that. How high is high? Is it constantly? On what kind of machine are you running HA?

**Comment by JIBYC** [comment]
Error in my setup. Disregard
