### ISSUE TITLE
[Documentation]: Fail to install bluepy (missing libglib2.0-dev)

### ISSUE THREAD

**Issue by maorcc** [custom-components/ble_monitor#1237]
### What happened?

Installation of `bluepy` may fail when following the [current instructions](https://custom-components.github.io/ble_monitor/faq#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key:~:text=Example%3A-,python3%20get_beacon_key.py,-AB%3ACD%3AEF).
The current instructions here are:
```
pip3 install bluepy
```
As explained [here](https://github.com/IanHarvey/bluepy/issues/420#issuecomment-690341146), the following command may also be needed:
```
apt-get install python3-pip libglib2.0-dev
```
I suggest mentioning it in the ble_monitor doc above too.

**Comment by Ernst79** [comment]
Thanks, changed it

![image](https://github.com/custom-components/ble_monitor/assets/24375847/a3fb329b-c721-42fa-a5c2-775cbe3588f6)
