### ISSUE TITLE
[Bug]: All Xiaomi stopped sending their data at the same time

### ISSUE THREAD

**Issue by donparlor** [custom-components/ble_monitor#1252]
### What happened?

All Xiaomi stopped sending their data at the same time
<img width="1530" alt="Capture d’écran, le 2023-10-19 à 17 23 15" src="https://github.com/custom-components/ble_monitor/assets/97048708/8bf002d3-fad9-402d-989d-009ea3c7ba40">

Is there an update problem with any recent Home Assistant update?

**Comment by Ernst79** [comment]
Try a full system reboot (not only HA, but a system reboot). I suspect that the Home Assistant Os update caused this, as it has several Bluetooth updates. Restarting will load the correct firmware/software

**Comment by donparlor** [comment]
You were correct. All good after restart.

**Comment by donparlor** [comment]
I close it now
