### ISSUE TITLE
[New Sensor]: add support for PTX BLE Wireless Switch 090615.remote.btsw1

### ISSUE THREAD

**Issue by mywp** [custom-components/ble_monitor#1255]
### Sensor Description

PTX BLE Wireless Switch 090615.remote.btsw1

### Additional information

PTX BLE Wireless Switch 
   NAME:     PTX wireless switch(bluetooth version)
   MODEL:    090615.remote.btsw1

**Comment by Ernst79** [comment]
Without more info I can’t do anything, we will need BLE date and the format that is used.

**Comment by slm85kbh** [comment]
I have done a `sudo hcidump --raw hci > dump.txt` and attached the dump.txt file, the device was in pairing mode at the time (3 clicks and hold untill slow blink).
[dump.txt](https://github.com/custom-components/ble_monitor/files/14105328/dump.txt)

**Comment by slm85kbh** [comment]
I also paired the switch to my phone running nRF Connect and logged while doing it:
[Log 2024-01-31 00_44_29.txt](https://github.com/custom-components/ble_monitor/files/14111294/Log.2024-01-31.00_44_29.txt)

**Comment by mywp** [comment]
> Without more info I can’t do anything, we will need BLE date and the format that is used.
NAME:     PTX-1
BLE KEY:  a74510b40386d35ae6227a7451efc76e
MAC:      A4:C1:38:A5:B9:AD
MODEL:    090615.remote.btsw1
[ptx-1.txt](https://github.com/custom-components/ble_monitor/files/14391319/ptx-1.txt)

**Comment by Ernst79** [comment]
I finally had some time to look into it. Looks like it is possible to add this

```
result  ({'rssi': -52, 'mac': 'A4C138A5B9AD', 'type': 'PTX', 'packet': 4, 'firmware': 'Xiaomi (MiBeacon V5 encrypted)', 'data': True, 'one btn switch': 'toggle', 'button switch': 'single press'}, None)
```

**Comment by Ernst79** [comment]
PR is ready
