### ISSUE TITLE
Anki (Over)Drive

### ISSUE THREAD

**Issue by Megachip** [custom-components/ble_monitor#1256]
### Sensor Description

Z.  Drive

### Additional information

https://www.digitaldreamlabs.com/products/overdrive
https://web.archive.org/web/20191217053551/https://www.anki.com/en-us/overdrive.html

### BLE advertisements

```shell
0x0201061107F48D4D9CD80B81837E408661EFBE15BE09FFBEEF0013095473D80F091060300120202020447269766500020A00
```

**Comment by Ernst79** [comment]
This device will need to set up a BLE connection, which is not possible with BLE monitor (out of the scope of this project, we only support passive scanning. So, unfortunately, we can’t support this device.
