### ISSUE TITLE
[New Sensor]: Grundfos MI401

### ISSUE THREAD

**Issue by tokkeherfst** [custom-components/ble_monitor#1258]
### Sensor Description

Grundfos MI401 ALPHA Reader

### Additional information

Hi, I would like to request implementation of a sensor for the MI401 pump data reader.
MI401 ALPHA Reader
(https://product-selection.grundfos.com/products/alpha-reader/mi401-alpha-reader-98916967?pumpsystemid=2204502992&tab=variant-specifications)

I have been monitoring pump flow rate and pressure on my old cacti setup with this Alphadecoder python script
(https://github.com/JsBergbau/AlphaDecoder - in German only)

Some reverse engineering details are already described on that page so there should be a good base for a sensor already there.

### BLE advertisements

```shell
will upload dump file, may contain data from other devices
```

**Comment by tokkeherfst** [comment]
[dump.txt](https://github.com/custom-components/ble_monitor/files/13250332/dump.txt)

**Comment by tokkeherfst** [comment]
And some sample output from the AlphaDecoder script which might help

root@cacti:/home/admin/AlphaDecoder# ./AlphaDecoder.sh 
Wenn keine Daten ausgegeben werden, bitte prüfen, ob als root läuft und der AlphaReader eingeschaltet und in Empfangsreichweite ist
Set scan parameters failed: Input/output error
Volumenstrom: 645
Förderhöhe: 1.18 Meter
Pumpentemperatur: 10 °C
Batteriestatusindikator: 03
Pumpenkennung: 0598
Signalstärke: -64 dBm
Datenprotokollversion: 01
Unbekannt 1: 1C
Pumpenmodus: Konstantdifferenzdruck Stufe 1 (07)
Unbekannt 2: 01BC
Unbekannt 3: 01 BE 00 00 

Volumenstrom: 645
Förderhöhe: 1.18 Meter
Pumpentemperatur: 10 °C
Batteriestatusindikator: 03
Pumpenkennung: 0598
Signalstärke: -64 dBm
Datenprotokollversion: 01
Unbekannt 1: 1C
Pumpenmodus: Konstantdifferenzdruck Stufe 1 (07)
Unbekannt 2: 01C0
Unbekannt 3: 00 00 B4 A2 

Volumenstrom: 645
Förderhöhe: 1.18 Meter
Pumpentemperatur: 10 °C
Batteriestatusindikator: 03
Pumpenkennung: 0598
Signalstärke: -64 dBm
Datenprotokollversion: 01
Unbekannt 1: 1A
Pumpenmodus: Konstantdifferenzdruck Stufe 1 (07)
Unbekannt 2: 01C4
Unbekannt 3: 04 32 54 48 

Volumenstrom: 645
Förderhöhe: 1.19 Meter
Pumpentemperatur: 10 °C
Batteriestatusindikator: 03
Pumpenkennung: 0598
Signalstärke: -63 dBm
Datenprotokollversion: 01
Unbekannt 1: 19
Pumpenmodus: Konstantdifferenzdruck Stufe 1 (07)
Unbekannt 2: 01C8
Unbekannt 3: 11 06 FF 40

**Comment by tokkeherfst** [comment]
Hi, anyone had a chance to look at this request? Asking politely ;-)

**Comment by Ernst79** [comment]
I had a look at the data and site, but I thing (as far as my Secondary school German goes) that it requires to first send a BLE data packet to the pump reader, and that it will than send data back. Am I right?

that isn't possible with BLE monitor, as this project only supports passive reading of BLE data, without "asking for it"

**Comment by tokkeherfst** [comment]
No actually, it is completely passive, the script is just running hcidump
and parsing that. The pump is continously sending broadcasting the pump
data...

Tx,

Tom.

**Comment by Ernst79** [comment]
ah, ok, do you know the MAC address of the sensor than? That will make it easier to filter out the useful data from your log

**Comment by tokkeherfst** [comment]
yes: AC:4D:16:F1:65:95

I think what might have confused you, is that on the github README, the
author describes his attempts at reverse engineering by modifying packets
and playing them back to find out what the fields do.

But that is not what the alphareader script itself does, it's using
completely passive parsing and using just a few fields like pump
pressure and volume flow.

Thanks for having a look, appreciate it!

Tom.

**Comment by Ernst79** [comment]
It should be possible to add something for this device. I'll create something coming days.

**Comment by tokkeherfst** [comment]
Awesome, thanks!

Tom.

**Comment by Ernst79** [comment]
Some first results

{'packet': 122, 'bat_status': 3, 'pump_id': 38917, 'flow': 645.1612903225806, 'current cost level': 1.1908322397534106, 'pump mode': 7, 'temperature': 13, 'rssi': -64, 'mac': 'AC4D16F16595', 'type': 'MI401', 'firmware': 'Gundfos', 'data': True}

I will add some rounding and will have to create some new sensor types probably. 

Any idea what this is? `Aktuelle Förderhöhe`. It is translated to something like `current cost level` Is that ok?

**Comment by Ernst79** [comment]
In meters of water? Is that the same as Meters Sea Water (MSW)?  https://en.wikipedia.org/wiki/Metre_sea_water#:~:text=One%20standard%20metre%20sea%20water%20is%20also%20approximately%20equal%20to,75.0062%20mmHg

Home Assistant is measuring pressure in one of the following units 
```
    PA = "Pa"
    HPA = "hPa"
    KPA = "kPa"
    BAR = "bar"
    CBAR = "cbar"
    MBAR = "mbar"
    MMHG = "mmHg"
    INHG = "inHg"
    PSI = "psi" 

From that link, I understand that a pressure of 10 msw is defined as 1 bar. So, the measurement is 1.19 / 10 = 0.119 bar? is that correct?

**Comment by tokkeherfst** [comment]
Yes, that is correct!

Greetings,

Tom

**Comment by Ernst79** [comment]
hmmm. I have a problem with the fact that the sensor can send data for different pumps (pump id's). The BLE monitor code isn't really easy adoptable to create different sensors for each pump. 

As a start, I can assume it is measuring only one pump and add the pump id in the sensors attributes. This will allow a user with multiple pumps to create template sensors that filters out the data to individual pump sensors. Not the most user friendly way, but that is the easiest I can do right now. In the future, we can see how to improve this.

**Comment by tokkeherfst** [comment]
I understand, it's not a problem for me though as I have only one pump ;-)
 Also, these MI401 pump bluetooth modules are fairly expensive, it would be
rather rare to have multiple of them.

Tom.

**Comment by Ernst79** [comment]
Can you give it a try in 12.7.1

**Comment by tokkeherfst** [comment]
Woop woop! Looks great!

[image: image.png]

The data is correct and I also tested changing modes, which display
correctly!

Awesome work!


Tom.
