### ISSUE TITLE
The sensor's value update very slow, request a debug method

### ISSUE THREAD

**Issue by someonewating** [custom-components/ble_monitor#1260]
Hi,

I configured this custom integration in home asstant on raspberry pi 4b, and added a xiaomi door sensor via this successfully.

The xiaomi door sensor used Bluetooth broadcast to update its status. But I found this integration updates the sensor's value very slow, sometimes it doesn't work. 

I would like to kindly request a method to let me know how to check the logs, as there is no log from the home assistant side for this integration.

Thank you in advance.

**Comment by Ernst79** [comment]
you will have to enable debug logging for the BLE monitor integration (at debug level). 

```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: debug
```

Check the logs for messages from you sensor's mac address. Most likely, bad reception/range issues?

**Comment by someonewating** [comment]
Thank you for your reply. @Ernst79 

I will try to set the debug in the configuration.yaml as you suggested. But honestly I don't think it's because the single, as I tested next to my rpi.

Whatever, I will try your method first. Thanks again.

**Comment by someonewating** [comment]
HI @Ernst79 ,

I checked the log, and I only saw the log for those records that successfully showed on the dashboard of the home assistant. But there were logs printed when the dashboard didn't successfully show the status changes.

Not sure why this happens. I tested my wifi and it works well, so I think it's not because of the antenna. Also the `signal strength` shows the strength is around `-50db`, I guess the signal is ok.

Would you mind to share some debug tips, thanks a lot.

**Comment by someonewating** [comment]
Checked the [source code](https://github.com/custom-components/ble_monitor/blob/master/custom_components/ble_monitor/bt_helpers.py), and I found once the code running to the method `btmgmt_sync.send`, it will be stuck. 

So maybe this is the reason?

**Comment by Ernst79** [comment]
Rssi signal strength is ok. WiFi is not related, as communication is Bluetooth (although WiFi antennas can block Bluetooth signals.

> But there were logs printed when the dashboard didn't successfully show the status changes.

Where these messages from the same sensor/MAC address? Or different MAC addresses?

**Comment by someonewating** [comment]
Hi @Ernst79 , I'm sorry I think I made a mistake. I monitored the logs of home assistant, and I found the log was comes from a Xiaomi scale, which was not related to my door sensor. 

Thus, I think for those events(door sensor: open/ door sensor: close) that were successfully shown on the home assistant, they also printed in the log. And for those events which did NOT show on the home assistant, they did NOT be printed in the log as well.


I don't understand why this happens, as the signal strength was always around -50 db. My only suspicion was the following.

> Once the code running to the method btmgmt_sync.send, it will be stuck.

**Comment by Ernst79** [comment]
I'm not sure what is wrong. But one thing you could check is whether you receive data from the sensor with a different device (e.g. use a Bluetooth sniffer app on your phone, Bluetooth LE Scanner. In this way, you can check if it is Home Assistant not receiving/processing the data, or the sensor, not sending the data.

**Comment by someonewating** [comment]
@Ernst79 Thanks, I think this issue is because the rpi didn't receive the Bluetooth message. Not sure why the rpi wasn't receiving it. But whatever, thanks a lot.

**Comment by someonewating** [comment]
Hi @Ernst79 , I tried to use an esphome Bluetooth proxy on my esp32, and then everything works well. But I was using my esp32 for another project. Thus, I would like to ask if it is possible to transmit the Bluetooth message from esp32 to ble_monitor using my own code, instead of using esphome.

**Comment by Ernst79** [comment]
There are some examples on the BThome website (bthome.io). These example are of course in BTHome format, but you could modify it a bit such that it is still in xiaomi’s own format. See e.g. BTHomeV2 ESP32 https://github.com/Chreece/BTHomeV2-ESP32-example

**Comment by someonewating** [comment]
Thanks a log!
