### ISSUE TITLE
[New Sensor]: Fluval Smart LED

### ISSUE THREAD

**Issue by Filiaes** [custom-components/ble_monitor#1261]
### Additional information

Hi, I would love to see the Fluval Smart LEDs supported here. There was already some debugging related to that and there is an ESPHome "modification": [fluval_ble_led](https://deploy-preview-2653--esphome.netlify.app/components/fluval_ble_led.html). The modification is based on the topic here: [Fluval Aquasky BLE RGB-Light](https://community.home-assistant.io/t/fluval-aquasky-ble-rgb-light/259598) and the source code of the manufacturer app is accessible here: [FluvalSmart](https://github.com/hzgworld/FluvalSmart).

The product itself can be found here: https://fluvalaquatics.com/ca/shop/lighting
There are several products with different light "channels" 4 or 5 channels, also there are some presets that can be defined and the channels can be configured each by itself.

Hopefully this is enough information, otherwise I will provide the advertisements data!

Best regards.

**Comment by Ernst79** [comment]
Unfortunately, BLE monitor only supports passive scanning, not sending data to switch on a light. A Bulb requires a BLE a connection. This is out of the scope of BLE monitor. So, unfortunately, we won’t implement support
