### ISSUE TITLE
[New Sensor]: Inkbird  IBS-TH3 

### ISSUE THREAD

**Issue by giuseppe072000** [custom-components/ble_monitor#1283]
### Sensor Description

Inkbird  IBS-TH3 

### Additional information

 
is possible to read data over wifi from Inkbird  IBS-TH3 ?

what other options are to read data from IBS-TH3 ?

### BLE advertisements

```shell
is possible to read data over wifi from Inkbird  IBS-TH3 ?

what other options are to read data from IBS-TH3 ?
```

**Comment by Ernst79** [comment]
BLE monitor can only read BLE advertisement data, no WiFi. Please post your question on the Home Assistant forum.

**Comment by stephentos** [comment]
Its only a bluetooth device. Not wifi. 
When using android inkbird app device is visible with bluetooth id.

**Comment by stephentos** [comment]
ignore last comment, wrong device
