### ISSUE TITLE
Jaalee JHT sensor wrongly calculated temperature and humidity data in HA

### ISSUE THREAD

**Issue by gya352** [custom-components/ble_monitor#1285]
### What happened?

I recently purchased a new Jaalee JHT heat and humidity sensor. I found that the heat and humidity values shown by the app and HA differ significantly. The problem is that the calculation of the sensor data in the jaalee.py file seems to be incorrect. The correct calculation method can be found on the website below: https://sensor.jaalee.com/scan_api.html. A different calculation method is used in the  jaalee.py file.

### Sensor type

Jaalee JHT

**Comment by Ernst79** [comment]
Thanks, the temperature formula was reverse engineered in the past, as we were not able to find any formula. I'll check if the formula's make sense and if they do, will implement them

**Comment by Ernst79** [comment]
Thanks, released as 12.8.0
