### ISSUE TITLE
[Bug]: SJWS01LM stopped updating "ble moisture" sensor statuses

### ISSUE THREAD

**Issue by ilshatms** [custom-components/ble_monitor#1295]
### What happened?

The SJWS01LM smart water leak sensor has stopped updating the "ble moisture" sensor statuses in the latest component releases. Everything works correctly on the version of the component "ble_monitor-12.5.0", on the latest versions the "ble moisture" sensor does not respond to water leaks. The rest of the sensors work correctly.

The sensor itself is displayed as available. But when tested, it does not detect moisture.

Perhaps the error is massive and does not manifest itself in any way without a real leak, so there are no requests from users. I came across it by accident while regularly testing sensors in the house.

![photo](https://github.com/custom-components/ble_monitor/assets/17129298/9b5a7056-5875-4d1e-9e03-8811b6b6087a)

Information about my system.
Core 2024.1.2
Frontend 20240104.0

### Sensor type

The SJWS01LM smart water leak sensor

**Comment by Ernst79** [comment]
Could you try the following. 

in the file custom_components/ble_monitor/const.py

Change `True` to `False` on the following line

https://github.com/custom-components/ble_monitor/blob/1128e2e6569eab54dc0bc4eb3a877194ec48a441/custom_components/ble_monitor/const.py#L234

Restart HA and try it again? It should look like

```
    BLEMonitorBinarySensorEntityDescription(
        key="moisture detected",
        sensor_class="BaseBinarySensor",
        update_behavior="Instantly",
        name="ble moisture",
        unique_id="mo_",
        device_class=BinarySensorDeviceClass.MOISTURE,
        force_update=False,
    ),
```

**Comment by ilshatms** [comment]
@Ernst79 

Did not work.

I took the component "ble_monitor-12.8.1", made the recommended changes to custom_comComponents/ble_monitor/const.py and restarted Home Assistant. The water test did not process the change in the sensor.

**Comment by Ernst79** [comment]
Very strange. If I enter a BLE advertisement manually, it updates fine

message 043e2902010000bc27e044ef541d020106191695fe5859630808bc27e044ef54f58fe704000000fc69d15ca8
key 255e6cabb39b2eddd0de992b9fee2bf2

![image](https://github.com/custom-components/ble_monitor/assets/24375847/41713a60-9bff-4667-befe-2c526bfd50b6)

Can you post a debug log (enable logging at debug level for BLE monitor) and send me the encryption key?

**Comment by Ernst79** [comment]
Possibly the same issue as #1296 ?

**Comment by ilshatms** [comment]
> Possibly the same issue as #1296 ?

is very similar. But in my example the sensor is available. It just doesn't react to water. There is no transition from "dry" to "moisture detected".

although I previously caught the same behavior, perhaps just with the release of 12.5.1

**Comment by Ernst79** [comment]
Could you do a test for me? Remove the device via the BLE monitor options (select the MAC of the sensor at the bottom of the options menu, Send, enable the option to delete the device, 2 send). Next restart HA and after that, add it again.

**Comment by ilshatms** [comment]
> Possibly the same issue as #1296 ?

I think we can merge the [bugs](https://github.com/custom-components/ble_monitor/issues/1296) into one branch. I additionally tested the operation of the sensor with component 12.5.1, everything works correctly there. This is truly the latest working version of the component.
