### ISSUE TITLE
[Bug]: Precision of xiaomi temperature

### ISSUE THREAD

**Issue by MichalLytek** [custom-components/ble_monitor#1302]
### What happened?

Even tho the TelinkFlasher is able to collect the precise data from the sensor (2 digits precision):

![image](https://github.com/custom-components/ble_monitor/assets/10618781/a732e24a-307b-4ed1-bcae-b5a6da82f41a)

HA only gets the single digit precision:

![image](https://github.com/custom-components/ble_monitor/assets/10618781/e68da3cb-0ba6-499a-afe4-32589388e8f2)

Entity precision in HA is set properly:

![image](https://github.com/custom-components/ble_monitor/assets/10618781/0a357ec4-0551-46a7-9e6d-c00cef8ca905)

### Sensor type

LYWSD03MMC

**Comment by Ernst79** [comment]
I think that this is a difference in how the information is obtained. 

- The TelinkFlasher is connecting to the device and "asking" for the temperature. In BLE terms, this is called reading the characteristics. 
- BLE monitor is passively listening to BLE broadcasts. This won't require to set up a connection, the sensor is just broadcasting every x minutes its current temperature. 

The passive BLE advertisements are with one digit precision. It actually sends an integer (zero precision) and divides that by 10 making it 1 digit precision. So it is not possible to get 2 digit precision, unless you make a connection (which is out of the scope of BLE monitor. 

```python
def obj1004(xobj):
    """Temperature"""
    if len(xobj) == 2:
        (temp,) = T_STRUCT.unpack(xobj)
        return {"temperature": temp / 10}
    else:
        return {}
```

**Comment by MichalLytek** [comment]
Thanks for the clarification.

I wanted to calibrate the readings from my sensors by 1 digit precision rounding is a bit limitating. It's ok for temperature tracking in HA although.

![opera_prJEuB2i4Z](https://github.com/custom-components/ble_monitor/assets/10618781/bf7dc056-29c3-4502-adde-f3edf4e5765f)
