### ISSUE TITLE
[Bug]: Unable to remove unwanted devices

### ISSUE THREAD

**Issue by sezlony** [custom-components/ble_monitor#1304]
### What happened?

I've dozens of unknown devices gathered by BT and I can't delete them in configuration

there are some impressive 55 pieces of unknown sensors like heart rate, steps, etc, discovered presumably through a nearby ibeacon, but whenever I delete them by configuration they still come back an sit in the list like nothing happened…

### Relevant log output

```shell
Logger: custom_components.ble_monitor.config_flow
Source: custom_components/ble_monitor/config_flow.py:249
Integration: Passive BLE monitor (documentation, issues)
First occurred: 20:24:16 (3 occurrences)
Last logged: 20:24:41

Removing BLE monitor device 74278BDA-B644-4520-8F0C-720EAF059935 from device registry
Removing BLE monitor device E20A39F4-73F5-4BC4-1864-17D1AD07A962 from device registry
Removing BLE monitor device E2C56DB5-DFFB-48D2-B060-D0F5A71096E0 from device registry
```

**Comment by Ernst79** [comment]
I can't reproduce this. I have just deleted two iBeacons as a test, but it worked fine. How do you delete the iBeacons?

**Comment by sezlony** [comment]
I click on "configure" on the page of Passive BLE monitor integration, and then choose the unwanted device from 'Devices' dropdown menu, submit, check the 'Delete device' option and submit.

After this reopening the devices list the previously deleted device is still there...

**Comment by Ernst79** [comment]
And what happens if you click submit twice after deleting the device?

**Comment by sezlony** [comment]
pushing again submit at the end works! although it never did that way, there was only 2 submits, as far as I remember...

thanx for the advice!
