### ISSUE TITLE
[New Sensor]: Jaalee JHT Temperature/Humidity/Dewpoint/VPD Sensor 

### ISSUE THREAD

**Issue by propagandalf** [custom-components/ble_monitor#1306]
### Sensor Description

Jaalee JHT Temperature/Humidity/Dewpoint/VPD Sensor (F51C)

### Additional information

Similar sensor to this one: https://github.com/custom-components/ble_monitor/issues/1042
Maybe new version or is it different? I thought I was getting the supported, but apparently it is different and didnt work with HA. F525 vs this one F51C.

https://www.aliexpress.com/item/10000335836820.html

Link from Jaalee seller: http://sensor.jaalee.com/scan_api.html?spm=a2g0s.imconversation.0.0.62eb3e5fepdaN8

![BLE2](https://github.com/custom-components/ble_monitor/assets/9726765/4d7d83f6-738b-4030-99c2-a8a7ca792e5a)
![BLE](https://github.com/custom-components/ble_monitor/assets/9726765/2aca1e3d-b614-40cf-86c6-12d3b9862962)
![BLE3 jpg](https://github.com/custom-components/ble_monitor/assets/9726765/e6c646ac-ac4b-4f1d-bc6a-64c4a29151ff)

### BLE advertisements

```shell
RAW Data:
0201041BFF4C000215EBEFD08370A247C89837E7B5634DF525632E5535CC6403031CF50F161CF56465E6AA4CB0C801632E5535
```

**Comment by propagandalf** [comment]
How it looks like in the Jaalee APP:
![image](https://github.com/custom-components/ble_monitor/assets/9726765/85a7d0be-eb51-4730-9cdc-f8b2648ce079)

**Comment by Tomashaglund1** [comment]
Same issue here :)

**Comment by Ernst79** [comment]
Added in 12.9.2
