### ISSUE TITLE
[Bug]: Raspberry pi 5 not found any device

### ISSUE THREAD

**Issue by roisec** [custom-components/ble_monitor#1308]
### What happened?

Hi
I pretty new in HA, I am installing ble-monitor to detect if my phone is located in my home.
I am using the build-in Raspberry pi 5 bluetooth sensor. 
<img width="1022" alt="image" src="https://github.com/custom-components/ble_monitor/assets/68992144/1d695f2d-0965-45c4-b28e-7b71af48b0b3">

What am I doing wrong?

**Comment by Ernst79** [comment]
Device tracking is not really the aim of this integration, although it is possible for devices have a fixed ip or send beacon messages. You need to add the mac manually in the options and enable track device. https://custom-components.github.io/ble_monitor/configuration_params#track_device

Problem is that most phones have a rotating MAC address, preventing it from being tracked. So, better to use a beacon device on your keyring.
