### ISSUE TITLE
[Bug]: last_packet_id is typed as last_packet id 

### ISSUE THREAD

**Issue by DrewIshy** [custom-components/ble_monitor#1314]
### What happened?

Just noticed that in line 1108 and 993 of sensor.py extra_state_attribute has last_pacekt [space] id whereas all the other places it has last_packet_id.  
I'm writing a new sensor and came across this while debugging something completely different. 

NO IDEA if this is causing an issue as I have not looked into it, but I got a error message which had this in it and was wondering if this was the cause.  Seemed like a typo for PowerSensor and SwitchSensor which I am not using

**Comment by Ernst79** [comment]
Thanks, good spot. Didn’t affect the working much I think, but good to fix anyways.
