### ISSUE TITLE
[Bug]: Mijia wireless switch XMWXKG01LM Automation does not have sensor options

### ISSUE THREAD

**Issue by w961471797** [custom-components/ble_monitor#1330]
### What happened?

The first image is about creating automation using ble_monitor integration. The second image is about creating automation using HA Xiaomi BLE integration. ble_monitor missing sensor options 
![111](https://github.com/custom-components/ble_monitor/assets/77659586/9828200f-d941-4438-ba92-7e8a440777ea)
![222](https://github.com/custom-components/ble_monitor/assets/77659586/3f6fb0c5-b4fb-464f-8504-39ac4819e66d)

### Sensor type

XMWXKG01LM

**Comment by Ernst79** [comment]
BLE Monitor does not support events and predefined device automations. But you can always create automations based on the sensor state (changes) and attribute state (changes). 

There are no plans to add this. The advise is to move to the official Xiaomi-BLE integration, as further development will mostly be done on the Xiaomi-BLE integration (I maintain both). We are currently moving the Locks over to Xiaomi-BLE, as the last category of Xiaomi devices (probably in HA 2024.4).

**Comment by w961471797** [comment]
OK thank you
