### ISSUE TITLE
[Bug]: No encryption key found for device with MAC

### ISSUE THREAD

**Issue by mathgim** [custom-components/ble_monitor#1332]
### What happened?
Hi everyone,
I just found this error in my log entries. I don't know how to react to that,
Thanks for your help :-)

### Relevant log output

```shell
This error originated from a custom integration.

Logger: custom_components.ble_monitor.ble_parser.xiaomi
Source: custom_components/ble_monitor/ble_parser/xiaomi.py:1337
integration: Passive BLE monitor (documentation, issues)
First occurred: 6:02:11 PM (1 occurrences)
Last logged: 6:02:11 PM

No encryption key found for device with MAC (masked for privacy)
```
```

**Comment by Ernst79** [comment]
You have a Xiaomi BLE sensor that sends data , but requires an encryption key to read the data. You can enter it in the BLE monitor settings., by configure the integration, click on the devices pull down and select your sensors MAC address . Click submit and a new window will open where you can enter the encryption key.

instructions on how to ket the encryption key is explained in the faq
https://custom-components.github.io/ble_monitor/faq#how-to-get-the-mibeacon-v4v5-encryption-key
