### ISSUE TITLE
[New Sensor]: Medisana Blood Pressure Monitor

### ISSUE THREAD

**Issue by RobusK** [custom-components/ble_monitor#1345]
### Sensor Description

Medisana Blood Pressure

### Additional information

[Link](https://www.medisana.com/en/Health-control/Blood-pressure-monitor/)

There already exists an integration https://github.com/bkbilly/medisanabp_ble/tree/main?tab=readme-ov-file, but it conflicts with ble_monitor. It would be nice if ble_monitor could support them natively

```shell
[custom_components.ble_monitor.ble_parser] Unknown advertisement received for mac: 78:04:73:CB:BF:D4service data: []manufacturer specific data: [b'\t\xffBH\xd4\xbf\xcbs\x04x']local name: LS BPMUUID16: 4120,UUID128: None
[custom_components.ble_monitor.ble_parser] Unknown advertisement received for mac: 78:04:73:CB:BF:D4service data: []manufacturer specific data: []local name: LS BPMUUID16: None,UUID128: None
```

**Comment by Ernst79** [comment]
It looks like this device uses an active connection. at least that is what the linked integration seems to use. The passive BLE adversiment only contains the max

09  = lenght
ff4248 = UUID
d4bfcb730478 = MAC Address (reversed per two characters. 

Unfortunately, we can't add this device to BLE monitor, as we only use passive scanning. To use both integrations at the same time, you will need to add a second BLE dongle to your HA machine and use one with passive scanning for BLE monitor and the other with connections for the blood pressure monitor. Seems to be the only solution.
