### ISSUE TITLE
Bluetooth Temperature Humidity Sensor tuya app

### ISSUE THREAD

**Issue by cocolino83** [custom-components/ble_monitor#1346]
### Sensor Description

Bluetooth Temperature Humidity Sensor tuya 

### Additional information

![Screenshot_20240415-154303](https://github.com/custom-components/ble_monitor/assets/88486650/0849555e-f077-4d76-bd9e-479a778a9bda)

![Screenshot_20240415_155124_uk co alt236 btlescan](https://github.com/custom-components/ble_monitor/assets/88486650/e79d2328-071f-417a-828f-bd9d75d74dfc)
![Screenshot_20240415_155139_uk co alt236 btlescan](https://github.com/custom-components/ble_monitor/assets/88486650/5b29d312-a29f-4a1e-ae61-aec8885ceed7)
![Screenshot_20240415_155154_uk co alt236 btlescan](https://github.com/custom-components/ble_monitor/assets/88486650/cf960b55-aac5-465b-9168-6cb301c7d78d)
![Screenshot_20240415_155200_uk co alt236 btlescan](https://github.com/custom-components/ble_monitor/assets/88486650/911b657b-54f0-48ea-97f5-6ded7c6b6ea1)

### BLE advertisements

```shell
Bluetooth information detected with Bluetooth le scanner app.  as per screenshot in comments
```

**Comment by Ernst79** [comment]
Please check this issue for Tuya support. There is an alternative firmware for now to add support. We don't have figured out the stock firmware format, as it is encrypted. I will close this isssue here, please add your info the the following issue. 

https://github.com/custom-components/ble_monitor/issues/1063
