### ISSUE TITLE
setup fail on HA 2024.4.3

### ISSUE THREAD

**Issue by robertomontinaro80** [custom-components/ble_monitor#1347]
### What happened?

ble_monitor setup fails after updating HA from 2024.4.2 to 2024.4.3 
Below the log
`Setup failed for custom integration 'ble_monitor': Requirements for ble_monitor not found: ['aioblescan>=0.2.14', 'janus>=1.0.0'].`

### Relevant log output

```shell
Setup failed for custom integration 'ble_monitor': Requirements for ble_monitor not found: ['aioblescan>=0.2.14', 'janus>=1.0.0'].
```

**Comment by Ernst79** [comment]
Try a full system restart first.

**Comment by Ernst79** [comment]
I don’t have this issue on my system, also running 2024.4.3. 

Did you install BLE monitor after you installed HA 2024.4.3?

**Comment by robertomontinaro80** [comment]
> I don’t have this issue on my system, also running 2024.4.3.
> 
> Did you install BLE monitor after you installed HA 2024.4.3?

I use the BLE integration monitor since 2 years :) but ok, I can try again to reinstall the version 2024.4.3.

**Comment by robertomontinaro80** [comment]
just updated HA to the version 2024.5.3 and now the error appeared again and it does not want to go away :(

`Requirements for ble_monitor not found: ['janus>=1.0.0', 'aioblescan>=0.2.14'`

**Comment by Ernst79** [comment]
Can you install these packages manually on your system with pip install janus and pip install aioblescan

**Comment by robertomontinaro80** [comment]
I use HA in docker installation and usually I don't need to install manually any package. I can try to reinstall HA but I'm not sure how useful could it be.

**Comment by Ernst79** [comment]
No, just try 'pip install janus' and 'pip install aioblescan' first (in the docker environment of course). The problem is that you seem to be the only one that is having this issue. Perhaps the above already solves it.

**Comment by robertomontinaro80** [comment]
I don't know why but after restarting directly the O.S. of my raspberry - I'm using OMV 6 with portainer docker manager installed on it, in wich HA is running as container - ble integration started to work again. Thanks for your support anyway.
