### ISSUE TITLE
[Bug]:  ble_monitor' accesses hass.helpers.device_registry.

### ISSUE THREAD

**Issue by cloudbr34k84** [custom-components/ble_monitor#1350]
### What happened?

Detected that custom integration 'ble_monitor' accesses hass.helpers.device_registry. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from device_registry directly at custom_components/ble_monitor/binary_sensor.py, line 134: dev_registry = hass.helpers.device_registry.async_get(hass), please create a bug report at https://github.com/custom-components/ble_monitor/issues

**Comment by cloudbr34k84** [comment]
wrong integration to log issue

**Comment by Ernst79** [comment]
Why would this be the wrong repo?

**Comment by cloudbr34k84** [comment]
> Why would this be the wrong repo?

Ahh bugger my bad, i logged this in HA Core repo, but got confused, ill reopen this

**Comment by Ernst79** [comment]
I'll fix it, should be an easy fix. Thanks for reporting

**Comment by cloudbr34k84** [comment]
> I'll fix it, should be an easy fix. Thanks for reporting

Cheers, going through logs to see what can be fixed

**Comment by Ernst79** [comment]
could you try 12.11.0-beta (enable beta's in HACS) to see if this fixes the errors?

**Comment by cloudbr34k84** [comment]
Will do this morning

**Comment by cloudbr34k84** [comment]
> could you try 12.11.0-beta (enable beta's in HACS) to see if this fixes the errors?

Hey still seeing the error after updating to the beta version
```
Detected that custom integration 'ble_monitor' accesses hass.helpers.device_registry. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from device_registry directly at custom_components/ble_monitor/binary_sensor.py, line 134: dev_registry = hass.helpers.device_registry.async_get(hass), please create a bug report at https://github.com/custom-components/ble_monitor/issues
Detected that custom integration 'ble_monitor' accesses hass.helpers.entity_registry. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from entity_registry directly at custom_components/ble_monitor/binary_sensor.py, line 135: ent_registry = hass.helpers.entity_registry.async_get(hass), please create a bug report at https://github.com/custom-components/ble_monitor/issues
```
![image](https://github.com/custom-components/ble_monitor/assets/58960644/f495eb20-5bf2-4acd-b5b3-c5b9d087c610)

**Comment by Ernst79** [comment]
Ah, sorry, my mistake. I took the wrong branch when releasing the beta. I’ll make a new one later today. I’ll let you know when finished.

**Comment by Ernst79** [comment]
Done, can you try 12.11.1-beta

**Comment by cloudbr34k84** [comment]
> Done, can you try 12.11.1-beta

hey it seems to be gone now from the logs.. let m keep an eye on it today and report back then ill close the ticket off

**Comment by Ernst79** [comment]
Can I release it as final?

**Comment by cloudbr34k84** [comment]
Yeah sorry appears to be gone
