### ISSUE TITLE
[New Sensor]: Mija Mosquito Repellent

### ISSUE THREAD

**Issue by iturbay** [custom-components/ble_monitor#1361]
### Sensor Description

Xiaomi Mija Mosquito Repellent

### Additional information

WX10XM New model

**Comment by Ernst79** [comment]
Please post a log with ble advertising data, see the documentation how to get this data.

**Comment by iturbay** [comment]
in the log I only get these entries from him:

2024-06-12 13:46:13.622 INFO (Thread-104) [custom_components.ble_monitor.ble_parser] Unknown advertisement received for mac: 64:9E:31:95:95:13service data: []manufacturer specific data: []local name: Mesh Mi Mosq V2UUID16: None,UUID128: None

**Comment by Ernst79** [comment]
In that case, it is only sending its name, and it would require a connection to get the data. That is out of the scope of BLE monitor, as we only parse passive BLE advertisements. You could try with ESPHome BLE Client to get the data, but we can't add it to BLE monitor
