### ISSUE TITLE
Linptech KS1 Button

### ISSUE THREAD

**Issue by alexreddy78** [custom-components/ble_monitor#1370]
### Sensor Description

Button sensor

### Additional information

https://home.miot-spec.com/spec/linp.remote.ks1

### BLE advertisements

```shell
Button is supported in Xiaomi Gateway 3 integration as flw:

    14945: ["Linptech", "Wireless Button KS1", "linp.remote.ks1"],
    "spec": [
        BaseConv("battery", mi="4.p.1003"),
        BaseConv("action", "sensor"),
```

**Comment by Ernst79** [comment]
Added in 12.12.3-beta to test. Can't verify it, as I don't have this button. If someone can confirm it works OK, I'll add it in the final version.
