### ISSUE TITLE
[Bug]: Can't setup new BLE_MONITOR Errors before setup

### ISSUE THREAD

**Issue by korruptcow** [custom-components/ble_monitor#1389]
### What happened?

I had to update ble_monitor because HA was complaining so i used the latest release and when HA restarts i get this error.
Setup failed for custom integration 'ble_monitor': Unable to import component: cannot import name 'UnitOfConductivity' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

How to fix?

### Relevant log output

```shell
Setup failed for custom integration 'ble_monitor': Unable to import component: cannot import name 'UnitOfConductivity' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

**Comment by Ernst79** [comment]
Did you update home assistant as well?

**Comment by korruptcow** [comment]
That would be it. Sorry, I thought i did but i didn't. Updated to latest and its working again thanks!
