### ISSUE TITLE
Is there a reason why the device class of conductivity is not: `SensorDeviceClass.CONDUCTIVITY`?

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#1405]
Is there a reason why the device class of conductivity is not: `SensorDeviceClass.CONDUCTIVITY`?

_Originally posted by @Chreece in https://github.com/custom-components/ble_monitor/issues/1399#issuecomment-2486506748_

**Comment by Chreece** [comment]
[PR](https://github.com/custom-components/ble_monitor/pull/1406) created

**Comment by Ernst79** [comment]
fixed in 12.19.0
