### ISSUE TITLE
[Bug]: Ble_monitor not loaded Raspi 4 4GB

### ISSUE THREAD

**Issue by mlinko6** [custom-components/ble_monitor#1415]
### What happened?

The BLE Monitor on my Raspberry pi4 is not loaded, the version is 12.19. I've rebooted it a few times but I can't get it to work. Does anyone know why?

KR
Rok

**Comment by Ernst79** [comment]
Any error messages in the logs?

**Comment by mlinko6** [comment]
You can close the Ticket, the Issue was because of the DNS unreachability from HA... Don't know what "no DNS" has to do with the BLE Monitor not working :-).

**Comment by Ernst79** [comment]
Good to hear it is solved.
