### ISSUE TITLE
Error ble device tracker

### ISSUE THREAD

**Issue by uPagge** [custom-components/ble_monitor#145]
it seems your integration is breaking ble device tracker

This error appears with your plugin

![изображение](https://user-images.githubusercontent.com/40397740/98403649-5b9c4900-207a-11eb-9038-e9cf8b6cd91f.png)

I use your plugin to get data from plant sensors and if you remove this from the sensors, the error does not appear

![изображение](https://user-images.githubusercontent.com/40397740/98403701-6fe04600-207a-11eb-8609-918d84474baf.png)

**Comment by Magalex2x14** [comment]
Hello, @uPagge! Until now, the conflict between our component and the tracker did not lead to the error you specified (as far as I know). Components conflict, yes, but it manifests itself differently - either only one of the two components (ours or the tracker) works, or both work, but only partially (data is partially lost), but in any case, this does not cause I / O errors. The specific situation depends on luck, and on the combination of the period (custom.mitemp_bt) and interval_seconds (bluetooth_le_tracker) parameters. The problem[ is reported in our FAQ](https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md#conflicts-with-other-components-using-the-same-bt-interface).

All our component does is to put the bluetooth interface into scanning mode, and, as far as I know, other software is in no way limited in its ability to change scan parameters, stop it, and other manipulations with the interface.
But maybe I'm wrong. Therefore, I ask you to tell us more about your system.

**Comment by Magalex2x14** [comment]
I close because the possibility of a conflict is known and described in the documentation.
