### ISSUE TITLE
Move to integration domain key

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#146]
According to [this ADR 0007](https://github.com/home-assistant/architecture/blob/413e3cb248cf8dca766c0280997f3b516e23fb6d/adr/0007-integration-config-yaml-structure.md), we should move mitemp_bt to the integration domain key. 

> New integrations have to put the integration configuration section under the integration domain key if configuration YAML is used.

If I understand it correctly, we should move to the following. 

```
# Allowed
mitemp_bt:
  rounding: True
  etc.

# Not allowed
sensor:
  - platform: mitemp_bt
    rounding: True
    etc.
```

It's not a big deal if we don't do this, but if we want to follow the guidelines, I think we should change this some day.

**Comment by Magalex2x14** [comment]
I agree that we should follow the guidelines wherever we can. Moreover, since breaking changes are coming, it is better to make them in one release. Will you do it?

**Comment by Ernst79** [comment]
That's ok. Hopefully it won't interfere with your changes of #147

**Comment by Magalex2x14** [comment]
Even if it does interfere somewhere, I will take care of the solution.

**Comment by Magalex2x14** [comment]
After reading the documents from the (architecture) repository you pointed, I found that flake8 does not work for my environment. Repaired and made a commit with corrections of the found issues to the master.

**Comment by Ernst79** [comment]
Merged it in the restructure_config branch.

**Comment by Magalex2x14** [comment]
By the way, @Ernst79, have you ever thought about changing the integration name (mitemp_bt)? Maybe we should come up with a name that will better reflect the essence of our component? No?

**Comment by Ernst79** [comment]
Yes, good idea. 

Lets think about a good name.

**Comment by Ernst79** [comment]
I'm having trouble getting this right. I can get the configuration right, but I fail in getting the code in the right place. We need to move part of the code from sensor.py to __init__.py, as we have to `setup the component there (`async def async_setup(hass, config):`). This is working fine, but I think we have to move large parts of the sensor.py code to __init__.py, I think. But I don't understand why I can't get e.g. config[ACTIVE_SCAN] to also work in sensor.py. I understand that this needs to change to config[DOMAIN][ACTIVE_SCAN], but it still doesn't work.

**Comment by Ernst79** [comment]
I've uploaded my current WIP to the `integration level` branch. I'm stuck at the last part, getting setup_platform to work. 

It won't run BLEscanner(), which makes sense, as I have moved it to `__init__.py`. I'm stuck on how to solve this. Second issue I have is how to get config[DOMAIN][CONF_REPORT_UNKNOWN] etc working in sensor.py. 

If you have time @Magalex2x14 , could you help me with this. I'm feeling lost now. 

BTW. (minimal) configuration is now

`mitemp_bt:`

You can, of course, use all the old config parameters.

**Comment by Ernst79** [comment]
I had a good night sleep and I think we have to start the scanner part also in __init__.py, and submit the data to hass.data. This can be read in sensor.py. I’ll look into that further.

**Comment by Magalex2x14** [comment]
I can see more details in the evening. Here's what I found while looking for answers:

https://developers.home-assistant.io/docs/creating_integration_file_structure

__init__.py: The component file. If the integration only offers a platform, you can keep this file limited to a docstring introducing the integration """The Mobile App integration."""

You can override a built-in integration by having an integration with the same domain in your config/custom_components folder. Note that overriding built-in components is not recommended as you will no longer get updates. It is recommended to pick a unique name.

and

https://developers.home-assistant.io/docs/dev_101_index
DOMAIN should be set as I understood

In addition, our component is not asynchronous, but multithreaded, so we need to use setup_platform, as it was before, and this has nothing to do with integration domain, i think.

**Comment by Magalex2x14** [comment]
Perhaps the problem is somehow related to the fact that the original mitemp_bt is at a different configuration level? And everything will work if you just try a unique name, as I mentioned above?

**Comment by Magalex2x14** [comment]
passive_ble_monitor, maybe? (passive_ble_monitor.py, DOMAIN="passive_ble_monitor")
or xiaomi_passive_ble?

**Comment by Ernst79** [comment]
> If the integration only offers a platform

Before we only had a platform, but now we change to an integration. So we have to use `__init__.py` to load the platform with `async def async_setup(hass, config):` or `def setup(hass, config):`. 

I tried to keep al things in `sensor.py`, like we had + the setup, but you will get an error that it can't setup the integration (makes sense). 

So, in `__init__.py` we setup the platform, and with `hass.helpers.discovery.load_platform(hass, 'sensor', DOMAIN, {}, config)` we load the sensor platform. Subsequenly, in `sensor.py` we setup the sensor platform with `def setup_platform(hass, config, add_entities, discovery_info=None):`. This is already in there and working fine. There is an standard clean example of this [here](https://github.com/home-assistant/example-custom-config/tree/master/custom_components/example_load_platform). 

The remaining issue I have is that part of the old code is still in the setup_platform in `settings.py`, which needs parameters and functions that are defined in `__init__.py`. I also noticed that the actual measurement in the example is determined in `__init__.py` and passed on to `hass.data[DOMAIN]`, see `(hass.data[DOMAIN] = {'temperature': 23}`. 

So, what needs to be done (I think) is that a large part of the code that is still in `sensor.py`, in `setup_platform` has to move to `__init__.py` (I think we can just move it into `async def async_setup`) and the result of the measurement has to be passed on to hass.data[DOMAIN]. In `sensor.py` you can get the result with `self._state = self.hass.data[DOMAIN]['temperature']`. The only thing that needs to stay in `sensor.py` is the `add_entities` part.

**Comment by Ernst79** [comment]
> passive_ble_monitor, maybe? (passive_ble_monitor.py, DOMAIN="passive_ble_monitor")
> or xiaomi_passive_ble? or ble_monitor?

I think passive_ble_monitor is ok. Note that the file name must remain `sensor.py`, only change the folder name. In the code, we only have to change the DOMAIN (which is defined in const.py), the first line of the .py files and the manifest. 

Now I'm thinking about this, I remember that one of the sensors is a binary_sensor. I think we also have to make a binary_sensor.py file for that. But let's first focus on the above issue.

**Comment by Magalex2x14** [comment]
Hmmm... I see... Everything is a little more complicated than I imagined...
I'll look for a minute, some ready-made custom component, I'll see how it's done.

**Comment by Magalex2x14** [comment]
But still, I don't see any reason for moving any code yet.
It seems to me that our task now is to make the "bootloader" of our platform, that is, in init it is enough to do the following:
- describe the domain
- get configuration
- startup the platform
Since our platform does not involve the use of any centralized API, nothing else is required. I think so. We don't need to exchange any data between the integration level and the platform (except config and hass object at startup) or between multiple platforms. We have single platform and it is self-contained, so using the hass.data[DOMAIN] object is not required.

Perhaps I am still mistaken.

**Comment by Ernst79** [comment]
Ok, that's another way to look at it. Is also fine by me. But I will still have the issue that I have to use the config in `sensor.py`, which I can't seem to fix. I will update the code.

**Comment by Magalex2x14** [comment]
When I drew my conclusions, I looked at this code: https://github.com/markperdue/pyvesync/tree/master/home_assistant/custom_components.
Look, maybe something clears up. If not, then in the evening I will also have the opportunity to experiment...

**Comment by Ernst79** [comment]
Moved the code back to sensor.py. 
`__init__.py` is now only doing the following
- describing the domain
- reading the configuration
- startup the platform

When you run the code, you will see an error that it has an KeyError on `active_scan = config[DOMAIN][CONF_ACTIVE_SCAN]`. For some reason, it can't read the config that is definied in `__init__.py`. 

Note that your link is also doing stuff in `setup`.
- In `manager` it is connecting to something, 
- It is making an update in `manager.update()` and 
- It is passing data to `hass.data[DOMAIN] = {'manager': manager}`

But, please have a look tonight, when you have time.

**Comment by Magalex2x14** [comment]
> Note that your link is also doing stuff in setup.

In our case, it doesn't matter. We don't need to exchange any data between the integration level and the platform (except config and hass object at startup) or between multiple platforms.

But hass.data came in handy (see below).

My config:

```yaml
mitemp_bt:
    rounding: False
    decimals: 2
    period: 60
    log_spikes: True
    use_median: False
    batt_entities: True
    hci_interface:
      - 0
      - 1
      - 2
    report_unknown: True
    devices:
      - mac: '58:2d:34:31:40:00'
        name: sensor
      - mac: "A4:C1:38:2F:87:6B"
        encryption_key: "217C568CF5D22808D120181502D84C1B"
      - mac: "A4:C1:38:D1:6A:8D"
        encryption_key: "C99D2313182473B38A01086FEBF781BD"
    discovery: True
```

> When you run the code, you will see an error that it has a KeyError on

1. Since we pass config [DOMAIN] to the platform, in the platform the configuration is already available without the [DOMAIN] key - it must be returned as it was.

2. After correcting the previous point, I started looking at the actual content of the config variable, and I found that an empty dictionary comes to the platform. I suspect this is due to the fact that the full format is expected with the keys `sensors` and `platform` (possibly), and the core transfers to the loaded platform only what is relevant to it. Didn't experiment further, but just decided to pass the configuration through hass.data.

Everything works now. I'll upload the changes to the branch now.

**Comment by Magalex2x14** [comment]
This is how `config[DOMAIN]` looks like (just for clarity):

```
OrderedDict(
[  ('platform', 'mitemp_bt'), 
   ('rounding', False), 
   ('decimals', 2), 
   ('period', 60), 
   ('log_spikes', True), 
   ('use_median', False), 
   ('batt_entities', True), 
   ('hci_interface', [0, 1, 2]), 
   ('report_unknown', True), 
   ('devices', [
                 OrderedDict([('mac', '58:2d:34:31:40:00'), ('name', 'sensor')]), 
                 OrderedDict([('mac', 'A4:C1:38:2F:87:6B'), ('encryption_key', '217C568CF5D22808D120181502D84C1B')]), 
                 OrderedDict([('mac', 'A4:C1:38:D1:6A:8D'), ('encryption_key', 'C99D2313182473B38A01086FEBF781BD')])]), 
    ('discovery', True), 
    ('active_scan', False)
])
```

**Comment by Ernst79** [comment]
Excellent, I knew it was a small thing, but could not lay my finger on it. Thanks. I'll have a look later tonight.

**Comment by Magalex2x14** [comment]
Another question - if we rename passive_ble_monitor, then in addition to the corresponding changes in the code, we need to change the name of the repository folders... What do you think, can any difficulties arise because of this?

**Comment by Magalex2x14** [comment]
And the repository name...

**Comment by Ernst79** [comment]
I was thinking about that too in the car. Changing the folder name is not an issue. But I'm not sure about the repository name and how HACS will deal with that. Perhaps we have to ask the developer.

**Comment by Magalex2x14** [comment]
Will you talk to @ludeeus?

**Comment by Ernst79** [comment]
On line 430 in sensor.py, you use conf instead of config? Is that right?

def setup_platform(hass, conf, add_entities, discovery_info=None):

**Comment by Ernst79** [comment]
> Will you talk to @ludeeus?

Yes, I will ask him, but that will be tomorrow.

**Comment by Magalex2x14** [comment]
Yes. An empty dictionary comes into this variable, therefore, it is no longer used. Instead, I did `config = hass.data[DOMAIN]`

**Comment by Ernst79** [comment]
Thanks, still learning ....

**Comment by Ernst79** [comment]
Are we sure about the name? Preferably, we change it only once. passive_ble_monitor or ble_monitor, I'm doubting. The last is shorter, the first is better telling what it is doing.

**Comment by Magalex2x14** [comment]
I don't know: D

But if think about it, then I lean more towards the shorter version since the word "monitor" implies only the monitoring function, and it is passive by definition, it seems to me. And the absence of the word Xiaomi in the name gives us the freedom to implement support for other protocols in the future.

**Comment by Ernst79** [comment]
ok, I like the short name as well. I'll ask @ludees what is possible.

**Comment by Ernst79** [comment]
Second thing to think about, the full name. In the manifest.json we had

  "domain": "mitemp_bt",
  "name": "Xiaomi passive BLE monitor sensor integration",

I propose to change this to: 

  "domain": "ble_monitor",
  "name": "Passive BLE monitor integration",

What do you think?

**Comment by Magalex2x14** [comment]
On the one hand, I would like to leave the word Xiaomi in the title so that it would be easier to find us.
Alternatively, we can remove it (for the above reason), and add the corresponding note to the README and description.

In general, formally, the ecosystem is called Mijia, and the protocol is called Mijia BLE MiBeacon protocol.

![image](https://user-images.githubusercontent.com/4982025/98866879-b2d95980-247e-11eb-89d5-edd56e025979.png)

**Comment by Ernst79** [comment]
hmmm, difficult decisions. The above screen is the title of github page (below about), we can change that perhaps to 
Passive BLE monitor integration (Xiaomi Mijia BLE MiBeacon Protocol)

**Comment by Magalex2x14** [comment]
maybe Passive BLE monitor integration (Xiaomi Mijia BLE MiBeacon monitor)?

**Comment by Ernst79** [comment]
Yes, OK. Let's use that for HACS.

**Comment by Magalex2x14** [comment]
We can change this text in the description (on github, below about) at any time, and it does not affect anything (except for visual information)?

**Comment by Ernst79** [comment]
Yes, we can change it right now

**Comment by Magalex2x14** [comment]
ОК. Now let's wait, what will Ludeeus say?
For now, we can release the updated code in the 0.8.1 beta (adding README with changes to the integration level), and then we will act depending on the answer?

**Comment by Ernst79** [comment]
I propose I ask ludeeus tomorrow, and depending on the answer we decide what to do next. 

I've updated the code to use `ble_monitor` right now, but we can change that tomorrow. After the answer, I will update the docs and prepare a 0.8.1 beta release, after your approval. 

But for now, I'm going to bed.

**Comment by Magalex2x14** [comment]
Yes, of course. Me too ) Good night )

**Comment by Ernst79** [comment]
I've asked, and he thinks it can be done without any issue. He first suggested to open a new repo, but I explained we prefer to keep the issues in the repo and do not want users to uninstall one component and reinstall another one. 
Next I asked if it was possible to keep the repo, change the name, and in a next step, roll out an update that removes the mitemp_bt folder and installs the ble_monitor folder. He thought that can be done without problems.

**Comment by Magalex2x14** [comment]
Good news, thank you. We can make a preliminary announcement on the forum also.

**Comment by Ernst79** [comment]
Will you do that? 
I'll update the documentation this evening, I propose we first change the repo name this evening and see what happens. Perhaps we have to update some links. If it all works, we can make a beta release later, or tomorrow.

**Comment by Magalex2x14** [comment]
Yes of course. Let's see what happens and I'll make an announcement at the same time as the beta is released.
