### ISSUE TITLE
Can I use a CGG1H (HomeKit version)?

### ISSUE THREAD

**Issue by EdwardJB** [custom-components/ble_monitor#149]
Hi, 

I've accidentally bought a HomeKit version of one of these sensors. I've tried adding it the usual way (I have existing, working sensors, the little square ones) but it doesn't work. Is there any way to use this model with this component - some settings tweak or firmware flash, etc?

```
sensor:
  - platform: mitemp_bt
    sensor_names:
        'A4:C1:38:0D:xx:xx': 'Room1' # Works
        'A4:C1:38:D1:xx:xx': 'Room2' # Works
        'D5:B2:17:C2:xx:xx': 'CCG1H' # Doesn't work
```

**Comment by Magalex2x14** [comment]
Hmmm...
First try turning on the [report_unknown option](https://github.com/custom-components/sensor.mitemp_bt#report_unknown) and see what happens in the HA log.

**Comment by EdwardJB** [comment]
> Hmmm...
> First try turning on the [report_unknown option](https://github.com/custom-components/sensor.mitemp_bt#report_unknown) and see what happens in the HA log.

Thanks for the tip. I've enabled that (plus the logging settings) and get the message about it being enabled.

`2020-11-11 19:21:40 INFO (SyncWorker_16) [custom_components.mitemp_bt.sensor] Attention! Option report_unknown is enabled, be ready for a huge output...`

However I don't see anything Bluetooth-related messages in the logs? It's been enabled for a long time, btw, as I actually found these settings not long after my first post.

**Comment by Magalex2x14** [comment]
OK. Move on.

Mija ecosystem bt-sensors (all or most) do not send data unless the device is activated with the official MiHome app.
If your sensor is not added anywhere, then you need to find a way to activate it. How should this look for the HomeKit version?

**Comment by Magalex2x14** [comment]
It is possible, of course, that this device does not send data in Mija MiBeacon protocol at all. In this case, everything becomes complicated... Either reflash it (if they have the same hardware, and you need to have specific knowledge to do this) or implement support for the QingPing protocol (I'm not ready to take on this now).

**Comment by Magalex2x14** [comment]
@EdwardJB I am closing this issue for now.
Feel free to reopen if there are any news or questions.

**Comment by EdwardJB** [comment]
> @EdwardJB I am closing this issue for now.
> Feel free to reopen if there are any news or questions.

Sorry for not coming back sooner. In the end I bought a bunch of regular Mi CGG1s so didn't pursue things any further.
