### ISSUE TITLE
Error in Home assistant integration

### ISSUE THREAD

**Issue by frabar55** [custom-components/ble_monitor#151]
Hi All,
I followed the guide to integrate the component in the home assistant (cor under p\i4). I always receive the error below.
where am I wrong?
Thanks & Regards

"Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/.homeassistant/custom_components/mitemp_bt/sensor.py", line 140, in run
    mysocket = aiobs.create_bt_socket(self._interface)
  File "/srv/homeassistant/lib/python3.8/site-packages/aioblescan/aioblescan.py", line 1280, in create_bt_socket
    sock = socket.socket(family=socket.AF_BLUETOOTH,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

**Comment by Magalex2x14** [comment]
Your python3.8 binary is built without Bluetooth socket support. Google this problem.
A little later I will try to find what keys I compiled with.

**Comment by Ernst79** [comment]
See this [solution](https://github.com/custom-components/sensor.mitemp_bt/issues/125#issuecomment-713355926)

**Comment by Ernst79** [comment]
Closing this issue. Feel free to reopen if you still have issues.

**Comment by frabar55** [comment]
I apologize for this delay. I solved the issue one week ago re-installing everithing from scratch.
Regards
