### ISSUE TITLE
Version 0.8.1 beta not downloadable from HACS

### ISSUE THREAD

**Issue by enribomber** [custom-components/ble_monitor#153]
It is not possible to download 0.8.1 beta.

Once you run "install" button, a red notification appears (not able to read because it's overlap with other buttons) and installation quits.

**Comment by Xitro01** [comment]
This is a sync issue, see: https://github.com/custom-components/ble_monitor/issues/152
Try restarting your host/HA.

**Comment by Ernst79** [comment]
Restart of home assistant will fix this.

**Comment by enribomber** [comment]
After a couple of reboots i was able to solve the issue
