### ISSUE TITLE
No content to download

### ISSUE THREAD

**Issue by artomka** [custom-components/ble_monitor#156]
Hi, I use your great BLE integration in HACS, but unfortunately, I cannot update to version 0.8.1. All the time it shows these messages: 
```
No content to download
8:29:03 PM – HACS (ERROR) - message first occurred at 2:12:40 PM and shows up 19 times

No file found 'custom_components/mitemp_bt/manifest.json'
8:29:03 PM – HACS (ERROR) - message first occurred at 11:28:45 AM and shows up 58 times
```
What can I do to fix this issue?

Thank you in advance for the advice.

**Comment by Ernst79** [comment]
Uninstall the component, restart home assistant, and install the component normally helps. We expect that this is an issue in HACS that is related to the change in the folder name of our component. Probably a sync issue.

Please report back if this works for you. Also keep this issue open for a while, as more people seem to have this issue.

**Comment by artomka** [comment]
It works. Thank you!
