### ISSUE TITLE
Update to 0.8.1 via HACS fails

### ISSUE THREAD

**Issue by jacekpaszkowski** [custom-components/ble_monitor#158]
Component is downloaded to custom_components location but in HACS there is still update available. Also after restart.
But version of component is working in HA. After performin "Update" in HACS.

![image](https://user-images.githubusercontent.com/4264991/99306385-71b5c080-2855-11eb-9ca3-3be62215eccb.png)

I also get this error message when i try to update:

```
2020-11-16 21:46:03 ERROR (MainThread) [custom_components.hacs.repository.integration.custom-components.ble_monitor] No file found 'custom_components/mitemp_bt/manifest.json'
```

**Comment by Ernst79** [comment]
Do you have a ble_monitor folder in the custom_components, or mitemp_bt?

**Comment by jacekpaszkowski** [comment]
After clicking "Update" `ble_monitor` was created and `mitemp_bt` removed.
And the error in loggs occured.

Now in HACS update is avaialbe but v0.8.1 of the component is running.

**Comment by Ernst79** [comment]
Just wait a day and check again tomorrow. It is most likely a sync issue in HASC due to the folder change. More people had the same issue, and it solves itself after a while.

**Comment by jacekpaszkowski** [comment]
Nothing changed automatically.
I had to uninstall the component, then restart HA and reinstall v0.8.1. Now there is no problem in HACS.
