### ISSUE TITLE
temperature_unit vs unit_of_measurement

### ISSUE THREAD

**Issue by andrey80nik** [custom-components/ble_monitor#162]
The sensor created in ble_monitor in the card outputs a value in "°C".
A normal sensor created by Home Assistant outputs values in "C"
And the Lovelace [History Graph Card](https://www.home-assistant.io/lovelace/history-graph) doesn't overlay data in a single graph
![5bTUhF6 1](https://user-images.githubusercontent.com/67071776/99783823-022d2300-2b2c-11eb-8305-ad394899adf9.png)

**Comment by Ernst79** [comment]
Can you tell me which integration you use for the `sensor.humidifier_temp`.  Temperature should be in °C, not in C, as this is defined as TEMPERATURE_UNIT in home assistant core const.py. So to my opinion, the other sensor is "wrong". E.g. ESPHome sensors also use °C

![image](https://user-images.githubusercontent.com/24375847/99790780-de1a1380-2b24-11eb-8bc0-01294675dcd5.png)

You can always overrule the unit_of_measurement in the configuration --> customizations menu. Just click the pencil and make the unit_of_measurement the same. 

![image](https://user-images.githubusercontent.com/24375847/99790938-26393600-2b25-11eb-89f5-7501c05f4465.png)

**Comment by andrey80nik** [comment]
- platform: template
  sensors:
    humidifier_temp:
      device_class: temperature
      unit_of_measurement: "C" 
      value_template: "{{ state_attr ('fan.xiaomi_miio_device', 'temperature') }}"

**Comment by Ernst79** [comment]
aha, just change the following line

`unit_of_measurement: "C"`

to 

`unit_of_measurement: "°C"`

**Comment by andrey80nik** [comment]
thank you, I already realized that the problem is not in the blu monitor, but no method helped, apparently the problem is in the home assistant.
![w66v1mc 1](https://user-images.githubusercontent.com/67071776/99794815-cac67280-2b3b-11eb-9dfa-489fcaa29628.png)
ахаха

**Comment by Ernst79** [comment]
Perhaps try this.
Remove the template sensor from your config, 
restart, 
Remove the entity if still present in the entity list
Add the template sensor again with the correct unit
Restart again.

**Comment by andrey80nik** [comment]
does not work. the card still only shows "C" without "°"

**Comment by Ernst79** [comment]
let me try it with your template sensor. Can you show the code you have right now?

**Comment by andrey80nik** [comment]
- platform: template
  sensors:
    humidifier_temp:
      device_class: temperature
      unit_of_measurement: "°C" 
      value_template: "{{ state_attr ('fan.xiaomi_miio_device', 'temperature') }}"

**Comment by andrey80nik** [comment]
perhaps the original fan integration is to blame ? I don't know what to look at anymore
`speed_list:
  - Silent
  - Medium
  - High
  - Auto
speed: Auto
model: zhimi.humidifier.ca1
temperature: 24.5
humidity: 52
mode: auto
buzzer: false
child_lock: false
target_humidity: 60
led_brightness: 2
use_time: 4495290
hardware_version: '0001'
motor_speed: 744
depth: 51
dry: true
friendly_name: Увлажнитель
supported_features: 1`
it does not specify the unit of measurement

**Comment by Ernst79** [comment]
It is working fine here.

![image](https://user-images.githubusercontent.com/24375847/99799006-428f9f80-2b32-11eb-8af5-c5c645f26af8.png)

**Comment by andrey80nik** [comment]
I don't understand why this happened in my case

**Comment by Ernst79** [comment]
Can you show the properties in development tools --> states of both sensors for me

**Comment by andrey80nik** [comment]
![JaZ1S50 1](https://user-images.githubusercontent.com/67071776/99800828-0a925780-2b46-11eb-987a-dbfa283cd7d0.png)

и 
![Eyc3cuz 1](https://user-images.githubusercontent.com/67071776/99800733-e0d93080-2b45-11eb-8964-17cf5bd43a21.png)
I don't see anything suspicious

**Comment by Ernst79** [comment]
Looks fine to me, to be honest, I'm running out of idea's. 

One more try
try to make a temperate sensor with a different name, and check again. Perhaps there is something stored in the database that is messing things up.

**Comment by andrey80nik** [comment]
and you are a persistent person))) it's working, yuhuu

**Comment by Ernst79** [comment]
I think the old sensor will work after all data with C as measurement is out of the database, probably after 24 h.

**Comment by madmicio** [comment]
is it possible to hide the unit of measurement?

**Comment by Ernst79** [comment]
That's possible in two ways.

1. Change it in the UI, when adding an entity in an entity card. At the unit of measurement, type a space. 

![image](https://user-images.githubusercontent.com/24375847/108636237-452cc880-7484-11eb-9e9f-f75c97d9f8bc.png)

2. under configuration --> customizations. Find your sensor and type a space in the unit of measurement field. 

![image](https://user-images.githubusercontent.com/24375847/108636292-9dfc6100-7484-11eb-8d16-ee3535f26533.png)
