### ISSUE TITLE
No content to download when trying to upgrade to 0.8.1

### ISSUE THREAD

**Issue by iemand-dev** [custom-components/ble_monitor#163]
I'm experiencing the same issue as with https://github.com/custom-components/ble_monitor/issues/157 but other than teamsuperpanda, first reinstalling 0.7.7 (and rebooting) and afterwards installing 0.8.1 simply gives the same result.

Does anyone have a suggestion which I perform?
Thanks

**Comment by Magalex2x14** [comment]
Someone was helped by uninstalling the component, rebooting HA, installing 0.8.1

**Comment by iemand-dev** [comment]
Thanks @Magalex2x14 that solved it.
I was hoping to avoid doing that but it clearly took a lot less time as originally expected ;)

Rest of the upgrade (breaking change) seems to work great!
Thanks again and thanks to the great developer behind it.
