### ISSUE TITLE
Two entities and unknown status

### ISSUE THREAD

**Issue by guillaumevende** [custom-components/ble_monitor#178]
Hello, two behaviors I have :
- first, I have 2 entities with different names but I declared only one
- secondly, they are displaying "unknown" values

Entities seem to be found (as they are displayed with blue icon, and I made my card reflecting this. 
<img width="361" alt="Capture d’écran 2020-12-01 à 17 24 54" src="https://user-images.githubusercontent.com/29797653/100767492-23c6be00-33fa-11eb-961c-e5b606f1190e.png">

**Comment by Magalex2x14** [comment]
I assume you have the `discovery` option enabled. If you do not have such sensors, then perhaps these are neighbors :)
The component creates entities when it receives packets from the appropriate devices. Pay attention to the differences in the mac addresses. The component does not know how to invent them :)

**Comment by guillaumevende** [comment]
I set False and now, nothing appears. So the entities I had weren't the one I configured. 
I'm going to try again later. Thanks for your help!
