### ISSUE TITLE
HHCCJCY01 (Mi Flora) sensor has no battery level

### ISSUE THREAD

**Issue by jacekpaszkowski** [custom-components/ble_monitor#18]
Wow,plant sensors are now supported by your component. Thank you.
There is no battery level info for HHCCJCY01 like i see for LYWSDCGQ.

Is it a bug or battery info is not available?

Cheers.

**Comment by Magalex2x14** [comment]
Battery info is not available.  The search led me to reports that the battery information was missing from some version of the firmware.  As I remember, devices released not so long ago (differ in a greenish tint in the color of the case) come with firmware without information about the battery.

**Comment by Magalex2x14** [comment]
in the README.md there is a mention of this (there is indicated a version in which there is already definitely no information about the battery).

**Comment by jacekpaszkowski** [comment]
ok, i understand. So maybe there is an option to create some kinde of hybrid solution and pull battety info like miflora component in HA?

**Comment by Magalex2x14** [comment]
interesting thought ... worth considering ...

**Comment by jacekpaszkowski** [comment]
:) nice to hear it and it would be possible to implement. Once again thank you for so nice component!

**Comment by tonyawad88** [comment]
I am also using the Mi Flora sensor, it works great with HAAS 0.112.4 but the battery level does not show. The Mi Flora I have is running firmware 3.2.2.

Using the Xiaomi "Flower Care" app shows the battery sensor info. Also the out of the box miflora haas integration (https://www.home-assistant.io/integrations/miflora/) shows the battery sensor info as well. Any idea if it's being broadcasted as well as the other sensors data? 

Let me know if there's something I can do to help.
Cheers.

**Comment by septeven** [comment]
I've decided to go with your component as I'm using room-assistant and this was not compatible with the miflora component I was using. Your component works well along with room-assistant so I'm happy with that, but that's sad that your component is not pulling the battery info. Any chance you implement this soon ?

Thanks for your great work btw !

**Comment by aqualx** [comment]
MiFlora sensor doesn't send battery information in _passive_ way. At least in FW 3.2.1. This component only listens passively to packets device sends by itself.
Even ESPHome that also fetches BLE information in _passive_ way - removed "battery sensor" from MiFlora component.
HA build-in compenent uses active BLE requests, but such comunication has negative impact on battery life...

As battery lasts almost 1 year - it is not so critical to implement any workarounds to get battery information. IMHO.

**Comment by septeven** [comment]
Thanks for the details @aqualx, I've been using miflora component since several months now and I can tell there's not been any impact on the battery so far...

**Comment by Magalex2x14** [comment]
It is not yet possible to receive data from sensors using a direct connection using our component in its current form.
During the development of a component, the potential possibility of such functionality is kept in mind.

**Comment by optikkore** [comment]
if you use home assistant i pull battery from miflora integration and use the passive ble for the other 4 sensors since that seems to update better and save battery
sensor:
  - platform: miflora
    mac: 'XX:XX:XX:XX:XX:XX'
    name: miflora
    force_update: false
    scan_interval: 3600 #battery level every hour
    monitored_conditions:
      - battery

**Comment by andrelung** [comment]
For anyone with hopes, the mentioned solution by @optikkore is not working anymore. 
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/4161059/206181841-72983cbb-a41e-4b7b-98e1-9da4b42294ee.png">

If you've landed here (like me), this might be the thread to look for help:
https://community.home-assistant.io/t/xiaomi-ble-mi-flora-unavailable/458707/2

**Comment by Ernst79** [comment]
The MiFlora sensor is available in the official xiaomi-ble integration. That integration is polling the battery once a day, and also gives you the other sensor measurements.

**Comment by Ernst79** [comment]
Battery level is "collected" in a different way, by "connecting" to the device and asking for the data. All other data is received passively. 

Connecting requires a better connection, so if the sensor is not close, this might fail, while the passive sensors still work nicely. One way to solve this is using ESPHome Bluetooth proxy, which can improve the reception.
