### ISSUE TITLE
Add support for Xiaomi Mi Flood Detector - SJWS01LM

### ISSUE THREAD

**Issue by pasolobo2** [custom-components/ble_monitor#181]
Hi.

I need support for the new Xiaomi Flood Detector - SJWS01LM

[log.txt](https://github.com/custom-components/ble_monitor/files/5630956/log.txt)
![photo_2020-12-02_18-27-28](https://user-images.githubusercontent.com/13574756/100908688-1548d700-34cc-11eb-8ed4-dec4f2b5ba86.jpg)
![photo_2020-12-02_18-27-43](https://user-images.githubusercontent.com/13574756/100908705-18dc5e00-34cc-11eb-8f49-503de1bd33dd.jpg)

Detect water leaks.

Thanks!!!

**Comment by Magalex2x14** [comment]
Thanks, I'll take a look tomorrow.

**Comment by Magalex2x14** [comment]
@pasolobo2 unfortunately, the dump you posted does not contain a single package with useful data. Please make sure that the sensor is added to the official application (MiHome), and that this application is closed while receiving the log (there is no active connection to the sensor), and try again to capture data.

**Comment by pasolobo2** [comment]
Hello again.

I did what you said.
Here is the news log. I wait its correct.
[log.txt](https://github.com/custom-components/ble_monitor/files/5648577/log.txt)


Thanks

**Comment by Magalex2x14** [comment]
@pasolobo2 thank you. We are dealing with another encryptor. In order to continue working on its support, you need to get the encryption key anyway. This can be done using one of the methods [described in our FAQ](https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key). The simplest is the MiHome mod by vevs. Consider the fact that after re-adding the sensor to the application, you will need to get the HA log again. There are two options here:
1. You give me a key and a new log
2. You tell me which version of the component you are using, I make a new code based on it, you add the key to the component's configuration, and write a new log in which the messages will already be decrypted.

The first option is safer. You can then change the key (by deleting and adding the sensor to MiHome again), if this is important to you.

**Comment by pasolobo2** [comment]
Hello again. 

I send you the key and the new logs.


[log.txt](https://github.com/custom-components/ble_monitor/files/5690389/log.txt)

Thanks

**Comment by pasolobo2** [comment]
Sorry... the key.
[key.txt](https://github.com/custom-components/ble_monitor/files/5690394/key.txt)

**Comment by Magalex2x14** [comment]
Received. I'll take a look a little later.

**Comment by Ernst79** [comment]
@Magalex2x14 Can you explain how you decrypt the advertisement. I can add this device, but I don’t understand how to decrypt the messages.

**Comment by Ernst79** [comment]
@pasolobo2 There is no `bind key` in your key.txt. The `token` mentioned in key.txt is not the key we need. Please follow the [instructions here](https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key) to find the `bind key`. It should have 32 characters.

**Comment by Magalex2x14** [comment]
@Ernst79 I had an idea to change the parser code so that, in the case of an unknown device, logging would occur after decryption (if the packet is encrypted), but my hands have not yet reached ...

In general, I just took the actual parser code and constants and added them to a small program that parses the text file with dump. Unfortunately, I am now out of place, and I do not have it at hand. I will return to this in early January.

**Comment by pasolobo2** [comment]
Hello and happy new year !!!....

I hope it is correct now.

[pairings.txt](https://github.com/custom-components/ble_monitor/files/5760144/pairings.txt)
[log.txt](https://github.com/custom-components/ble_monitor/files/5760145/log.txt)

**Comment by Ernst79** [comment]
Yes, that's the correct bind_key. I'll look into it.

**Comment by Ernst79** [comment]
I have created the [SJWS01LM](https://github.com/custom-components/ble_monitor/tree/SJWS01LM) branch, which adds support for your sensor. 

I used the Moisture type Binary Sensor, so it should show wet/dry as state. 

I have one strange thing, the device_type is shown as `b'c\x08'` in my script, while it is more likely to be `b'\x63\x08'`. I used the last, so please try. 

Please copy the code from `__init__.py`, `const.py` and `binary_sensor.py` to test. 

I haven't found a battery reading but I assumed it does send battery info, given your screenshot above. 

@Magalex2x14 What is the actual difference/purpose in the `MMTS_DICT` of battery at the measuring sensors as well as binary sensors, should I enable them both?

**Comment by Ernst79** [comment]
@pasolobo2 Did you had a change to try it?

**Comment by pasolobo2** [comment]
Hi.
I made the change in ble monitor, added the encryption_key in the config.yaml
I restarted my HA but I don't see the changes. What should i see?

ble_monitor:
  hci_interface: 0
  discovery: True
  active_scan: False
  report_unknown: False
  batt_entities: False
  rounding: True
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  restore_state: False
  devices:
    - mac: '54:EF:44:E0:27:BC'
      name: 'Agua'
      encryption_key: '255e6cabb39b2eddd0de992b9fee2bf2'

I dont see anything on the logs

logger:
  default: info
  logs:
    custom_componets.ble_monitor: debug

**Comment by Ernst79** [comment]
Aren't there any lines in the logs about ble_monitor?

Is a sensor added under integrations --> ble_monitor --> devices?

If not, you could try to change `b'\x63\x08'` in `const.py` to `b'c\x08'`

**Comment by pasolobo2** [comment]
Hi.

I made the change. 

#    b'\x63\x08': ("SJWS01LM", True),
    b'c\x08': ("SJWS01LM", True),

I send 
[b c x08.txt](https://github.com/custom-components/ble_monitor/files/5788819/b.c.x08.txt)
[b x63 x08.txt](https://github.com/custom-components/ble_monitor/files/5788821/b.x63.x08.txt)

you the logs with the two options.

**Comment by Ernst79** [comment]
It looks like something is wrong on this line. 

`Line 512:   File "/config/custom_components/ble_monitor/binary_sensor.py", line 113, in async_run`

Do you have the previous and/or next line in the log. I think something is missing around these lines, which indicates what is wrong.

**Comment by pasolobo2** [comment]
Here is ...

Traceback (most recent call last):
  File "/config/custom_components/ble_monitor/binary_sensor.py", line 113, in async_run
    sw_i, op_i, l_i, b_i = MMTS_DICT[sensortype][1]
ValueError: too many values to unpack (expected 4)

I send you a zip of my component...
[ble_monitor.zip](https://github.com/custom-components/ble_monitor/files/5788936/ble_monitor.zip)

**Comment by Ernst79** [comment]
You also had to copy `__init__.py` and `binary_sensor.py`, you now still have the old ones.

**Comment by pasolobo2** [comment]
Hi.

It´s work.
I send you the logs.

[log.txt](https://github.com/custom-components/ble_monitor/files/5792446/log.txt)

**Comment by Ernst79** [comment]
Great, thanks. I will prepare a beta release a.s.a.p.

**Comment by Ernst79** [comment]
Can you check one thing. Does it report battery state? (and at what interval).

**Comment by pasolobo2** [comment]
Sorry, yesterday my HA installation stopped working. I must reinstall it.
Also, my PC started doing weird things. I have to check. I will take a few days.

**Comment by alessocci** [comment]
Follow

**Comment by benkwyan** [comment]
> Hello and happy new year !!!....
> 
> I hope it is correct now.
> 
> [pairings.txt](https://github.com/custom-components/ble_monitor/files/5760144/pairings.txt) [log.txt](https://github.com/custom-components/ble_monitor/files/5760145/log.txt)

How do you find the bindkey for xiaomi Flood Detector?

**Comment by Ernst79** [comment]
Check the faq

https://custom-components.github.io/ble_monitor/faq#how-to-get-the-mibeacon-v4v5-encryption-key
