### ISSUE TITLE
Unable to get humidity from LYWSD02

### ISSUE THREAD

**Issue by vellanix** [custom-components/ble_monitor#189]
I just upgraded from 0.7.x to latest 0.8.5, changed the config and I cannot get the Humidity from LYWSD02.

I get the temperature, the battery level but not the humidity.
Any idea?
Thank you
<img width="663" alt="Schermata 2020-12-08 alle 17 57 57" src="https://user-images.githubusercontent.com/72751032/101515710-ee344e80-397e-11eb-9752-f7d264717ad5.png">

**Comment by andras-tim** [comment]
I had the same problem. I don't know how or why, but after several restarts, the thins are going now again...

This is a bit weird because there wasn't any error message in dmesg/HA/... logs.

**Comment by Magalex2x14** [comment]
Yes, I remember a similar issue. This was probably you, @andras-tim?
This looks suspicious as the issue was about the same sensor 🤔
I need to think about what this may be connected with. There are no ideas yet...
Extra sensors have not appeared in the list of entities?

**Comment by Magalex2x14** [comment]
Have you tried taking the battery out of the sensor and putting it back in?

**Comment by vellanix** [comment]
No, I'll try...


Il giorno 8 dic 2020, alle ore 20:35, Aleksey Makarenko <notifications@github.com> ha scritto:

﻿
Have you tried taking the battery out of the sensor and putting it back in?

**Comment by andras-tim** [comment]
Hi @Magalex2x14,

> Yes, I remember a similar issue. This was probably you, @andras-tim?
> This looks suspicious as the issue was about the same sensor 
> I need to think about what this may be connected with. There are no ideas yet...
> Extra sensors have not appeared in the list of entities?

As far as I remember, I wrote down this problem when I updated to version 1.1.2_00085, but unfortunately, I couldn't provide any useful info.

I have 3x WX08ZM, 1x CGG1, 1x LYWSD02, but the LYWSD02 was the only one that suffered from this problem.

> Have you tried taking the battery out of the sensor and putting it back in?

I had to replace the batteries in the near future. And maybe that was the time since it works properly. :slightly_smiling_face:

**Comment by vellanix** [comment]
> Have you tried taking the battery out of the sensor and putting it back in?

Done!

And now it's working....

Thanks!

**Comment by Magalex2x14** [comment]
Curious...

**Comment by andras-tim** [comment]
Everything worked fine after the **HA (0.118.5 => 2020.12.1)** and **ble_monitor (0.7.7 => 0.9.3)** upgrade for hours, but then I got this issue again...

- I tried to restart the machine, power off the dongle, but nothing helped on that side.
- However, When I removed temporarly the batteries from LYWSD02 that solved the problem immediately.

_(this should be a firmware bug I think.)_

**Comment by Magalex2x14** [comment]
Yes, it looks like a firmware issue. Anyway, I don't see any potential connection between this problem and the integration work. Communication with the sensor is only one-way...

**Comment by andras-tim** [comment]
FYI: the problem still exists, occurs regularly, but

* in connection w/ the Linux kernel, because w/ stock kernel of Ubuntu 20.01.1 (w/o upgrade) is affected, but the `5.4.0-58-generic` typically works
* if this issue appears then it always can be fixed by battery removal & reconnect
