### ISSUE TITLE
Encription key 24 characters long -- Error

### ISSUE THREAD

**Issue by txespirito** [custom-components/ble_monitor#193]
I cannot integrate LYWSD03MMC and CGD1 devices. They have a encryption key of 24 characters (eg 0fabea99ad86c38a49b85792)  instead of 32, and home assistant only lets you put keys of 32 characters.

**Comment by Magalex2x14** [comment]
The encryption key must be 32 characters long (16 bytes).
If your key has a different length, then this is the wrong encryption key or not encryption key at all.
Where did you get these keys?

**Comment by txespirito** [comment]
With an old version of Mi Home (log file) :(

**Comment by andrewjswan** [comment]
You must be confusing the bind key with encryption token (token in paring.txt file, It appears only when you add a device to MiHome, if it has already been added, this information is not available).

**Comment by txespirito** [comment]
Its true!!! Thanks :)

**Comment by Magalex2x14** [comment]
Feel free to reopen this issue, if needed.

**Comment by Magalex2x14** [comment]
By the way, guys, can you show me what a logfile from vevs MiHome mod looks like so that I know for the future?

**Comment by andrewjswan** [comment]
What logs?

пт, 11 дек. 2020 г., 15:54 Aleksey Makarenko <notifications@github.com>:

**Comment by Magalex2x14** [comment]
Logs from MiHome app, where you get encryption keys. I do not have an android, and I do not know how these logs look, and how to find the key there.

**Comment by andrewjswan** [comment]
I dont have logs when paring, but paring file look like:
Did: blt.3.13...
Token: f307...
Bindkey: f435...
Mac: 58:2D:....


пт, 11 дек. 2020 г., 18:29 Aleksey Makarenko <notifications@github.com>:
