### ISSUE TITLE
Support Request: Mi Body Composition Scale 2 (XMTZC05HM)

### ISSUE THREAD

**Issue by stefangries** [custom-components/ble_monitor#200]
I would like to request support for the Mi Body Composition Scale 2. Therefore I followed the [instructions ](https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation) but nothing like "BLE ADV from UNKNOWN" shows up in the log. Is there anything else I can do to provide information? Maybe the Data has to be pulled?

**Comment by Magalex2x14** [comment]
No, unfortunately, our integration is not capable of pulling data. If my memory serves me, we already had a request to miscale support, which ended in failure (the scale did not send any data). If you have other sensors that work with our component, and you are sure that the scale was in a reliable reception area, then I'm afraid there is nothing more we can do.

**Comment by stefangries** [comment]
That's sad, but thanks for your reply :-)
