### ISSUE TITLE
Question: downgrade firmware HHCCJCY01

### ISSUE THREAD

**Issue by rayholland** [custom-components/ble_monitor#214]
Does anyone know how to downgrade the HHCCJCY01 firmware? Because the latest firmware does not advertise the battery level info anymore :-(

**Comment by Ernst79** [comment]
As far as I remember, battery level isn't broadcasted by the MiFlora sensors, also not in older firmware versions. Battery info can only be received by polling the device (asking the device to send it). But that is not how our component works, it is passive, so it only listens, without asking. Unfortunately, we won't implement active polling, which means our component won't support battery info for MiFlora devices.  

The standard HA integration seems to support local polling
https://www.home-assistant.io/integrations/miflora/

**Comment by Magalex2x14** [comment]
Actually, some time ago (year, may be two), in the ESPhome repository, I read that the battery report was supported. But this is a very old firmware, miFlora has long been delivered with updated firmware without battery support (I bought my sensor a couple of years ago, and there are no more batteries).

**Comment by ACrazyConcept** [comment]
I just use the standard miflora integration only checking the batteries and then only polling a couple of times a day. Could probably be even less frequent.
