### ISSUE TITLE
Refactoring to use in a standalone project, e.g. ble2mqtt

### ISSUE THREAD

**Issue by nicolaerosia** [custom-components/ble_monitor#220]
Hello,

I'm running HA in a Docker container/or in cloud and I'm unable to forward hci adapter to the container.
I was wondering if you would accept factoring out the logic so this project could be used standalone, to publish to MQTT like zigbee2mqtt does (with advertisement to homeassistant/ so it automatically picks up devices).

What do you think?

Best regards,
Nicolae

Later Update: after a bit of google, I found this: https://github.com/devbis/ble2mqtt/ but it's active, not passive, and does not support all the devices this repo supports

**Comment by quarcko** [comment]
Hello,

Just posting to show there is interest in this function from more ppl!
I currently use this:
https://github.com/ChristianKuehnel/plantgateway
But it is as well quite limited active scanner to mqtt.
Also there is as well this one (never tried it so don't know):
https://github.com/ThomDietrich/miflora-mqtt-daemon

So there are lots of active solution, lets see this one goes MQTT as well!

**Comment by nicolaerosia** [comment]
check https://github.com/devbis/ble2mqtt/issues/1, the developer added support for one sensor.

**Comment by Ernst79** [comment]
I think it would be easier to put your bets on ble2mqtt. It shouldn’t be that difficult to add other devices in ble2mqtt, now they have support for passive mode for one device. Just look up the relevant parts in our code and copy it into ble2mqtt. I don’t expect ble_monitor will be converted to support Mqtt, but I’m not sure about @Magalex2x14 plans.

**Comment by Ernst79** [comment]
Closing this issue. Please continue in #34
