### ISSUE TITLE
More fine tuning parameters for "active" scan

### ISSUE THREAD

**Issue by quarcko** [custom-components/ble_monitor#223]
Hi,

Some devices (miflora) do not report battery level via passive messages,
To get them - you really have to do "active" scan, but current options are quite limited,
you can just set ON or OFF.
So this feature request is as follows:

1. Add configurable time how often to scan (in case of battery info it is really enough once 24h)
2. Choose which parameters to scan for (to be able to limit active scanner to just get battery stats)
    This option really should be "per device". like in each device section in settings specify what parameter
     is going to be "actively" scanned for. And if no parameters specified - no active scanning at all (even if enabled globally)

Off course it could be done some other way around, but you get the idea, make active scanning a bit more useful 
at getting missing bits of information without hitting battery life of devices too much.
Really even if just "timer" for active scanner is implemented - it is still good enough, i would set it to 24H and 
that's it.

Thank you!

**Comment by Ernst79** [comment]
@quarcko Good suggestion. It means however a mixed mode of active and passive scan. I'm afraid this will be quite some work to implement. @Magalex2x14 is a bit busy with work, so I don't know his opinion, but I don't expect that this will be implemented soon. But lets keep your issue open and we keep it in mind when further developing the component.

**Comment by Ernst79** [comment]
@quarcko I started to look into your request. First, I wanted to check what extra information I could get if I use active scan. But I don't see messages that seem to contain battery data. The only message I see is one that contains the name. 

`043e1902010400f34f6b8d7cc40d0c09466c6f7765722063617265b5`


Position | 00 | 01 | 02 | 03 | 04 | 05 | 06 | 07 | 08 | 09 | 10
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Value | 46 | 6c | 6f | 77 | 65 | 72 | 20 | 63 | 61 | 72 | 65


In ASCII, this is equal to `flower care` (https://github.com/vrachieru/xiaomi-flower-care-api)

From your message, I thought you were able to get the battery data with active scan. Is this correct?

**Comment by quarcko** [comment]
@Ernst79 

I never scanned the devices myself at such low-level,
but native Home Assistant integration with active scanning
and https://github.com/quarcko/plantgateway (that i am currently using)

Are able to get from plant sensor:
Moisture, Battery, Light, Conductivity, Temeprature.

Maybe look into plantgateway how it's done there?

**Comment by Ernst79** [comment]
Thanks, from what I understand, it's not just using enabling active scan (e.g. once every hour), but also sending the MAC and a request which data you actually want. I have to check if this is possible with `aioblescan`, which we currently use to do the Bluetooth parsing.

**Comment by Ernst79** [comment]
Another user mentioned the following solution.

> if you use home assistant, you can pull battery info with the miflora integration and use passive ble monitor for the other 4 sensors, since that seems to update better and save battery
> sensor:

```
platform: miflora
- mac: 'XX:XX:XX:XX:XX:XX'
   name: miflora
   force_update: false
   scan_interval: 3600 #battery level every hour
   monitored_conditions:
   - battery
```

**Comment by Ernst79** [comment]
I’m closing this issue as BLE monitor won’t support connecting to a sensor, due to its passive nature. Battery info from plant sensors can be found with the above solution.
