### ISSUE TITLE
BLE Monitor in docker swarm

### ISSUE THREAD

**Issue by TeoTN** [custom-components/ble_monitor#225]
Is it possible to run the BLE Monitor in docker swarm? I tried to configure it but it always fails to find hci0

**Comment by TeoTN** [comment]
I'm no expert in that area but I did a little bit of reading and probably it would be possible to run the monitor in docker swarm if it used `sysfs` instead of hci.

The issue is that Docker Swarm doesn't allow exposing devices to containers and it's not entirely clear if this ever will be implemented. Is adding support for sysfs an enhancement you could consider?

**Comment by Ernst79** [comment]
@TeoTN Sorry for responding so late. I'm not really into the details of docker swarm. I use a supervised installation myself, which is HA in a docker environment, as I understand. It's working fine there, but I don't know the difference with docker swarm.

**Comment by TeoTN** [comment]
Hey, the problem lies actually in what is used to interact with Bluetooth protocol. I looked around a bit and [this line](https://github.com/custom-components/ble_monitor/blob/master/custom_components/ble_monitor/aioblescan_ext.py#L33) seems to suggest you're using HCI for that. However, in Docker Swarm environment, containers do not have access to HCI.
So I asked around a bit, and it seems if the component was using `sysfs` instead, it would be possible to use it also in a swarm.

**Comment by Ernst79** [comment]
Thanks for the info. At the moment, we use aioblescan (slightly modified, see aioblescan_ext.py) to do the Bluetooth communication. It is making a hcidump to collect the data from Bluetooth, so it is correct that it uses HCI at the moment. 

Unfortunately, I'm not an programmer and I'm just learning by trial and error. Rewriting the code to use `sysfs` will be quite a challenge for me. I did make a start this week with updating our modified `aioblescan` to the latest version, perhaps that is a first step for me to better understand what it is doing now. 

So, it's not that I'm not willing to make this change, but it's the lack of experience that is holding me back at the moment. Hopefully, someone with more experience will step up and help me/us with this in the future.

**Comment by Ernst79** [comment]
I had a better look at this issue. Aioblescan uses [socket](https://docs.python.org/3/library/socket.html) to communicate with the Bluetooth adapter. It uses AF_BLUETOOTH, which allows to use Bluetooth communication directly in python3

> AF_BLUETOOTH supports the following protocols and address formats:
> - BTPROTO_L2CAP accepts (bdaddr, psm) where bdaddr is the Bluetooth address as a string and psm is an integer.
> - BTPROTO_RFCOMM accepts (bdaddr, channel) where bdaddr is the Bluetooth address as a string and channel is an integer.
> - BTPROTO_HCI accepts (device_id,) where device_id is either an integer or a string with the Bluetooth address of the interface.
> - BTPROTO_SCO accepts bdaddr where bdaddr is a bytes object containing the Bluetooth address in a string format. (ex. b'12:23:34:45:56:67') This protocol is not supported under FreeBSD.

aioblescan uses BTPROTO_HCI. We might be able to add one of the other options as well.

**Comment by Ernst79** [comment]
I just read that the docker container has to use `network_mode: host`, to use Bluetooth. Could you check if your container has this?

**Comment by Ernst79** [comment]
@TeoTN I'm closing this issue. The following topic shows a solution to make HCI available in docker, as described in my previous post. 

https://forums.balena.io/t/bluetooth-need-network-mode-host-to-be-visible-in-container/135723
