### ISSUE TITLE
Support for Oral-B Smart Toothbrush

### ISSUE THREAD

**Issue by Dskurihin** [custom-components/ble_monitor#226]
Hi, can support for Oral-B Smart Toothbrush be added (how it is done in https://github.com/Hypfer/Cybele/blob/master/docs/devices/OralBToothbrush.md ). Implementation seems to be pretty straight forward ..

**Comment by Ernst79** [comment]
Thanks for your request. 

At the moment, ble_monitor only supports devices that support the Mi-Beacon BLE advertisement protocol. 

I'll leave the issue/request open, but we have more urgent issues at the moment to add/change. We are looking into support for other protocols, the ATC advertising format (sensors with custom ATC firmware) will be investigated first.

**Comment by Ernst79** [comment]
ATC support is added, as well as qingping support. So, I can have a look at implementing your toothbrush. The link you gave doesn’t give all the info I need. Could you collect some data from the toothbrush with the following command.

`sudo hcidump --raw hci > dump.txt`

You can upload the file here by dragging it into a message.

**Comment by Ernst79** [comment]
@Dskurihin any update on this? Have you been able to get the data?

**Comment by Ernst79** [comment]
Let me know if you need some help. An easy possibility is adding the following line in `ble_monitor/ble_parser/__init__.py`

Change this part in the file 
```
def ble_parser(self, data):
    """Parse the raw data."""
```
With 
```
_LOGGER = logging.getLogger(__name__)

def ble_parser(self, data):
    """Parse the raw data."""
    _LOGGER.error("Received data: %s", data.hex())
```

Restart HA and after a few minutes, check your HA log, it should be filled with errors :-). Copy the log text and paste it into a file. You can add this file here to a post as a txt file. Make sure you play around with the tooth brush during this time. As it will collect all BLE messages, also from your phone etc, we will have to figure out which one comes from your toothbrush. If you know the MAC address (perhaps its in the app), it will make the search easier.

**Comment by alasdair-mott** [comment]
hi, Firstly, sorry if I'm going against etiquette posting on a closed issue. Secondly, thanks for the integration. After months of battling with other options i found HACS and your integration which just worked !

See attached log file for an Oral-b tooth brush. I have the mac address from a BLE scanner but its not included in the log
[home-assistant.log](https://github.com/custom-components/ble_monitor/files/7696085/home-assistant.log)
