### ISSUE TITLE
cannot make it working, getcap command not found

### ISSUE THREAD

**Issue by sunsgs** [custom-components/ble_monitor#227]
Hi All,
I'm using HASSIO on rpi3 but when I try to run sudo getcap `readlink -f \`which python3\`` it says command not found.
Any help?

**Comment by Ernst79** [comment]
This command is normally not needed on HASSIO installs (HASSIO is called Home Assistant nowadays). The the first line in step 1. 

> This is usually only needed for alternative installations of Home Assistant that only install Home Assistant core.

**Comment by sunsgs** [comment]
This is the error I get in to the logs 

HCIdump thread: OS error (hci1): [Errno 19] error while attempting to bind on interface 1: No such device

**Comment by Ernst79** [comment]
Try hci0 in stead of 1

**Comment by sunsgs** [comment]
Ok, no error in to the logs, but i cannot see the device . I mean, it has been discovered but the value is always unknown

ble humidity A4C138CB99DA
2 minutes ago
Unknown


so it is also temperature.

The sensor type is LYWSD03MMC

**Comment by Ernst79** [comment]
Did you enter the encryption key? It’s required for this sensor. It’s explained how to do that in the sensor description and faq. This sensor is also quite slow, only 1 message every 10 minutes with default firmware. (Battery even slower). ATC firmware can increase this.

**Comment by sunsgs** [comment]
Thanks,installed ATC firmaware, but now it says unavailable.

Is the mac address the same?
I need the encryption key now?

**Comment by Ernst79** [comment]
With ATC firmware, you have to select Mi-Like, when flashing the firmware. No key is needed

**Comment by Ernst79** [comment]
@sunsgs, if it works, could you please close the issue, to keep things tidy? thanks!
