### ISSUE TITLE
HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed

### ISSUE THREAD

**Issue by DmitriusDan** [custom-components/ble_monitor#228]
Hello,

Can you help to solve the following issue?

Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:520
Integration: Passive BLE monitor (documentation)
First occurred: 6:53:15 AM (1 occurrences)
Last logged: 6:53:15 AM
HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed

Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:345
Integration: Passive BLE monitor (documentation)
First occurred: 6:53:25 AM (1 occurrences)
Last logged: 6:53:25 AM
Waiting for the HCIdump thread to finish took too long! (>10s)

**Comment by Ernst79** [comment]
Did you update python recently? If so, Did you check the solutions in #167 ? 

Other option, how long did you set the period option? Try to increase it, if it is set short

**Comment by DmitriusDan** [comment]
I have update Python to 3.8 today!

Thank you.

**Comment by Ernst79** [comment]
So, it solved now? If so, please close the issue. Thanks

**Comment by DmitriusDan** [comment]
Thank you a lot!
