### ISSUE TITLE
sensor not detected in HA

### ISSUE THREAD

**Issue by jactora** [custom-components/ble_monitor#229]
I have 3 xiaomi sensors.
LYWSDCGQ with original firmware from xiaomi works fine and gets detected in HA
i have 2 of LYWSD03MMC
one of the LYWSD03MMC has original firmware from xiaomi works fine and gets detected in HA
another of LYWSD03MMC has the ble monitor firmware patched on it.
it is not detected in Mi app or HA.
i tried to refresh it with original firmware and back again with custom firmware.
but it never gets picked up. i got the key too although it was not needed
what could be the problem?
should i stick with original firmware?

**Comment by Ernst79** [comment]
You need to set the advertising to Mi-Like, see my mouse pointer

![image](https://user-images.githubusercontent.com/24375847/104035451-700fd580-51d2-11eb-8731-c18c22cbf9b5.png)

**Comment by jactora** [comment]
thanks. i thought i had set that up. i retried now and it worked.
do u know why this is now not being detected in mi app?
the flashed ones can be found in mi app as new devices but cannot be added

**Comment by Ernst79** [comment]
On the ATC website, it creates a new bind key when you activate it, so the old bind key in MiHome does not work anymore. When you want to use MiHome, you will have to add it there again, but this will/should recreate a new bind key, which means that the old bind key won’t work anymore. 

If you want it to work both in HA and in our component, you will need to use method 2 or 3 in the FAQ. MiHome mod is the easiest method. The FAQ was updated the day before yesterday by me with a step by step instruction.
