### ISSUE TITLE
Can’t get the encryption key for LYWSD03MMC with MiHome mod

### ISSUE THREAD

**Issue by redyuan43** [custom-components/ble_monitor#232]
Hi guys, can you please help me configure my LYWSD03MMC. I have installed app from @vevsvevs and I see token for the device but it's 24 characters. How to find the 32 one?

_Originally posted by @kozerskil in https://github.com/custom-components/ble_monitor/issues/7#issuecomment-616108969_

**Comment by Ernst79** [comment]
To help you, I need a little more information. 
Did you follow the instructions in the [faq](https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key)?
Did you add the sensor to MiHome mod?
Did you get the pairings.txt file on your phone?
If not, did you create the logs folder manually?

**Comment by Ernst79** [comment]
Closing this issue due to no response. Feel free to reopen if you still have this issue.
