### ISSUE TITLE
Qingping CGDK2 

### ISSUE THREAD

**Issue by Velcovsky** [custom-components/ble_monitor#234]
Hello, 

do you plan to implement Temp and Humidity sensor Qingping CGDK2? Or is it possible?
I gained BindKey of the sensor by MiHome Mod and then I added by GUI interface to HA, but the new sensor wasn't there.

Thank you
Jan V.

**Comment by Ernst79** [comment]
Sure, but we need the data to add it. Can you follow [these](https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation) instructions and send us the data. We also need the encryption key to decrypt the messages.

**Comment by Velcovsky** [comment]
@Ernst79 Thank you for the info.

Here are data. 

Log:
`2021-01-12 20:02:52 INFO (Thread-3) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -85, MAC: 582D34122089, ADV: 043e1f02010000892012342d58130201060f1695fe30586f0606892012342d5808ab
`
Key: a3bfe9853dd85a620debe3620caaa351

Is it okay? :)

**Comment by Ernst79** [comment]
Yes, excellent. Seems possible to add, will look into it tonight.

**Comment by Ernst79** [comment]
This was an easy one.

Please copy `const.py` from [this location](https://github.com/custom-components/ble_monitor/blob/CGDK2/custom_components/ble_monitor/const.py) to your custom_components/ble_monitor folder and overwrite the file (or copy past the content). 

If you can confirm it is working, I will include it in the next update.

**Comment by Velcovsky** [comment]
Ernst, you are awesome ;) 

I copied the code to `const.py ` and it works.

You can add to the next update :)

**Comment by Ernst79** [comment]
Released as 0.9.6-beta

**Comment by Manox35** [comment]
Hello, Can you tell how you have the bind key ? Which version of MiHome, which serveur ? I have Always an error trying ton add CDGK2 to MiHome. Thx

**Comment by Ernst79** [comment]
@Velcovsky can you answer this question perhaps? I don’t have a CDGK2 myself.

**Comment by Velcovsky** [comment]
Yes 👍  @Ernst79 

Hi @Manox35, I hope this helps you :)

1. Download MiHome mod (MiHome_6.0.203_63303_vevs.apk) 
2. I used https://temp-mail.org/ for creating a new account (I don't belivie  edited code for security reason)
3. And the I continue by 
I used manual [https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key](url)


If you have a problem with the error `standard verification failed`, reset the device to factory reset.
![reset_factory](https://user-images.githubusercontent.com/35589319/104699560-392a4a00-5713-11eb-909e-e1d1870a7881.PNG)

The original source of IMG (https://fccid.io/2AQ3F-CGG1/User-Manual/User-Manual-3990175)

**Comment by Manox35** [comment]
> Yes 👍 @Ernst79
> 
> Hi @Manox35, I hope this helps you :)
> 
> 1. Download MiHome mod (MiHome_6.0.203_63303_vevs.apk)
> 2. I used https://temp-mail.org/ for creating a new account  (I don't believe changed code, for security reason)
> 3. And then I continue by
>    I used manual [https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key](url)
> 
> If you have a problem with the error `standard verification failed`, reset the device to factory reset and then you try pair device :)
> ![reset_factory](https://user-images.githubusercontent.com/35589319/104699560-392a4a00-5713-11eb-909e-e1d1870a7881.PNG)
> 
> The original source of IMG (https://fccid.io/2AQ3F-CGG1/User-Manual/User-Manual-3990175)

Thx for all, now i can connect it and i receive informations. But even if i've tried about 50 times with so many version of Mi Home and i still don't have the file pairing.txt in the directory logs that i have created. I realy don't know what to do now after about 5h of work !!

**Comment by Manox35** [comment]
> > Yes 👍 @Ernst79
> > Hi @Manox35, I hope this helps you :)
> > 
> > 1. Download MiHome mod (MiHome_6.0.203_63303_vevs.apk)
> > 2. I used https://temp-mail.org/ for creating a new account  (I don't believe changed code, for security reason)
> > 3. And then I continue by
> >    I used manual [https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key](url)
> > 
> > If you have a problem with the error `standard verification failed`, reset the device to factory reset and then you try pair device :)
> > ![reset_factory](https://user-images.githubusercontent.com/35589319/104699560-392a4a00-5713-11eb-909e-e1d1870a7881.PNG)
> > The original source of IMG (https://fccid.io/2AQ3F-CGG1/User-Manual/User-Manual-3990175)
> 
> Thx for all, now i can connect it and i receive informations. But even if i've tried about 50 times with so many version of Mi Home and i still don't have the file pairing.txt in the directory logs that i have created. I realy don't know what to do now after about 5h of work !!

The directory is always empty !!

**Comment by Ernst79** [comment]
I've seen one other user that also had this issue, that the file wasn't created. He was able to solve it in two ways
1, use an old version of MiHome mod that starts with 5.x, or
2. use another phone, with a different android version.

**Comment by Manox35** [comment]
> I've seen one other user that also had this issue, that the file wasn't created. He was able to solve it in two ways
> 1, use an old version of MiHome mod that starts with 5.x, or
> 2. use another phone, with a different android version.

Thank you, I tried on Note 10 +, then on Galaxy Tab S7, I tried lower versions in 5.x but there was a connection error !! I will now try on IOS to see if it works. I'm going crazy ;) Thx for all anyway. I will keep you inform

**Comment by Ernst79** [comment]
MiHome mod won't work on iOs as far as I know

**Comment by Manox35** [comment]
> MiHome mod won't work on iOs as far as I know. 
> 
> I also had a lot of trouble when adding a LYWSD03MMC sensor. Had to try it about 20 times, before it was even added to MiHome. 


I'm giving up ! 4 phones, 17 apk versions, 15 hours trying several possibilities, nothing to do, I can not see the bindkey. Thanks for your help. It  was very kind of you

**Comment by Ernst79** [comment]
Sorry, I have no further ideas

**Comment by Manox35** [comment]
> Sorry, I have no further ideas


I took one last try and it worked and I figured out why. So if that can help somebody. It is specified on github ”The app will create a folder / devicestorage / vevs /. Add a folder logs in this folder (/ devicestorage / vevs / logs /) ”. In fact you should not simply create / logs in the / vevs created by the application but create the complete tree structure /vevs/logs otherwise no pairing.txt file. If you create /logs only then no files, if you create vevs / logs / before the application does it, it works. Now I will try to make work better because the refresh information is a bit long (sometimes no data during 10mn) . Sorry for my bad english  ;)

**Comment by Ernst79** [comment]
I'll update the faq with your information. Thanks.
