### ISSUE TITLE
Battery charge sensor for SJWS01LM have unavailable status

### ISSUE THREAD

**Issue by andrewjswan** [custom-components/ble_monitor#238]
I add to YAML new sensor like:
````
  - mac: '54:EF:XX:XX:XX:XX'
    name: 'Washing machine'
    encryption_key: 'XXXXX'
````
Restart HA and have this:
![ble](https://user-images.githubusercontent.com/3609660/104849593-2cfce300-58f3-11eb-955f-d3a5994bf715.PNG)

I try run ble_monitor.cleanup_entries but not help ...

PS: Fixed.

**Comment by andrewjswan** [comment]
I was able to remove unnecessary sensors, but now there is no sensor for the battery charge.
![image](https://user-images.githubusercontent.com/3609660/104850169-2f147100-58f6-11eb-91f1-e07c26d40b84.png)

**Comment by Ernst79** [comment]
When adding this sensor, I saw from the messages I got from @pasolobo2 hat there wasn't any battery reading. I expect that there is a battery advertisement, but very rarely (I see it in your printscreen above that it is available as attribute, so it has been send in the past. 

I propose you wait one day and check tomorrow if it has come up. also, do one more restart to make sure everything is loaded normally after the cleanup.

**Comment by andrewjswan** [comment]
Okay, not a problem, but I also noticed that restoring the state does not work for this sensor. After every HA reboot, it's in status unknown.

**Comment by Ernst79** [comment]
That's strange, could you to change the following line in `binary_sensor.py`

`_LOGGER.debug(old_state)`

to

`_LOGGER.error("Restored state: %s", old_state)`

It's somewhere in the following part of the code 

`async def async_added_to_hass(self):`

Then, do a restart, there should be an error in the log with Restored state. Can you post that message?

**Comment by andrewjswan** [comment]
Not today, but I'll see if the next reboot doesn't change anything, I'll make those changes and let you know.

**Comment by andrewjswan** [comment]
I connected this sensor on 0.9.7 Beta, but on this version all my temperature sensors stopped updating their values, I returned to 0.9.6, I observe.  There will be news to report.

**Comment by Ernst79** [comment]
0.9.8-beta has been released with a fix for your last issue. Please try again to see if it solves your issue.

**Comment by andrewjswan** [comment]
Thanks, i try to check ...

**Comment by andrewjswan** [comment]
Look like worked ...

**Comment by metronidazole** [comment]
@Ernst79 

I have a similar issue with the LYWSD03MMC. Did you want me to make a separate issue?

I'm using pvvx firmware with advertising type set to custom as you suggested, and my sensors were added automatically via the home assistant UI. They voltage level shows up as "unknown". However, if I click on the HA device for each sensor, it shows the battery level there. 

See https://i.imgur.com/B8lkR3R.png

**Comment by Ernst79** [comment]
When you go to integration, ble monitor tile, devices and than select your device, does it show the “voltage” sensor?

**Comment by metronidazole** [comment]
> When you go to integration, ble monitor tile, devices and than select your device, does it show the “voltage” sensor?

It does - that's what I meant when I said battery.

**Comment by Ernst79** [comment]
Did you reload the integration or restart HA?

**Comment by metronidazole** [comment]
I restarted HA. I just tried reloading the integration but it didn't make any difference either.

**Comment by Ernst79** [comment]
Aha, I can confirm your issue. 

You will have select "Generate battery entities" in the options of BLE Monitor to show battery sensors. This also applies for the voltage sensor at the moment.

**Comment by metronidazole** [comment]
Excellent that worked! It added separate entities for the battery %, and now the voltage ones are working too.

**Comment by Ernst79** [comment]
Note is added to the docs.
