### ISSUE TITLE
Is this project available for docker?

### ISSUE THREAD

**Issue by kifgep** [custom-components/ble_monitor#240]
I am running HASS from Synology NAS, is this project possible for me?

**Comment by Ernst79** [comment]
Not sure, Synology NAS does not have bluetooth, I assume. Not sure if it works with a dongle?

**Comment by kifgep** [comment]
Actually, I have several MiHome devices that play a role as Bluetooth gateway, like Redmi speaker, yeelight bath heater, I can access all my sensors through the MiJia app remotely.

The NAS actually running as a VM on an HP Gen8 microserver with Server 2019, I am not sure if the dongle can be recognized by the HASS......

**Comment by Ernst79** [comment]
I'm not sure either, you should just try. Note that this component uses the Bluetooth of the system HA is running on, and not the Bluetooth of an external gateway. So you have to add Bluetooth to the Synology NAS and the dongle should be made available to the HA docker. On normal Linux systems, this is normally possible.

Another option is to the Xiaomi Gateway 3 and this component [XiaomoiGateway3](https://github.com/AlexxIT/XiaomiGateway3). This component communicates to the gateway, and the gateway communicates with BLE sensors.

**Comment by kifgep** [comment]
I found this plugin, it will pull data from the Xiaomi server, so no need for Bluetooth for the docker image installed on Synology.
[MIoT](https://github.com/ha0y/xiaomi_miot_raw)

**Comment by Ernst79** [comment]
Ok, thanks for the reply. My Chinese isn't that well :-), but good to see that there is an alternative.
