### ISSUE TITLE
Integration can not be added via Menu (4a)

### ISSUE THREAD

**Issue by chiefmaster81** [custom-components/ble_monitor#241]
When trying to add teh integration in HOME-Asstistant after installation via HACS (4a)

after clicking on "Passive BLE..." it jumps back to Integration listing and in Logs appears: 

Logger: homeassistant.config_entries
Source: config_entries.py:526
First occurred: 7:50:30 (2 occurrences)
Last logged: 7:50:44

Error occurred loading configuration flow for integration ble_monitor: cannot import name 'CONF_UNIQUE_ID' from 'homeassistant.const' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/const.py)

**Comment by Ernst79** [comment]
Which version do you have of ble_monitor?

**Comment by chiefmaster81** [comment]
0.98 beta and 0.96 both with same issue on Home Assistant 0.111.4

**Comment by Ernst79** [comment]
I assume that you did a restart of Home Assistant after installation of ble_monitor? 

I'm afraid it's related to the drop of python 3.7 support in Home Assistant. Not much we can do about.

**Comment by chiefmaster81** [comment]
sure after each modifikation/installation. So will have to upgrade my Raspberry OS then I think...

**Comment by Ernst79** [comment]
I have removed and installed ble_monitor multiple times lately, so it works fine on the latest docker, 

I assume you use a `virtual  environment` installation at the moment. You don't have to reinstall the entire OS. Upgrading python and making a new virtual environment is enough. Note that you don't forget to add bluetooth support for python. There are instructions in the [FAQ](https://github.com/custom-components/ble_monitor/blob/ATC_support_v2/faq.md#i-get-attributeerror-module-socket-has-no-attribute-af_bluetooth-in-home-assistant-after-the-installation-or-python-upgrade)

Alternative is a `supervised` installation, which has the advantage that you don't have to worry about the python version anymore (will be updated automatically).
