### ISSUE TITLE
LYWSDCGQ connectivity issue

### ISSUE THREAD

**Issue by katatohuk** [custom-components/ble_monitor#244]
Hi there,
I need some help with my LYWSDCGQ sensor.
So I did a fresh install of Home Assistant OS as vm on Virtualbox, all was good in the beginning, sensor worked just fine.
After a couple of restarts of the host system, sensors temp/humidity are marked as "Restored" in the Entities tab.
Here are some logs from the host system:
`[32098.873968] Bluetooth: hci0: command 0x2003 tx timeout
`
And here is a piece of the log from Core:
```
2021-01-24 05:41:46 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.
2021-01-24 05:43:46 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed.
2021-01-24 05:43:46 ERROR (Thread-3) [root] Uncaught thread exception
```

I tried to google this issue, but all I could find is relevant from RPIs :(
Any help is much appreciated.
Thanks in advance

**Comment by Ernst79** [comment]
Did you check this [issue](https://github.com/custom-components/ble_monitor/issues/167)

Did you change python version recently? If so, check which version is used at the moment

`sudo getcap `readlink -f \`which python3\```

It might be linked to an outdated version, if have updated recently. If you have installed a newer python version, try the following command, where you change 3.8 to your new python version you have, of course.

`sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3.8\```

**Comment by katatohuk** [comment]
Hi there, 
Yeah, i saw the issue you mentioned, but the problem is that neither getcap or setcat  binaries are available at my hassos :(

**Comment by Ernst79** [comment]
I don't have a clue what could be wrong. Can you check `hcitool dev` to check the HCI interface is ok. 

Does a normal HCI dump work?

`sudo hcidump --raw hci > dump.txt`

**Comment by katatohuk** [comment]
Well, there is no hcidump tool as well, all I have related to bluetooth are:
- bluemoon
- bluetoothctl
- btmon

**Comment by Ernst79** [comment]
I found this [checklist](https://github.com/currantlabs/ble/issues/11). But not sure what you can run on HassOs, I don't have HassOs myself. It seems more related to your bluetooth installation than to `ble_monitor`. 

- Check if your system is running "bluetoothd", if yes, turn it off for now and see if that's the case.

Reset the HCI device in case it was in some bad status we couldn't recover from.

```
sudo hciconfig hci0 reset
sudo go run scanner/main.go
```

Check if your system (kernel) was configured with bluetoooth enabled at all.
```
sudo hciconfig hci0 up
sudo hcitool -i hci0 lescan
```

**Comment by katatohuk** [comment]
Seems HassOS has a very limited functionality. It doesn't even have sudo command and none of the above unf :(

**Comment by Ernst79** [comment]
You can try without sudo, I thought HassOs is already running as sudo. Otherwise, I'm out of ideas. Normally, it works out of the box on HassOs. Perhaps @Magalex2x14 has an idea.

**Comment by katatohuk** [comment]
Yeah, I login directly under root, so sudo isn't needed.
But anyway HassOS is lacking all of the commands you suggested
I can't get why this stuff worked in the very beginning, I haven't changed anything. Anyway thanks for your help :)

**Comment by zalvuccio** [comment]
I also have the same problem and have not changed anything solutions? my system is hassio

**Comment by katatohuk** [comment]
Okay, so here is what weirdly helped me:
- Since I'm using TP Link Bluetooth dongle I tried to plug it in a different USB port (have 4 on the back side of my DELL Optiplex mini PC), that didn't help at all
- I also have 2 front USB ports, plug into one of those magically helped !!!

I can confirm that issue isn't reproducible anymore, I restarted both hassio/host itself several times.

**Comment by Ernst79** [comment]
Do you have a SSD drive in the DELL? SSD's are known to interfere with Bluetooth, perhaps that is causing the issue. Or a power issue to the USB port?

**Comment by katatohuk** [comment]
Yeah, I'm using 2 SSD drives, m2 and regular 3.5

**Comment by Ernst79** [comment]
My guess is that your issue was related to the SSD drives, which interfere with the Bluetooth signal. 

@zalvuccio. If you still have the issue, and you have an external dongle, please try another port or put the dongle on a long USB extension cable

**Comment by Ernst79** [comment]
@zalvuccio. Closing this issue. Feel free to reopen if you still have the issue.
