### ISSUE TITLE
Support for Xiaomi Thermometer & humidity Sensor

### ISSUE THREAD

**Issue by vincentsticky** [custom-components/ble_monitor#246]
Hello
I'm using such a thermometer : https://www.amazon.fr/gp/product/B082B4X29R/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
It is accessible in the Xiaomi gateway (I can read the values in the xiaomi app on android)
On HA, I can get the devices, but they don't offer the values (battery/thermometer/hydrometry)
Do you think this integration is missing ?
If I can help do not hesitate
![image](https://user-images.githubusercontent.com/73120862/105706810-52e93f80-5f12-11eb-8dbb-1520a6f36972.png)

**Comment by Ernst79** [comment]
Based on the picture, it is the LYWSD03MMC sensor (you can check by clicking on "appareils"). By default, this device is encrypted, so you need to set set your [encryption_key](https://github.com/custom-components/ble_monitor#encryption_key) in the options (click on options, at the bottom, click on your device (MAC address, click submit and a new window will open where you can set your `encryption_key`). The [FAQ](https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key) explains how to get this encryption key. 

The other option is to use custom firmware, which doesn't need an encryption key. This is described on the main page, see below for a copy of the text.  

  `ble_monitor` also supports custom ATC firmware (both the firmware by `ATC1441`, available [here](https://github.com/atc1441/ATC_MiThermometer), and the improved firmware by `pvvx` available [here](https://github.com/pvvx/ATC_MiThermometer)). Both custom firmware's broadcast temperature, humidity, battery voltage and battery level in percent (note that both battery sensors are only visible as sensor with `batt_entities: True`). For the `pvvx` firmware, it is advised to change the `advertisement type` from `all` to `custom`. Sending multiple advertisment types at the same time might cause the voltage sensor from not showing up, depending on which advertisement comes first. The advertisement type `custom` will also result in a higher accuracy. Reloading the integration is needed to receive the voltage sensor after switching the firmware)

**Comment by vincentsticky** [comment]
Thanks a lot for your help !
Works fine with encryption Key. Thanks for the tuto ;)

Have a nice day!

Le lun. 25 janv. 2021 à 15:11, Ernst Klamer <notifications@github.com> a
écrit :
