### ISSUE TITLE
Possible support for Yeelight M2 Bulbs (YLDP25YL/YLDP26YL)

### ISSUE THREAD

**Issue by thawizard** [custom-components/ble_monitor#247]
I might be completely wrong here, but is there a possibility to support following ble mesh bulbs without a xiaomi multimode / yeelight gateway?

YLDP25YL/YLDP26YL
https://www.aliexpress.com/item/1005001868729811.html

**Comment by Ernst79** [comment]
I'm afraid not. This component is only listening passively to message send from devices. So it can't send messages to devices to turn them on/off. There are no plans to implement this in the (near) future.

**Comment by DemonidZe** [comment]
I am ready to somehow help with integration, send logs or do some manipulations.
