### ISSUE TITLE
LYWSD03 with PVVX custom not working

### ISSUE THREAD

**Issue by clau-bucur** [custom-components/ble_monitor#248]
I'm using `ble_monitor` 0.9.9 and `pvvx` 1.7 (tried with all pvvx versions).
I've enabled `report_unkown` and set log level to `info` for the component.

When I set advertising type to `custom` the device is not read and **no entries shown in HA log for the device's MAC**.
Once I switch to `mi` the device is readable again, and some UNKNOWN entries start to appear in the logs:
```
	95	2021-01-26	13:53:40	 INFO (Thread-5) [custom_components.ble_monitor] UNKNOWN dataobject from DEVICE: LYWSD03MMC, MAC: A4C13822EA5D, ADV: 043e5e0d021300005dea2238c1a40100ff7fc600000000000000000016151695fe50305b052a5dea2238c1a40a10013702890a130000fa2a2238c1a40100ff7fb600000000000000000016151695fe50305b0504fa2a2238c1a40a10011f000000
	96	2021-01-26	13:53:40	 INFO (Thread-5) [custom_components.ble_monitor] UNKNOWN dataobject from DEVICE: LYWSD03MMC, MAC: A4C13822EA5D, ADV: 043e5e0d021300005dea2238c1a40100ff7fc600000000000000000016151695fe50305b052a5dea2238c1a40a10013702890a130000fa2a2238c1a40100ff7fb600000000000000000016151695fe50305b0504fa2a2238c1a40a10011f000000
	98	2021-01-26	13:54:30	 INFO (Thread-5) [custom_components.ble_monitor] UNKNOWN dataobject from DEVICE: LYWSD03MMC, MAC: A4C13822EA5D, ADV: 043e5e0d021300005dea2238c1a40100ff7fba00000000000000000016151695fe50305b052f5dea2238c1a40a10013602810a13000038006538c1a40100ff7fb000000000000000000016151695fe50305b05db38006538c1a40d1004dc008301
	99	2021-01-26	13:54:30	 INFO (Thread-5) [custom_components.ble_monitor] UNKNOWN dataobject from DEVICE: LYWSD03MMC, MAC: A4C13822EA5D, ADV: 043e5e0d021300005dea2238c1a40100ff7fba00000000000000000016151695fe50305b052f5dea2238c1a40a10013602810a13000038006538c1a40100ff7fb000000000000000000016151695fe50305b05db38006538c1a40d1004dc008301
```

**Comment by Ernst79** [comment]
I'll check it tonight, I have pvvx version 1.2, and that worked fine with `custom`

**Comment by clau-bucur** [comment]
Thanks. I've tried with 3 sensors and all behaved the same for me.

**Comment by Ernst79** [comment]
The mi-like advertisements should work fine, as far as I can see. I get a proper result of your advertisement. Your first line results in:

`result:  {'rssi': -58, 'mac': 'A4C13822EA5D', 'type': 'LYWSD03MMC', 'packet': 42, 'data': True, 'battery': 55} `

don’t mind the UNKNOWN messages.

The custom advertisement probably fail due to the extended advertisement length you seem to have. In my case, I get the short advertisement. This depends on the Bluetooth adapter, I think. 

To make it work, I need to have the format in a hcidump. I’ll look up the commands, one moment.

**Comment by clau-bucur** [comment]
Unfortunatelly I can't run those commands (or I don't know how to). I'm running HassOS and hciconfig/hcitool seem to be missing.

**Comment by Ernst79** [comment]
What you can do as an alternative, is adding a debug messages in your HA log. 

Look for the following lines in `__init__.py` in the ble_monitor folder

```
    def parse_raw_message(self, data):
        """Parse the raw data."""
```

And add a debug line, like this

```
    def parse_raw_message(self, data):
        _LOGGER.debug("Data is: %s", data.hex())
        """Parse the raw data."""
```

Now turn on debug logging (at debug level), and the messages should appear in your Home Assistant log. Don't forget to remove after you are finished, as it will fill your log with a lot of data. 

Next, copy it to a text file, and look for lines with 161a18 (or 161A18). These are the ones you need. Post them here.

**Comment by clau-bucur** [comment]
I have this until now:
```
	56	2021-01-27	12:14:16	 DEBUG (Thread-5) [custom_components.ble_monitor] Data is: 043e2d0d011300005dea2238c1a40100ff7fc40000000000000000001312161a185dea2238c1a4e908a10e920a386404
	88	2021-01-27	12:14:21	 DEBUG (Thread-5) [custom_components.ble_monitor] Data is: 043e640d021300005dea2238c1a40100ff7fc00000000000000000001312161a185dea2238c1a4e908a10e920a3864041000014cacb4725a3f0100ff7fb40000000000000000001f1eff06000109200239efefc3edfda05cf041281b9cf390ba68aa92f820b8a1
	303	2021-01-27	12:17:12	 DEBUG (Thread-5) [custom_components.ble_monitor] Data is: 043e2d0d011300005dea2238c1a40100ff7fc40000000000000000001312161a185dea2238c1a4e708950e850a367504
	370	2021-01-27	12:18:12	 DEBUG (Thread-5) [custom_components.ble_monitor] Data is: 043e2d0d011300005dea2238c1a40100ff7fc60000000000000000001312161a185dea2238c1a4e9089c0e820a367b04
	402	2021-01-27	12:18:35	 DEBUG (Thread-5) [custom_components.ble_monitor] Data is: 043e2d0d011300005dea2238c1a40100ff7fc40000000000000000001312161a185dea2238c1a4ec089a0e870a377d04
```
Let me know if it's enough or shall I add more.

**Comment by clau-bucur** [comment]
Here are all the messages I collected: https://pastebin.com/VWD1kGkY
I commented out the debug line and disabled debug logging.

**Comment by Ernst79** [comment]
Thanks, I'll look into it tonight.

**Comment by Ernst79** [comment]
I found the issue, it's due to the extended (extra long) format of the advertisements you have. Good news, all data is available. First line is my sensor, second and third are yours. 

The bad news, I need to make some modifications for your advertisements. I'll create an update in the coming days. 

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------
HCI  Evt Len Sub Num Evt  Peer -------MAC-------        RSSI                   Len Len AD  Xiaomi ------MAC--------  ---------------PAYLOAD---------------- RSSI
type code    evt rep type addr                                                        Type  UUID                       Temp   Hum   Volt   Batt Count Flag   
--------------------------------------------------------------------------------------------------------------------------------------------------------------

 04   3e 1f  02  01   00  00  f4 83 02 38 c1 a4                                13  12  16  1a 18  f4 83 02 38 c1 a4    a9 06  69 11  b6 0b  58    f7   0d   de
 04   3e 2d  0d  0113 00  00  5d ea 22 38 c1 a4 0100ff7f c4 000000000000000000 13  12  16  1a 18  5d ea 22 38 c1 a4    c0 08  3a 0d  4b 0a  30    ae   04
 04   3e 2d  0d  0113 00  00  5d ea 22 38 c1 a4 0100ff7f c6 000000000000000000 13  12  16  1a 18  5d ea 22 38 c1 a4    ad 08  b3 0d  40 0a  2f    62   04
```

**Comment by clau-bucur** [comment]
Quite interesting. I wonder why mine are broadcasting such extended data?

**Comment by Ernst79** [comment]
I think it's a newer Bluetooth protocol of the dongle/radio you use or something like that. This difference is taken care of in the `mi-like` parsing in our component, but I didn't do that for the ATC sensors. To be honest, till last week, I thought it was something on the sensor side, but it seems to be on the receiving side. 

But no problem, I can take care of that. Just give me some time.

**Comment by clau-bucur** [comment]
Could be, I'm using a BLuetooth 5 dongle, so yes, it's pretty new.

**Comment by Ernst79** [comment]
Could you give it a try by updating `__init__.py` from the following branch.

Just replace the file with the content of this file. 

https://github.com/custom-components/ble_monitor/blob/ATC_extended/custom_components/ble_monitor/__init__.py

**Comment by clau-bucur** [comment]
Working! Thank you sir.

**Comment by Ernst79** [comment]
Will be included in the next update.

**Comment by Ernst79** [comment]
0.9.11 has been released, which fixes this issue.
