### ISSUE TITLE
Add version to a text field inside integration 

### ISSUE THREAD

**Issue by saikek** [custom-components/ble_monitor#250]
Please add **component version** in options section, 
so it would be easier to know when to update, 
when using with home-assistant (not hassio)

**Comment by Ernst79** [comment]
What do you mean by "options section"?

**Comment by clau-bucur** [comment]
Could be something similar as what Zigbee2MQTT creates.
![image](https://user-images.githubusercontent.com/47672949/106261540-5d654b00-622a-11eb-8881-7715dd022528.png)

**Comment by Ernst79** [comment]
But that is for the firmware version, not component version. The sensor does not send firmware information in passive mode. I think @sailek is looking for the version of `ble_monitor`? Or not?

**Comment by clau-bucur** [comment]
What I attached, and what Z2M produces, is the component version (the version of Zigbee2MQTT), not the actual firmware version of the RTCCQ11LM device.
But indeed, the version of any HACS component can be found as you noted.

**Comment by saikek** [comment]
Yes, i'm looking for a version of `BLE_monitor`. Since I'm **not** using hassio / HACS, it is not clear what's the current version and if I should update.

**Comment by Ernst79** [comment]
Ok, clear. I will think of something. 

The firmware field is used to make distinction between ATC firmware or Xiaomi (MiBeacon) firmware, so we can't use that (starting from 0.9.11-beta). 

**Note to myself:**
I have to look what is the best place to put this
 - attribute of the sensors
 - text in the options menu of our integration 

And we need to figure out if it can be filled automatically, without having to change the number in the code each time we release an update

**Comment by Ernst79** [comment]
As a start, I added the version number to manifest.json (starting from 1.2.0-beta). This seem to become mandatory in the future, see https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions . Personally, I hope this information will be displayed somewhere in HA in the future (can't find it at this moment), as it seems to become a requirement.
