### ISSUE TITLE
LYWSD03MMC's ATC format no longer works

### ISSUE THREAD

**Issue by eduperez** [custom-components/ble_monitor#257]
The v2 branch added support for LYWSD03MMC's ATC format, and it worked great. Unfortunately, after 0.9.9 only Mi-Like format works. I tried 0.9.11-beta, and neither format worked; now on 0.9.11, and only Mi-Like format works.

I'm currently using HassOS core-2021.1.5 on a Raspberry Pi 3 Model B Rev 1.2, without any external BT dongle.

**Comment by Ernst79** [comment]
Ok, lets find out what is going on. First 2 questions that can help us find out what is wrong.  

- Can you set the sensor to one of the ATC formats and enable `report_unkown` in the options, also enable debug logging at info level (put the following YAML in configuration.yaml) and restart HA. 

```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: info
```

  After the restart, wait a couple of minutes and check if there are a number of "BLE ADV from UNKNOWN" messages accumulated in the log. Copy these lines here in this issue.  
- If that doesn't work, look up the following line in `__init__.py` in the ble_monitor folder

```
    def parse_raw_message(self, data):
        """Parse the raw data."""
```

Change it to the following

```
    def parse_raw_message(self, data):
        _LOGGER.error("Data: %s", data.hex())
        """Parse the raw data."""
```

  Restart HA and you will get a lot of errors in you log with `Data:` followed by a long number. Wait a couple of minutes and copy the lines from the log here in this issue (you can add a txt file)

**Comment by Ernst79** [comment]
Do you use `discovery: False` in your config? I found a small bug, that could explain it

**Comment by eduperez** [comment]
Yes, i have `discovery` set to `False`; and yes `1.0.0` fixed the issue.
Many thanks!
