### ISSUE TITLE
[Enhancement] Expose number of messages and number of devices as a sensor

### ISSUE THREAD

**Issue by borpin** [custom-components/ble_monitor#265]
I'd like to see the status of the integration exposed as a sensor.  The log reports;
```
[custom_components.ble_monitor.sensor] 114 MiBeacon BLE ADV messages processed for 5 measuring device(s).
```
If a `sensor.ble_monitor_status` could be exposed with these 2 pieces of information it would be useful. I'd use it to notice if one of the sensors was not responding.

**Comment by Ernst79** [comment]
Cant you use the last packet_id attribute for that? This is changed every period and is the last frame count (message number). If it isn’t changed, it probably has stopped working. Note however that some sensors do not update very often. So, it depends on the sensor wether you should expect an increase of the number every period (1 minute by default).

The number of messages in a period can be checked as well, with the “last mean of” attribute.

you can use template values to extract this data.

**Comment by borpin** [comment]
Would just be useful. The other methods are just a PITA to implement. A simple sensor would be a great enhancement IMHO.

**Comment by Ernst79** [comment]
I understand your request, but unfortunately I'm not going to implement this. 

Let me explain why. It is not common to include sensors that just report the status of the component. It also adds more code to maintain, update, etc. and my time is limited (it's just a hobby). So I want to focus on the core of the component. 

So, at this moment, I'm not going to add this, I'm sorry. If you really need this information, it can (more or less) be achieved with template sensors, as explained above.
