### ISSUE TITLE
Non-existent devices have been added.

### ISSUE THREAD

**Issue by pothirak** [custom-components/ble_monitor#267]
![image](https://user-images.githubusercontent.com/34833872/107363377-a2339080-6b0c-11eb-94f2-3cc0b257fbc4.png)

3 devices above Is a device that I have not added. And i don't own it,
It has no status and information sent in any way.

It is always being added by itself What caused this problem?

**Comment by Ernst79** [comment]
It's probably a sensor from your neighbor, which is just at the edge of the range. When BLE monitor receives a message that is known to come from a Xiaomi device, it generates the sensor in HA automatically. If it receives more data, it starts generating the actual data, like temperature. 

What you can do is using the `discovery: False` option. This will stop adding sensors automatically. Next, remove the three sensors you don't want by typing `-` in the MAC field of the sensor (via integrations - ble monitor - options - devices drop down menu - select the device with the mac you want to remove). If you use config in YAML mode, just set `discovery: False` and make sure you have the three sensors you want added under the `devices` option.
