### ISSUE TITLE
CGDN1 Qingping Air Monitor Lite

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#269]
Request for support for CGDN1 by @kleju00

**CGDN1**
Name: Qingping Air Monitor Lite
Address: 04:CF:8C:28:A4:0C
CGDN1 also has the function of a BLE gateway

![image](https://user-images.githubusercontent.com/24375847/107527645-4d9a1f00-6bb9-11eb-8efd-aa6074c49518.png)

**HCI Dump 1**
[dump CGDN1.txt](https://github.com/custom-components/ble_monitor/files/5958971/dump.CGDN1.txt)
PM2.5 - 28
PM10 - 33
CO2 - 678 ppm
Temp - 17,0 C
RH - 71%

**HCI Dump 2**
[dump CGDN1 2.txt](https://github.com/custom-components/ble_monitor/files/5958990/dump.CGDN1.2.txt)

PM2.5 - 13
PM10 - 14
CO2 - 715 ppm
Temp - 16,2 C
RH - 85%

```
HCI  Evt Len Sub Num Evt  Peer -------MAC-------   Len Len Type Val Len  AD         Frame Product Frame ------MAC--------      RSSI  
type code    evt rep type addr                             flag         type  UUID   ctrl   ID    cnt                       
--------------------------------------------------------------------------------------------------------------------------------------
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD        08 0E         0A A4 28 8C CF 04      DA 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C   00    0A A4 28 8C CF 04   81 D7
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD        08 0E         0A A4 28 8C CF 04      DB 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C   00    0A A4 28 8C CF 04   81 DB 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C   00    0A A4 28 8C CF 04   81 DB 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD        08 0E         0A A4 28 8C CF 04      DB 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD        08 0E         0A A4 28 8C CF 04      DB 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD        08 0E         0A A4 28 8C CF 04      D9 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C   00    0A A4 28 8C CF 04   81 D9 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD        08 0E         0A A4 28 8C CF 04      D9 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD        08 0E         0A A4 28 8C CF 04      DA 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C   00    0A A4 28 8C CF 04   81 DA 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD        08 0E         0A A4 28 8C CF 04      D9 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C   00    0A A4 28 8C CF 04   81 D8
 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C   00    0A A4 28 8C CF 04   81 CE 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C   00    0A A4 28 8C CF 04   81 CC
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD        08 0E         0A A4 28 8C CF 04      CE 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C   00    0A A4 28 8C CF 04   81 CD
```

**Comment by boesing** [comment]
hey there, 

dont want to make any pressure, just curious:

Is this already planned for an upcoming release or just parked as "nice to have somewhen in the future"?

I am asking, because I've recently bought this device and for now I dont even get it attached to my wifi 🙄 
As the display turns off after some time aswell (even when on AC), the device is actually not really helpful for me. 

So I'd like to wait for this to be implemented but if this will be available in the unforseen future, I would send the device back to amazon and re-order when this device is supported by ble_monitor.

Would love to get some feedback.
Thanks in advance.

**Comment by Ernst79** [comment]
I've checked the second log, but it's all the same data. Basically, I only see the RSSI level at the moment, the rest isn't containing any data. 

@kleju00 is the device connected to MiHome? If not, it probably doesn't send data. Can you check if it is added in MiHome?

**Comment by boesing** [comment]
I would help here but I am struggling with the device.

I've added it to the Qingping+ App (tested android & iOS) and connected to my wifi.
I cannot change any setting (getting errors) or update the firmware (stays at 0%).

Even tho, its not detected by Xiaomi Home App (the device is not even listed when I search for Qingping?).

Not sure if I am doing something wrong or if I got a broken device...

**Comment by kleju00** [comment]
> is the device connected to MiHome? If not, it probably doesn't send data. Can you check if it is added in MiHome?

Yes, the device was connected to Xiaomi Home all the time.
It is possible that this device is not sending measurement data.
The BLE gateway from the air humidifier cannot see this device. The BLE gateway from the device can see all other devices. 
A device without configured WiFi has the Bluetooth module turned off.
I think it is not possible to add this device.
![image](https://user-images.githubusercontent.com/50960830/108431793-a87be800-7243-11eb-99a9-5f8ae23fa422.png)
![image](https://user-images.githubusercontent.com/50960830/108431804-ae71c900-7243-11eb-8ebb-95b04343a502.png)

> Even tho, its not detected by Xiaomi Home App (the device is not even listed when I search for Qingping?).

This device requires China as the app region. The picture shows where this device is on the list.
![image](https://user-images.githubusercontent.com/50960830/108432118-2a6c1100-7244-11eb-9f89-49af5f6a0dce.png)

**Comment by kleju00** [comment]
Small bug ... the correct MAC address is 04:CF:8C:28:A4:0A. Sorry.

**Comment by Ernst79** [comment]
I am afraid I agree that it is not possible  than. Its probably communicating its measurements to mihome by Wi-Fi, I guess. 

Closing the issue, but feel free to reopen if someone finds new data.
