### ISSUE TITLE
After installation, can't find Passive BLE monitor in integration

### ISSUE THREAD

**Issue by riyas1980** [custom-components/ble_monitor#270]
Hello,

I've installed this addon in HACS. After installation, I've restarted it many times. But after that when I go to configuration => Integration, I can't find Passive BLE Monitor. I don't understand why it's not working. I am using Home Assistant Supervised (Version | core-2021.2.3)

Can you please tell me if it's a known issue ?

Thanks and Regards,

**Comment by Ernst79** [comment]
No, it’s not a known issue.

Please check if the ble_monitor folder is in the folder custom_components. 
It might also be a caching issue, try it in an incognito tab of your browser

**Comment by riyas1980** [comment]
Tried to add manually with yaml. Suddenly it appears now. I don't have any explanation. But it's working fine. Thanks

**Comment by STmateo** [comment]
same thing happened to me. I can't find it. It's not showing up in integrations.
Did anyone find a solution for this?

**Comment by Ernst79** [comment]
Just hit F5 a couple of times to refresh the browser cache
