### ISSUE TITLE
No automatic detection

### ISSUE THREAD

**Issue by Ryukenden88** [custom-components/ble_monitor#273]
Hello,

i flashed the ATC firmware and selected the custom firmware option.
Then i installed the BLE monitor integration in haccs, and in integrations.

Then when i select options and press submit (without changing any settings) noting happens.
What should i see next? what will it show when it detects new devices?

**Comment by Ernst79** [comment]
Next, it should automatically show a new device in the integration tile within one minute. So, you did all what’s needed.

are there any errors in the log?
Can you try placing the sensor next to your HA device

**Comment by Ryukenden88** [comment]
it says:
HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed

The device is litterally 20 centimeters from the raspberyy pi 4

**Comment by Ryukenden88** [comment]
![Naamloos](https://user-images.githubusercontent.com/77883357/107888697-47d07080-6f0e-11eb-9846-907c575cad99.png)

**Comment by Ernst79** [comment]
Try running this command.

`sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3.8\`` `

change 3.8 to the same version as HA is using.

**Comment by Ryukenden88** [comment]
im putting it in ssh terminal addon and it shows me this:
![3](https://user-images.githubusercontent.com/77883357/107888920-d72a5380-6f0f-11eb-95f6-e28b8a512ebf.png)

**Comment by Ernst79** [comment]
What type of Home assistant installation do you have?

**Comment by Ryukenden88** [comment]
where can i see those details?
i installed it on a raspberry pi4.

in the ssh terminal it says OS Version Home assistant os 5.11
Home Assistant Core 2021.2.3

**Comment by Ernst79** [comment]
That is enough info. 

Can you try the above command again without `sudo`

**Comment by Ryukenden88** [comment]
![2](https://user-images.githubusercontent.com/77883357/107889246-7dc32400-6f11-11eb-9fe5-9e0e4eb14e0c.png)

**Comment by Ernst79** [comment]
Try installing it

`apt-get install libcap2-bin `

**Comment by Ryukenden88** [comment]
bash: apt-get: command not found

**Comment by Ryukenden88** [comment]
![4](https://user-images.githubusercontent.com/77883357/107889489-3c337880-6f13-11eb-8eda-965af5dff3af.png)

**Comment by Ernst79** [comment]
Hmmm, you have this issue. 

https://github.com/custom-components/ble_monitor/issues/167

In that topic, they were able to run the first command. I know HassOs is already running as Sudo and is quite restrictive on installing things yourself. You can’t install programs with apt-get on HassOs, I forgot.

could you just try a full restart

**Comment by Ryukenden88** [comment]
restart server? or unplug the pi from the wall ?

**Comment by Ernst79** [comment]
Full restart

supervisor - system - reboot host

**Comment by Ryukenden88** [comment]
it has rebooted now, sorry takes a while

**Comment by Ernst79** [comment]
Still the same error?

**Comment by Ryukenden88** [comment]
the same thing shows with the apt-get and the setcap command,
command not found

**Comment by Ernst79** [comment]
Yes, I understand, but do you have the same error in HA?

**Comment by Ryukenden88** [comment]
omg ! New voltage sensor found with MAC address xxx xxx xxx
ble monitor now shows te device!

**Comment by Ernst79** [comment]
Wait a minute, the rest should show as well

**Comment by Ryukenden88** [comment]
yes, i cut the message short

**Comment by Ernst79** [comment]
Enable battery entities in the options of blemonitor to show the voltage sensor

**Comment by Ryukenden88** [comment]
you mean generarate battery entitities?

**Comment by Ernst79** [comment]
Yep

**Comment by Ryukenden88** [comment]
so basically what was the issue here? did i just need a host reboot in the end ?

**Comment by Ernst79** [comment]
I’m afraid so, not sure why.

**Comment by Ryukenden88** [comment]
so maybe i could now just use the stock version of the xiaomi too, instead of flashing firmware ?

**Comment by Ernst79** [comment]
Yes, you can, but custom firmware is more accurate. I would keep it, but that’s up to you. Stock firmware doesn’t have the voltage reading as well

**Comment by Ryukenden88** [comment]
ill keep it as it is now,
Thank you SO much for your help, and for your time ofcourse.

this problem has been kicking my behind for 2 days and i would not have been aible to solve it without your help Ernst!

**Comment by Ernst79** [comment]
You’re welcome
