### ISSUE TITLE
Xiaomi Mi Body Composition Scale

### ISSUE THREAD

**Issue by josemml2019** [custom-components/ble_monitor#282]
Hi, is made possible add support for Xiaomi Mi Body Composition Scale?
Thanks
Best regards

**Comment by Ernst79** [comment]
please check the faq on how to get a new device added. We need some data from the sensor from you to get it added.

https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation

**Comment by perseus177** [comment]
I tried today but nothing in logs

**Comment by Dskurihin** [comment]
Could this be helpful - https://github.com/lolouk44/hassio-addons/tree/master/mi-scale ?

**Comment by Ernst79** [comment]
It would be helpful if someone can send a hcidump with the MAC address 

`sudo hcidump --raw hci > dump.txt`

**Comment by xekil** [comment]
@Ernst79 Hello, I want to try but I am on hassio and the command does not work

**Comment by Ernst79** [comment]
On Home Assistant OS (previously Hassio) you will have to use this procedure first to get ssh access to the operating system and run the commands (I tried it, and it worked). 

https://developers.home-assistant.io/docs/operating-system/debugging/

In short, you have to generate a key, put it on a USB and reboot your HA system. This will give you SSH access (e.g. with putty). Type `login` and you will get access to the `hcidump` command.

**Comment by xekil** [comment]
I tried the procedure but it doesn't work
(Home Assistant OS 5.12)

**Yet I have:**

- Formatted the USB key as eXFat
- Renamed the key in CONFIG
- Generated the public SSH key with Putty
- Create an authorized_keys file at the root of the USB stick
- Pasted and saved the SSH key in this file

Do you have a sample file?
Maybe there are elements that are not good?

**Comment by Ernst79** [comment]
Did you specify your private key in putty, under connection, SSH, Auth?

![image](https://user-images.githubusercontent.com/24375847/113903662-80cfe780-97d1-11eb-90a3-527269083f85.png)

**Comment by xekil** [comment]
indeed I did not have to add the private key in putty, I can now connect to port 22222 but not identify myself

![private](https://user-images.githubusercontent.com/69087258/113905058-099b5300-97d3-11eb-820c-2a0705c85af0.png)

**Comment by xekil** [comment]
server refused our key !

**Comment by Ernst79** [comment]
If I look in notepad++ I see it's UTF8. The instructions indeed say it should be ANSI, didn't look at that. Nevertheless, it worked for me. 

![image](https://user-images.githubusercontent.com/24375847/113905772-cdb4bd80-97d3-11eb-9754-660d3bf701c7.png)

I get the error you have if I did not select the private key.

**Comment by xekil** [comment]
I think it's the way of copying it to the file that is causing the problem, do you have an example of your file?

Should we leave the following lines?
---- BEGIN SSH2 PUBLIC KEY ----

**Comment by Ernst79** [comment]
Did you also check line ends to be LF

![image](https://user-images.githubusercontent.com/24375847/113906472-972b7280-97d4-11eb-8357-682e1d7e97de.png)

**Comment by Ernst79** [comment]
No, it is only one line, like this

![image](https://user-images.githubusercontent.com/24375847/113906573-ae6a6000-97d4-11eb-882d-f44446f5abf8.png)

**Comment by xekil** [comment]
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20210407"
AAAAB3NzaC1yc2EAAAABJQAAAQEAySAmcMK5zwbZbbXJ7tva2i5h/2bSS1yOobGo
ttCMozNU4LyYmuvgTvGQojAHs2z3Q55WSQ55/n+bvOtUhTVfffVi2sOG22tGF3SM
EoscjH8T01yTjQdvnyvlHvpG7SNIspmisazr+vKQ1Wws034KTQN8XfI0RzgbccLV
6568/WZVpyk7ITIdoVF6e5dLlSmqiL0pqUIO6IaRstMuQ6U5BlLyfypOBP0GAIK3
2aCWfKzoQjw8OJCPhSac0w0g2u9PA56J8UlwS5I3Mjn865Sukh80iFCrdNnez+cQ
QR9QXFKTrLuApbLi1DXG/SeX6F2J4DAVFEDt9xmavk6t7MvTZQ==
---- END SSH2 PUBLIC KEY ----

no LF !

**Comment by Ernst79** [comment]
Did you click on view --> show symbols --> line ends?

**Comment by xekil** [comment]
I regenerated a new key and this time I have the symbols but there are several lines in my files

![public](https://user-images.githubusercontent.com/69087258/113908108-77954980-97d6-11eb-909c-5bed4a6d73e9.jpg)

**Comment by xekil** [comment]
ok I will try

**Comment by xekil** [comment]
server refused our key !

**Comment by Ernst79** [comment]
Ah, I remember I used the other method, as I did not succeed with the puttygen method. sorry

https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#platform-mac

1. Open Git Bash.
2. `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`

**Comment by xekil** [comment]
ok thanks for the info, it seems complicated the other method ...

**Comment by xekil** [comment]
So I generated the two keys with this method, there is indeed LF at the end, in puti I select the cihicer without extension and it does not work

![o](https://user-images.githubusercontent.com/69087258/113911816-b4fbd600-97da-11eb-8545-ac030c8b7e94.jpg)

**Comment by Ernst79** [comment]
Are you sure you put the right file on the stick, and rebooted the HA machine. 
Are you also sure you have selected the private key in putty when making a connection. 

I see the message shows something about OpenSSH, that seems to be your old private key. 

And did you use the "legacy" rsa to create your key.

**Comment by xekil** [comment]
two files were generated **key** and **key.pub**
I copied the contents of key.pub to the authorized_keys file and the end of the line is LF
in putty, I chose the **key** file

how to use the legacy method ?
In Git I simply entered :

`ssh-keygen -t rsa -b 4096 -C "my_email@example.com"`

I did not have to make a choice, only to enter a file name

**Comment by Ernst79** [comment]
That should be correct. Perhaps the UTF-8 has to be converted to ANSI, or try UTF-8 format, which worked for me. 

Did HA mention something in the logs after a reboot that the new key is loaded?

**Comment by xekil** [comment]
i just tried again, no change whatsoever utf-8 or ANSI
No error in HA logs

**Comment by Ernst79** [comment]
I think we should look into the private key, as it says “unable to use key file...private key”. Can you load your key in puttygen (not generate, but load it).

**Comment by xekil** [comment]
Sorry but I have checked everything, the key is good and it is correctly loaded by puttygen, but I saw on the other post that you had them given by another user, it's great because I also a V2 :)

**Comment by Ernst79** [comment]
1.6.0 has been released with support for V2 scales. So, I think we can close this request. Feel free to reopen if it doesn't work.
