### ISSUE TITLE
CGDK2 LCD sensor Qingping not working

### ISSUE THREAD

**Issue by TFhdKi95ae8L** [custom-components/ble_monitor#283]
The CGDK2 temp/humi is listed as supported.
I have two of these, albeit with an LCD screen, from Qingping.

They are recognized by HA, but no state is reported.
These units use encryption, and I have acquired their token by the token_extractor and put these in the encryption key fields of the integration.

Still no reported states.

Can you implement support for these units?
Otherwise a warning in the devices list for the Qingping CGDK2 LCD type?

If there is any info I can provide, please let me know!

Thanks!

**Comment by wbidus** [comment]
It is not the token (as ex. in humidifier or other xiaomi devices) you need to acquire, but the pairing key. Today i verified CGDK2 on my freshly installed HA and those are reported fine.

**Comment by Ernst79** [comment]
The encryption key can be found with [Xiaomi cloud token extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor) if it is added to MiHome, but as @wbidus said, you need the BLE KEY, not the token. 

Your encryption key should be 32 characters, tokens are generally shorter

**Comment by TFhdKi95ae8L** [comment]
Thanks for your replies.

At the moment I have 7 other devices in the integration on my Raspberry pi4 with HA OS:
5 pieces LYWSD03MMC with custom pvvx firmware
1 piece LYWSD02 standard (E-ink clock temp-humi)
1 piece HHCCJCY01 standard (plant sensor)
Have I reached the maximum connections?

The extractor @Ernst79 mentioned still worked great, and I found the BLE keys. (32 chars, less is not accepted by the integration anyway)
The model is ''cgllc.sensor_ht.dk2", is this the same as yours?

I have reset the devices like @wbidus said and used the newly generated keys. Still the devices show unknown states.

Any advice on how to proceed?

**Comment by Ernst79** [comment]
There is no limit on the number of devices.

I assume the other sensors work fine. Not sure what is wrong then. Let’s find out. First, are there any errors in the logs in HA?

**Comment by TFhdKi95ae8L** [comment]
Yes, several:

cipherpayload: f0488167ac
20:31:28 – Passive BLE monitor (ERROR) - message first occurred at 9:38:42 and shows up 242 times
encrypted_payload: f0488167ac020000ebcd3a54
20:31:28 – Passive BLE monitor (ERROR) - message first occurred at 9:38:42 and shows up 242 times
nonce: eb9711342d586f0603020000
20:31:28 – Passive BLE monitor (ERROR) - message first occurred at 9:38:42 and shows up 242 times
token: ebcd3a54
20:31:28 – Passive BLE monitor (ERROR) - message first occurred at 9:38:42 and shows up 242 times
Decryption failed: MAC check failed
20:31:28 – Passive BLE monitor (ERROR) - message first occurred at 9:38:42 and shows up 242 times

I have pasted the full log in pastebin:
https://pastebin.com/5LWg3t7y

**Comment by Ernst79** [comment]
`Decryption failed: MAC check failed `

this means that the encryption key is wrong.

**Comment by TFhdKi95ae8L** [comment]
![image](https://user-images.githubusercontent.com/76049094/108554064-d9b3f100-72f3-11eb-9b65-d8e3cb1db338.png)

Since I have two, I now gave both the same encryption key to make sure I did not mix them up.

**Comment by Ernst79** [comment]
The one with FFFFFFFF at the end is a device that does not require a key.

**Comment by TFhdKi95ae8L** [comment]
Correct, that's the LYWSD02 clock, which is working.
The second entry is one of both CGDK2 sensors.
As you can see, the key has been entered identically on the left. Now for both.

**Comment by TFhdKi95ae8L** [comment]
Apparently I'm an idiot and i cant copy 32 characters... One is working now!

Thanks for helping, issue closed.
