### ISSUE TITLE
CGH1 and CGPR1

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#284]
**cgllc.magnet.hodor**
“pd_id”: 982 = b’\xD6\x03’: (“CGH1”, False),

events same as mijia window/door sensor 2

“evt”:[{“eid”:4121,“edata”:“01”}] - closed
“evt”:[{“eid”:4121,“edata”:“00”}] - open
“evt”:[{“eid”:4121,“edata”:“02”}] - open for 1m
 4121 is 19 10 in hex

**cgllc.motion.cgpr1**
“pd_id”: 2691 = b’\x83\x0A’: (“CGPR1”, False),

events similar to mijia motion sensor 2, but it supports lux not just dark/bright

“evt”:[{“eid”:15,“edata”:“490300”}] - motion + lux
“evt”:[{“eid”:4119,“edata”:“3c000000”}] - no motion since sent on 1m, 2m, 5m, 10m, 20m, 30m with time
“evt”:[{“eid”:4103,“edata”:“490300”}] - lux sent every ~10m (does not depend on lux change)

15 is 0F 00 in hex
4119 is 17 10 in hex
4103 is 07 10 in hex

they both send events like battery level or rssi. both encrypted. motion can trigger every ~15s, but it needs 10-15s of constant time without motion to trigger next motion event. i have some problem with it. all automations even local have ~3s lag compared to motion sensor 2 from lumi. hope it’s firmware thing and will be fixed.

**Comment by Ernst79** [comment]
@rezmus. Small question. 
- Do you know whether the window/door contact sensor **CGH1** (right picture) sends light state, like the **Mijia window/door sensor 2**?
- In the picture below of the  window/door contact sensor **CGH1** (right picture), it looks like I see a button. Does it send a message? 

![image](https://user-images.githubusercontent.com/24375847/108736957-664bf280-7532-11eb-98b7-c5303bb5f348.png)

- Do you know whether the **CGPR1** motion and ambient light sensor (left picture above) has a button, like the **Mijia motion sensor 2** (picture below).  

![image](https://user-images.githubusercontent.com/24375847/108737158-9b584500-7532-11eb-8c06-70d1fbc4aae5.png)

**Comment by rezmus** [comment]
window/door sensor does not have light sensor. button does not send msg on press, it's possible it sends some event when you reset (press for long time), but i doubt you want to handle reset event. motion sensor does have reset button inside the case, no other buttons. you can set detection interval between 5-60s, maybe less.

**Comment by Ernst79** [comment]
Thanks.

**Comment by Ernst79** [comment]
1.1.2-beta has been released with support for both sensors.

**Comment by Ernst79** [comment]
Final release 1.1.2 is released with support for these sensors. If someone has this sensor, please report if it is working OK, by posting a message.

**Comment by Ernst79** [comment]
Do you have a SSD drive connected to you HA machine? This is often causing problems with Bluetooth

**Comment by wieluk** [comment]
yes I do. I just read it in the Faq ... anything I can do? I need this ssd so removing is no option. Can I shield it somehow?

**Comment by Ernst79** [comment]
I have an external SSD and I just use a long cable to place the SSD 30 cm away from the raspberry with an extension cable. This solved it for me.

**Comment by wieluk** [comment]
Yea it is 100% the SSD sorry about the confussion. I installed homeassisant on my second pi and it works without any problems. I will just use remote_homeassistant to forward my door sensors. It is easier for me. Thanks anyways
