### ISSUE TITLE
LYWSD03MMC Custom Firmware Pin-Code

### ISSUE THREAD

**Issue by tagru** [custom-components/ble_monitor#286]
Hello,

the custom firmware for device LYWSD03MMC supports enabling a PIN Code. This means, in order to connect to the device, a PIN Code is needed for Bluetooth pairing. Is it possible to use this behaviour in ble_monitor as well?

I set the PIN on one device for test purposes but than no new values were sent to Home Assitant anymore. After removing the PIN everything worked again.

Is this already possible or can it be made possible with the custom component ble_monitor?

**Comment by Ernst79** [comment]
At the moment, this is not possible. I will look into this, good suggestion.

**Comment by Ernst79** [comment]
I tried setting the pincode, but it seems that it keep on working fine. 

```
8:25:56 PM: PinCode: '123456'
8:25:56 PM: Send pincode ok
8:26:07 PM: New custom config: [1, 0, 0, 0, 40, 4, 191, 124, 49, 56, 60]
8:26:07 PM: Settings 55010000002804BF7C31383C was send successful
8:26:08 PM: Hardware Version: LYWSD03MMC, Software Version: 2.3
8:26:08 PM: Custom config: [1, 0, 0, 0, 40, 4, 191, 124, 49, 56, 60]
8:26:56 PM: Disconnected.
```

Are you sure it stops working in your case. I have flashed 2.3p.

**Comment by tagru** [comment]
Hi,

ok I tested again. Set the Pin and it's still sending the values like expected. Even after a restart of Home Assistant.

Looks like my first try did something else wrong, because there it was not retrieving values for over an hour. That's why I opendend the issue.

So PIN usage is fine after all :)

**Comment by Ernst79** [comment]
yep, I guess so. Closing the issue for now, feel free to reopen if you find another issue.
