### ISSUE TITLE
Invalid data: MAC is not present in whitelist

### ISSUE THREAD

**Issue by rafkan20** [custom-components/ble_monitor#293]
After updating to version 1.1.2 an error occurred:

Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:673
Integration: Passive BLE monitor (documentation)
First occurred: 10:10:48 (149 occurrences)
Last logged: 10:13:11

Invalid data: MAC is not present in whitelist

**Comment by Ernst79** [comment]
Thanks, you can ignore this message. In a next update, I will move this message to a debug message in stead of an error.

Just to confirm, I assume you have discovery: false in your configuration for ble_monitor

**Comment by rafkan20** [comment]
Yes, I have five devices plugged in, each set up "discovery: false"
[https://images90.fotosik.pl/477/4c2cb61cb6c9252a.jpg](url)

**Comment by Ernst79** [comment]
Yes, we changed something to the error handling in the last version. Its our mistake. 

But your sensors should work fine, I assume. It's just an error message that isn't a real error, just a message telling that it catched an message from a xiaomi device, that isn't in the list you have in your config. Possible a device from a neigbour.

**Comment by rafkan20** [comment]
I understand.
The sensors I have connected via this integration are working fine.
