### ISSUE TITLE
Not able to modify options or add the integration in HA 2021.3

### ISSUE THREAD

**Issue by mpikosdimitris** [custom-components/ble_monitor#299]
Hello and thanks for you excellent work.
I have a problem with the selection of HCI interface. On Passive BLE Monitor options menu, i can't select any of the interfaces 0,1,2 and always showing the nymbers 0,1,2 without any change of my options. I've tried to reinstall the addon form HACS, to clear the cash of my browser, tried different browser, tried from the HA app in my mobile device. Nothing. What can i do ? Also, is there a place that i can find my discovered devices (something like the YAML file) to manually add/change the bind key or something else ? 
![Capture](https://user-images.githubusercontent.com/22566894/110159344-40a4d000-7df3-11eb-96b8-349201c752d1.PNG)
Thanks
Dimitris

**Comment by Ernst79** [comment]
To start with your last question, you can see your discovered devices by clicking on Devices at the bottom (see your printscreen, last option below Restore State. After clicking Submit, it will open a new window with options for that specific device. 

Regarding your first issue, let me check on my end, one moment please.

**Comment by mpikosdimitris** [comment]
I select interface 0 then i select the device, pessing 'Submit' and i get the same error. If you see, the interfaces 0, 1, 2 seems like are always selected, but yesterday while i was changing my selections the interface that i select was only showing in the HCI Interface.
(Sorry for my english)

**Comment by Ernst79** [comment]
Yes, I see the same behavior. I will investigate it.

**Comment by mpikosdimitris** [comment]
I'm in 2021.3.0 with the same behavior. Can i find somewhere the data of my discovered devices to change something ? In my case, i want to add the encryption key in one of my devices.

**Comment by Ernst79** [comment]
I explained above, you can change it here

![image](https://user-images.githubusercontent.com/24375847/110169772-78167b00-7df9-11eb-9c3c-04af14e8769b.png). 

A pull down menu will open, click on submit and a new windows will open. 

But I think it won't work in your case, because of the errors with the form. 

Still looking into it, I have to find out what changed in HA 2021.3.x

**Comment by mpikosdimitris** [comment]
Yes i know, i configured my other sensors with that way. Just asking if there is another way to configure it.
Thanks again for your support.

**Comment by Ernst79** [comment]
I'm afraid the only way is in YAML at the moment. Or downgrading to 2021.2.3. 

I need some time to find out what is changed. I don't see a breaking change that could have caused this.

**Comment by Ernst79** [comment]
OK, I narrowed it down to the `devices` option, which is causing the issue. If I remove the `devices` option from the config flow (the menu in the screenshot, it all works fine.

**Comment by SPEC1AL1ST** [comment]
Same error

**Comment by ilkanaev** [comment]
i have the same isue. 
at the first stage the only way to add new device is by selecting all the HCS interfaces.
once added. no any option to add more. update or delete already added.
i tryed to get back to the older version - did not help.

**Comment by Ernst79** [comment]
Workaround to change options is selecting HCI 0 and 1, next select only 0 (assuming you use hci0), change the option you want to change and click submit.

I’m still looking into it, unfortunately I don’t have a clue what is wrong. It looks like an issue with the config validation of either the hci field and/or the devices field. @Magalex2x14 @koying could you help me solving this issue, I’m starting to feel a bit lost.

A new installation of the integration will fail at the moment. A workaround is changing the following in config_flow.py. This will at least open the menu. Next, use the workaround with the hci option as above (select0 and 1, and next select 0 and submit).

```
       vol.Optional(CONF_DEVICES, default=[]): vol.All(
            cv.ensure_list, [DEVICE_SCHEMA]
        ),
```

to

 ```
       vol.Optional(CONF_DEVICES, default=[]): vol.All(
            cv.ensure_list, cv.string
        ),
```

**Comment by TwinsenLiang** [comment]
> I'm in 2021.3.0 with the same behavior. Can i find somewhere the data of my discovered devices to change something ? In my case, i want to add the encryption key in one of my devices.

same to me。

**Comment by Ernst79** [comment]
I finally found the error. In the end, it was an easy fix, when you know what to look for :-). The issue was in the HCI field, after changing the config validation from a dictionary to a list, it all starts to work again. 

Please update to 1.3.0-beta to check. Please report back if it works for you, I would like to release the final a.s.a.p. after confirmation that it works.

**Comment by TwinsenLiang** [comment]
> I finally found the error. In the end, it was an easy fix, when you know what to look for :-). The issue was in the HCI field, after changing the "multi_select config validation" from a dictionary to a list, it all starts to work again.
> 
> Please update to 1.3.0-beta to check. Please report back if it works for you, I would like to release the final a.s.a.p. after confirmation that it works.
> 
> A beta can be installed in HACS by clicking the three dots on the BLE monitor integration tile, reinstall, select the "show beta versions" button and install. Make sure you restart Home Assistant after the update.

yeah，fix it。thank u

**Comment by Ernst79** [comment]
Thx. Final version 1.3.0 is released.

**Comment by ilkanaev** [comment]
works fine for me.
thank you very much for fix !

**Comment by mpikosdimitris** [comment]
> Thx. Final version 1.3.0 is released.

Just upgraded it ! Thank you very much !
