### ISSUE TITLE
CGH1 reinstall fails

### ISSUE THREAD

**Issue by rjh169** [custom-components/ble_monitor#303]
I am using HA 2021.3.3 and Passive BLE monitor 1.3.0 on a Pi 4b

I successfully added 6 CGH1’s and could see them opening and closing.
Subsequently I obtained new bindkeys for 2 of them using the Mijia modified app.
However I cannot get either of them to reinstall correctly in HA.

I deleted the device and entity as per the github details. Everything looks good. The integration
device and entity count decreases by 1. I can no longer see any evidence of its presence.

I place the battery back in the device and it is seen by HA and the integration
device and entity count increases by 1. So far so good. The first indication of trouble ahead is that the entity is unavailable/disabled. I enable it. All looks as it should but it never responds to the sensor. I believe that the device has never really been deleted as its “history” always remains and possibly? the original bindkey.
ie:  ble opening 582D34600BE1
   Became unavailable 
   12.00.41   4 hours ago
 Became unavailable 
   11.51.13   4 hours ago
Became unavailable 
   11.26.46   4 hours ago
etc
I have spent several days on this and tried everything I can think of. I have used both Remove entity
and Delete,  but whatever I do the “history” remains and the sensor will not work. They both work with the Mijia app.

**Comment by Ernst79** [comment]
Normally, there shouldn't be a need to delete the sensor, just applying the new `encryption_key` to the configuration would be good enough. You could try the following

1. If the sensor is added to MiHome, please double check you have the correct key by checking it with [xiaomi cloud token extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor). 
2. If that doesn't work, you might want to try to delete the integration, restart HA and reinstall it again.

**Comment by rjh169** [comment]
My fault. I somehow got my bindkeys mixed up.
All 6 CGH1's now working correctly.
