### ISSUE TITLE
CGG1-M

### ISSUE THREAD

**Issue by pvvx** [custom-components/ble_monitor#308]
> README.md: (please confirm if it works for CGG1 by creating an issue).

There are more than 3 variants of the CGG1 on sale.

**CGG1-M**
---
https://www.qingping.co/temp-rh-monitor/overview
Alternative firmware is currently only possible on CGG1-"M" - Mi-Home versions. Clarifications can be found here:
https://pvvx.github.io/CGG1
This is a newer CGG1-M based on the Telink platform. Has a price of 1.5 - 2 times lower than that of older versions of CGG1.
Alternative firmware for CGG1-M has a single interface with LYWSD03MMC and MHO-C401. There is no difference in BLE.

**CGG1 old** 
---
[CGG1 old - 2018.11. BLE Name 'Goose' ](https://github.com/pvvx/ATC_MiThermometer/issues/41#issuecomment-802254030) 
https://fccid.io/2AQ3F-CGG1/Internal-Photos/Internal-Photos-3990168
https://github.com/kelchm/cgg1-thermometer-firmware
Original Advertising:
| len | id | uuid | id | mac | id | temp/10 | hum/10| id | bat level |
| :--: | :--:| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| 14 | 16 | F9 FF | 08 01 | AE 16 10 34 2D 58 | 01 04 | 14 01 | 53 01 | 02 01 | 58 |

MAC: 58:2d:34:10:16:ae, temp: 27.6 C, hum: 33,9 %, bat level: 88 % 

**CGG1-H**
---
https://www.qingping.co/temp-rh-monitor/overview  
CGG1 Apple HomeKit versions
https://fccid.io/2AQ3F-CGG1H/Internal-Photos/Internal-Photos-4723738

---

> FAQ: If you want to use MiHome and our custom component at the same time, follow the instructions here ...

The description has been removed. Violates the user agreement for Mi-Home.
All used functions: recovering keys and transferring them to advertisements in encrypted form using bindkey, etc. remained ...

**Comment by Ernst79** [comment]
Thanks for the info, much appreciated. I will add part of it to the readme and/or FAQ.

**Comment by Ernst79** [comment]
Thanks again, readme and faq are updated.
