### ISSUE TITLE
Bluetooth BLE connection support

### ISSUE THREAD

**Issue by pilot1981** [custom-components/ble_monitor#309]
Hi,
I already know your component do only passive monitoring of Xiaomi object using Bluetooth, but I need to start and stop Xiaomi Mosquito Repellent smart.

So I decided to develop software to do it!

I can use part of you code? You can explain which part of your cose I have to use?

you would integrate my part in your code or you prefer to do a fork?

regards

**Comment by Ernst79** [comment]
Our component is making a HCIDUMP, which collects the data and filters out the useful parts. For the HCIDUMP, we use a modified aioblescan, which is normally available as pypi package. We copied it to our code (see aioblescan_ext.py), as we made some small changes, which were not added to the original pypi package. The bluetooth communication is done in that file. 

All the processing of the data is done in `__init__.py`, especially in the last part, where the messages are read and the data is filtered and converted to something useful. The useful data is than send to the sensor or binary sensor. 

Note that our component is currently designed to do things passively. You will have to write the connection part yourself

I have to talk to @Magalex2x14 how he things about adding code that uses an active connection. I'm not against it, but my time is limited to maintain the code.

You can always make a start with a fork, we can decide later.

**Comment by pilot1981** [comment]
@Ernst79 @Magalex2x14 you evaluated my proposal?

**Comment by Ernst79** [comment]
I'm not against your proposal, but it doesn't seem easy to implement. You will need to write something that sends BLE advertisements, while our component is only listening at the moment. You will also need to implement a switch, which isn't available in the code right now. Looks serious work to me.

**Comment by Magalex2x14** [comment]
@pilot1981 sorry for the long silence - was captured by offline life entirely.

Here are my thoughts. I see two ways:

1. establish a connection with the device immediately when it needed and immediately restart scanning after connection termination - the delay in receiving data from other devices will be equal to the time spent on the active connection
2. use different bt adapters for scanning and connecting - no delays in receiving data at all

If your desire has not died down yet, we can discuss this task.

**Comment by pilot1981** [comment]
Thanks for reply: no problem!

I think have second Bluetooth adapter could be a good solution!

**Comment by Ernst79** [comment]
I’m closing this issue here, due to the move to core HA integrations. This issue won’t be fixed in BLE monitor, please make a request on the home assistant github (Xiaomi BLE integration). This integration will add support to polling battery info from a MiFlora sensor in next month release (2022.9), so the devs might be able to add this as well.
