### ISSUE TITLE
Multiple Bluetooth Dongles not working

### ISSUE THREAD

**Issue by borpin** [custom-components/ble_monitor#310]
This is a marker for this issue as I cannot fully debug as the USB import to allow access to the OS is not working at present.

I have a 'Blue' with HA OS - fully up to date.

The component works when a single external dongle is configured but not when more than one is configured. Tried multiple configurations (one issue is I do not know which HCI interface the dongles are on).

I will post more detailed debugging when I have it.

**Comment by Ernst79** [comment]
You can get "lower level access" to HA OS with this procedure

https://developers.home-assistant.io/docs/operating-system/debugging/

This will allow you to check the hci port. 

It's a bit more complicated, but doable :-)

**Comment by borpin** [comment]
Yes there is a bug though in the latest release preventing this. https://github.com/home-assistant/supervisor/issues/2748

**Comment by Ernst79** [comment]
Please try updating to 1.5.0-beta. This version will allow you to specify the MAC address in stead of the HCI number. The MAC addresses will be presented in the logs during startup of HA (when using YAML for configuration). When configuring in the User Interface. it will present a drop down menu in the options with available Bluetooth interfaces (Mac Addresses) on your system.

**Comment by Ernst79** [comment]
Any update on this issue, or can it be closed

**Comment by Ernst79** [comment]
Closing this issue. Feel free to reopen if the issue still exists.
