### ISSUE TITLE
Xiaomi Smart Water Leak Sensor SJWS01LM

### ISSUE THREAD

**Issue by DmitriusDan** [custom-components/ble_monitor#317]
For some unknown reason, the sensor becomes unavailable after restarting the HA. All other sensors operate normally (LYWSD03MMC, CGD1) and come online in 30 seconds after restart. But this one may not be available for about 1-2 days. It works good in the Mi Home app. I have 5 Mi smart plug (BLE gateway version) and two of them are close to the water leak sensor

**Comment by Ernst79** [comment]
Did you try to place it closer to HA, to verify that you do not have a range issue? You mention that it does become available after 1-2 days, so I suspect an issue with the range.

**Comment by DmitriusDan** [comment]
Ok, I will try. Does this mean that the BLE HA integration does not use BLE gateways? This is a very good integration and I only have an issue with 1 of 11 sensors

**Comment by Ernst79** [comment]
No, BLE monitor uses the Bluetooth dongle/radio/receiver of the Home Assistant hardware (e.g. Raspberry Pi). So, the sensor has to be within the range of your Home Assistant machine. It does NOT use a gateway, although sensors often do need to be added to a gateway to start broadcasting data.  

If it isn't within range, you will have to look for alternatives. 
- Improve the range of HA machine (check the faq for options)
- Use a second remote HA machine at a second location
- Use ESP home for sensors that are too far away (https://esphome.io/components/sensor/xiaomi_ble.html)
- Use the gateway 3 integration (https://github.com/AlexxIT/XiaomiGateway3)

Unfortunately, the last two options do not seem to support your sensor. It should be easy for them to add support, I suppose, but I didn't find your sensor in the list of supported sensors.

**Comment by DmitriusDan** [comment]
I placed it closer to rasp pi and it working good now. Thank you.
