### ISSUE TITLE
Xiaomi door sensor 2 MCCGQ02HL data status unknown.

### ISSUE THREAD

**Issue by stylishkrio** [custom-components/ble_monitor#320]
The data comes very badly. He writes very often it is unknown. Bindkey registered.
![Xiaomi door sensor 2 MCCGQ02HL data status unknown](https://user-images.githubusercontent.com/77132140/114005273-0f8f4380-9868-11eb-840d-d04a371eea99.PNG)

**Comment by Ernst79** [comment]
Is the sensor within the range of your Bluetooth receiver. Can you check the RSSI value (click on one of the sensors, it's in the attributes (if it is not 'unknown' of course). 
Try to place the sensor close to your HA machine, to see if it makes a difference. 

Are there any errors in the log?

**Comment by stylishkrio** [comment]
> Is the sensor within the range of your Bluetooth receiver. Can you check the RSSI value (click on one of the sensors, it's in the attributes (if it is not 'unknown' of course).
> Try to place the sensor close to your HA machine, to see if it makes a difference.
> 
> Are there any errors in the log?

The RSSI value is good. There are no errors in the log.

It helps to turn on, off in the "Dim / bright light detection" item in the settings of the sensor itself in mi home. But if I restart the home assistant, then the data disappears again and does not come. Even after 24 hours of waiting.

**Comment by Ernst79** [comment]
Hmmm, I have no clue. Did you double check the encryption key?  

Do you have access to SSH? If so, try to make a hcidump for some time and check if you receive messages from the sensor (of upload the file here, and I'll check it). Note. hcidump won't work on Home Assistant OS, at least not without some additional steps. 

```
sudo hcidump --raw hci > dump.txt
```

**Comment by stylishkrio** [comment]
> Hmmm, I have no clue. Did you double check the encryption key?
> 
> Do you have access to SSH? If so, try to make a hcidump for some time and check if you receive messages from the sensor (or upload the file here, and I'll check it). Note. hcidump won't work on Home Assistant OS, at least not without some additional steps.
> 
> ```
> sudo hcidump --raw hci > dump.txt
> ```

The encryption key has been checked many times. He's correct. SSH is there. But didn't work with hcidump.

**Comment by stylishkrio** [comment]
> Hmmm, I have no clue. Did you double check the encryption key?
> 
> Do you have access to SSH? If so, try to make a hcidump for some time and check if you receive messages from the sensor (or upload the file here, and I'll check it). Note. hcidump won't work on Home Assistant OS, at least not without some additional steps.
> 
> ```
> sudo hcidump --raw hci > dump.txt
> ```
Xiaomi Gateway 3 integration AlexxIT. But also no problem. 
![Xiaomi Gateway 3 integration AlexxIT  But also no problem](https://user-images.githubusercontent.com/77132140/114067447-80088580-98a5-11eb-9561-77212a3e5be7.PNG)

**Comment by stylishkrio** [comment]
> Hmmm, I have no clue. Did you double check the encryption key?
> 
> Do you have access to SSH? If so, try to make a hcidump for some time and check if you receive messages from the sensor (or upload the file here, and I'll check it). Note. hcidump won't work on Home Assistant OS, at least not without some additional steps.
> 
> ```
> sudo hcidump --raw hci > dump.txt
> ```
The data is coming in. But not all.
![The data is coming in  But not all](https://user-images.githubusercontent.com/77132140/114068680-d88c5280-98a6-11eb-9d17-8d4ac3bb2732.PNG)

**Comment by Ernst79** [comment]
Can you enable debug logging. Add the following to configuration.yaml and restart. Post the logs after a while.

```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: debug
```

**Comment by Ernst79** [comment]
I checked the post when @Magalex2x14 created support for this sensor, it seems that it only sends date on an event, like opening the door. 
- Does it update when you open/ close the door?
- Does it update when you turn on/off the light?

see https://github.com/custom-components/ble_monitor/issues/115#issuecomment-730614072

**Comment by stylishkrio** [comment]
> I checked the post when @Magalex2x14 created support for this sensor, it seems that it only sends data on an event, like opening the door.
> 
> * Does it update when you open/ close the door?
> * Does it update when you turn on/off the light?
> 
> see [#115 (comment)](https://github.com/custom-components/ble_monitor/issues/115#issuecomment-730614072)
Updated when the door is closed / opened. But do not update when the light is turned on / off.

**Comment by stylishkrio** [comment]
> Can you enable debug logging. Add the following to configuration.yaml and restart. Post the logs after a while.
> 
> ```
> logger:
>   default: warn
>   logs:
>     custom_components.ble_monitor: debug
> ```
> 
> note that battery is only updated once per 24h

[logs.log](https://github.com/custom-components/ble_monitor/files/6285615/logs.log)

**Comment by Ernst79** [comment]
I don't see anything strange in the logs. 

One tip is to use the option `restore_state: True` to keep the state during a restart and/or reloading of the integration. This will at least prevent it from being `unknown`, but will restore the state after a restart to the state before the restart. Can be set at integration level, but also at device level. 

Regarding the light sensor, I have no idea why it isn't updating.

**Comment by stylishkrio** [comment]
> I don't see anything strange in the logs.
> 
> One tip is to use the option `restore_state: True` to keep the state during a restart and/or reloading of the integration. This will at least prevent it from being `unknown`, but will restore the state after a restart to the state before the restart. Can be set at integration level, but also at device level.
> 
> Regarding the light sensor, I have no idea why it isn't updating.
Data on version 1.6.0 is updated correctly.

**Comment by stylishkrio** [comment]
> I don't see anything strange in the logs.
> 
> One tip is to use the option `restore_state: True` to keep the state during a restart and/or reloading of the integration. This will at least prevent it from being `unknown`, but will restore the state after a restart to the state before the restart. Can be set at integration level, but also at device level.
> 
> Regarding the light sensor, I have no idea why it isn't updating.

Data on version 1.6.0 is updated correctly.

**Comment by Ernst79** [comment]
Ok, thanks for reporting back. I suppose we can close the issue then. Feel free to reopen if you still have issues.
