### ISSUE TITLE
problem of  Bluetooth interface found in componenet check configuration

### ISSUE THREAD

**Issue by pilot1981** [custom-components/ble_monitor#321]
Hi,
I'm using this config:

`ble_monitor:
  discovery: False
  batt_entities: True
  bt_interface: 'B8:27:EB:A0:08:89'
  devices:
    - mac: '74:a3:4a:c0:16:78'
      name: 'Mosquito'`

but when I use check home assistant configuration component I receive this error:

[11:50:22] ERROR: Found an error in the log output of the check!
[11:50:22] ERROR: See the output below for more details.
ERROR:custom_components.ble_monitor:No Bluetooth interface found. Make sure Bluetooth is installed on your system
[11:50:22] INFO: The full output has been written to /share/check_config.txt

what I have to change in configuration.yaml?

**Comment by Ernst79** [comment]
It is saying that it can't find the Bluetooth interface with MAC address 'B8:27:EB:A0:08:89'

Is BLE monitor working right now? 
What kind of installation do you have? Could you post the result of `hcitool dev` with SSH.

**Comment by pilot1981** [comment]
MAC address 'B8:27:EB:A0:08:89' result from #bluetoothctl command line output...

I also tried this config:



`ble_monitor: discovery: False batt_entities: True devices: - mac: '74:a3:4a:c0:16:78' name: 'Mosquito'`

but I always obtain same log error from component check config:


[12:50:22] ERROR: Found an error in the log output of the check!
[12:50:22] ERROR: See the output below for more details.
ERROR:custom_components.ble_monitor:No Bluetooth interface found. Make sure Bluetooth is installed on your system
[12:50:22] INFO: The full output has been written to /share/check_config.txt

but BLE monitor work fine with both configuration...

can I upgrade lo lastest HASSIO version?

**Comment by Ernst79** [comment]
Yes, you can update to the latest HassIo version.

The error is due to the latest update of BLE monitor. BLE monitor runs `hciconfig` to get the available MAC addresses on your system. You get the error if it doesn't find any Bluetooth MAC address. 

What I don't understand is that BLE monitor does work, but it doesn't find the MAC address. Can you do a restart of Home Assistant, and right after the restart check the logs. There should be a warning in the HA logs with a list of available MAC address(es), 

Do you only get this error, when you do the configuration check, or also after a restart?

**Comment by pilot1981** [comment]
I get this error only when I start component check config...

BLE_monitor works fine.

no any other error in HA logs, also after restart HA.

so if I get MAC address from #bluetoothctl cmmand, it isn't correct? I have to get it using @hciconfig in command line?

**Comment by Ernst79** [comment]
the `hciconfig` command won't work on Home Assistant OS, at least not with the SSH add-on. But that is not needed. 

I assume you used configuration of BLE monitor in YAML, is that correct? 

If so, you should get a message in the log that says. 

`Available Bluetooth interfaces for BLE monitor:`

Do you have this message in the log (it's a warning message). if you have this message, can you tell me what is says.

**Comment by pilot1981** [comment]
I'm speaking about official component "check home assistant configuration" here:
![image](https://user-images.githubusercontent.com/46350465/114037018-db744c80-9880-11eb-8910-9a34c0200aa9.png)

**Comment by pilot1981** [comment]
I found it:

![DDAD7AC0-46F0-443E-80FB-C028C2507E41](https://user-images.githubusercontent.com/46350465/114099583-53636680-98c3-11eb-8971-8c0b3ad8ac9e.png)
![6F01827F-EF5F-4AC8-BBA0-35F760160E8A](https://user-images.githubusercontent.com/46350465/114099589-552d2a00-98c3-11eb-8841-5a92f3ec6c2a.png)

**Comment by Ernst79** [comment]
Sorry, I don't understand? What did you find? 

I tried it on my system, and it didn't find an error. (Supervised installation on raspberry OS).

**Comment by pilot1981** [comment]
I found info into HA GUI, but not bluetooth interface...

on HASSIO, chere you find message in the log that says: "Available Bluetooth interfaces for BLE monitor:"
in which file?

**Comment by Ernst79** [comment]
You can find it under Configuration --> Logs

![image](https://user-images.githubusercontent.com/24375847/114158627-31023500-9925-11eb-9a79-a64971f12d83.png)

**Comment by pilot1981** [comment]
I don't found it...

I suppose first I have to enable logs in configuration.yaml?!

custom_components.ble_monitor: debug

**Comment by pilot1981** [comment]
ok, done. I report here my logs:

Logger: custom_components.ble_monitorSource: custom_components/ble_monitor/__init__.py:261Integration: Passive BLE monitor (documentation)First occurred: 12:08:32 (1 occurrences)Last logged: 12:08:32
Available Bluetooth interfaces for BLE monitor: ['B8:27:EB:A0:08:89']


so, this could confirm my good setup in configuration.yaml:

`ble_monitor: discovery: False batt_entities: True bt_interface: 'B8:27:EB:A0:08:89' devices: - mac: '74:a3:4a:c0:16:78' name: 'Mosquito'`

so, I think this problem could be related to HA addon "check home assistant configuration"?

**Comment by Ernst79** [comment]
Yes, it seems so. Looks like everything is fine, except the check home assistant configuration. As I said, it didn’t cause an error on my system (HA supervised). I will do a check with Home Assistant OS this weekend, have to find an SD card somewhere first. Will get back to you a.s.a.p.

**Comment by pilot1981** [comment]
I have raspberry 3 pi b+, so only one bluetooth interface...

To replicate issue you need to use addon check config 3.6.0 and try to go from HASSIO 2021.3.x to 2021.4.1


regards

**Comment by Ernst79** [comment]
I tried again, now with YAML config in stead of configuration in the User Interface (still Supervised installation). I now do get the error. 

![image](https://user-images.githubusercontent.com/24375847/114177204-69613d80-993c-11eb-97ac-1aec0657c920.png)

I will look into it

**Comment by pilot1981** [comment]
yes, this is the same error for me!

**Comment by Ernst79** [comment]
This issue is fixed in 1.7.2-beta.

**Comment by Ernst79** [comment]
1.7.2 has been released, which should fix this issue.

**Comment by Ernst79** [comment]
Ill look into it
