### ISSUE TITLE
Restore state isn't working

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#326]
Users reported in #292 that the `restore_state` isn't working as expected, 

@serb1906 

> "I have some problem with 1.6.1beta - with cheked "Restore state" in Intergration value not restore after HA restart."

@Kaibob2 

> "I agree with serb1906 that when i add restore_state: True in my YAML config the scale value does not restore and the entity remains unavailable until i touch the scale."

@serb1906 uses UI config, @Kaibob2 YAML config. 

I noticed similar behavior for one of my binary sensors, but didn't notice it on measuring sensors.

I'm currently thinking that `ble_monitor` is restoring the state when the first message arrived for a specific device, so restoring state isn't done right after a restart. Till now, this was not noticed for most sensors, as most sensors send data all the time. But the scale sensors only send data when they are active, so they won't be restored. 

Solution is to restore the state right after the restart. 

@Kaibob2, @serb1906 Question, do you have other BLE sensors? If yes, which ones (type) and are these restoring their state after a restart?

**Comment by Kaibob2** [comment]
> @Kaibob2, @serb1906 Question, do you have other BLE sensors? If yes, which ones (type) and are these restoring their state after a restart?

I have four LYWSD03MMC with ATC firmware (configured to send a message every minute) and the value is there right after a restart. The scale value is not restored and the sensor is unavailable.

Before restart:
![SharedScreenshot1](https://user-images.githubusercontent.com/20832276/114739703-6655bb00-9d49-11eb-808f-949a306f9023.jpg)

After restart:
![SharedScreenshot2](https://user-images.githubusercontent.com/20832276/114739725-6d7cc900-9d49-11eb-81f6-3d0b6b850979.jpg)

**Comment by Kaibob2** [comment]
The MJYD02YL sensors restore as well. Forgot to mention in my last post.

**Comment by serb1906** [comment]
> @Kaibob2, @serb1906 Question, do you have other BLE sensors? If yes, which ones (type) and are these restoring their state after a restart?

I have other one LYWSDCGQ and it sensor in HA also not restore after HA restart (i'm removed a battery before restart).

**Comment by Ernst79** [comment]
Thanks, I figured out that it is only restoring the state after HA receives the first message of each device. The first message is the trigger to add a device to HA, and somewhere in this process there is the restore state process, which restores the state of all sensors of that specific device. 

So, at this moment it works as follows.
- Without restore state you have to wait till the end of the `period` to become available
- With restore state it, it becomes available after the fist BLE message

This is an issue, especially for the scales, as they don’t send data when not activated.

I will look into this, but will require some time to figure out.

**Comment by think-nice-things** [comment]
Hi,
I can just confirm that restore_state doesn't work for the Mi Scale 2 :-(

**Comment by Ernst79** [comment]
Yes, I know. Working on that now. Almost finished, but it required some rewriting of the code.

**Comment by Kaibob2** [comment]
There is a problem which i think might be related to the restore state issue but i'm not sure how to verify. 
I have a nodered flow which creates three entities for three different weight ranges. This works fine as long as i don't restart HA during a phase while the scale doesn't send any messages. If so, the scale entity stays unavailable and if i step on it it becoes available and the entity get's its last known value which triggers the nodered flow and leads to a "wrong" measurement.
Example:

- I (80kg) step on the scale in the evening.
- My weight gets routed to my entity and everything is fine
- My wife (55kg) steps on the scale afterwards
- Her weight gets assigned to her entity and everything is fine
- The night passes. In the morning i restart HA
- I step on the scale
- The weight of my wife from yesterday get's assigned to her entity as soon as i step on the scale
- My weight gets assigned to my entity right afterwards

I hope this is understandable :)

**Comment by Ernst79** [comment]
I've prepared a 1.7.1-beta, which should fix this issue. Please give it a try and report back if it works. 

To explain what was wrong, in the old situation, it restored the state upon the first BLE message. For scales, this doesn't work, as it only sends data when stepped on. So I changed it to restore upon restart, but your sensors' MAC address has to be configured in the options. When you use the UI configuration, this is most of the times already taken care of (otherwise, open the options and submit). If you use YAML, make sure that you configure your MAC address of the sensor, otherwise it will still use the old behavior (restoring upon the first BLE message).

**Comment by Ernst79** [comment]
@Kaibob2, @serb1906 Did you had a chance to test it with 1.7.2-beta?

**Comment by Kaibob2** [comment]
Sorry, I only had little time since I updated to 1.7.2-beta. Until now everything is working as expected. All sensors restore on startup and the issue described under https://github.com/custom-components/ble_monitor/issues/326#issuecomment-825115167 is no more existent. I'm pretty happy with it.

**Comment by Ernst79** [comment]
Thanks, 1.7.2 (final) has been released.
