### ISSUE TITLE
Power state of XIAOMI MOSQUITO SMART REPELLENT

### ISSUE THREAD

**Issue by pilot1981** [custom-components/ble_monitor#329]
Hi,
It’s possibile to add also power state on/off for XIAOMI MOSQUITO SMART REPELLENT?

regards

**Comment by Ernst79** [comment]
What do you mean with power state? 

At the moment, WX08ZM has support for these three sensors
- battery
- switch (on/off state)
- consumable sensor (in percentage)

In ESPHome, there is support for  "tablet resource level, on/off state and battery level', which are the same three sensors. 

Isn't power state not the same as the current switch sensor?

**Comment by pilot1981** [comment]
Switch state seems to don’t works...

**Comment by Ernst79** [comment]
Can you check which entities are part of the device in HA? Settings - Devices - select your repellent device. Normally it should be added automatically. 

If the switch binary sensor is present, what it the state of the sensor?

**Comment by pilot1981** [comment]
sensor.ble_switch_mosquito

or

binary_sensor.ble_switch_mosquito

**Comment by Ernst79** [comment]
A switch is always a Binary sensor, so `binary_sensor.ble_switch_mosquito`

**Comment by Ernst79** [comment]
Can you explain what isn't working exactly. Do you see the binary sensor? Is it unavailable/unknown?

**Comment by pilot1981** [comment]
Binary sensor is working fine


What I have to do with sensor?

**Comment by Ernst79** [comment]
`sensor.ble_switch_mosquito` is a left over from an early version of BLE monitor (in the beginning, we didn't had binary sensors, only sensors). You can delete it safely.

**Comment by pilot1981** [comment]
ok, thanks for explantation|
