### ISSUE TITLE
Request to add new BLE Device: Kegtron

### ISSUE THREAD

**Issue by millercentral** [custom-components/ble_monitor#331]
This is a request to add support for a non-Xiaomi sensor to Passive BLE Scanner. The device is a flow monitor for Kegerators called "Kegtron". 

Website for the device: [https://kegtron.com/gen1/](https://kegtron.com/gen1)

The BLE Advertisement Protocol for the device is documented here; [BLE Message Format](https://kegtron.com/docs/Gen1BLEMessageFormat.pdf)

Note, there are two versions of this device. One has 1 flow sensor, and one has 2 flow sensors. The 2 sensor version alternate BLE advertisements for each sensor over time (this is the version I have).

I'm running Home Assistant OS (2021.4.5 / 5.13) on a RPI4. hcidump does not appear to be installed on this image. However, I've attached a log from the bluetoothctl scan as an alternative:
[bluetoothctl_dump.txt](https://github.com/custom-components/ble_monitor/files/6338188/bluetoothctl_dump.txt)

I installed the current Passive BLE component on my system and enabled report unknown and enabled info level logging, but I'm not seeing any logs yet other than a line that says "Attention! Option report_unknown is enabled, be ready for a huge output...". (Note, I wasn't able to select a device in the config setup).

Let me know if there is anything else I can do to help! Thank you for your efforts here.

**Comment by Ernst79** [comment]
I will look into it. If needed, I’ll prepare a version which allows you to use the report_unknown function. This will not work for this sensor at the moment, as it is not recognized as being a Xiaomi, ATC or qingping sensor.

**Comment by millercentral** [comment]
Thank you very much. Happy to help/test in any way I can.

**Comment by Ernst79** [comment]
Can you do me a favor? I've added the `report_unknown` functionality for Kegtron devices. Could you do the following. 

- Replace the content of `__init__.py` in your custom component folder with the contents of [`__init__.py` in the Kegtron branch](https://github.com/custom-components/ble_monitor/blob/kegtron/custom_components/ble_monitor/__init__.py)
- enable `report_unknown`
- add logging at `info` level for ble_monitor
- Restart HA and collect some data
-  The documentation you added in the first post says that it needs to have active scan. This is possible, but I'm curious if it works without active scan as well (as our component is meant to be passive :-). Could you try with and without active scan and send a couple of lines from your log with the data. Please add if you used active scan or not (`active_scan` is a setting you can set in the options of BLE monitor).

**Comment by millercentral** [comment]
I might of done something wrong, I get this error on reload (active scan not set):

```
Logger: homeassistant
Source: custom_components/ble_monitor/__init__.py:778
First occurred: 11:11:07 AM (1 occurrences)
Last logged: 11:11:07 AM

Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 862, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1866, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 778, in process_hci_events
    msg, binary, measuring = self.parse_raw_message(data)
TypeError: cannot unpack non-iterable NoneType object
```

Here is my config entries:
```
# Passive BLE Monitor configuration (temp)
ble_monitor:
  bt_interface: "DC:A6:32:59:AA:8D"
  discovery: False
  report_unknown: True
  devices:
    - mac: "D0:CF:5E:5C:9B:75"
      name: "Kegtron"
      restore_state: True

# Logger settings
logger:
  default: warn
  logs:
    custom_components.ble_monitor: info
```

**Comment by Ernst79** [comment]
Sorry, my mistake, 

I've added line 1453 in [`__init__.py`](https://github.com/custom-components/ble_monitor/blob/kegtron/custom_components/ble_monitor/__init__.py) to fix it. Have to do it without being able to test the code myself :-)

Can you try again

**Comment by millercentral** [comment]
Here is a quick capture (active scan not enabled in my config), let me know if you want it to run longer or if anything doesn't look right.
[home-assistant.log](https://github.com/custom-components/ble_monitor/files/6353138/home-assistant.log)

**Comment by Ernst79** [comment]
Thanks, this is all I need. Have to solve another issue first, will then continue with this.

**Comment by Ernst79** [comment]
I've made a first start to analyze the data. I found 2 types of advertisements in your data, lets call them short and long. 

**Long advertisments**
First the long advertisements. This seems to follow the format that is described in the documentation in the chapter "Scan Response Data". 

line 1. The first line is the index of the bytes
line 2-4. The next three lines are the example given in the [documentation](https://kegtron.com/docs/Gen1BLEMessageFormat.pdf)
line 5. One of the messages in the scan result with **active_scan** enabled. 

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HCI  Evt Len Sub Num Evt  Peer -------MAC-------   Len Len Type Val Len  AD  Kegtr Keg  Vol.  Vol.  port  ----------- port ---------------------- RSSI  
type code    evt rep type addr                             flag         type  UUID size start disp  state             name
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                       0                 1   2 3   4 5   6 7   8 9   10  1112131415161718192021222324252627282930     position (31 bytes)
                                                       1e                ff  ffff  49ef  1388  02e2  01  53696e676c6520506f7274000000000000000000     example 1 from docs
                                                       1e                ff  ffff  c350  c350  32c8  41  506f727420310000000000000000000000000000     example 2 from docs 
                                                       1e                ff  ffff  49ef  1388  02e2  51  326e6420506f7274000000000000000000000000     example 3 from docs
 04   3e 2b  02  01   04   00  75 9b 5c 5e cf d0   1f  1e                ff  ffff  4c5e  4c5e  0000  41  7b6e6f6e657d2020202020202020202020202020  af active adv long
```

It seems to follow the format, but it is only send with `active_scan` enabled. Not a big issue, but something we have to add in our documentation. 

**Short advertisments**
I also found shorter messages in both the logs with and without `active_scan` enabled. All messages are the same (except RSSI). 

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HCI  Evt Len Sub Num Evt  Peer -------MAC-------   Len Len Type Val Len  AD  Kegtr     len type flag Len type pwr Len type -----------total name------------------  RSSI  
type code    evt rep type addr                             flag         type  UUID 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                       0   1    2    3   4   5    6    7   8  9  10 11 12 13 14 15 16 17 18 19 20 21
                                                                                       02  01   06   02  0a  08   0f   09  k  e  g  t  r  o  n  x  x  x  x  x  x  x       expected according to docs
 04   3e 2a  02  01   00   01  2f 95 1e 86 f6 7f   1e  02   01  02  13   ff  ffff  66  62  62   66   30  65  32   37   33  35 35 34 36 63 35 36 02 0a f1 03 03 56 34   b9 passive adv
 04   3e 2a  02  01   00   01  43 30 94 fd f6 52   1e  02   01  02  13   ff  ffff  66  62  62   66   30  65  32   37   33  35 35 34 36 63 35 36 02 0a f1 03 03 56 34   b4 active adv short
```

I can't make much sense of the data. I would expect that this data followed the format what they describe in the documentation under "Advertisement Data". The first line shows what I would expect based on the docs, but the received data looks different.

Moreover, the MAC address in the beginning seems to be different for both messages (active and passive), but is also different compared to the Long advertisements. I would have expected the same MAC address for all three messages. Is there a way to verify the MAC address of the Keg? And do you have one keg, or multiple?

**Comment by millercentral** [comment]
Hi, thanks for investigating.  The version I have has support for two kegs. Its only MAC address (as far as I know) is D0:CF:5E:5C:9B:75.

Each interesting message ends with a string of the name of the keg that I set in its app. So you should see one that shows:
```
0    1   2   3   4   5   6   7   8   9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
------------------------------------------------------------------------------------------
4c 5e 4c 5e 0a 62 51 50 61 63 69 66 69 63 20 43 72 65 73 74 20 50 61 6c 65 20 20     [7 - 26]: "Pacific Crest Pale  "
4c 5e 4c 5e 00 00 41 7b 6e 6f 6e 65 7d 20 20 20 20 20 20 20 20 20 20 20 20 20 20     [7 - 26]: "{none}              "
```
Which I suppose are the "long" when active scan is enabled, alternating every 500ms or so.

**Comment by millercentral** [comment]
I think 74:48:4D:B8:0F:F3 is a different random device in my house. Not sure how to identify what it is, but I don't think it is related to the kegtron.

**Comment by Ernst79** [comment]
Thanks, I finished the decoding in useful readable data. Last step is to create the sensors, hope to finish that today or tomorrow.

**Comment by Ernst79** [comment]
I'm creating three sensors (don't look at the numbers, I use a dummy value). 

![image](https://user-images.githubusercontent.com/24375847/115989170-53e74700-a5bd-11eb-97e4-c7080a6d95ee.png)

![image](https://user-images.githubusercontent.com/24375847/115989161-4336d100-a5bd-11eb-91b8-0d7c61c42cfc.png)

The other port parameters, I will add as attributes. 

I used the keg icon, or do you prefer something else (look for mdi icons)

**Comment by Ernst79** [comment]
1.8.0-beta has been released, please give it a try. You have to enable `active_scan`, otherwise it won't work. 

Let me know if the names and icons of the sensors and attributes are OK. I tried to stick with the names in the documentation.

**Comment by millercentral** [comment]
Hi!

This works, sortof. I installed the 1.8.0-beta, and the kegtron device and the sensors you describe do show up, but there are a few issues (or misunderstandings by me, not sure which). Notes:

Kegtron shows up in the list of devices, with the keg size, volume dispensed and volume start sensors (cool icon!). However the sensors constantly toggle between the values of the two ports on the device -- see the attached video. Ideally, when the device is a 2 port device it would create unique sensors for each port. 

https://user-images.githubusercontent.com/7720102/116011264-f95be400-a5d8-11eb-897d-de0034426ee0.mp4

The only other attribute that is missing that would be valuable is the defined name of the keg. 

My ultimate goal is to have a lovelace UI element that shows the keg name, keg size, the number of glasses poured (dispensed / glass volume) and number of glasses remaining ( (start vol - dispensed) / glass volume), for each port. Feels like I'm really close to being able to do that now. :)

I know I've said it a few times, but thank you for your development effort on this. It is hugely exciting for me and I appreciate it. If there is a way I can donate to buy you a beer or something, please let me know.

**Comment by millercentral** [comment]
Thinking more about the sensors vs attributes....

* I think the only sensor entity needed is "Volume dispensed", with distinct entities for each port index (create one or two entitles based on the "port count" attribute of the Port/State byte.
* "Port Name", "Keg Size", and "Volume Start" are all static values that are provided in the configuration app. These can just be attributes to the Volume Dispensed sensor. "Port Count" not needed as an attribute as that will be obvious based on how many entities are created.
* Ideally Keg size would be represented as a string, mapped from the list of constant dictionary of values (below). If keg size doesn't match one of the constants, name it "Other (XX.XXX L)"
```
b'\x24\xf8' : "Half Corny (2.5 gal)"
b'\x49\xef' : "Corny (5.0 gal)"
b'\x4c\x66' : "1/6 Barrel (5.167 gal)"
b'\x4c\x5e' : "1/6 Barrel (5.167 gal)" 
b'\x4e\x20' : "20L (5.283 gal)"
b'\x4f\xe9' : "Pin (5.404 gal)"
b'\x72\x99' : "1/4 Barrel (7.75 gal)"
b'\x9f\xd3' : "Firkin (10.809 gal)"
b'\xc3\x50' : "50L (13.209 gal)"
b'\xe5\x32' : "1/2 Barrel (15.5 gal)"
```

What do you think?

**Comment by Ernst79** [comment]
Yes, I think all points should be possible. I’ll look into it in the coming days.

**Comment by Ernst79** [comment]
I will release a 1.8.1-beta in a few minutes. I changed all your request, the only thing I still have to add is the "port name". Will do that in the next beta update. 

I made a significant change, by splitting all the different parsers in the `__init__.py` file into different files, one per "manufacturer". This makes the programming somewhat more readable to me, as I got lost, due to the increasing number of supported sensors. I made this change in this version, so it might have some unexpected issues (although I think it should not happen. Could you tell me if you are using other BLE sensors as well with BLE monitor, or only Kegtron?

Another important thing, please delete the Kegtron devices completely first, as I changed the device name from Kegtron to Kegtron KT-200 (or KT-100). HA has the behavior to stick with the old name, even when deleting it from the options menu. The easiest is to delete BLE monitor, restart and install it again. If you don't have to many other sensors, that's the easiest way to go. Otherwise, there is a service to delete the devices from the registry, I can help you with that. **This step is important to do**

**Comment by millercentral** [comment]
This works great! I completely blew away the integration and ensured it was gone in core.config, then installed the new version. I had to manually add the device MAC (in the Add Device section of config), but it worked fine and identified it as Kegtron KT-200 with two entities, with all the attributes in place (except beer name which you said was coming later). I poured a celebratory pint to ensure it was working:
![Kegtron](https://user-images.githubusercontent.com/7720102/116333313-15ea4e80-a788-11eb-8bb8-93b67ecf1e94.png)

**Comment by Ernst79** [comment]
hmm, it should have been automagically discovered with `discovery: True`. Didn't you set it to False accidently?

I'll add the port name later yes, shouldn't be that difficult.

**Comment by millercentral** [comment]
I'll remove it and re-add and screen record it when I get a chance. There is definitely a high chance of user error here.

**Comment by Ernst79** [comment]
1.8.3-beta has been released, which adds the port name as an attribute (and another small fix). 

As far as I can see, it should be finished now :tada: Let me know if you want any final changes or if you want things to be named differently. Also let me know if the autodiscovery is working. 

If you still want to donate a :beer:, there is now a [sponsor](https://github.com/sponsors/Ernst79) button at the top of the page. Cheers!

**Comment by millercentral** [comment]
I removed the integration, deleted and reinstalled with the latest version and set everything up again. It is **perfect**. All fields are exactly as expected/hoped. Now I need to work on my lovelace layout, but this is absolutely wonderful, thank you.

Discovery was in fact user error. I mistakenly assumed the Devices dropdown in the first window would show it, but as you can see in the attached video it showed up just fine when I hit submit.

Sponsored, thanks again.

Video of install process:



https://user-images.githubusercontent.com/7720102/116496194-5796fa00-a859-11eb-99f8-b03e528d15ff.mp4

**Comment by millercentral** [comment]
So I haven't really spent any time with my lovelace layout in HA yet, but this took all of 15 minutes to put together. THANK YOU. THANK YOU. THANK YOU.
![Screenshot 2021-04-28 205615](https://user-images.githubusercontent.com/7720102/116500903-5fa86700-a864-11eb-9415-141ac27f6a8d.png)

**Comment by Ernst79** [comment]
You're welcome. Thanks for the :beer: 

Will release the final release tonight.

**Comment by Ernst79** [comment]
1.8.3 has been released.
