### ISSUE TITLE
Add support Yeelight bedside lamp (Bluetooth)

### ISSUE THREAD

**Issue by xekil** [custom-components/ble_monitor#335]
Hello,

Would it be possible to add support for the Yeelight  bedside lamp (Bluetooth).
There is an integration but it gives me a lot of problem, there is a lot of error and it I have the impression that it interferes with the BLE Monitor integration, result it does not always work.

It would be ideal to integrate this lamp into the BLE Monitor integration :)

https://github.com/hcoohb/hass-yeelightbt

Thank you

**Comment by Ernst79** [comment]
I'm afraid it won't be possible to add (at least not easy). A light requires to be make a connection to the light and sending data to the light (like hass-yeelightbt is doing), while this integration is passively listening to BLE messages. This means it can't turn on/off the light, it might only receive the state of the light, if it is broadcasted by the light. And I assume you want to turn of/off the light from HA.

A workaround for the problems you face might be to use a second bluetooth dongle. BLE monitor is able to specify the Bluetooth radio/dongle it is using, so it might help to use one for BLE monitor and the other for hass-yeelightbt.

**Comment by xekil** [comment]
Thank you for your answer, yes indeed I wish I could turn the light off and on :(
Unfortunately I cannot use two bluetooth dongles on HomeAssitantOS, the second dongle is not recognized by Hassio, I have tried several different bluetooth dongles and cannot make more than one dongle work, either on Rapberry (Haasio) or on a Virtual Machine (Hassio). I say it's a known bug of HomeAssitantOS (Hassio).
If you have a solution, I'm interested :)
Thank you

**Comment by Ernst79** [comment]
I use a supervised installation on Raspberry OS, which is working fine with a dongle + internal Bluetooth. I tried it on Debian (as recommended for HA), but on Debian, I had a lot of trouble getting the internal Bluetooth to work. In the end, I gave up and went back to Raspberry OS. (I'm using a RPi3b+). Bluetooth can be a pain in the ..., I know.

**Comment by xekil** [comment]
I use a rapsberry 2 :) for HA Remote (BLE Monitor, YeelightBT) and Proxmox for HA Master. Both are under HomeAssistantOS.

I am concentrating my tests on Rapberry 2 because it is he who is near my YeelightBT lamps and so far I have not succeeded in having a second Bluetooth dongle recognized, I will try again ...
