### ISSUE TITLE
Unable to resolve MAC addres for hci0 device

### ISSUE THREAD

**Issue by skynetua** [custom-components/ble_monitor#339]
I'm getting issue with resolving MAC address of hci device after upgrading host os to ubuntu 21.04 from 20.10. It shown as 00:00:00:00:00:00 in config window. I'm running home assistant os on qemu virtual machine. How can I check what causes this issue?

**Comment by Ernst79** [comment]
This means that python is not able to find a Bluetooth interface. BLE monitor tries to check that a Bluetooth receiver is available on hci0, hci1 or hci2. In case it doesn't find anything (like in your situation) BLE monitor will use the default hci0, but most likely, BLE monitor isn't working. 

Your virtual machine most likely doesn't have access to your Bluetooth dongle/radio. I'm not into the details of making Bluetooth available in your virtual machine, but google will most likely help you out. I see some solutions here:

https://communities.vmware.com/t5/VMware-Workstation-Pro/Bluetooth-device-showing-in-VM-guest-even-after-disabling/td-p/2734218

**Comment by Ernst79** [comment]
I'm closing this issue. If you still have the issue, feel free to reopen the issue.
