### ISSUE TITLE
Support for the Huawei Body fat Scale AX100

### ISSUE THREAD

**Issue by sudoMD** [custom-components/ble_monitor#343]
Hi all, I just purchased a Huawei Bluetooth Body Mass scale and wondering if is possible to integrate with HA

**Comment by Ernst79** [comment]
Lets try to find out. You can get a log with ble messages with the option report_unkown. Use "other" to get all ble messages, as we dont know the uuid (yet). You have to enable debug logging at info level, see instructions in the faq. It would help if you can find the Mac address. Perhaps in an app you use for the scale.

**Comment by Ernst79** [comment]
Out of curiousity, why did you close the issue.? Is it too much trouble getting the data? I can help you if something isnt clear.
