### ISSUE TITLE
Support for soocare.toothbrush.m1

### ISSUE THREAD

**Issue by Chriserus** [custom-components/ble_monitor#344]
Hello there! First off, thank you for supporting the project, really like the Xiaomi T500 toothbrush support! I am here to kindly ask for support for another Xiaomi-branded toothbrush model, which is soocare.toothbrush.m1. I found the github that explains what is being brodcasted by the device, so maybe it will help you out!
Here's the link: https://github.com/freenetwork/ble-in-xiaomi/blob/master/doc/devices/soocare.toothbrush.m1.md
I would be very greatful if you add this support, and maybe some other people would be?
Kindly think about my request, thank you in advance, and guys, keep up the good work! :)

**Comment by Ernst79** [comment]
According to the link, the toothbrush requires a connection to be set up. There is no advertisement broadcasted. This component is only passively listening to ble advertisements, but is not able to set up a connection.  To make sure this is True, you can try the option "report_unknown: xiaomi" (make sure you enable debug logging as well. Instructions are in the faq).

**Comment by Fubi95** [comment]
I already tried to collect data from my m1 using the `report unknown` option. Unfortunately I had no success. Maybe @Chriserus has more luck.

**Comment by Ernst79** [comment]
I'm closing this issue for now. Unfortunately it isn't possible to add the toothbrush, as it requires a connection to be set up, which is out of the scope of BLE monitor (only listens passively).
