### ISSUE TITLE
Trouble adding a Yeelight Wireless Switch S1 YLAI003

### ISSUE THREAD

**Issue by EdwardJB** [custom-components/ble_monitor#350]
Hi,

I have a working integration (many devices already working well) but having trouble adding this switch. It's encrypted, but I cannot find the key. Normally I add the device to the Mi app, then run the CLI tool which lists the keys. But this switch doesn't seem to pair with the app.

Can anyone help?

Thanks.

**Comment by Ernst79** [comment]
Which CLI tool did you use? Xiaomi cloud token extractor?

**Comment by EdwardJB** [comment]
> Which CLI tool did you use? Xiaomi cloud token extractor?

Well yes I used that for all my _other_ devices. But this switch won't pair with the Mi app, so I assume I can't use it for that?

**Comment by Ernst79** [comment]
I know from @resmuz that for the Yeelight dimmer they use this method. So, you need the token from the device it is connected to (in the example below a ceiling light) first. You should be able to get this via xiaomi clould token extractor. Next, you can get the beaconkey from the switch with one of the commands below. Didn't try it myself though. Let me know if this works, than I can add it to the faq. 

> you need IP/TOKEN of your ceiling light. you can get it with token extractor (check ble monitor faqs for details).
> 
> install python-miio and send
> 
> `miiocli device --ip IP --token TOKEN raw_command ble_dbg_tbl_dump '{"table":"evtRuleTbl"}'`
> or php-miio and send
> 
> `php miio-cli.php --ip IP --token TOKEN --sendcmd '{"id":1234,"method":"ble_dbg_tbl_dump","params":{"table":"evtRuleTbl"}}'`

**Comment by EdwardJB** [comment]
Thanks for this info!

I don't actually have any other device. I just bought the switch only cos saw it listed as supported in the README.

**Comment by Ernst79** [comment]
When reading #268 you should be able to pair it to the MiHome App just normally. Which region do you use in the app. Some devices are only available if you select China. Otherwise, ask @andrewjswan, he has this device and I know he often responses

**Comment by EdwardJB** [comment]
> When reading #268 you should be able to pair it to the MiHome App just normally. Which region do you use in the app. Some devices are only available if you select China. Otherwise, ask @andrewjswan, he has this device and I know he often responses

That was the problem. I changed the region to China and everything is working now. Thanks a lot for your help!!

**Comment by Ernst79** [comment]
No problem
