### ISSUE TITLE
Yeelight remotes

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#352]
Request from @bluefoxlee from #289 

Hi.
Wonder is there any possible to add support for this remote since it's very similar to 01YL but slightly different.
It comes with Yeelight celling fan/light product. Got PID 1678 through Miiocli. however can't find the model number of it.

![image](https://user-images.githubusercontent.com/24375847/118835135-03fd5680-b8c3-11eb-9d76-910b8c3364ee.png)
[Left: YLYK01YL] [Right: PID 1678]

**Comment by Ernst79** [comment]
@bluefoxlee can you log it with hcidump or ble_monitor debug log? each button single click, double click and long press. pretty sure it can be supported.

```
  var RemoteControllerType = {
    BLERC: 339,
    SEESAW: 950,
    BHFRC: 959,
    VENFAN: 1254,
    FANCL: 1678
  };
```

Or 

The easiest to try is modify the following two files, In each file look for YLYK01YL, copy this line and modify to YLYKxxYL). In the first file, also modify b'\x53\x01 to b'\x8E\x06 in the new line.

`\custom_components\ble_monitor\ble_parser\xiaomi.py`

```
    b'\x53\x01': ("YLYK01YL", True),
    b'\x8E\x06': ("YLYKxxYL", True),
```

and in `\custom_components\ble_monitor\const.py`

```
    'YLYK01YL'       : [[9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9], [0, 9, 9, 9, 9, 9, 9, 9]],
    'YLYKxxYL'       : [[9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9], [0, 9, 9, 9, 9, 9, 9, 9]],
```

and

```
    'YLYK01YL'       : 'Yeelight',
    'YLYKxxYL'       : 'Yeelight',
```

For now, states will probably the same as for the YLYK01YL remote, but let first find out if this works. You might need an encryption key (24 characters). You can follow the instructions here, for 'ceiling light', you can read 'fan', I guess (seems like a fan remote).

I think the remote belongs to the YLFD001 ceiling fan light, isn't there a name on the back or insight an battery compartement?

**Comment by bluefoxlee** [comment]
Thanks @rezmus and @Ernst79 for replay and help to open an issue. I will make some test with it and report it back tomoroww.

**Comment by bluefoxlee** [comment]
> For now, states will probably the same as for the YLYK01YL remote, but let first find out if this works. You might need an encryption key (24 characters). You can follow the instructions here, for 'ceiling light', you can read 'fan', I guess (seems like a fan remote).

I use the method 2, and as you mention. the remote work exactly the same as YLYK01YL. It shows M, Sun, On, Off, + and - ATM. Also tried hcidump, will post the log later after clean other message of it.
 
> I think the remote belongs to the YLFD001 ceiling fan light, isn't there a name on the back or insight an battery compartement?

Yes, I think Yeelight ceding fan light comes with this remote. unfortunately, there is no any Information about the remote model. Will try to dis-assembly it tomorrow to see if I can find any thing from PCB.

**Comment by Ernst79** [comment]
I’ll prepare a beta this weekend. I’ll try to make a fan_remote sensor which shows the names of the buttons. Can you tell me the meaning of each button (no idea what each button exactly does)

**Comment by bluefoxlee** [comment]
The buttons:

| Buttons Left  | Buttons Right |
| ------------- | ------------- |
| Fan toggle  | Light toggle |
| Stand Wind speed toggle  | Color Temp. toggle |
| Natural Wind speed toggle  | Brightness toggle |


I have both 01YL and this unknown model. I disassemble them this morning. 
not much found here, but interestingly the unknown model designed in 2012, and 01YL is 2016. The unknown model PCB did shows Type S5. Should we call it 05 perhaps?

**Comment by rezmus** [comment]
it's a part of bigger product so i guess it does not have it's own model. just call it YLYK-FANCL like in the plugin. there is also similar remote for yeelight kitchen fan (pid 1254 YLYK-VENFAN). pretty sure sends same payloads as all such remotes.

https://post.smzdm.com/p/awxl0924/
https://am.zdmimg.com/201906/25/5d119e3567c4e3524.jpg_e680.jpg

btw: in separate remote "sun" button is actually color temperature button.

**Comment by Ernst79** [comment]
I will use the following

YLYK01YL-FANCL
YLYK01YL-VENFAN
etc.

Will rename fan to color temperature..

Beta release will be released today (for YLYK01YL-FANCL).

**Comment by Ernst79** [comment]
2.2.0-beta has been released, please give it a try. There are no binary sensors for this fan remote. You can remove the old ones after a restart (also remove the old remote sensor, a new fan remote sensor will be new)

**Comment by bluefoxlee** [comment]
Thanks!! It works and shows correct button name now. And nice call for remote naming.

**Comment by Ernst79** [comment]
2.2.0 has been released as final. Thanks for reporting back. 

Will add the others later.

**Comment by Ernst79** [comment]
2.3.0-beta has added support for yLYK01YL-VENFAN.

The only missing remote is (YLYK01YL-)BHFRC: pid = 959, I have no idea which device this is?

RC probably stands for Remote Control, but don’t no where the abbreviation BHF is standing for?

**Comment by rezmus** [comment]
@Ernst79 https://www.youtube.com/watch?t=600&v=PaNbnOg_NT8

**Comment by Ernst79** [comment]
Yeah, I just updated my previous post. But to add this, we first need someone with this remote to understand which button sends what bytes. 

If anyone have this device, please help us by sending a hcidump.

**Comment by bluefoxlee** [comment]
Quick translate for YLYB01YL. 

| HEAT button  | Air exchange button| DRY button | Fan button |
| :-------------: | :-------------: | :-------------: | :-------------: |
| Swing | Wind speed -  | Wind speed + | Stop |
|| Light toggle ||

There are some discussion about this add-on and Yeelight 07YL/08YL remote on Chinese forum, I will try to post there to see if anyone have it and can help maybe.

**Comment by Ernst79** [comment]
Thanks, I just updated the script to get the [beaconkey](https://github.com/custom-components/ble_monitor/blob/master/faq.md#how-to-get-the-mibeacon-v2v3-encryption-key), so it can now also be used for this YLYB01YL device.

**Comment by froggyfly** [comment]
I have this Bathroom Heater remote, but how to log it?

**Comment by Ernst79** [comment]
I’ll prepare a special version for you, which logs automatically. Give me an hour

**Comment by Ernst79** [comment]
@froggyfly 

- Please install version 2.4.0-beta (enable beta versions in HACS). 
- Make sure you configure your MAC and encryption key, which can be found with method 5 in the [FAQ](https://github.com/custom-components/ble_monitor/blob/master/faq.md#how-to-get-the-mibeacon-v2v3-encryption-key)
- After the restart, press a button, this should (hopefully) create a sensor entity (`ble_bathroom_heater_remote_AABBCCDDEEFF`)
- Open the sensor
- Click on each button and for each button, report back the result of Byte 1, Byte 2 and Byte 3. 
- Do this again with a "long" click (press and hold for a few seconds while). The other sensors are able to make distinction between short clicks and long clicks. Maybe this one as well, although I doubt it will.
- Also try with a "double" and "triple" click, to see if it sends different bytes. 

![image](https://user-images.githubusercontent.com/24375847/119270360-9a4fb600-bbfc-11eb-9362-67c0ceeac707.png)

**Comment by froggyfly** [comment]
> @froggyfly
> 
> * 请安装版本2.4.0-beta（在HACS中启用beta版本）。
> * 确保您配置了MAC和加密密钥，这可以在[FAQ中的](https://github.com/custom-components/ble_monitor/blob/master/faq.md#how-to-get-the-mibeacon-v2v3-encryption-key)方法5中找到。[](https://github.com/custom-components/ble_monitor/blob/master/faq.md#how-to-get-the-mibeacon-v2v3-encryption-key)
> * 重新启动后，按一个按钮，这应该（希望）创建一个传感器实体（`ble_bathroom_heater_remote_AABBCCDDEEFF`）
> * 打开传感器
> * 单击每个按钮，然后为每个按钮报告字节1，字节2和字节3的结果。
> * 再次单击“长按”（按住几秒钟），再次执行此操作。其他传感器能够区分短点击和长点击。也许也可以，尽管我对此表示怀疑。
> * 也可以尝试单击“ double”和“ triple”，以查看是否发送了不同的字节。
> 
> ![图像](https://user-images.githubusercontent.com/24375847/119270556-8789b100-bbfd-11eb-8d17-db47c4dcdd18.png)
ok, I'll log it this evening.

**Comment by froggyfly** [comment]
@Ernst79 
Hey,  the scripts command @FAQ 5, rejected my wget connection, and the modify Android app can't find this remote, so I have no idea for this key now... Sorry, I have nothing about Linux/code, so any extended operation is extremely difficult for me. 
If you give me more details, I'll try again tomorrow
I'm sorry about this

**Comment by bluefoxlee** [comment]
> If you give me more details, I'll try again tomorrow

@froggyfly 

1. 在你的 Linux 中打开终端机
2. 输入
`wget https://raw.githubusercontent.com/custom-components/ble_monitor/master/custom_components/ble_monitor/ble_parser/get_beacon_key.py
pip3 install bluepy`
这个步骤是取得 get_beacon_key.py 这个档案，并安装 Bluepy 这个函数库
3. 输入
`python3 get_beacon_key.py <MAC> <PRODUCT_ID>`
其中 <Mac> 的地方 改成你的遥控器 Mac Address，通常你在米家浴霸里面已配对的遥控器可以看到
<PRODUCT_ID>  填入 959
4. 应该会类似这样
`python3 get_beacon_key.py AB:CD:EF:12:34:56 959`
5. 应该就会显示像这样一串
`[{'mac': '563412efcdab', 'evtid': 4097, 'pid': 959, 'beaconkey': '11f245f7a60c6c17aaca1e83'}]`
后面就是你需要的 beaconkey
6. 到 UI 或者看您的留言，是用 YAML 配置。输入对应的 Mac 跟 Beacn Key，再去按一下遥控器应该就会出现了

**Comment by Ernst79** [comment]
@froggyfly The python file is probably already in config/custom_components/ble_monitor/ble_parser/

**Comment by froggyfly** [comment]
error :
pip3 install bluepy
Collecting bluepy
  Downloading bluepy-1.3.0.tar.gz (217 kB)
     |████████████████████████████████| 217 kB 1.3 MB/s 
Building wheels for collected packages: bluepy
  Building wheel for bluepy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i2uvv01d/bluepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i2uvv01d/bluepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bkp84isr
       cwd: /tmp/pip-install-i2uvv01d/bluepy/
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  Working dir is /tmp/pip-install-i2uvv01d/bluepy
  execute make -C ./bluepy clean
  execute make -C bluepy -j1
  Failed to compile bluepy-helper. Exiting install.
  Command was 'make -C bluepy -j1' in /tmp/pip-install-i2uvv01d/bluepy
  Return code was 2
  Output was:
  b"make: \xe8\xbf\x9b\xe5\x85\xa5\xe7\x9b\xae\xe5\xbd\x95\xe2\x80\x9c/tmp/pip-install-i2uvv01d/bluepy/bluepy\xe2\x80\x9d\ntar xzf bluez-src.tgz\ntouch ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c\nPackage glib-2.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `glib-2.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'glib-2.0' found\nPackage glib-2.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `glib-2.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'glib-2.0' found\ncc -L. -g -Wall  -Os -DHAVE_CONFIG_H -I./bluez-5.47/attrib -I./bluez-5.47 -I./bluez-5.47/lib -I./bluez-5.47/src -I./bluez-5.47/gdbus -I./bluez-5.47/btio -I./bluez-5.47/sys  -o bluepy-helper bluepy-helper.c ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c \nbluepy-helper.c:33:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   33 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/att.c:33:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   33 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/gatt.c:32:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   32 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/gattrib.c:34:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   34 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/utils.c:30:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   30 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/btio/btio.c:37:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   37 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/log.c:38:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   38 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/io-glib.c:30:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   30 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/timeout-glib.c:22:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   22 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\nmake: *** [Makefile:30\xef\xbc\x9abluepy-helper] \xe9\x94\x99\xe8\xaf\xaf 1\nmake: \xe7\xa6\xbb\xe5\xbc\x80\xe7\x9b\xae\xe5\xbd\x95\xe2\x80\x9c/tmp/pip-install-i2uvv01d/bluepy/bluepy\xe2\x80\x9d\n"
  ----------------------------------------
  ERROR: Failed building wheel for bluepy
  Running setup.py clean for bluepy
Failed to build bluepy
Installing collected packages: bluepy
    Running setup.py install for bluepy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i2uvv01d/bluepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i2uvv01d/bluepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_45wdio1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/bluepy
         cwd: /tmp/pip-install-i2uvv01d/bluepy/
    Complete output (11 lines):
    running install
    running build
    running build_py
    Working dir is /tmp/pip-install-i2uvv01d/bluepy
    execute make -C ./bluepy clean
    execute make -C bluepy -j1
    Failed to compile bluepy-helper. Exiting install.
    Command was 'make -C bluepy -j1' in /tmp/pip-install-i2uvv01d/bluepy
    Return code was 2
    Output was:
    b"make: \xe8\xbf\x9b\xe5\x85\xa5\xe7\x9b\xae\xe5\xbd\x95\xe2\x80\x9c/tmp/pip-install-i2uvv01d/bluepy/bluepy\xe2\x80\x9d\ntar xzf bluez-src.tgz\ntouch ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c\nPackage glib-2.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `glib-2.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'glib-2.0' found\nPackage glib-2.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `glib-2.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'glib-2.0' found\ncc -L. -g -Wall  -Os -DHAVE_CONFIG_H -I./bluez-5.47/attrib -I./bluez-5.47 -I./bluez-5.47/lib -I./bluez-5.47/src -I./bluez-5.47/gdbus -I./bluez-5.47/btio -I./bluez-5.47/sys  -o bluepy-helper bluepy-helper.c ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c \nbluepy-helper.c:33:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   33 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/att.c:33:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   33 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/gatt.c:32:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   32 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/gattrib.c:34:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   34 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/utils.c:30:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   30 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/btio/btio.c:37:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   37 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/log.c:38:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   38 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/io-glib.c:30:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   30 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/timeout-glib.c:22:10: fatal error: glib.h: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n   22 | #include <glib.h>\n      |          ^~~~~~~~\ncompilation terminated.\nmake: *** [Makefile:30\xef\xbc\x9abluepy-helper] \xe9\x94\x99\xe8\xaf\xaf 1\nmake: \xe7\xa6\xbb\xe5\xbc\x80\xe7\x9b\xae\xe5\xbd\x95\xe2\x80\x9c/tmp/pip-install-i2uvv01d/bluepy/bluepy\xe2\x80\x9d\n"
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i2uvv01d/bluepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i2uvv01d/bluepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_45wdio1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/bluepy Check the logs for full command output.

**Comment by rezmus** [comment]
@froggyfly share your yeelight heater to xiaomi id 2235426215 in mi home app. i will tell you mac/key.

**Comment by Ernst79** [comment]
try `pip3 install bluepy`

**Comment by froggyfly** [comment]
> @froggyfly share your yeelight heater to xiaomi id 2235426215 in mi home app. i will tell you mac/key.

Thanks, device shared.

**Comment by rezmus** [comment]
@froggyfly here is your mac/key. please delete post with my xiaomi id.

F8:24:41:B0:48:DC
6c0a024a2d1987223a19ce5d

**Comment by froggyfly** [comment]
> @froggyfly here is your mac/key. please delete post with my xiaomi id.
> 
> F8:24:41:B0:48:DC
> 6c0a024a2d1987223a19ce5d

Great, I'll log this remote later tonight!

**Comment by froggyfly** [comment]
log for YLYB01YL-BHFRC here:

![微信图片_20210525195624](https://user-images.githubusercontent.com/67083902/119493961-58a54380-bd93-11eb-8913-1f824fed4010.png)

No double or triple clicks actions.  all "long/hold" clicks shows like "*", "0", "6" .

**Comment by Ernst79** [comment]
Excelent, I will add this

**Comment by Ernst79** [comment]
2.4.2-beta has been released with support for YLYB01YL-BHFRC, please try it out.

**Comment by Ernst79** [comment]
2.4.3 has been released as final. i'm closing this issue now, all remotes are added.

**Comment by bluefoxlee** [comment]
@Ernst79 Thanks a million for the great work.
