### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'mitemp_bt'. 

### ISSUE THREAD

**Issue by hamzboy99** [custom-components/ble_monitor#355]
Logger: homeassistant.loader
Source: loader.py:794
First occurred: 9:40:28 (1 occurrences)
Last logged: 9:40:28

No 'version' key in the manifest file for custom integration 'mitemp_bt'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'mitemp_bt'

**Comment by Ernst79** [comment]
mitemp is a very old version. Our integration is now called ble_monitor. If you have the latest version of BLE monitor, you probably still have a left over from the old integration.  

To fix it, delete the following folder: `\config\custom_components\mitemp_bt`, including its content.

**Comment by hamzboy99** [comment]
Update to latest version fixed the problem.
