### ISSUE TITLE
[SOLVED] HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed

### ISSUE THREAD

**Issue by ikomtur** [custom-components/ble_monitor#356]
Hi all

I'm trying to add my LYWSD03MMC sensor but recieving this issue

Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:542
Integration: Passive BLE monitor (documentation, issues)
First occurred: 19:38:48 (1 occurrences)
Last logged: 19:38:48

HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed.

Home Assistant 2021.5.5
python3 3.85

**Comment by Ernst79** [comment]
Did you try this solution?

https://github.com/custom-components/ble_monitor/issues/167#issuecomment-739541674

**Comment by ikomtur** [comment]
Yes. Executed it, restarted HA but got the same.

**Comment by Ernst79** [comment]
What kind of installation do you have? Venv, supervised or home assistant Os?

**Comment by ikomtur** [comment]
supervised

**Comment by ikomtur** [comment]
Iguess there is a problem when trying scan
`self._event_loop.run_until_complete(btctrl[hci].send_scan_request(self._active))`

when I run  `sudo hcitool lescan` I receive

`Set scan parameters failed: Connection timed out`

**Comment by Ernst79** [comment]
try the following commands

```
sudo hciconfig hci0 down
sudo hciconfig hci0 up
```
if this doesn't work or it hangs in DOWN status, try:

```
sudo service bluetooth restart
sudo service dbus restart
```

What is the result of this command?

```
sudo getcap `readlink -f \`which python3\``
```

and 

```
hcitool dev
```

**Comment by ikomtur** [comment]
Was triyng many solutions for 4 hours :)

I think its a hardware problem. There was a patch for similar dongles with the same id
https://gist.github.com/nevack/6b36b82d715dc025163d9e9124840a07

Will change my dongle tomorrow to another. If it will help so it will be a solution.

**Comment by Ernst79** [comment]
ok, let me know if it worked with the new dongle. Bluetooth (dongles) can be a pita.

**Comment by ikomtur** [comment]
SOLVED

With new dongle (https://www.asus.com/Networking-IoT-Servers/Adapters/All-series/USBBT400/) it works fine. So it was a problem with not original CSR chip.
