### ISSUE TITLE
YLYK01YL

### ISSUE THREAD

**Issue by viiy** [custom-components/ble_monitor#358]
all my YLYK01YL light remote switch to fan after last update. How can i fix it?

**Comment by Ernst79** [comment]
What do you mean by "switch to fan"?  which remote do you have, there are currently two types supported (YLYK01YL and YLYK01YL-FANRC), see the pictures in the supported sensors documentation. Which type do you have (based on the picture).

**Comment by Ernst79** [comment]
Oh, nevermind, I see the mistake. I'll update a.s.a.p.

**Comment by Ernst79** [comment]
2.2.2 has been released, should fix your problem. Please let me know if it's all OK after the update.

**Comment by viiy** [comment]
already on 2.2.2 version.
ill try to readd all remotes later.

**Comment by viiy** [comment]
hm. 
i think something wrong with hacs;
 i was go to hacs page, and seen there update from 2.2.1 to 2.2.2 againg,  although i already updated to this version.
 after reupdate all fine.
 ty.
