### ISSUE TITLE
Missing Bluetooth adapters on Version 2.2.2

### ISSUE THREAD

**Issue by stefangries** [custom-components/ble_monitor#359]
Running HassOS 6.0.RC2 / Supervisor 2021.05.1 / Core 2021.5.5
The new BLE Monitor 2.2.2 does not recognize the native onboard Bluetooth Adapter of my Intel NUC. Version 2.0.2 does.

**BLE Monitor 2.0.2**
![image](https://user-images.githubusercontent.com/10342151/119227288-63e73d80-bb0d-11eb-8493-444ea8eb21fa.png)

**BLE Monitor 2.2.2**
![image](https://user-images.githubusercontent.com/10342151/119227319-95600900-bb0d-11eb-8b40-6edeed9a680b.png)
![image](https://user-images.githubusercontent.com/10342151/119227328-9bee8080-bb0d-11eb-8745-07ab445a9aed.png)

**Comment by Ernst79** [comment]
Could you show the output of `hciconfig`? 

The code normally runs this command and extracts the MAC addresses, but I changed something recently in that part of the code. But I'm curious what the result of `hciconfig` shows.

**Comment by stefangries** [comment]
```
hci1:   Type: Primary  Bus: USB
        BD Address: AC:67:5D:12:00:24  ACL MTU: 1021:4  SCO MTU: 96:6
        UP RUNNING 
        RX bytes:24384 acl:0 sco:0 events:2972 errors:0
        TX bytes:684468 acl:0 sco:0 commands:2812 errors:0

hci0:   Type: Primary  Bus: USB
        BD Address: 00:1A:7D:DA:71:11  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING 
        RX bytes:976023 acl:0 sco:0 events:36748 errors:0
        TX bytes:3942 acl:0 sco:0 commands:197 errors:0
```

**Comment by Ernst79** [comment]
I can reproduce your issue. Will look into it.

**Comment by Ernst79** [comment]
The quick fix:

in `\custom_components\ble_monitor\ble_parser\__init__.py` 

change

```
    def get_mac(self, interface_list=[0]):
```

to 

```
    def get_mac(self, interface_list=[0, 1, 2, 3]):
```

Wil fix it in the next release.

**Comment by stefangries** [comment]
Thanks, seems to be working! 👍

**Comment by Ernst79** [comment]
Final solution will be slightly different, as you should normally have self in the function. But for now, it works

**Comment by Ernst79** [comment]
Could you please try version 2.3.0-beta and let me know if it works?

**Comment by stefangries** [comment]
Seems to be working. Thanks!

**Comment by Ernst79** [comment]
Thanks. 2.3.0 has been released.
