### ISSUE TITLE
Rewrite of parser

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#365]
I'm going to rewrite the parser, such that it only parses the service data. This issue will be used to keep track of the process

- [x] Prepare `__init__.py` to extract the service data (version 2.4.3)
- [x] Remove the binary/measuring type out of the parser (version 2.4.3)
- [x] Fix the whitelist option to not reverse the MAC (version 2.5.0)
- [x] Fix the key dictionary to not reverse the MAC (version 2.5.0)
- [x] Xiaomi parser (2.8.1)
- [x] Kegtron parser (version 2.5.0)
- [x] Qingping parser (version 2.5.1)
- [x] MiScale parser (version 2.6.1)
- [x] ATC parser (2.7.1)
- [x] Add [encrypted ATC format](https://github.com/pvvx/ATC_MiThermometer/issues/94#issuecomment-846984018) (2.7.1)
- [x] Rewrite sensor and binary sensor part to new measuring type dict (3.0.0)

[Inspired by custom pvvx version of BLE monitor](https://github.com/pvvx/ble_monitor)

**Comment by airy10** [comment]
I'm getting this exception with 2.8.0-beta - 2.7.1 is fine 
My devices are using pvvc firmware - pvvc ad format, not encrypted
```
2021-06-03 12:38:19 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ble_monitor/sensor.py", line 189, in async_run
sensors = await async_add_sensor(mac, sensortype, firmware)
File "/config/custom_components/ble_monitor/sensor.py", line 116, in async_add_sensor
sensors.insert(h_i, HumiditySensor(self.config, mac, sensortype, firmware))
File "/config/custom_components/ble_monitor/sensor.py", line 684, in __init__
if self._device_firmware[0:6] == "Xiaomi":
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Ernst79** [comment]
Hmm, strange. Could you check something for me. When you open a sensor, e.g. a temperature measurement, could you check the attribute Firmware. What is it saying? Is one of them saying None?

![image](https://user-images.githubusercontent.com/24375847/120679099-17025000-c499-11eb-8ef2-0b0391c8f4c9.png)

**Comment by airy10** [comment]
Looks like it's because I have some sensors that used to be reachable by my HA PI (using some older version of the BLE integration)  but currently aren't anymore (I'm using a esphome bridge for them)
Last states knows for these entities don't have the "firmware" attribute and I guess that it's the problem
All of the reachable devices are "ATC (Custom)"

**Comment by Ernst79** [comment]
Ok, I will just add a check for "not None" Thanks for reporting.

**Comment by airy10** [comment]
Thanks. My setup is happy again with 2.8.1-beta 👍
