### ISSUE TITLE
RSSI sensor

### ISSUE THREAD

**Issue by lupumihai** [custom-components/ble_monitor#37]
Dear developers, 
I congrats you for the plugin,  I find it well made.
From the version "0.5.3" you added the possibility to see the battery level as an entity, and it's working great.

For the next releases, I suggest to include the same thing for RSSI. It will be nice to have also this information easily available.

thank you.

**Comment by Magalex2x14** [comment]
Can i ask you? Why do you need this?

I did not initially make either a battery or RSSI as separate entities, since those who really needed it could easily get this data from the attributes. A sensor template or, for example, since the storage system (implemented in HA by default) is not suitable for storing large amounts of data (I quickly encountered poor performance even after switching to MariaDB) I personally use InfluxDB, and there the attributes are already presented as separate fields, which can be easily visualized using Grafana, for example.

No, I do not refuse to implement your suggestion. Just curious.

**Comment by lupumihai** [comment]
The main reason it's that I don't like and it's quite hard for me to write YAML configuration files in order to obtain this kind of information.  Overall I'm still a newbie in HA. 
I tried before other systems that are easier to configure (web interface) but I like too much the HA interface and the way to configure it these days, with the help of Lovelace interface.
So from what I see, HA is going more and more for entity auto-discovery.
Adding also RSSI  will be even easier, I use RSSI for my all devices to detect WIFI/BT coverage issues, this helps me to correct them by adding or changing the position of transceivers around the house.

Thank you, for considering this request.

**Comment by andrewjswan** [comment]
I use template sensors like:
````
     rssi_ble_bedroom:
        device_class: signal_strength
        unit_of_measurement: dB
        value_template: >-
          {% set sensors = [state_attr('sensor.ble_temperature_bedroom','rssi')|float, state_attr('sensor.ble_humidity_bedroom','rssi')|float, state_attr('sensor.ble_battery_bedroom','rssi')|float] %}
          {% if sensors | sum == 0 %}
            -99 
          {% else %}
            {{ ((sensors | sum) / (sensors | select('lt',0) | list | length)) | round | int }} 
          {% endif %}
````

**Comment by Ernst79** [comment]
@Magalex2x14 I don't see the need for this anymore. Entity cards in Lovelace are able to show attributes in an entity card, just like a normal sensor. 

![image](https://user-images.githubusercontent.com/24375847/102713087-d84f5380-42c5-11eb-81c6-d026c2b0b29f.png)

Also in the entities cards (the one with multiple entities), this is possible. Just add a entity, click on the pencil, click on show code editor and add the following

```
type: attribute
entity: sensor.ble_temperature_livingroom
attribute: rssi
name: RSSI
```

![image](https://user-images.githubusercontent.com/24375847/102713389-367d3600-42c8-11eb-800c-c891627353a0.png)

And although not documented, you can also add an icon. Note however that the code editor switches to the code for the full card. 

![image](https://user-images.githubusercontent.com/24375847/102713411-5ad91280-42c8-11eb-8ff7-140ac6485ba3.png)

For graphs, you can use the template sensor. 

I'll propose I will write a faq for this, but we close this issue.

**Comment by Magalex2x14** [comment]
I agree 👍
