### ISSUE TITLE
BLE sensor updates

### ISSUE THREAD

**Issue by pravdik** [custom-components/ble_monitor#372]
After the last update LYWSDCGQ sensors send data only with the 'Discovery' option enabled. The 'Active Scan' useless too.

**Comment by Ernst79** [comment]
Can you show your configuration? Do you use YAML configuration or do you configure in the UI?

**Comment by pravdik** [comment]
from UI

**Comment by Ernst79** [comment]
I can confirm the issue, I'll fix it a.s.a.p. Please temporary keep Discovery enabled till it is fixed.

**Comment by pravdik** [comment]
Ok, thank you

**Comment by Ernst79** [comment]
The discovery option is fixed in 2.6.2. 

How about the active scan, what is the problem with active scan?

**Comment by pravdik** [comment]
> 
> 
> The discovery option is fixed in 2.6.2.
> 
> How about the active scan, what is the problem with active scan?

Now with 2.6.2 everything works fine. Thank you one more time.
