### ISSUE TITLE
Support for the TMALL Genie Chlorop Wireless Switch Button

### ISSUE THREAD

**Issue by toraidl** [custom-components/ble_monitor#378]
It is a very cheap advice( costs about $3) .
device description is avaialble here:https://www.aihome.com.my/product/tmall-genie-chlorop/)

I just wondering if it is possible to use ble_monitor.

Below is the log file, but I am not sure if it helps: 
[home-assistant.log](https://github.com/custom-components/ble_monitor/files/6565916/home-assistant.log)
around 16:03:15 I started a single click 
16:03:20 double click 
and 16:03:36 long click 
Besides, I find some development guides maybe related to this device 
https://www.aligenie.com/doc/357554/gtgprq
https://www.aligenie.com/doc/357554/hochaf

**Comment by Ernst79** [comment]
I will have a look, but I think this device needs an connection to be set up, if I understand the documentation. This is out of the scope of this Passive BLE monitor integration, as it listens passively only. 

But I will have a better look at your data later.

**Comment by Ernst79** [comment]
I have to close this request, this sensor needs a connection to be set up, which is out of the scope of BLE monitor, which only listens passively. I'm sorry.
