### ISSUE TITLE
change default name/entity_id

### ISSUE THREAD

**Issue by FrancYescO** [custom-components/ble_monitor#379]
Actually when you add a device with this components, it will pgenerate entities like `ble_` + property + name

My suggestions is just align the default behaviour to the majority of components in HA so use name + property

basically, for a sensor called "Pippo" instead of creating these entities:

ble motion Pippo - binary_sensor.ble_motion_pippo
ble button Pippo - sensor.ble_button_pippo
ble light Pippo - binary_sensor.ble_light_pippo
ble battery Pippo - binary_sensor.ble_battery_pippo

use these namings as default:

Pippo motion - binary_sensor.pippo_motion
Pippo button - sensor.pippo_button
Pippo light - binary_sensor.pippo_light
Pippo battery - binary_sensor.pippo_battery

**Comment by Ernst79** [comment]
Thanks for the suggestion. I have to think about this. I like the idea, but I have to see if it doesn't mess with the existing installations. I'm a bit afraid that it will generate new entities, leaving people with sensors and automations that don't work anymore. But I promise I will think this over coming days.

**Comment by FrancYescO** [comment]
Yep, thats true, my suggestion about this is to use a new flag that will keep the old naming (or enable the new naming) than start considering the old naming/entity_id deprecated until a "breaking version"

**Comment by andrewjswan** [comment]
> _sensor.ble_

By this prefix you can select the sensors of this integration, and this is very convenient in some moments.
Like: `devices: "{{ states.sensor | selectattr('entity_id', 'search', '^sensor.ble_') | selectattr('attributes.mac address', 'defined') | map(attribute='attributes.mac address') | unique | sort | join('') | replace(':', '') if is_state('binary_sensor.ble_gateway', 'on') }}"`

**Comment by Ernst79** [comment]
I have decided to not fix this issue. It's too much work to change and I don't see the real benefit of changing this. Sorry.
