### ISSUE TITLE
Air Box WP6003 support

### ISSUE THREAD

**Issue by RubenKelevra** [custom-components/ble_monitor#382]
Hey guys!

I was wondering if there's a chance to integrate the very cheap WP6003 Bluetooth Air Quality monitor? :)

There's a thread about it in the [community forum](https://community.home-assistant.io/t/air-box-wp6003/275115)

**Comment by Ernst79** [comment]
As far as I understand, this device needs a connection to be set up, which is out of the scope of this passive BLE component. But you can check by enabling the report_unknown: Other. This will create a log with all ble messages, so it would be helpfull if you can find the MAC address as well. This app might be useful for that https://play.google.com/store/apps/details?id=uk.co.alt236.btlescan

**Comment by RubenKelevra** [comment]
Does it make more sense to write down the communication with the device with the regular app? 🤔

I'm not sure what exactly the app does, since the device never appears as normal Bluetooth device in the device settings.

I was under the impression that this means it's a BLE device of some kind.

**Comment by Ernst79** [comment]
There are two types of BLE, 
1. one that just broadcasts data, which can be read by anyone, and 
2. one type that one broadcasts "I need a connection to be set up". 

The last one requires some ble data to be send to the device first, and when this is OK, it starts communicating back with the actual data, which can only be read by the device that has made the connection. 

BLE monitor listens to sensors that use type 1 communication. Type 2 isn't supported unfortunately. As far as I can see, your device uses type 2 BLE communication.

**Comment by Ernst79** [comment]
I'm closing this request. This sensor needs a connection to be set up, which is out of the scope of BLE monitor, which only listens passively. I'm sorry.
