### ISSUE TITLE
Xiaomi Soocas X3 Electric Toothbrush - Support

### ISSUE THREAD

**Issue by perseus177** [custom-components/ble_monitor#384]
**[Xiaomi Soocas X3 Electric Toothbrush - Support]**

sudo hcidump --raw hci > dump.txt
https://pastebin.ubuntu.com/p/sx2S6sD24K/

**Screenshots from Xiaomi App**
![Screenshot_20210601-153455_Mi Home](https://user-images.githubusercontent.com/25415840/120332599-33628900-c2ef-11eb-9a93-7640d91b842b.jpg)
![Screenshot_20210601-153503_Mi Home](https://user-images.githubusercontent.com/25415840/120332619-38273d00-c2ef-11eb-9271-7bf4c83e57ca.jpg)

**Comment by Ernst79** [comment]
I analyzed the data, but I think it requires a connection to be set up. All messages only show `0D` as payload, no idea what the meaning is of this number (0D = 13) (the PTH-3M is for comparison with another sensor). It also sends the name and an appearance message, which is usually a message saying that it needs a connection to be set up before it starts communicating. This is currently not possible in BLE monitor. 

---------------------------------------------------------------------------------------
Len  AD  Xiaomi Frame Product Frame ------MAC--------   -----PAYLOAD-------------  RSSI
     type  UUID   ctrl   ID    cnt                      
---------------------------------------------------------------------------------------
0F   16  95 FE  30 5A  11 07   01   AB 0B 0D 38 C1 A4   08 07 09 50 54 48 2D 33 4D  B2   PTH-3M
0F   16  95 FE  31 20  CE 00   00   AA ED 9A 2C 2B CC   0D                          AB   Toothbrush
Other data
02   01  06 (Flags: 06)
07   09  53 4D 49 2D 58 33 (name: SMI-X3)
03   19  00 00 (Appearance)

**Comment by Ernst79** [comment]
I'm closing this issue for now. Unfortunately it isn't possible to add the toothbrush, as it requires a connection to be set up, which is out of the scope of BLE monitor (only listens passively).
