### ISSUE TITLE
HA 2021.6.0 version key warning confusion

### ISSUE THREAD

**Issue by hugalafutro** [custom-components/ble_monitor#385]
Hi,
I just updated HA to 2021.6.0 (docker on rpi3) and now on startup I get this in HA log 
```
2021-06-02 23:22:12 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'mitemp_bt' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
```

But, the integration is loaded in Integrations screen and all the sensors are receiving data and showing in the dashboard.

**Comment by Ernst79** [comment]
mitemp_bt is the old name of the integration (for quite some time already). If you have upgraded to ble_monitor, you can delete the folder /config/custom_components/mitemp_bt (and all content). Also remove mitemp_bt from your configuration and make sure you have ble_monitor installed via HACS and configured in your configuration (either via the UI setup or in YAML)

**Comment by hugalafutro** [comment]
I've had the integration installed since long before it was renamed. Isn't there any easier way to convert the entities than redo the whole setup? I've got quite a few sensors and not really keen on digging up all the encryption keys and mac addresses.

If manually setting up from scratch is the only way feel free to close the issue.

**Comment by Ernst79** [comment]
Did you configure mitemp_bt in YAML is the past? If so, just follow these instructions to convert the YAML.

https://github.com/custom-components/ble_monitor/blob/master/update_instructions.md

if you used setting up in the UI, the easiest way is to enable HA debug logging of mitemp_bt. I think (not 100% sure) it will show your configuration in the log, including your encryption keys and Mac addresses.

**Comment by hugalafutro** [comment]
Indeed I previously configured in yaml, and then reconfigured in ui (via that same link), but apparently I must've missed up a step somewhere because it turns out I had both `mitemp_bt` and `ble_monitor` in `custom_components` although hacs only showed the new one. I could've sworn I uninstalled the old one when switching from yaml, but somehow it stayed behind.

 I just deleted the `mitemp_bt` directory in there and did nothing else, restarted ha container and it just works.

**Comment by Ernst79** [comment]
Good to hear. I've seen some more people with this issue. I think it's related to HACS, which didn't delete the old folder during the update. Not sure why, for most people it was deleted without any problems, but you're not the only one. But manually deleting is the solution in that case.
