### ISSUE TITLE
error in the update to 2021.6.2

### ISSUE THREAD

**Issue by xabaras75** [custom-components/ble_monitor#389]
Hi, before updating HA to version 2021.6.2 I have made a check with the addon "check home assistant configuration" and I received back this log:

![image](https://user-images.githubusercontent.com/64804254/120856512-4b047080-c580-11eb-943c-7cb616356409.png)

is there any problem if I finalize the update?
from the log it seems that the integration could not be found after update.

**Comment by Ernst79** [comment]
I’m not sure, what is this plants.yaml file? It isn’t part of ble_monitor.

**Comment by xabaras75** [comment]
> I’m not sure, what is this plants.yaml file? It isn’t part of ble_monitor.

It is a package containing miflora devices setup.

**Comment by Ernst79** [comment]
It looks more like an issue in the the package. I just tested ble monitor on 2021.6.2 and it is working fine.

**Comment by Ernst79** [comment]
I would just try to update, you can always go back to a previous version

**Comment by xabaras75** [comment]
Hi, I just finished the update and I had no problem on ble monitor side. I had more problem on other integration :). Many this
