### ISSUE TITLE
Repeated operation of YEELIGHT dimmer (YLKG07YL, YLKG08YL)

### ISSUE THREAD

**Issue by sirarikako** [custom-components/ble_monitor#391]
When repeating operations, such as clicking, clicking again after a while, but always keep "short press 1 x" on the sensor, so the second click cannot trigger automation. Hopefully, like the "Yeelight Smart Wireless Switch", it will return to the "no press" state 1 second after the trigger. Thank you.

**Comment by Ernst79** [comment]
That should be possible to add. I´m currently in the process of rewriting sensor.py, will add it afterwards.

**Comment by sirarikako** [comment]
> That should be possible to add. I´m currently in the process of rewriting sensor.py, will add it afterwards.

Thank you.

**Comment by Ernst79** [comment]
I will keep the issue open till it is finished, as a reminder.

**Comment by Ernst79** [comment]
Added in 2.9.1-beta. 

I use the `reset_timer` option to set the number of seconds before it returns to `no press`. I also added this to the Yeelight Smart Switch, so in stead of a fixed value of 1 seconds, it can now be set to anything you want, or even turned off (`reset_timer = 0`). 
Note that the default value is 35 seconds of this option, it is advised to change this to e.g. 1 second. The default comes from the motion sensors, so I won't change the default value. 

Could you give it a try? 

Note that 2.9.0-beta also had some significant changes internally.

**Comment by sirarikako** [comment]
> Added in 2.9.1-beta.
> 
> I use the `reset_timer` option to set the number of seconds before it returns to `no press`. I also added this to the Yeelight Smart Switch, so in stead of a fixed value of 1 seconds, it can now be set to anything you want, or even turned off (`reset_timer = 0`).
> Note that the default value is 35 seconds of this option, it is advised to change this to e.g. 1 second. The default comes from the motion sensors, so I won't change the default value.
> 
> Could you give it a try?
> 
> Note that 2.9.0-beta also had some significant changes internally.


I tried 2.9.1-beta, and it can return to "no press" after 1 second regardless of clicking, double-clicking, or rotating.
Thank you.

Now the ble device only uses a dimmer, so the 2.9.0 change will not affect me. Thanks for reminding.

**Comment by Ernst79** [comment]
3.0.0 has been released as final version
