### ISSUE TITLE
Repeated operation of Yeelight Remote Control (YLYK01YL)

### ISSUE THREAD

**Issue by E-Sergey** [custom-components/ble_monitor#395]
When repeating operations, such as clicking, clicking again after a while, but always keep "short press 1 x" on the sensor, so the second click cannot trigger automation. Hopefully, like the "Yeelight Smart Wireless Switch", it will return to the "no press" state 1 second after the trigger. 
I use the reset_timer option to set the number of seconds before it returns to no press, but this option does not work with Yeelight Remote Control (YLYK01YL). 
However the same option works well with dimmers YLKG07YL, YLKG08YL.
Thank you.

**Comment by Ernst79** [comment]
I was already expecting this request. But the YLYK01YL has an on and off button, so I thought that it was of less use. You normally won't press on, if it is already on. 

On the other hand, adding it will give the user flexibility, you can always turn it off by setting it to `reset_timer: 0`.

**Comment by Ernst79** [comment]
Please try with 3.2.1-beta. Should be added.

**Comment by Ernst79** [comment]
3.2.1 has been released, which adds this feature.
