### ISSUE TITLE
Add Support for Xiaomi Kettle PRO

### ISSUE THREAD

**Issue by ManuBoss55** [custom-components/ble_monitor#398]
Hi,

I've been using your integration for a long time, could you add support to the Kettle Pro Version (the Xiaomi kettle with the display)?

![5b30f99a-7951-41c4-a628-2f63c55d4e6c](https://user-images.githubusercontent.com/51408103/121329626-aaaea300-c915-11eb-8a5b-34ab65c7d04d.jpg)

**Comment by Ernst79** [comment]
Sure, we can try. But we need some data from you. Can you enable the option `report_unknown` (set it to `Xiaomi`) in the options of BLE monitor and enable debug logging at info level, by putting the following in your configuration.yaml

```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: info
```

After a restart, you should (hopefully) get log messages in the Home Assistant Log (Configuration --> Logs --> Load Full Home Assistant Log). Please post a your log here (or attach it in a file).

**Comment by ManuBoss55** [comment]
Hi, 

This morning I did a series of tests and I brought you the use cases with the corresponding generated log file. If you need other tests, just ask me.
(The kettle is the one that ends with E5: 77)


Use Case:
`

1. After the HA reboot, the kettle is not connected to the base, so as a first action I connect the kettle;
2. After 3 minutes I press the "Warm" button (the temperature is set to 90°C) the kettle starts heating up to the level and indicates it with an acoustic signal;
3. After 2 minutes I press "Warm" again, so the kettle stops holding the temperature and cool down;
4. After 2 min I press the "Boil" button and wait for the temperature to reach 100°C, after boil, the kettle automatically switches to "Warm" 90°C mode;
5. After 2 minutes I open the Mi Home app and set 40°C (the kettle was too hot, so it just needs to cool down);
6. After 2 minutes I open the Mi Home app and set 50°C (the kettle was too hot, so it just needs to cool down);
7. After 2 minutes I open the Mi Home app and set 70°C (the kettle was too hot, so it just needs to cool down);
8. After 2 minutes I open the Mi Home app and set 80°C (the kettle was too hot, so it just needs to cool down);
9. After 2 minutes I open the Mi Home app and set 90°C (the kettle had dropped to 84°C, so it starts heating up to 90°C);
10. After 1 minute, I remove the kettle from the base and I save the log.


`

[xiaomi.log](https://github.com/custom-components/ble_monitor/files/6629707/xiaomi.log)

**Comment by Ernst79** [comment]
Hmm, the log shows only messages without data (all messages only show 01 00 at the end). Two questions:
- did you add it to MiHome? This is sometimes needed to make it start sending data. 
- Is it possible to create a HCIDUMP? this is not easily possible on Home Assistant OS though. You can make a HCIdump with the following command on most systems (except Home Assistant OS).  

```
sudo hcidump --raw hci > dump.txt
```

- A third option we could try is to just assume that it is behavior the same as the other Kettles.

In /ble_monitor/ble_parser/xiaomi.py, there is a list will codes in the beginning. Look for the `YM-K150EU` and change the 4 numbers from `0x0113` to `0x05D9`. Leave the name the same for now. 

So, change:

`    0x0113: "YM-K1501EU",`

to 
  
`    0x05D9: "YM-K1501EU",`

and restart

**Comment by ManuBoss55** [comment]
1. I confirm that I added it to the MiHome app, in fact I took the Kettle's BLE Key from the Xiaomi Cloud
2. I should find a workaround since I use Home Assistant OS
3. I have integrated the change of the line code as indicated by you, in the logs there are no longer the report_unknown but in any case the device is not added to the integration

**Comment by Ernst79** [comment]
About point 3, too bad, it was worth to try. 

About point 1, I will need the key later, but lets first try to see if we can find useful data.

About point 2. No problem, there is a workaround :-).

What you can do is past the following line into `/custom_components/ble_monitor/ble_parser/xiaomi.py`. 

Look for the following line (around line 339): 

```
def parse_xiaomi(self, data, source_mac, rssi):
```

and add the 2nd line

```
def parse_xiaomi(self, data, source_mac, rssi):
    _LOGGER.error("Data: %s", data.hex())
```

Next, do a restart, it will log every BLE message that will follow the Xiaomi format, also the ones that were ignored with report_unknown.

**Comment by ManuBoss55** [comment]
I tried as you indicated (I only added the mac to the string so as not to confuse it with other devices) but the data read is always of the type: `Data: 111695fe3058d9050177e58038c1a4280100`

[xiaomi.log](https://github.com/custom-components/ble_monitor/files/6636753/xiaomi.log)

**Comment by Ernst79** [comment]
Hmm, that means that this is the only message that is send in the MiBeacon format.

I would like to do one last attempt,

in `/ble_monitor/ble_parser/__init__.py`, all BLE message will pass by, without any filtering. 

On line 15, please add the following two lines. (btw you can turn of report_unknown option, its not needed).
I copied the MAC part right to the beginning, such that no filtering it applied at all. 

```python
def ble_parser(self, data):
    # MAC address
    mac = (data[8 if is_ext_packet else 7:14 if is_ext_packet else 13])[::-1]
    _LOGGER.error("MAC: %s, Data: %s", mac.hex(), data.hex())
```

this will generate a lot of lines in the log, but we can filter on the MAC later. don't keep it running too long, as it will fill your log quite fast, I think. But make sure you use the kettle while collecting data.

**Comment by ManuBoss55** [comment]
Hi, 

sorry for the absence, I've been very busy. 

I attach the log file (with an "if" in the code, I made sure that it only printed the kettle mac).

[xiaomi.log](https://github.com/custom-components/ble_monitor/files/6669334/xiaomi.log)

**Comment by Ernst79** [comment]
Unfortunately still only a message with a name and a message with no data (01 00). I think this kettle needs a connection to be set up, which is not supported by BLE monitor (it is only passively listening to BLE). So, this means that this kettle can't be added to BLE monitor unfortunately. I'm closing this issue therefore, feel free to reopen if you have other data that shows something different than 0100 at the two bytes just before the last byte.

**Comment by tismofied** [comment]
Sorry if this is not approved to piggyback on someone else's post but is the decision of incompatibility still true for Govee electric kettle H7170?

**Comment by Ernst79** [comment]
The Govee kettle is a different device, so we might be able to add that. Please check the documentation how to collect the data for a new device and post it in a new issue. Also turn on active scan, as Govee sensors require active scan to be enabled.

**Comment by tismofied** [comment]
> The Govee kettle is a different device, so we might be able to add that. Please check the documentation how to collect the data for a new device and post it in a new issue. Also turn on active scan, as Govee sensors require active scan to be enabled.
> 
> https://custom-components.github.io/ble_monitor/sensor_request

the only way it showed up was on the android app, but I couldn't connect it. I am not very good at this so hopefully someone more knowledgeable with the same device could get the details needed to integrate the Govee kettle.

**Comment by ayed3** [comment]
what about the newer version with screen and Wifi support, xiaomi kittle pro 2, the Xiaomi integration dose not have this version on the devices list

**Comment by devnoname120** [comment]
@ayed3 Where do you see a Xiaomi Kettle Pro 2? I only see a Xiaomi Kettle 2 model and it's not a smart device.

**Comment by asruda** [comment]
@ManuBoss55  I know this is years later. I put together a solution for this `Xiaomi Smart Kettle Pro`. So here's the link for anyone who might still need it – https://github.com/asruda/mi_kettle_pro
