### ISSUE TITLE
Add Support for Roidmi Nex 2 Pro

### ISSUE THREAD

**Issue by ManuBoss55** [custom-components/ble_monitor#399]
Dear Ernst Klamer,

since I'm really appreciating your work and your availability, I take this opportunity to make a new integration request: **Roidmi vacuum cleaner**. 
I have the **Nex 2 Pro model** that you can see in the picture. It communicates the status of sensors via BLE to the Roidmi app.

![Immagine](https://user-images.githubusercontent.com/51408103/121501769-d007e380-c9df-11eb-94ba-17e68c29b74d.png)

**Comment by Ernst79** [comment]
Hi again, 

We can try, but I don't know if it is using Xiaomi Mibeacon format or some other own Roidmi format. Therefore, you could first try to create a log with report_unkown: Xiaomi, like you did for the kettle. It would be convenient if you know the MAC address. If you can't find anything with this setting, use report_unkown: "Other". In that case it becomes even more important to know the MAC address, at it will log all messages (also from phones, PC's etc etc.).

**Comment by ManuBoss55** [comment]
I get something similar to what we saw for the Kettle Pro: 
`from UNKNOWN Xiaomi device: RSSI: -79, MAC: A4: C1: 38: 02: 4F: 0E, ADV: 111695fe305a6108010e4f0238c1a4280100`

**Comment by Ernst79** [comment]
See my comment for the Kettle pro, same 0100 data. I will check the log with the method explained for the Kettle, if you send it.

**Comment by Ernst79** [comment]
Unfortunately, the same conclusion for this device as for the Kettle pro, it requires a connection to be set up, which is not supported by BLE monotor (due to its passive nature). I'm closing this request, if you find other data, your free to reopen this issue of course.

**Comment by pskowronek** [comment]
@Ernst79 what this adv data: "0x0201060502F5FED0FF0F1695FE3120CC0901A87DBE8CCF04091509524F49444D492046382050726F2056616375756D" - it's been sniffed from Roidmi F9 vacuum cleaner.
