### ISSUE TITLE
statistics.StatisticsError: no median for empty data

### ISSUE THREAD

**Issue by hung2kgithub** [custom-components/ble_monitor#402]
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/ble_monitor/sensor.py:402
Integration: Passive BLE monitor (documentation, issues)
First occurred: 4:35:38 PM (122 occurrences)
Last logged: 5:42:39 PM

Update for sensor.ble_temperature_xiaomi_kettle fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 558, in async_device_update
    raise exc
  File "/config/custom_components/ble_monitor/sensor.py", line 402, in async_update
    state_median = round(sts.median(measurements), rdecimals)
  File "/usr/local/lib/python3.8/statistics.py", line 430, in median
    raise StatisticsError("no median for empty data")
statistics.StatisticsError: no median for empty data

HA Version : core-2021.6.2
Sensor : YM-K1501 Xiaomi Mijia Smart kettle

Try to use `use_median: True`  at device level still got this error since version 3.0

**Comment by Ernst79** [comment]
Hi, this issue has been fixed in 3.2.1-beta.

**Comment by hung2kgithub** [comment]
I will wait for latest release, thanks for quick reply and hard working.

**Comment by Ernst79** [comment]
It has just been released. Feel free to reopen the issue if the issue returns.
