### ISSUE TITLE
No BLE devices seen or data received until 'hcitool lescan' run

### ISSUE THREAD

**Issue by Nick-Innes** [custom-components/ble_monitor#406]
Hi,

I foolishly did a bunch of updates all at once and I'm not quite sure what's broken, but previously this system was working fine.

I'm running Ubuntu 18.04 on a NUC, and Home Assistant Container on top of this.

I updated OS, Home Assistant to 2021.6.4, Supervisor to 2021.6.0 with no issues elsewhere, but I started to see issues with the older mitemp_bt integration, I'm afraid I forget the precise message or version). I moved to the latest version (3.1.1 I believe) deployed through HACS, deleting the old mitemp_bt folder below custom_components. 

I'm now seeing these messages logged:-
```
2021-06-15 15:24:55 DEBUG (Thread-22) [custom_components.ble_monitor] HCIdump thread: start main event_loop
2021-06-15 15:25:53 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
2021-06-15 15:25:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 11 measuring device(s).
2021-06-15 15:25:55 DEBUG (Thread-22) [custom_components.ble_monitor] HCIdump thread: main event_loop stopped, finishing
2021-06-15 15:25:55 DEBUG (Thread-22) [custom_components.ble_monitor] HCIdump thread: Scanning will be restarted
2021-06-15 15:25:55 DEBUG (Thread-22) [custom_components.ble_monitor] 2 HCI events processed for previous period.
2021-06-15 15:25:55 DEBUG (Thread-22) [custom_components.ble_monitor] HCIdump thread: Run
2021-06-15 15:25:55 DEBUG (Thread-22) [custom_components.ble_monitor] HCIdump thread: connected to hci0
2021-06-15 15:25:55 DEBUG (Thread-22) [custom_components.ble_monitor] HCIdump thread: start main event_loop
```
Yet when I run `hcitool lescan` on the host OS the log suddenly becomes alive and I see values for all the sensors, but this peters out almost immediately, but returns repeatably with repeated runs. This behaviour seems consistent across reboots, and I'm somewhat at a loss to explain what's happening and haven't had any further inspiration!

Many thanks,

Nick

**Comment by Ernst79** [comment]
I think your docker container doesn't have access to the Bluetooth of the Ubuntu system anymore. 

https://stackoverflow.com/questions/28868393/accessing-bluetooth-dongle-from-inside-docker

**Comment by Nick-Innes** [comment]
Thanks for your prompt reply (and the terrifically useful integration), I've not disappeared, but I've not yet had an opportunity to look properly - I will at the weekend.

N

**Comment by Ernst79** [comment]
Any update on this issue?

**Comment by Nick-Innes** [comment]
Hi Ernst,

Apologies for the slow reply. Neither weekend were quite what I expected.

I'm pretty confident "`--net=host`" is being used - I'm seeing 
```
"NetworkSettings": {
 :
            "Networks": {
                "host": {
```
when I inspect the homeassistant container. When I run bash in the container and "`hcitool lescan`", it works fine and I see sensor readings in the log.

I'm doing a little more testing this afternoon.

Nick

**Comment by Nick-Innes** [comment]
Hi Ernst,

I'm afraid I've no further insight into what's going on or causes the issue. I'm wondering about migrating to a more traditional install, as I've not used the Ubuntu host for anything (the things I wanted to do on the native OS are easily done in Home Assistant now and I believe it supports NVME which it didn't when I built the box). This will very likely make everything more reproduceable and that's worth a lot.

I'll back up the current build and then look to rebuild it. If there's anything you'd like to see then give me a shout - I likely won't get an opportunity until this weekend at the earliest.

Thanks again for all your help,

Nick

**Comment by Ernst79** [comment]
Hopefully better luck after the rebuild. Bluetooth can be a PITA. I had all sorts of trouble with rasbian, while Raspberry OS was working fine. Never have been able to figure out why. Not very helpful for you though, hopefully your new built will work better.

**Comment by Nick-Innes** [comment]
Hi Ernst,

Worked perfectly after the rebuild - definitely not a bug with ble_monitor.

Amazed by how well the builtin backup/recovery stuff worked - anticipated a fight and there wasn't one.

Restored the backup and all the sensors came back to life (albeit with different names)!

Thanks for your support and patience - is there a way to bin this non-issue as I'm not sure it has anything of utility to the community, other than reassurance that a backup, rebuild and restore isn't as traumatising as it could be?

Nick

**Comment by Ernst79** [comment]
You're welcome. I just close the issue normally. No idea we can bin it, but don't think that is necessary.
