### ISSUE TITLE
Strange battery level for MJYD02YL

### ISSUE THREAD

**Issue by andrewjswan** [custom-components/ble_monitor#408]
In all sensors for MJYD02YL i see 10% but in battery sensor 9%
9%
![image](https://user-images.githubusercontent.com/3609660/122094487-e7e2cb80-ce14-11eb-81aa-569697bc2cf1.png)
10%
![image](https://user-images.githubusercontent.com/3609660/122094557-fc26c880-ce14-11eb-8ca2-03144797f336.png)
![image](https://user-images.githubusercontent.com/3609660/122094640-0d6fd500-ce15-11eb-9047-42d261d5f466.png)
It's been like that for three days now...

**Comment by Ernst79** [comment]
Hmmm, that's rather strange. I'll look into it, but don't have a clue yet where to look. I guess it is something in the binary sensor part of BLE monitor. Anyway, I will try to figure out what is going on.

**Comment by andrewjswan** [comment]
Maybe different round options? 9.5 -> 9 or 9.5 -> 10 ?

**Comment by andrewjswan** [comment]
Now in all binary sensors i have 10% but in battery sensor i have 3% ... :(

**Comment by andrewjswan** [comment]
![image](https://user-images.githubusercontent.com/3609660/123681739-d78a1200-d852-11eb-8361-7b2f5d0fb93d.png)

**Comment by Ernst79** [comment]
Are these all MJYD02YL, or do you see the same in other sensors?

**Comment by andrewjswan** [comment]
Only for MJYD02YL

пн, 28 июн. 2021 г., 22:30 Ernst Klamer ***@***.***>:

**Comment by Ernst79** [comment]
Do you have other **binary** sensors?

**Comment by andrewjswan** [comment]
Yes, MCCGQ02HL, but now on this sensors i have 100% for battery ...

пн, 28 июн. 2021 г., 23:39 Ernst Klamer ***@***.***>:

**Comment by Ernst79** [comment]
I finally found the issue, will fix it as soon as possible.

**Comment by Ernst79** [comment]
Should be fixed in 3.5.0-beta. Can you try?

**Comment by andrewjswan** [comment]
Look like all work fine for me :) Thanks.

вт, 29 июн. 2021 г., 17:26 Ernst Klamer ***@***.***>:
