### ISSUE TITLE
Ruuvitag sensors - Testers wanted

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#410]
In 3.3.1-beta, support for Ruuvitag sensors is added. I'm looking for someone who can test that it is all working

Especially the motion sensor might not work as expected. To explain, the sensor is now reporting motion detected when the motion counter has changed, if it doesn't change it will report motion clear. I'm not sure how fast the sensor will report motion clear, this all depends on the update interval. 

So, if you have this sensor and want to do some testing, it would be appreciated.

**Comment by Kaibob2** [comment]
Hi Ernst,
there seems to be a problem with the Influxdb addon which (apparently) appears after uprading the ble_monitor. I just wanted you to be aware of this. I'm affected, too. Influxdb stopped working when HA came back up after installing ble_monitor 3.3.3 (could also be 3.3.1-beta)
I have no idea if it's coincidence or a problem with your integration.
See https://github.com/home-assistant/core/issues/51956

**Comment by Ernst79** [comment]
Thanks, I’ve responded in the other topic. I do not really understand how it can be related.

**Comment by Kaibob2** [comment]
Me neither, but my coding skills are much more limited than yours ;)

**Comment by Ernst79** [comment]
3.4.0-beta has been released with a new parser for Ruuvitag sensors, which should not have the Influxdb issue anymore. 

Please let me know if this version is working, if one of you have this sensor.

**Comment by rkallensee** [comment]
I updated to 3.4.0-beta and added my two Ruuvitag sensors (they are reporting with v5 format) but no devices/entities are being created in Home Assistant. The Ruuvitag sensors work fine (I am receiving data with the "RuuviTag Discovery" add-on) and I am using ble_monitor with some Xiaomi temperature sensors since quite some time, just the Ruuvitag sensors are not working yet.

**Comment by Ernst79** [comment]
@rkallensee Thanks for taking the time to test. 

I hope you are willing to help. Could you enable debug logging at info level by putting this in your configuration.yaml. 

```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: info
```

and enable  `report_unknown: "Ruuvitag"` (either in YAML or in the options menu of the BLE monitor integration). After a restart, have a look in your HA logs by "load full Home Assistant Log". If nothing shows up, try again with `report_unknown: "Other"`

Another, perhaps easier, option is to make a hcidump with the following command. 

`sudo hcidump --raw hci > dump.txt`

But this doesn't work on Home Assistant OS.

**Comment by rkallensee** [comment]
Here are two advertisements each from both of my sensors in the log:
```
2021-06-24 17:18:26 INFO (MainThread) [custom_components.ble_monitor] Attention! Option report_unknown is enabled for Ruuvitag sensors, be ready for a huge output...
2021-06-24 17:18:29 INFO (Thread-17) [custom_components.ble_monitor.ble_parser.ruuvitag] BLE ADV from UNKNOWN Ruuvitag DEVICE: RSSI: -86, MAC: EE:43:F4:8D:E9:55, ADV: 043e2b0201030155e98df443ee1f0201061bff9904050f368007c60cfdacfcc0ffe4a8760fcf62ee43f48de955aa
2021-06-24 17:18:35 INFO (Thread-17) [custom_components.ble_monitor.ble_parser.ruuvitag] BLE ADV from UNKNOWN Ruuvitag DEVICE: RSSI: -81, MAC: E9:BD:3B:4F:8D:0A, ADV: 043e2b020103010a8d4f3bbde91f0201061bff9904050e067848c5fffd6000e8fd3cac36985353e9bd3b4f8d0aaf
2021-06-24 17:19:10 INFO (Thread-17) [custom_components.ble_monitor.ble_parser.ruuvitag] BLE ADV from UNKNOWN Ruuvitag DEVICE: RSSI: -86, MAC: EE:43:F4:8D:E9:55, ADV: 043e2b0201030155e98df443ee1f0201061bff9904050f36802bc60afda8fcc4ffe8a7b60fcf82ee43f48de955aa
2021-06-24 17:19:27 INFO (Thread-17) [custom_components.ble_monitor.ble_parser.ruuvitag] BLE ADV from UNKNOWN Ruuvitag DEVICE: RSSI: -79, MAC: E9:BD:3B:4F:8D:0A, ADV: 043e2b020103010a8d4f3bbde91f0201061bff9904050e067881c601fd6000e8fd34acf698535be9bd3b4f8d0ab1
```

**Comment by Ernst79** [comment]
Thanks, the parser on my local PC works fine for this advertisement. 

result  {'mac': 'EE43F48DE955', 'type': 'Ruuvitag', 'rssi': -86, 'data': True, 'temperature': 19.47, 'humidity': 81.94, 'pressure': 1007.0, 'acceleration': 1023.8281105732544, 'acceleration x': -596, 'acceleration y': -832, 'acceleration z': -28, 'voltage': 2.947, 'tx power': 4, 'motion': 0, 'motion timer': 0, 'packet': 53090, 'firmware': 'Ruuvitag V5', 'battery': 94.7}

I will check if I made some other mistake somewhere.

**Comment by rkallensee** [comment]
No, only these lines, no errors.

**Comment by Ernst79** [comment]
These lines are ok, but they should not have gotten to the point "report_unknown". 

Can you try to comment out (with a #) the following lines in /custom_components/ble_monitor/ble_parser/ruuvitag.py (from line 103). I think it fails on that part. 

```python
                # Check for duplicate messages
                try:
                    prev_packet = self.lpacket_ids[ruuvitag_mac]
                except KeyError:
                    # start with empty first packet
                    prev_packet = None
                if prev_packet == packet_id:
                    # only process new messages
                    return None
                self.lpacket_ids[ruuvitag_mac] = packet_id
                if prev_packet is None:
                    # ignore first message after a restart
                    return None
```

**Comment by rkallensee** [comment]
Commenting out these lines didn't change anything. Logging a bit in the parser, I found out that `adstuct_type` is `62`, which I think doesn't match with any of the two outer conditions for the versions.

**Comment by Ernst79** [comment]
Where do you see 62? In init.py (and in ruuvitag.py again) it is filtered based on 0xFF, and than of comp_id 0x0499 and then it gets the version.  So it is looking for ff990405, which is in your advertisement.

**Comment by rkallensee** [comment]
I was logging the value of `adstruct_type` in `ruuvitag.py` (L20) after I noticed that it doesn't enter any of both conditions checking for version 3/5 or 2/4 right after.

```
if adstuct_type == 0x16:
    # ...
elif adstuct_type == 0xFF:
    # ...
else:
    # this is what happens
    result = None
```

**Comment by Ernst79** [comment]
Ah, thanks. You gave enough hints 😄 

In the previous version I had the full data passed in, but I should have passed adstruct

On line 78 in `__init__.py`, change `data` to `adstruct`

```
                    return parse_ruuvitag(self, adstruct, mac, rssi)
```

**Comment by Ernst79** [comment]
3.4.3-beta is released, should fix the issue (also for V2/V4). 

Please let me know if it all works after the update and thanks for the help.

**Comment by rkallensee** [comment]
The Ruuvitag devices now show up with their sensor entities, but now I see this error causing the integration to crash:

```
Traceback (most recent call last):
File "/config/custom_components/ble_monitor/sensor.py", line 189, in async_run
entity.collect(data, batt_attr)
File "/config/custom_components/ble_monitor/sensor.py", line 781, in collect
self._device_state_attributes["acceleration x"] = data["acceleration_x"]
KeyError: 'acceleration_x'
```

**Comment by Ernst79** [comment]
Remove the underscore _ in front of the x in `sensor.py`. Also for y and z. Line 781

Thanks again for testing, it is a bit hard to do it without having the actual sensor.

**Comment by rkallensee** [comment]
Works like a charm. Thank you so much for adding support for Ruuvitag sensors!

**Comment by Ernst79** [comment]
3.4.4 has been released as final.
