### ISSUE TITLE
InfluxDB problems after updating BLE monitor

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#411]
Having InfluxDB issues after installing 3.3.2 or 3.3.3. Please read carefully. If you have this error
`influxdb - cannot import name 'operators' from 'rx' (/usr/local/lib/python3.8/site-packages/rx/__init__.py)`

this is the solution. 
- Update to 3.3.4 first. 
- Next go to your docker environment (e.g. in portainer), 
- open the homeassistant container, 
- open a console and run the following commands

```
pip3 uninstall ruuvitag_sensor
pip3 install rx==3.2.0
```

This should fix InfluxDB, 

Ruuvitag support has been removed temporary, will be added later. Sorry for the inconvenience.

**Comment by Herus16** [comment]
how to fix with hassio (VM)?

**Comment by markusg1234** [comment]
Tried the solution but it didn't work on raspberry pi operating system type install.
followed the solution using home assistant command line.

1) Updated to 3.3.4
2) opened a terminal session.
3) pip uninstall ruuvitag_sensor
message saying skipping ruuvitag-sensor as it is not installed.

4) pip3 install rx==3.2.0
Successfully installed rx-3.2.0

5) Reboot host

Didn't fix issue and still get error when validating config unless I remove Influx from configuration.yaml

Component error: influxdb - cannot import name 'operators' from 'rx' (/usr/local/lib/python3.8/site-packages/rx/__init__.py)

Also if I reboot the host I can again install rx==3.2.0 as it doesn't say that it is already satisfied.

Any ideas?

**Comment by markusg1234** [comment]
One thing I have noticed is that when rebooting the host, rx--3.2.0 is then for some reason uninstalled as seen with a pip3 list.

If I install rx==3.2.0 again I then can see it with pip3 list, but if I then reboot the host it then isn't again listed anymore.

**Comment by Ernst79** [comment]
@markusg1234 what kind of installation do you have, venv, supervised, core?

**Comment by Ernst79** [comment]
@Herus16 , @markusg1234 you might also be able to update rx by adding it in custom_components/ble_monitor/manifest.json

add a line at the requirements, like this.

  "requirements": [
      "pycryptodomex>=3.10.1",
      "janus>=0.6.1",
      "aioblescan>=0.2.8",
      "rx>=3.2.0"
  ],

**Comment by markusg1234** [comment]
Running OS supervised.

Thankyou, followed your instructions and is all working now. 

Looks like rx is also hidden after reboot as it isn't listed with a pip3 list.

I assume putting it temporarily in the requirements gave it higher privilege's.  

Regards,
Markus

**Comment by Ernst79** [comment]
Glad it worked. Putting it in the requirements will make sure it is installed in the right place for Home Assistant, independent if the type of installation, with the correct rights.

**Comment by dennis3484** [comment]
I was a bit confused how to fix this after reading the comments, so here's what I did on a Supervised Raspberry Pi OS installation. Maybe it's helpful for others…

1. Edit `/root/config/custom_components/ble_monitor/manifest.json`
2. Add `"rx>=3.2.0"` to the `"requirements"` section (don't forget the add the comma after `"aioblescan>=0.2.8"`):
```
  "requirements": [
      "pycryptodomex>=3.10.1",
      "janus>=0.6.1",
      "aioblescan>=0.2.8",
      "rx>=3.2.0"
  ],
```
3. Install 'rx': `pip3 install rx==3.2.0`
4. Reboot host. (I did this in the Web UI under 'Supervisor -> System > **Reboot Host**'.)
5. The InfluxDB error was gone after the reboot…
6. Edit `/root/config/custom_components/ble_monitor/manifest.json` again and remove what was added in step 2.

**Comment by Ernst79** [comment]
Thanks. 

Step 3 won’t be needed, after a restart HA will check the requirements and will install rx automatically. 

Step 3 is actually an alternative way to update rx, but you have to do this in the correct environment (the environment that HA is using). And this depends on the type of installation (docker, supervised, HAos, etc). Your instruction will automatically take care of installing rx in the right environment.

**Comment by apeeters** [comment]
Small remark, use `==` instead of `>=` in the `rx` dependency, otherwise another error is showing up.

**Comment by Ernst79** [comment]
Thanks, I've updated the instructions in the posts above.
