### ISSUE TITLE
YEELIGHT dimmer (YLKG07YL, YLKG08YL) states

### ISSUE THREAD

**Issue by pewu78** [custom-components/ble_monitor#416]
Is it possible to change state to simple enumeration of possible states without any additional strings and values, and value to integer also without any additional string additions? I understand these are good for reading, but HA is about automation and having to regexp the values out of strings for that purpose is not good...

**Comment by Magalex2x14** [comment]
@Ernst79 , just a thought that pops into my mind from time to time - it seems to me that firing the corresponding HA events (instead of or in addition to the sensor state change) could be a good solution for "event-capturing" devices.

**Comment by Ernst79** [comment]
@Magalex2x14 What do you exactly mean by “firing the corresponding HA state”?

@pewu78 we can add a (integer) value as sensor attribute, but what does it need to represent? I can understand the number of step would make sense, but what else do you need?

**Comment by Magalex2x14** [comment]
@Ernst79 i mean [HA events](https://developers.home-assistant.io/docs/dev_101_events/#firing-events)
It is convenient to catch them in automations (event trigger), and it seems to me that waiting for an event in automation can load the system less than monitoring a state change (I don’t know for sure, perhaps a sensor state change in the HA core passes as an event). In any case, it seems to me, that this approach eliminates the need to check "how exactly the state has changed" (regex and etc.)

**Comment by Ernst79** [comment]
Ah, ok. So, something like:

`hass.bus.fire("ble_monitor_rotate_dimmer", {"steps": 20})`

but than you will also need an event that gives the direction and press type as well

`hass.bus.fire("ble_monitor_rotate_dimmer", {"direction": “right”})`
`hass.bus.fire("ble_monitor_rotate_dimmer", {"press type": “long press”})`

Not sure how this is different compared to a trigger on a state change, but it looks interesting.

anyway, I think I also need to remove the steps string from the dimmer attribute, it is now `dimmer = str(value) + " step(s)"` Better to return an integer and e.g. only add this in the sensor State where I combine it with the direction and type of press.

**Comment by Magalex2x14** [comment]
I did not dive into the details of the dimmers, perhaps in this case it is really difficult to apply events (if the direction and number of steps comes in different BLE messages). But I think that this approach can be useful in other sensors (binary, such as a motion event, leak event, an open / close event, and similar). Sorry for the little offtopic...

**Comment by pewu78** [comment]
@Magalex2x14 I guess you could create custom event in this integration and pass in it all the needed data (like hass.bus.fire("ble_monitor_rotate_dimmer", {"direction": “right”, "steps": 20}) and then have event-based trigger in automation handling it. This is system-wide however - not sure if that's required. There is also option to have [device trigger](https://developers.home-assistant.io/docs/device_automation_trigger) set up and then used as a trigger in automation - maybe that would be better approach.
@Ernst79 Like you mentioned an attribute with integer value representing number of presses or rotation steps is needed, along with information contained currently in 'Last type of press' attribute (type of action - press, rotate left, rotate right, rotate left pressed, rotate right pressed).

**Comment by Ernst79** [comment]
I now have made this, it this enough information? 

![image](https://user-images.githubusercontent.com/24375847/123165822-fbc1a980-d474-11eb-92f0-a62d7ede8853.png)

**Comment by pewu78** [comment]
Assuming the _state_ stays descriptive as it currently is (i.e. contains the type of operation and value) and both _Dimmer value_ and _Last type of press_ are updated at the same time with it (as it is now) we can use the state trigger to watch for **any** change of state and then make conditions / actions accordingly to the values of these two attributes.
**Any** change is needed for subsequent actions like rotations, where state does not return to _no press_ **but** for example it won't detect subsequent rotations of the same step value, as the state won't change. The ideal solution is to implement device trigger or event trigger as suggested which would send all events as they occur, the quick hack / workaround would be to include packet id in state.
Thanks!

**Comment by Ernst79** [comment]
I will look into the event trigger / device trigger later. 

For now, can't you make an automation that acts on a packet id update change. If the packet ID changes, do something with "last type of press" and "Dimmer value". packet ID won't change on "no press", as "no press" is only "send" by HA / BLE monitor itself, not by the dimmer (it's triggered by the reset_timer option).

**Comment by pewu78** [comment]
That's probably doable, but still more complex then normally should be. Need to store last used packet ID for comparison. Would need to use **numeric state trigger** together with **number helper** (input_number). Compare if current packet ID is greater than stored in input_number, if so proceed and add additional action to set input_number to current value. What about restarts - are packet ID's preserved (ever growing)?

 to save packet ID and compare if current is greater

**Comment by Ernst79** [comment]
Yes, clear. I'll look into implementing firing an event, as explained by @Magalex2x14.

**Comment by Ernst79** [comment]
Sorry for taking so long. I wonder if this still is an issue? I tried it myself by creating an automation that on every state update (trigger), even if the value is exactly the same, update a counter by 1 (action). This works fine. I use a battery sensor as dummy sensor, as the battery level doesn't change. Every minute, when an update is send to HA, the counter increases by one. 

![image](https://user-images.githubusercontent.com/24375847/140805258-67f6425c-6605-4631-aa86-af26d2118d99.png)

```
- id: '1636399281727'
  alias: Add one to counter when state updates
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ble_battery_a4c1388d18b2
  condition: []
  action:
  - service: counter.increment
    target:
      entity_id: counter.state_update_counter
  mode: single
```

Isn't this what you were looking for.

**Comment by pewu78** [comment]
Yes, it's still not resolved. Proper implementation of device or system triggers in this integration would be beneficial not only for this type of device. Any other solution is a workaround - cumbersome, if viable at all.
I don't think additional counter to state change will be of any benefit - see my updates from 24 June.

**Comment by Ernst79** [comment]
The counter was just an example of a possible action, my point was that a **state** trigger does trigger, even if the state is exactly the same. For my understanding, what is the issue with a automation that

- triggers on a `state` change of the dimmer
- condition state is not `no press`
- action is whatever you want it to do

I'm not trying to find a way to not implement your request, but I'm trying to understand why the above is not ok or not good enough. In other words, what is the benefit of a trigger that does something on a device trigger.

**Comment by pewu78** [comment]
I checked it with logging as action, the state trigger does indeed trigger due to attribute(s) change (as documented).
It should be good enough to create automation based on "last type of press" and "dimmer value".
Thanks.
