### ISSUE TITLE
Support for xiaomi redmi air dots

### ISSUE THREAD

**Issue by hudsonbrendon** [custom-components/ble_monitor#418]
Would it be possible to add support for xiaomi redmi air dots 1, 2, 3? I think information like battery levels or whether it's being used or not would be interesting.

![image](https://user-images.githubusercontent.com/5201888/123057237-14cb4b80-d3de-11eb-83d4-f2caa35a0550.png)

**Comment by Ernst79** [comment]
You can check by following these instructions in the [FAQ](https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation). 

I'm not sure this device will send data in MiBeacon format, there is a big change that it only broadcasts data when setting up a connection. But you can try with the option report_unkown: "Xiaomi" and following the instructions in the FAQ

**Comment by Ernst79** [comment]
Any update on this, did you try to get some data with report_unknown?

**Comment by Ernst79** [comment]
Feel free to reopen if you have additional data.
