### ISSUE TITLE
Only detects some sensors

### ISSUE THREAD

**Issue by Yersi88** [custom-components/ble_monitor#419]
I have 4 Xiaomi BLE sensor one LYWSDCGQ  and three LYWSD03MMC. I added all of them to ble monitor, no key for LYWSDCGQ and for the three new ones I put the encryption key. Ble monitor than only connected to the LYWSDCGQ and one of the 3 new ones. Connection also seems unstable. I have no idea what I'm doing wrong. All of them are really close well within 15 meters from raspberry and my xiaomi air quality monitor with built in ble gateway has no problem connecting to all of them.

**Comment by Ernst79** [comment]
I suspect some interference of e.g. an SSD drive connected to your Raspberry. Do you have an SSD drive? 

SSD Drives are knows to block the Bluetooth signal, when placed close to your bluetooth radio in your Pi. Adding a cable and placing the SSD away from your raspberry helps a lot often. But I don't know if you have an SSD of course.

**Comment by Yersi88** [comment]
> I suspect some interference of e.g. an SSD drive connected to your Raspberry. Do you have an SSD drive?
> 
> SSD Drives are knows to block the Bluetooth signal, when placed close to your bluetooth radio in your Pi. Adding a cable and placing the SSD away from your raspberry helps a lot often. But I don't know if you have an SSD of course.

I do have an SSD! I tried putting it away from the pi (half meter approx), not really successful. 

Do I need to do this command if I have full home assistant installed on the pi? 
sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\``

**Comment by Ernst79** [comment]
No, that command is only needed if it isn't working at all. 

About the SSD. This is a very common problem (I experienced it myself as well). But you said it didn't help. Any other device close to your Pi? Wifi router?

**Comment by Yersi88** [comment]
Correction, it added one more LYWSD03MMC after I moved the disk. But it does not seem to read any of them very good. And I still am missing one LYWSD03MMC. Strange thig is that it added the one that's furthest away in bathroom and it still didn't add one that's like two meters away!

**Comment by Ernst79** [comment]
Do these LYWSD03MMC have stock firmware. these sensors update only once in 10 minutes, so if reception isn't that well, it might take quite some time. Better to update them with ATC firmware (can be done online), this will make the sensor send 20 advertisements per minute, which will be much better if you sometimes miss a message. 

https://github.com/pvvx/ATC_MiThermometer

**Comment by Yersi88** [comment]
This is how it looks the morning after:
![image](https://user-images.githubusercontent.com/77145281/123250524-1120ed00-d4e2-11eb-98a1-67695cd68ac9.png)

Looks like it detected all 4, but it does take unacceptable amount of time to refresh. They do indeed have stock firmware. Until recently I was using the xiaomi air quality monitor as a BLE gateway for them and it work working wonderfully. I was wondering if there's is way to get this data from the xiaomi air monitor instead of built in bluetooth?

**Comment by Ernst79** [comment]
If you don’t want to try ATC firmware, you could have a look are ESPhome or the xiaomi gateway3 custom integration. But you have to check if all sensors are supported. I am not aware of an integration that uses the Bluetooth of an xiaomi air monitor

**Comment by Yersi88** [comment]
> If you don’t want to try ATC firmware, you could have a look are ESPhome or the xiaomi gateway3 custom integration. But you have to check if all sensors are supported. I am not aware of an integration that uses the Bluetooth of an xiaomi air monitor

I think I might try the ATC firmware. Will they still work with xiaomi gateway after that? Also is it possible to flash old firmware back?

**Comment by Ernst79** [comment]
Yes, you can force then to also send in Xiaomi format, to keep compatibility with Xiaomi gateways. You can also flash the old firmware back 

The online webtool has a button for flashing the old firmware and the ATC firmware. 

![image](https://user-images.githubusercontent.com/24375847/123288813-3167a080-d510-11eb-8dac-4952e8026528.png)

https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html

**Comment by Yersi88** [comment]
> Yes, you can force then to also send in Xiaomi format, to keep compatibility with Xiaomi gateways. You can also flash the old firmware back
> 
> The online webtool has a button for flashing the old firmware and the ATC firmware.
> 
> ![image](https://user-images.githubusercontent.com/24375847/123288813-3167a080-d510-11eb-8dac-4952e8026528.png)
> 
> https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html

How cool, I flashed the custom firmware on all 3 LYWSD03MMC. When I flashed first one HA started receiving the data straight away, I didn't even need to change anything in HA. It just started working like that! 

As enthusiastic as I am, I happily flashed the firmware on other two. Happiness was short lived, the other tow didn't get picked up by HA :( 

Side question: Is there also custom firmware for LYWSDCGQ  ?

**Comment by Ernst79** [comment]
Seems like a signal issue yes. The faq has some tips to improve signal, like moving away SSD, using external Dongle, etc. Have a look in the faq. Another option is using an ESP device with ESPhome if they are still too far away. There is no custom firmware for LYWSDCGQ unfortunately. Different chip inside, i guess.

**Comment by Yersi88** [comment]
Yes I was thinking about usb dongle. I even have a huge heatsink on the pi so that's definitely not helping the signal too. Are there any recemented usb dongles that are known to work? Couldn't seem to find any in faq

**Comment by Ernst79** [comment]
I have a cheap tplink dongle, which works fine, but the ones with antennas are better for the range, but also more expensive

**Comment by Yersi88** [comment]
I tried cheap small dongle but reception is exactly the same like the built in BT :/

**Comment by Yersi88** [comment]
All working good now with cheap BT dongle and long usb extension. Thank you very much for help!
