### ISSUE TITLE
Mi Body Composition Scale 2 does not send impedance data

### ISSUE THREAD

**Issue by hudsonbrendon** [custom-components/ble_monitor#422]
After these last updates I cannot access my scale's impedance data, the weight arrives correct but impedance does not update.

![image](https://user-images.githubusercontent.com/5201888/123500425-55aca580-d614-11eb-8852-7a8ec1c4270d.png)

Does anyone have this scale and is it working normally for you? Before anyone speculates she might be in trouble. The data normally arrives in the xiaomi app, it seems to be some problem with the integration.

**Comment by hudsonbrendon** [comment]
![image](https://user-images.githubusercontent.com/5201888/123500574-6d385e00-d615-11eb-8ea7-069abb9d9e0b.png)


after several tries, it finally worked, but it seems to be not so stable.

**Comment by Ernst79** [comment]
As far as I can see, it should behave the same as in the earlier versions. 

Impedance is only send if the hasImpedance flag isn't 0 in /ble_monitor/ble_parser/miscale.py. This hasImpedance flag is extracted form the controleByte that is send in the BLE advertisement.

```
        (measunit, controlByte, impedance, weight) = unpack("<BB7xHH", xvalue)
        hasImpedance = controlByte & (1 << 1)
```

If it is NOT zero, it will add the impedance to the result.  

```
    if hasImpedance:
        result.update({"impedance": impedance})
```

What you could try is to change the last two lines (line 78 and 79 in miscale.py) to this. 

```
    # if hasImpedance:
    result.update({"impedance": impedance}) 
```

Don't forget to remove 4 spaces in front of the second line. It will than always send the Impedance value, also the zero values, and also in case the scale isn't stabilized. Not sure if that is very useful, but at least you will than see all the measurements that are send. 

What might be an alternative idea is changing the same lines to 

```
    if impedance:
        result.update({"impedance": impedance})
```

This will send all impedance values, without the zero values. 

It might also be an reception issue. As impedance measurements are not send that often (far less than the weight measurements), and if the scale is a bit far away, it might sometimes miss the impedance measurements, while it does catch the weight measurements, that are broadcasted more often. To test, try to place your scale closer to your Bluetooth dongle. Make sure there are no SSD drives close to the Bluetooth dongle as well, they often block signals.

**Comment by Ernst79** [comment]
Any update on this, have you been able to do some tests and/or improve reception ?

**Comment by Ernst79** [comment]
Closing this issue due to no response. Feel free to reopen, if you still have this issue.
