### ISSUE TITLE
Support for the XIaomi HOTO Smart Kitchen Scale (QWCFC001)

### ISSUE THREAD

**Issue by kmbyatco** [custom-components/ble_monitor#424]
## Info
This looks like it sends BLE packets like how Mi smart scales do it. Can this be implemented too?

## BLE advertisements
[dump.txt](https://github.com/custom-components/ble_monitor/files/6721079/dump.txt)
```
(...)
2021-06-27 13:25:06 INFO (Thread-20) [custom_components.ble_monitor.ble_parser.xiaomi] BLE ADV from UNKNOWN Xiaomi device: RSSI: -71, MAC: B4:60:ED:8B:C8:D7, ADV: 0f1695fe3058801101d7c88bed60b408
2021-06-27 13:25:07 INFO (Thread-20) [custom_components.ble_monitor.ble_parser.xiaomi] BLE ADV from UNKNOWN Xiaomi device: RSSI: -70, MAC: B4:60:ED:8B:C8:D7, ADV: 0f1695fe3058801101d7c88bed60b408
(...)
```

## User Manual
[hoto-user-manual.pdf](https://github.com/custom-components/ble_monitor/files/6721086/hoto-user-manual.pdf)

**Comment by Ernst79** [comment]
@kmbyatco I had a first look, these two messages don't contain useful data, after the (reversed) mac at the end of the advertisement, there is only `08`, Can you try again, while using the scale (do not open MiHome at the same time) to see if you can get other (longer) advertisements?

**Comment by kmbyatco** [comment]
Unfortunately, I couldn't get anything else other than the `08` at the end. I think it might be encrypted. I made sure the mihome app is closed.

Weight data is parsed without issue to the mihome app, when I tested it separately

**Comment by Ernst79** [comment]
Did you try with `report_unknown: "Mi Scale"` The (person) scales use a different format (not MiBeacon), perhaps the kitchen scale as well. Or try to make a hcidump.

**Comment by kmbyatco** [comment]
`report_unknown: "Mi Scale"` does not produce any INFO messages, while DEBUG messages while it that mode only shows the same data as before:
```
(...)
homeassistant    | 2021-06-27 20:59:34 DEBUG (Thread-18) [custom_components.ble_monitor.ble_parser.xiaomi] Unknown Xiaomi device found. Data: 0f1695fe3058801101d7c88bed60b408
homeassistant    | 2021-06-27 20:59:34 DEBUG (Thread-18) [custom_components.ble_monitor.ble_parser.xiaomi] Unknown Xiaomi device found. Data: 0f1695fe3058801101d7c88bed60b408
homeassistant    | 2021-06-27 20:59:34 DEBUG (Thread-18) [custom_components.ble_monitor.ble_parser.xiaomi] Unknown Xiaomi device found. Data: 0f1695fe3058801101d7c88bed60b408
homeassistant    | 2021-06-27 20:59:34 DEBUG (Thread-18) [custom_components.ble_monitor.ble_parser.xiaomi] Unknown Xiaomi device found. Data: 0f1695fe3058801101d7c88bed60b408
(...)
```

However, doing a `sudo hcidump --raw hci > dump.txt` gave this:

```
File: dump.txt
(...)
11: > 04 3E 1F 02 01 00 00 D7 C8 8B ED 60 B4 13 02 01 06 0F 16 95 
12:   FE 30 58 80 11 01 D7 C8 8B ED 60 B4 08 B7 
(...)
42: > 04 3E 1F 02 01 00 00 D7 C8 8B ED 60 B4 13 02 01 06 0F 16 95 
43:   FE 30 58 80 11 01 D7 C8 8B ED 60 B4 08 B6 
(...)
71: > 04 3E 1F 02 01 00 00 D7 C8 8B ED 60 B4 13 02 01 06 0F 16 95 
72:   FE 30 58 80 11 01 D7 C8 8B ED 60 B4 08 C3 
```

I've pasted above some samples from the `dump.txt` any data that matched the `BLE ADV` data that was previously detected. Here is the full 
[dump.txt](https://github.com/custom-components/ble_monitor/files/6721632/dump.txt)

**Comment by Ernst79** [comment]
Unfortunately the same 08 at the end. It has one extra byte at the end, after the 08 which is the RSSI. This is not shown with the report unknown option. So, the same data, unfortunately.

**Comment by kmbyatco** [comment]
I see, data from the new kitchen scale must be transmitted by direct connection, instead of advertisment

**Comment by Ernst79** [comment]
I think so too, it will probably need a connection to be set up. This is out of the scope of BLE monitor

**Comment by kmbyatco** [comment]
Yeah, i'll close the ticket. Thanks for the help
