### ISSUE TITLE
Humidity data decimal

### ISSUE THREAD

**Issue by cspiby** [custom-components/ble_monitor#426]
I've just upgraded from an older version of the plugin that had temperature to 1 decimal, but humidity to 0 decimals, this worked well, however in the latest version, both temperature and humidity have a single option to change the decimal.

I'm finding the humidity steadily rises then falls on each of my sensors (sensor creep?), which creates strange graphs, can you add an option to control decimals on the temperature AND humidity independantly please, or remove the decimal all together from the humidity reading.

**Comment by Ernst79** [comment]
Hi @cspiby There has never been a separate decimal setting in the options for humidity. However, there is a workaround in the code that should fix this steadily rising temperature. I assume is rises with 0.1 every step and at 0.9 falls back to .0. There is a part of the code that is checking for sensors that show this behavior, but apparently it isn't working (anymore). 

Can you tell me which sensor you have? The workaround is currently implemented for LYWSD03MMC and MHO-C401 sensors with Xiaomi firmware. 

The relevant parts in the code. 

```python
        # LYWSD03MMC / MHO-C401 "jagged" humidity workaround
        if devtype in ('LYWSD03MMC', 'MHO-C401'):
            if self._device_firmware is not None:
                if self._device_firmware[0:6] == "Xiaomi":
                    self._jagged = True
```

```python
        if self._jagged is True:
            self._measurements.append(int(data[self._measurement]))
```

**Comment by cspiby** [comment]
> Hi @cspiby There has never been a separate decimal setting in the options for humidity. However, there is a workaround in the code that should fix this steadily rising temperature. I assume is rises with 0.1 every step and at 0.9 falls back to .0. There is a part of the code that is checking for sensors that show this behavior, but apparently it isn't working (anymore).
> 
> Can you tell me which sensor you have? The workaround is currently implemented for LYWSD03MMC and MHO-C401 sensors with Xiaomi firmware.
> 
> The relevant parts in the code.
> 
> ```python
>         # LYWSD03MMC / MHO-C401 "jagged" humidity workaround
>         if devtype in ('LYWSD03MMC', 'MHO-C401'):
>             if self._device_firmware is not None:
>                 if self._device_firmware[0:6] == "Xiaomi":
>                     self._jagged = True
> ```
> 
> ```python
>         if self._jagged is True:
>             self._measurements.append(int(data[self._measurement]))
> ```

I'm using the LYWSD03MMC

The behaviour you describe is exactly what's happening but it is for the humidity and not the temperature.

**Comment by Ernst79** [comment]
Yes, sorry, I meant humidity. Strange, I will try to reproduce myself and will get back to you when I have found the issue.

**Comment by Ernst79** [comment]
I don't see the behavior you describe. I have 1 digit for temperature, 0 for humidity. 

![image](https://user-images.githubusercontent.com/24375847/124438137-1c90d580-dd78-11eb-8f2f-c027e3d0fc89.png)

Could you post a screenshot of the sensor attributes, like this? I'm especially interested in the firmware attribute. 

![image](https://user-images.githubusercontent.com/24375847/124438340-582b9f80-dd78-11eb-8104-122a1a32f4f0.png)

**Comment by cspiby** [comment]
![Screenshot 2021-07-05 131709](https://user-images.githubusercontent.com/29413212/124470406-7b177d00-dd93-11eb-8f12-bc8a6f1404bb.png)

**Comment by Ernst79** [comment]
Can you show it for the humidity sensor?

**Comment by cspiby** [comment]
> Can you show it for the humidity sensor?

Sorry I initially uploaded the wrong one, that is humidity.

**Comment by Ernst79** [comment]
hmmm, that is really strange. Are you sure that you have the latest version? A couple of versions back we had this issue, but it should not be present in the latest version.

**Comment by cspiby** [comment]
> hmmm, that is really strange. Are you sure that you have the latest version? A couple of versions back we had this issue, but it should not be present in the latest version. You can check the version you have in `/config/custom_components/ble_monitor/manifest.json`

 "version": "3.5.0",

**Comment by Ernst79** [comment]
Ok, we need to do some debugging, as I can't reproduce it. 

Could you do the following. In /config/custom_components/ble_monitor/sensor.py, look for the part with `class HumiditySensor(MeasuringSensor):` (line 569 - 605). Replace this part with the code below, and restart HA. Wait till the humidity sensor is updated with a new measurement and after that, copy the errors in your log and paste them in your response. 

```python
class HumiditySensor(MeasuringSensor):
    """Representation of a Humidity sensor."""

    def __init__(self, config, mac, devtype, firmware):
        """Initialize the sensor."""
        super().__init__(config, mac, devtype, firmware)
        self._measurement = "humidity"
        self._name = "ble humidity {}".format(self._device_name)
        self._unique_id = "h_" + self._device_name
        self._unit_of_measurement = PERCENTAGE
        self._device_class = DEVICE_CLASS_HUMIDITY
        # LYWSD03MMC / MHO-C401 "jagged" humidity workaround
        _LOGGER.error("device: %s firmware: %s, MAC: %s", devtype, self._device_firmware, self._mac)
        if devtype in ('LYWSD03MMC', 'MHO-C401'):
            if self._device_firmware is not None:
                if self._device_firmware[0:6] == "Xiaomi":
                    self._jagged = True

    def collect(self, data, batt_attr=None):
        """Measurements collector."""
        if self.enabled is False:
            self.pending_update = False
            return
        if not CONF_HMIN <= data["humidity"] <= CONF_HMAX:
            if self._log_spikes:
                _LOGGER.error("Humidity spike: %s (%s)", data["humidity"], self._mac)
            self.pending_update = False
            return
        _LOGGER.error("Jagged: %s MAC: %s", self._jagged, self._mac)
        if self._jagged is True:
            self._measurements.append(int(data[self._measurement]))
        else:
            self._measurements.append(data[self._measurement])
        self._device_state_attributes["sensor type"] = data["type"]
        self._device_state_attributes["last packet id"] = data["packet"]
        self._device_state_attributes["firmware"] = data["firmware"]
        if batt_attr is not None:
            self._device_state_attributes[ATTR_BATTERY_LEVEL] = batt_attr
        self.pending_update = True
```

**Comment by cspiby** [comment]
2021-07-12 16:08:00 ERROR (MainThread) [custom_components.ble_monitor.sensor] device: LYWSD03MMC firmware: None, MAC: A4C1380E892A
2021-07-12 16:08:00 ERROR (MainThread) [custom_components.ble_monitor.sensor] device: LYWSD03MMC firmware: None, MAC: A4C1386AC8E3
2021-07-12 16:08:00 ERROR (MainThread) [custom_components.ble_monitor.sensor] device: LYWSD03MMC firmware: None, MAC: A4C13872C9E4
2021-07-12 16:08:00 ERROR (MainThread) [custom_components.ble_monitor.sensor] device: LYWSD03MMC firmware: None, MAC: A4C138CE06A8

2021-07-12 16:10:04 ERROR (MainThread) [custom_components.ble_monitor.sensor] Jagged: False MAC: A4C13872C9E4

**Comment by Ernst79** [comment]
ok. Apparently it returns firmware = None

Could you try the following, change this part

```
        if devtype in ('LYWSD03MMC', 'MHO-C401'):
            if self._device_firmware is not None:
                if self._device_firmware[0:6] == "Xiaomi":
                    self._jagged = True
```

to 

```
        if devtype in ('LYWSD03MMC', 'MHO-C401'):
            if firmware is not None:
                if firmware[0:6] == "Xiaomi":
                    self._jagged = True
```

**Comment by Ernst79** [comment]
If that doesn't help, could you check under devices what firmware is shown

![image](https://user-images.githubusercontent.com/24375847/125335764-38364600-e34d-11eb-9c86-16683fd3bda0.png)

I think in your case the line with Firmware is None (or empty). HA is keeping this value in the device registry (it won't be updated), For some reason, I think in your case it is stored as None and keeps on using that. You could try to delete the device from the integration and readd it. If that doesn't work, let me know, we than have to do some better deleting, which I will guide you through.

**Comment by cspiby** [comment]
Yes I don't see the Firmware line under the entity.

![image](https://user-images.githubusercontent.com/29413212/125583237-3db5064a-affa-4d8b-91e5-e2fbdc38f3b4.png)

I can't remember how I added the sensors, I do know that I installed a special version of the apk on my phone to get the encryption keys however.

**Comment by Ernst79** [comment]
Ok, That is the issue. Can you do the following steps (do not skip steps). 
- turn off discovery in the options and submit
- reopen the options and remove remove the sensor (select the mac under devices and in the next window type a `-` at the mac address (make a note of the mac and encryption key to add is later). Click submit
- Go to the integration menu in HA, and click on the devices button on the ble monitor tile. 
- 
![image](https://user-images.githubusercontent.com/24375847/125592735-1bb56b03-d2c1-41be-a40a-306948cf60b0.png)

- Open the device you have deleted, if still there
- Open each entity and click "remove entity". If not possible, do a restart of HA and try again.
- After all entities of this device are deleted, go to Developer tools --> services and select the 
- Passive BLE monitor: cleanup_entries
![image](https://user-images.githubusercontent.com/24375847/125592873-5f8a1c37-61f7-42b4-a4bc-898e4ae2b77a.png)
- After that check that the device is gone in the ble monitor integration tile
- Restart Home Assistant again and turn on discovery afterwards. click submit and wait 10 minutes
- Readd your device like before with mac and key. 
- Check after it is updated with data that the firmware attribute is visible 

Hopefully this will bring back the firmware and will than fix the humidity data issue

**Comment by cspiby** [comment]
Seems to have sorted it, thank you!
