### ISSUE TITLE
New sensor support - iNode Energy Meter

### ISSUE THREAD

**Issue by robertugo2** [custom-components/ble_monitor#427]
Hi,

I want to ask, if it is possible to add support for new device, that is iNode Energy Meter. It is using BLE advertising to send readings. Device is a simple pulse counter, that counts light pulses generated by energy meters.

Example hcidump raw data is:
> 04 3E 1E 02 01 00 00 47 3A 6D 6F 12 00 15 02 01 06 0E FF 90  82 04 00 CF E4 00 00 DC 05 B0 ED 10 02 0A 08 A5

Description of payload is also provided by manufacturer on (partially in polish, I can help with translation) [https://docs.google.com/document/d/1hcBpZ1RSgHRL6wu4SlTq2bvtKSL5_sFjXMu_HRyWZiQ/edit#heading=h.l38j4be9ejx7](url)

There are some existing implementations for:
* OpenMQTTGateway [https://github.com/1technophile/OpenMQTTGateway/pull/755](url) 
* ESPHome [https://github.com/michtam/esphome-inode-reader/blob/master/inode-reader.yaml](url)

I think at this moment most important info, that we can get from this device is
- value counter for given minute
- overall counter value.

Rest can be implemented later.

I can try to do that by my own, but I want to ask, if there is any tutorial, how I can do that? I have some experience in python programming. Anyway I will buy some big coffee to someone, that will help me 😄

**Comment by Ernst79** [comment]
Yes, it seems possible to add, no problem. I will prepare something later this week.

**Comment by robertugo2** [comment]
Thank you! Just inform me, if there is something, where I can help you.

**Comment by Ernst79** [comment]
Your message seems to have three bytes too many? 

`04 3E 1E 02 01 00 00 47 3A 6D 6F 12 00 15 02 01 06 0E FF 90 82 04 00 CF E4 00 00 DC 05 B0 ED 10 02 0A 08 A5`

The third byte (`1E`) is the message length (after 1E). 1E = 30 bytes + 3 bytes of `04 3E 1E` = 33 in total, while your message has 36 bytes. Could you get another message with hcidump to check that you didn't make a copy paste error?

**Comment by robertugo2** [comment]
Hi, sorry for late response. I have data from hcidump:
> 04 3E 21 02 01 03 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A 14 DD 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE BF 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE C5 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE CC 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE CD 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE CB 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE C4 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE C5 
> 04 3E 21 02 01 03 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A 14 D7 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE C2 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE CC
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE D6 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE CE 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE C6 
> 04 3E 21 02 01 03 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A 14 E1 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE CC 
> 04 3E 21 02 01 00 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A FE CA 

It seems, that last bytes are not relevant and can be ignored as it seems to be something random.

In terms of translation:
`constant = 1 (jeżeli constant == 0) ` - contant = 1 (if constant == 0), so it is defining default value for `constant` parameter
Those default values for constant are defined for different units, so for each unit setting, there is a different default value for constant.
Here you can find full translation (done by me) of part related to this sensor: [https://docs.google.com/document/d/1UShMYAU0e6RW9zuQp5iFh0bnKw1mMpxBhObPkFJyRts/edit?usp=sharing](url)

> And the other thing is this:
>> Obliczanie poprzedniego dnia tygodnia (weekDay) oraz sumy z poprzedniego dnia (weekDayTotal):

> Google translates this to
>> Calculation of the previous day of the week (weekDay) and the total for the previous day (weekDayTotal):

> Not clear to me what the difference is between the two and which unit?

I don't get it as well, what it means. I think it can be ignored, as I'm expecting that no one will use that.

In terms of calculation of sum/mean energy, I think you can leave that for user and provide just the impulse counter value for mean and sum.

**Comment by Ernst79** [comment]
Thanks, these messages are better. Your first message showed 1E at the 3rd byte, here you have 21, which is what I would have expected. 

About the calculation of average and sum. This is calculated according to the documentations, so why not using is that way?. This is the way I have programmed it now. As you can see, it depends on the "option" byte, from which the unit and constant are extracted. Apparently, you can change this setting somewhere, I guess. Your device seems to be set to unit == 0, so reporting in kWh and kW. Pulse counting is reported when it is to something else than 0 or 1. It this something you can change this on the device/settings/...?

```python
    if msg_length == 15 and device_id == 0x82:
        device_type = "iNode Energy Meter"
        (rawAvg, rawSum, options, batteryAndLight, weekDayData) = unpack("<HIHBH", data[4:])
        # Average of previous minute (avg) and sum (sum)
        unit = (options >> 14) & 3
        constant = options & 0x3FFF
        if unit == 0:
            avgUnit = "kWh"
            sumUnit = "kW"
            constant = 100
        elif unit == 1:
            avgUnit = "m3"
            sumUnit = "m3"
            constant = 1000
        else:
            avgUnit = "cnt"
            sumUnit = "cnt"
            constant = 1
        avg = 60 * rawAvg / constant
        sum = rawSum / constant

        # Battery in % and voltage level in V
        battery = (batteryAndLight >> 4) & 0x0F
        if battery == 1:
	        batteryLevel = 100
        else:
	        batteryLevel = 10 * (min(battery, 11) - 1)
        batteryVoltage = (batteryLevel - 10) * 1.2 / 100 + 1.8

        # Light level in %
        lightLevel = (batteryAndLight & 0x0F) * 100 / 15

        # Previous day of the week (weekDay) and total for the previous day (weekDayTotal)
        weekDay = weekDayData >> 13
        weekDayTotal = weekDayData & 0x1FFF

        result.update({"average": avg, "average unit": avgUnit, "sum": sum, "sum unit": sumUnit, "battery": batteryLevel, "voltage": batteryVoltage, "light level": lightLevel, "week day": weekDay, "week day total": weekDayTotal})
```

**Comment by robertugo2** [comment]
Yeah, you are right. If it is possible, then we should calculate things, as "cnt" unit is available as well. In terms of configuration - it is programmable via Android app, where it is possible to set "contant", unit and so on.

I see a bug in your code - you didn't include the if-else for constant default :)
```python
        if unit == 0:
            avgUnit = "kWh"
            sumUnit = "kW"
            constant = constant if constant>0 else 100
        elif unit == 1:
            avgUnit = "m3"
            sumUnit = "m3"
            constant = constant if constant>0 else 1000
        else:
            avgUnit = "cnt"
            sumUnit = "cnt"
            constant = constant if constant>0 else 1
```

**Comment by Ernst79** [comment]
That was the part where I didn't understand the Polish. 

So, if I use your changed code with this message

`04 3E 21 02 01 03 00 18 97 03 5E CF D0 15 02 01 06 0E FF A0 82 00 00 1A 00 00 00 00 19 C0 00 00 02 0A 14 DD`

The raw output is 

```
rawAvg =  00 00 --> 0
rawSum =  00 00 00 1A --> 26
options = 19 00
unit =  0
constant =  6400
```

With the above code, I get 

```python
avgUnit = "kWh"
sumUnit = "kW"
constant = constant if constant > 0 else 100
```

So, constant = 6400

```python
avg = 60 * rawAvg / constant
sum = rawSum / constant
```

Resulting in

```
avg = 60 * 0 / 6400 = 0 kWh
sum = 26 / 6400 = 0.0040625 kW
```

Is that the way it should be?

**Comment by robertugo2** [comment]
Yes, everything is correct! Readings are small as my device is still not mounted on energy meter and I olny checked, if pulses are counted (so I counted some and that was all).
Ship it! 😄

**Comment by Ernst79** [comment]
Yes, sure,

I still have to program the actual sensors, not finished yet. 😅 

I think I will create the following
- EnergySensor in kWh/m3/pulse
- PowerSensor in kW/m3/pulse
- BatterySensor in %
- VoltateSensor in V

Attributes for EnergySensor
- constant
- light level 
- week day
- week day total

We can remove the last two, if we cant figure out what they mean.

**Comment by robertugo2** [comment]
It looks great! In terms of 'week' attributes I think you can delete them, as I still don't know, what they mean.
In terms of data logging frequency - I will try to measure that in 1h.

**Comment by robertugo2** [comment]
So I have hcidump data with timestamps - see [https://pastebin.com/7YveAPBC](https://pastebin.com/7YveAPBC)
I tried to simulate light pulses to get some more real data. And from that I see:
* BLE msg is send every 1-2s
* Msg is updated every ~65s (so every minute + few seconds) - that is "avr" and "sum" have new updated values
* There is no live update of "sum" counter - it is updated every minute as well.

**Comment by Ernst79** [comment]
Ok, thanks, I will do an averaging sensor than, almost finished....

**Comment by robertugo2** [comment]
Or maybe something like checking, if value was updated and then send new status to HA?

**Comment by Ernst79** [comment]
Don't look at the device time and firmware 😃 
![image](https://user-images.githubusercontent.com/24375847/124659658-7cd16580-dea5-11eb-9731-39c483dd6a48.png)

![image](https://user-images.githubusercontent.com/24375847/124659709-89ee5480-dea5-11eb-9cab-42cba6db623c.png)

**Comment by Ernst79** [comment]
3.7.0-beta has been released, please give it a try and let me know if all works fine for you. Make sure you do a restart to verify everything keeps on working after the restart (either with restore_state enabled or disabled).

**Comment by robertugo2** [comment]
Thank you so much! I will give a try now.

**Comment by robertugo2** [comment]
It works!
![image](https://user-images.githubusercontent.com/70880205/124666645-a0e57480-deae-11eb-8133-0fae1ed035bd.png)
I spotted only one issue - readings are 1 minute delayed. I check that against hcidump. So sample, that I see in hci dump, will be displayed after 1 minute. I know, that it is due to averaging, but I curious, if it is possible to implement it in manner, that value will be updated only if there is a change - without averaging and so on.

**Comment by Ernst79** [comment]
Yes, sure. I will turn it to an instant updating sensor tomorrow, and only update when there is a change. No problem.

**Comment by Seba200086** [comment]
Thank you for this integration!
It works.
![obraz](https://user-images.githubusercontent.com/60579173/124734635-990ceb00-df15-11eb-9aca-e78ca3938ea4.png)

However, power and energy are swapped places. In the example above, the energy should be 9593.1 kWh and the power should be 0.2 kW.

By the way, I would like to ask could you please change the unit of power (from kW to W)?
I tried to get around this by changing the number of decimal to 3 and possibly multiplying it by 1000 (as template), but after changing decimal to 3 I still have 0.2 kW...

**Comment by Ernst79** [comment]
According to the HA docs, energy is in kWh and power in kW or W. I can change it to W, no problem. 

See this page of the documentation. https://www.home-assistant.io/integrations/sensor/

**Comment by robertugo2** [comment]
Hi. I think there is a bug in doc. Energy unit (sum) should be kWh (energy unit) and for avg in should be kW (power unit).

And I agree, that reported power unit should be W (current avg multiplied by 1000) - it will give more precise readings.

**Comment by robertugo2** [comment]
I added some comments to [https://github.com/custom-components/ble_monitor/commit/45f9803cb3a56ccc346f58a942668b88d4cbf28b](https://github.com/custom-components/ble_monitor/commit/45f9803cb3a56ccc346f58a942668b88d4cbf28b)

**Comment by Ernst79** [comment]
Fixed it in 3.7.1-beta. Please try again to see if everything now works as expected.

**Comment by robertugo2** [comment]
Thanks for fixing it! I'm currently testing it on real meter and everything seems to be working except rounding. Is it expected behavior? 
![Screenshot_20210707-222217_Home Assistant](https://user-images.githubusercontent.com/70880205/124823997-17977600-df72-11eb-94d0-033d3d8b89e5.jpg)

**Comment by Ernst79** [comment]
Ah, no, that is not how it supposed to be. Will fix that tomorrow, should be easy to fix.

**Comment by Seba200086** [comment]
Similiar issue (rounding).
![obraz](https://user-images.githubusercontent.com/60579173/124831380-6a296000-df7b-11eb-81e9-88fc035a97f4.png)
Aside from the above it works well. Thanks again!

Just for the record, at any time you can calibrate the sensor readings to match the current reading of the actual energy meter (e.g. instead of 0.677 kWh -> 9597.2 kWh).

There is an app for this purpose at https://support.inode.pl/apps/new/iNodeEM/ (I use Chrome for Android).

**Comment by Ernst79** [comment]
3.7.2-beta has been released, which adds rounding to energy and power measurements

**Comment by robertugo2** [comment]
Sorry for late response, but I was testing it a Little bit and everything is working fine :)

**Comment by Ernst79** [comment]
4.0.0 has been released as final.

**Comment by GamerClassN7** [comment]
Would be possible to add ability to calibrate device by input in home assistant device cart imple int input ?

**Comment by Gus1994** [comment]
Hello, does anyone know if this same sensor support water meter monitoring? It seems it does integrate a read switch within the sensor? Thanks
