### ISSUE TITLE
publish ATC firmware version

### ISSUE THREAD

**Issue by bthovda** [custom-components/ble_monitor#429]
Is it possible to publish ATC firmware version number?
Not only Firmware: ATC (Custom) 
but something like Firmware: ATC 3.2

Thanks for a great addon!

- BT

**Comment by Ernst79** [comment]
Unfortunately not, The firmware version is not send in the advertisement payload in advertising mode. see https://github.com/pvvx/ATC_MiThermometer#bluetooth-advertising-formats
