### ISSUE TITLE
track_device option not available

### ISSUE THREAD

**Issue by RomanKlein777** [custom-components/ble_monitor#432]
Heloo, I am on most updated hass.io on rPI4 and I get error when I want to use device tracker feature:

Invalid config for [ble_monitor]: [track_device] is an invalid option for [ble_monitor]. Check: ble_monitor->ble_monitor->devices->0->track_device. (See /config/configuration.yaml, line 18).

It is also not visible when i have used UI.

**Comment by Ernst79** [comment]
I assume you use YAML. did you fill in your MAC address, I see a `0` in the error message

And did you restart Home Assistant after updating (before changing your config)? Home Assistant needs to be aware of the new track_device option first, so, first do a restart, add the track_device option and restart again. For configuration in the UI, only the first restart is needed.

**Comment by RomanKlein777** [comment]
Hi, I have restarted it, updated ble monitor and hass core too. Now works :) I see first two iTags appearing :) very nice. Now using YAML. I think I will switch back to UI. Good job!

**Comment by Ernst79** [comment]
Good to hear.
