### ISSUE TITLE
Incompatibility between internal and doongle

### ISSUE THREAD

**Issue by Rubquila** [custom-components/ble_monitor#436]
Is it possible that there is an incompatibility when using internal bluetooth (RaspPi 4B+) with the bl_tracker and external dongle (Asus BT4.0) with the ble_monitor?
In my case, the bl_tracker loses the devices tracked every few minutes.

Thanks.

**Comment by Ernst79** [comment]
Not that I know. You could try increasing the consider_home time in the options

**Comment by Rubquila** [comment]
I've set the consider_home to 350 and interval to 10, but still the same problem.
Without ble_monitor i don't have any problems with tracker.
At the moment, i cant't get the two things works at the same time. It looks like the RaspPi can't manage classic bl on internal and ble on dongle at the same time.


> Logger: custom_components.ble_monitor
> Source: custom_components/ble_monitor/__init__.py:560
> Integration: Passive BLE monitor (documentation, issues)
> First occurred: 14:18:35 (5 occurrences)
> Last logged: 14:25:34
> 
> HCIdump thread: Runtime error while sending scan request on hci1: Event loop stopped before Future completed.

**Comment by Magalex2x14** [comment]
@Rubquila judging by what I see in the ble_tracker platform description, it has no setting for choosing an interface ...

**Comment by Magalex2x14** [comment]
What device are you trying to track? If it has a static mac-address, then you can use the [ble_monitor](https://github.com/custom-components/ble_monitor#device-tracker) to track it.

**Comment by Rubquila** [comment]
> 
> 
> What device are you trying to track? If it has a static mac-address, then you can use the [ble_monitor](https://github.com/custom-components/ble_monitor#device-tracker) to track it.

Yes, it's a static mac. I have tried it, but it hasnt worked, I guess because it is a classic bluetooth device and ble_monitor only tracks ble devices.



> 
> 
> @Rubquila judging by what I see in the ble_tracker platform description, it has no setting for choosing an interface ...

I have tried with -1, 0 and 1 on the device_id (and without the device_id), but it did not worked.

**Comment by Magalex2x14** [comment]
According to error above, ble_monitor was interrupted on the hci1 interface.

If your device is classic, then you are not using bluetooth_le_tracker, but bluetooth_tracker (I misunderstood). Then you have the option to choose the interface, yes (device_id option). Make sure you are using a different interface for ble_monitor (try one first, then the other, without changing the device_id setting) . If everything is fine with the settings, then there should be no conflict. Perhaps you are faced with poor work of the bt-module built into the raspberry. Have you tried leaving the tracked device next to the raspberry, is it lost then?

@Ernst79 I think we should consider adding the interface name in addition to the mac-address in the settings (but keep the binding by the mac-address), and add the mac-address of the interface to the log...

**Comment by Ernst79** [comment]
@Magalex2x14 With interface name you mean hci0 etc? This is already possible in YAML, isn't it? 

```
ble_monitor:
  hci_interface: 0
```

or 

```
ble_monitor:
  bt_interface: '04:B1:38:2C:84:2B'
```

will both work.

Or do you mean in the UI configuration (which only shows the bt_interface option? We could add the hci interface to the drop down menu, showing something like `hci0 (04:B1:38:2C:84:2B). Is that what you mean?

**Comment by Magalex2x14** [comment]
Yes, I meant the dropdown menu in the UI - so there will be at least one place in HA where you can specify the match.

**Comment by Ernst79** [comment]
Yes, I agree. I will look into that

**Comment by Rubquila** [comment]
> 
> 
> According to error above, ble_monitor was interrupted on the hci1 interface.
> 
> If your device is classic, then you are not using bluetooth_le_tracker, but bluetooth_tracker (I misunderstood). Then you have the option to choose the interface, yes (device_id option). Make sure you are using a different interface for ble_monitor (try one first, then the other, without changing the device_id setting) . If everything is fine with the settings, then there should be no conflict. Perhaps you are faced with poor work of the bt-module built into the raspberry. Have you tried leaving the tracked device next to the raspberry, is it lost then?
> 
> @Ernst79 I think we should consider adding the interface name in addition to the mac-address in the settings (but keep the binding by the mac-address), and add the mac-address of the interface to the log...

I have managed to get both to work for a few days, but as soon as I did a hard reboot it stopped working again. I have repeated the same procedure but to no avail.
I even tried with two dongles (1 internal + 2 external) at once, and it just doesn't want to work. Either the hassio tracker works, or the ble_monitor does, but not both.

**Comment by Ernst79** [comment]
There is a Home Assistant OS 6.2 update that updates the Bluetooth firmware. Might be worth a try.

**Comment by Ernst79** [comment]
Closing this issue. Feel free to reopen if you still have issues.

**Comment by Rubquila** [comment]
> 
> 
> There is a Home Assistant OS 6.2 update that updates the Bluetooth firmware. Might be worth a try.

No, the errors continue.... :(
