### ISSUE TITLE
Add support for Govee H5178

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#440]
From @Thrilleratplay in #386

There is another Govee device, H5178, that has [an open PR for sensor.goveetemp_bt_hci](https://github.com/Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci/pull/42), which may not be as easy to integrate. It is a multiple sensor device, there is a display with a temperature humidity sensor then a second temperature humidity sensor that, I believe, communicates via RF. The display broadcast the information via BLE for both sensors but only uses one MAC address.

This will require to make two Temperature/humidity and possibly battery/voltage sensors for one mac, which can be a bit tricky. Done that before for the Kegtron devices with two ports, but for that device, I just created two sensor classes,

**Comment by Ernst79** [comment]
I've added H5178 to the tests branch, with a second (outdoor) temperature and humidity sensor. I'm not sure the battery(/ies) will work ok, as I only have one battery sensor for now. It might mix the measurements of the two, if both report individual values. 

Will make a beta later

**Comment by Thrilleratplay** [comment]
@Ernst79 Were you asking me to check if the other Govee devices still work with 4.2.1-beta?  They do.

**Comment by Ernst79** [comment]
I was actually asking if you wanted to do a check of the H5178. I understand you don't have this device, so it would be better is @noah-holland could do the check. But I'm not sure he/she will read this and if he/she is prepared to move from govee_bt_hci to ble_monitor. I'll just wait a couple of days and will merge if I don't get a response.

**Comment by Thrilleratplay** [comment]
I decided to purchase the H5178.  I am using a H5074 for my outdoor temperature and it seems to be susceptible to direct sunlight so I'll see if this works any better.  I'll test it out and let you know.

**Comment by noah-holland** [comment]
I apologize, I've been away from home for the past two weeks. I can get you the HCI advertisement later today (my work day has just started). I'd be happy to test the beta as well.

**Comment by Ernst79** [comment]
@noah-holland No problem, glad you are willing to test 😄 You can first try with 4.2.2-beta, it might already work (I tried to add it based on your PR for govee_bt_hci). If not, please send me an hcidump for this sensor and I will add it.

**Comment by Thrilleratplay** [comment]
@Ernst79 I am not seeing the sensor in discovery or the logs.  I created a gist with the hcidump containing the lines with that device's mac address https://gist.github.com/Thrilleratplay/f66a61ef34fbf7826008c7b1d4b58418

**Comment by Ernst79** [comment]
Fixed it in 4.2.3-beta. I had the length byte wrong.

**Comment by Thrilleratplay** [comment]
@Ernst79 Working now.  Thank you.  Although, I only see one battery entity but not sure if that is broadcasted separately or if @noah-holland had that working for the Govee integration.

**Comment by Ernst79** [comment]
No problem. I created only one battery sensor. as I'm not sure about the battery either. It the commit of @noah-holland, I only see temperature and humidity as separate sensors, but I think it adds the battery per device as an attribute. 

The RSSI and battery seem to report the same value for both, but as battery is 100%, it is not possible to say if it is the battery per sensor not. Perhaps we can find out later, when the battery is a bit more empty. Creating a separate battery is a bit more difficult, as it isn't only used as a sensor, but also as the attribute of each sensor. I'll release the current status, we can always change it later.
