### ISSUE TITLE
Add support for Moat S2

### ISSUE THREAD

**Issue by Thrilleratplay** [custom-components/ble_monitor#441]
With the inclusion of Govee devices, I wanted to highlight the work of @SteveOnorato who created a component based on [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci](https://github.com/Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci) that includes a similar device, the Moat S2 BLE Temperature & Humidity sensor.  

The repo is: [SteveOnorato/moat_temp_hum_ble](https://github.com/SteveOnorato/moat_temp_hum_ble)

**Comment by Ernst79** [comment]
Added in 5.3.0. If anyone can confirm the correct working, that would be appreciated.
