### ISSUE TITLE
LYWSDCGQ data only once per 10-25 minutes

### ISSUE THREAD

**Issue by klim123123** [custom-components/ble_monitor#447]
I have LYWSDCGQ added to HA using ble_monitor and also AlexxIT/XiaomiGateway3 so i can compare data i receive on the same History Graph Card.
What i can see ble_monitor sometimes updates temperature value once per 10-25mins and sometimes once per few minutes. On the same time AlexxIT/XiaomiGateway3 updates it every 30-60seconds.
My devices are located just 1 meter from LYWSDCGQ.

Period: 60

![Screenshot_1](https://user-images.githubusercontent.com/64870895/126393077-b1595609-8edb-4590-ab84-155642773b75.png)

**Comment by Ernst79** [comment]
Do you have an SSD drive connected to your HA machine? SSDs might block the signal,
.

**Comment by klim123123** [comment]
> Do you have an SSD drive connected to your HA machine? SSDs might block the signal,
> .

No, i do not have SSD.
But i have aluminium case on my raspberry pi 4. May be this is the problem?

**Comment by Magalex2x14** [comment]
@klim123123 Yes, the aluminum case noticeably degrades both Bluetooth and WiFi performance.
An external Bluetooth dongle placed on a USB extension cable drastically improves the situation (especially models with a full-size antenna like for WiFi). For example, [FSC-BP119](https://www.feasycom.net/beacon/bluetooth--adapter/csr-4-0-wireless-transceiver-usb-dongle.html) - this is what works for me, and in combination with a 9dbi omnidirectional antenna (looks like TL-ANT2409CL) it receives data from a sensor located behind three brick walls at a distance of about 20 meters with RSSI about 70 dBm.

![](https://www.feasycom.net/uploads/201813049/small/csr-4-0-wireless-transceiver-usb-dongle35348194246.jpg) ![](https://img2.asbis.sk/tp-link-tl-ant2409cl-2-4ghz-9dbi-indoor-omni-directional-antenna-rp-sma-connector-l-type-w-o-cradle-w-o-cable_ien573926.jpg)

**Comment by Ernst79** [comment]
If the sensor is only 1 m away, a simple external dongle like a TP-link UB 400 might be ok as well. Adding a USB extension cable will also help placing it outside the case. But it all depends on the location of possible other sensors and the budget you have. I would recommend to try it first without the aluminum case. If that solves the issue, you should consider buying an external dongle/antenna.

![image](https://user-images.githubusercontent.com/24375847/126444446-967cd054-6128-40d3-a79b-e380f1a02cb4.png)

**Comment by klim123123** [comment]
Thank you for your help! I bought adapter with external antenna and installed it. 
I restarted my HA and selected new "MAC address Bluetooth interface" in Configurations.
Now i can see almost all BT devices in my house.
But i still have problem with LYWSDCGQ  device that is 1 m away. 

Data from HA using ble_monitor:
![image](https://user-images.githubusercontent.com/64870895/126726054-531671a9-ab80-4837-9b54-91971669670c.png)

Data from AlexxIT/XiaomiGateway3
![image](https://user-images.githubusercontent.com/64870895/126726074-a372e344-c1fc-4172-a3bc-97b3da074441.png)


May be i need to disable internal BT somehow? Or do i need to re-add my LYWSDCGQ device, because originally it was added using internal BT.


![image](https://user-images.githubusercontent.com/64870895/126725972-c6dae373-1716-480e-b000-59448ce0a585.png)

**Comment by Ernst79** [comment]
There is no need to re-add it, ble monitor is using the interface you have selected. 

I think the differences between the two can be explained as follows. BLE monitor is averaging the result of the measurements during a period (default 60 seconds). As far as I can see AlexxIT/XiaomiGateway3 is updating on every new packet_id number. This might explain the difference.

**Comment by Magalex2x14** [comment]
Ernst is right. The LYWSDCGQ takes more than 20 measurements per minute, and averaging these data increases the resolution (and accuracy, slightly). If, at the same time, one decimal is set in the integration settings, then the average value is rounded, which makes the readings more stable.

In addition to answering the question asked by Ernst, pay attention to these sensor attributes:
`Last mean of` - this is the number of messages from the sensor received during the last `period`.
`RSSI` - received signal strength indicator

**Comment by Magalex2x14** [comment]
To clearly see the above, you can try to set in the integration settings 2 or more decimal places for this sensor, and wait a couple of minutes until the readings stabilize.
