### ISSUE TITLE
new "statistics-graph" - does ble_monitor support tracking statistics?

### ISSUE THREAD

**Issue by kusmi** [custom-components/ble_monitor#460]
I just tried the new `statistics-graph` of home-assistant: [https://www.home-assistant.io/lovelace/statistics-graph/](https://www.home-assistant.io/lovelace/statistics-graph/)

But could not find any ble_monitor entities (I use plenty of LYWSD03MMCs) - it looks like there is some support needed from the integration: https://www.home-assistant.io/more-info/statistics/

**Comment by kusmi** [comment]
OK, I just saw you added support for it a couple of hours ago :-) Great!

**Comment by Ernst79** [comment]
Yep, added in 4.5.0 a few hours ago.
