### ISSUE TITLE
LYWSD03MMC no longer reports values to Homekit

### ISSUE THREAD

**Issue by miguelcouteirorodrigues** [custom-components/ble_monitor#463]
Hello,

Sometime after updating to version core-2021.8.2, the sensors for temperature, humidity and battery stopped reporting via the Homekit integration.

**Comment by Ernst79** [comment]
I need more info to solve this, which version of ble monitor? Any errors? Are the sensors working ok in home assistant? Did you check what changed in the Home Kit integration. 

In the ble monitor version 4.5.0 of yesterday, I have added an extra sensor_class attribute, to make use of the new statistics options of HA. It is important to know if it was this that caused the issue or something else, e.g. a change in the HomeKit integration.

**Comment by miguelcouteirorodrigues** [comment]
Hi,

ble monitor version 4.4.1.

The sensors work correctly on Home Assistant.

From the breaking change list for 2021.8, only mention was of scripts for switches, which seems unrelated.

Found this in the logs, don't know if it will help:
`2021-08-06 23:21:46 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for sensor.ble_humidity_a4c138bd78ac
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 628, in add_bridge_accessory
acc = get_accessory(self.hass, self.driver, state, aid, conf)
File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 206, in get_accessory
return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
File "/usr/src/homeassistant/homeassistant/components/homekit/type_sensors.py", line 117, in __init__
super().__init__(*args, category=CATEGORY_SENSOR)
File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 250, in __init__
firmware_revision=sw_version[:MAX_VERSION_LENGTH],
TypeError: 'NoneType' object is not subscriptable`

**Comment by Ernst79** [comment]
First, try with BLE monitor 4.5.0. If that doesn’t work, can You make a printscreen of the device, (integrations, select devices on the ble monitor tile, select the device that is causing issues) I want to check if the firmware attribute of the device is available, as the error is saying that sw_version is None.

**Comment by miguelcouteirorodrigues** [comment]
Hi,

Seems like there was a bug with Home Assistant Core. Version 2021.8.3 fixed it.

I'm going to close this issue.
