### ISSUE TITLE
Negative values for ThermoBeacon (thermoplus_ble)

### ISSUE THREAD

**Issue by titiviking** [custom-components/ble_monitor#464]
Hi,

I'm facing the issue that my bluetooth sensor is sometimes displayed as negative values in Home Assistant.

Can BLE_Monitor make an option available to specify what to do with out-of-range values or when the sensor is unavailable?

In below image, the humidity in the beroom is shown as minus 20% ...
![image](https://user-images.githubusercontent.com/73351833/128731744-4a26ec83-7c26-4280-95ed-268e13964dad.png)
![image](https://user-images.githubusercontent.com/73351833/128732070-a4051bd4-2f35-4084-b927-d6f4e6455466.png)

**Comment by Ernst79** [comment]
This is very strange, as humidity should filter out values below 0% or above 99.9%. In your case, you have -10%, which should have been filtered out. Could you try to enable the option “filter spikes” and check the logs at the time this happens. It should create a log entry in the HA logs, which could give a clue.

**Comment by titiviking** [comment]
Negative values are my fault... I re-discovered in my config that I'm using a template to apply a correction on the measurement...
But still it is annoying it goes to zero as it added low spikes on my graphs... I'd rather have no values at all if the values are unknown...

**Comment by Ernst79** [comment]
Ok, that explains the negative values. But still, if a measurement is below zero, it is omitted by the code, so it should not have recorded zero values. Are you sure this isn’t caused by the template sensor?

**Comment by Ernst79** [comment]
Any update on this issue?

**Comment by titiviking** [comment]
Negative values were due to my template sensor. I've attempted to apply filters on top, but it looks like it doesn't change much... I believe I will not face the issue anymore once I figure out why my sensor doesn't properly update every 60s

**Comment by Ernst79** [comment]
Issue is solved, was a reception issue due to SSD.
