### ISSUE TITLE
BLE not working

### ISSUE THREAD

**Issue by brontolo88** [custom-components/ble_monitor#465]
Hi, after updating to version 2021.8.1 and following, the platform BLE monitor is no longer available. Before the update I was using this integration for xioami bluetooth temperature sensor.
This is what I found in log.

Logger: homeassistant.setup
Source: setup.py:311
First occurred: 14:15:07 (1 occurrences)
Last logged: 14:15:07

Unable to prepare setup for platform ble_monitor.sensor: Platform not found (cannot import name 'VOLT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

**Comment by Ernst79** [comment]
This is already fixed, please Update ble monitor to the latest version.

**Comment by Ernst79** [comment]
This is already fixed, please Update ble monitor to the latest version.
