### ISSUE TITLE
unable to initialize

### ISSUE THREAD

**Issue by jameh** [custom-components/ble_monitor#474]
```
2021-08-14 09:26:33 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform ble_monitor.sensor: Platform not found (cannot import name 'STATE_CLASS_MEASUREMENT' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
```

I had this working before updating to 4.6.0-beta, but I'm not sure how to roll back.

I have homeassistant core-2021.4.6 installed which is not the most recent because newer versions seem to break my Hue integration's compatability with my diyhue emulated bridge server. Installed on a raspberry pi using the Home Assistant OS 6.2, supervisor-2021.06.8.

Might this just be cause by my older core version?

**Comment by jameh** [comment]
update: I rolled back to previous releases of ble_monitor and the newest one I don't get this issue in is 4.4.1

**Comment by Ernst79** [comment]
Yes, you will need to update to 2021.8. Maybe .7 or .6 will also work. In HA 2021.8 they introduced a new feature in HA, which allows you to use long term statistics on your data. So, I would suggest you stay on BLE monitor 4.4.1, till you solve your Hue issue. I’ll add a warning in the release notes, but there won’t be a fix for you.

**Comment by jameh** [comment]
thanks, fwiw - I opened an issue at diyhue about the breaking Hue compatibility [here](https://github.com/diyhue/diyHue/issues/678). It actually seems the newest working version of HA Core for that issue is 2021.5.0

I still experience this issue when upgrading to ble_monitor 4.5.0-beta and HA Core 2021.5.0.
