### ISSUE TITLE
cannot import name 'RRENAMED_MODEL_DICT'

### ISSUE THREAD

**Issue by IonutNeagu** [custom-components/ble_monitor#475]
Unable to prepare setup for platform ble_monitor.sensor: Platform not found (cannot import name 'RRENAMED_MODEL_DICT' from 'custom_components.ble_monitor.const' (/config/custom_components/ble_monitor/const.py)).

**Comment by Ernst79** [comment]
Thanks, fixed in 4.6.1-beta
