### ISSUE TITLE
Add RSSI sensor

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#479]
Request from @denilsonsa in #3 

Idea: Configuration toggle to ☐ Generate RSSI entities

Rationale: We used to have a batt_entities checkbox to enable the generation of battery percentage and battery voltage sensors. (Now, those entities are always generated.) Still, the battery level was already available as an attribute of the other sensors (temperature, humidity).

Likewise, RSSI is available as an attribute, but I think it also makes sense to have it as a separate sensor (automatically created with the correct name, icon, unit, device class).

Revised idea: Generate RSSI entities automatically, no option provided. If people don't like it, they can disable the entity (just like they can for the battery sensors).

**Comment by Ernst79** [comment]
I think there might be a better idea. We can add this sensor, and disable it by default. this is possible in HA. A user can than choose to enable it, as I think most users are not interested in RSSI. 

I will look into this.

**Comment by andrewjswan** [comment]
Hmmm https://github.com/custom-components/ble_monitor/issues/37#issuecomment-731997684

**Comment by Ernst79** [comment]
Yes, a template sensor can be used as well. But a default disabled RSSI sensor is probably easier. And I recently found out that this is possible, so why not.

**Comment by Ernst79** [comment]
Yes, a template sensor can be used as well. But a default disabled RSSI sensor is probably easier. And I recently found out that this is possible, so why not.

**Comment by andrewjswan** [comment]
We'll have to delete all templates :)

**Comment by Ernst79** [comment]
Added in 5.2.0 (sorry @andrewjswan, but you can delete your templates 😄 )

This RSSI sensor is disabled by default, and can be enabled via `configuration`, `integrations`, `devices` on BLE monitor tile, select device, `+1 disabled entities` and `enable entity`.

**Comment by andrewjswan** [comment]
Thanks :)

вс, 5 сент. 2021 г., 20:47 Ernst Klamer ***@***.***>:

**Comment by andrewjswan** [comment]
> This RSSI sensor is disabled by default, and can be enabled via

How i can enable RSSI sensor for all my devices through yaml configuration? 
I have more than 20 sensors, I really don't want to go into each one and turn it on by hand.

**Comment by Ernst79** [comment]
Sorry, it’s the only way at the moment.

**Comment by andrewjswan** [comment]
> Sorry, it’s the only way at the moment.

Got it, I'll fix it directly in the storage, device files. :)

**Comment by andras-tim** [comment]
> > Sorry, it’s the only way at the moment.
> 
> Got it, I'll fix it directly in the storage, device files. :)

You have a workaround, you can edit the appropriate `.json` file under the `.storage` directory :wink:

**Comment by andrewjswan** [comment]
> You have a workaround

I know, I did so, as I wrote about above. :)

**Comment by andras-tim** [comment]
> > You have a workaround
> 
> I know, I did so, as I wrote about above. :)

Ohh, sorry.
