### ISSUE TITLE
Support for Hughes Autoformer Power Watchdog

### ISSUE THREAD

**Issue by lewi3069** [custom-components/ble_monitor#482]
I am working on automating several systems in my camper as I am working and living full time on the road. There is a community of users that are also looking to do the same thing with their RV/Camper. One of the goals is to monitor power usage and costs as some sites charge per KWH. Also with pets being left at "home" it is important to know if there is a power outage or surge condition that may cut power to HVAC systems.

With the goal of power monitoring in mind I have purchased Power Watchdog. It is a surge protector with BLE built in. So far my efforts have been spent capturing the traffic with my phone while running the app to gather live data. Although I haven't been able to capture "alert" data yet. I have captured live data of what you see on the screenshot. I have also sent a "reset" of the power meter. At a minimum it would be great to capture the live watt, energy, volt, and amps. With the function of sending a reset so it could be setup as an automation to align with the billing schedule. Extended support would include reading alerts and "reconnecting" power after a disconnect event.

Another third party RVWhisper provides a similar function with a raspberryPi, but doesn't allow the extended functions HA does.

There are several models and I have the PWD50-EPO.
https://hughesautoformers.com/user-guides/

App View (although mine has a line 1 and line 2 being a 50 amp model, pictured is output of a 30 amp)
![image](https://user-images.githubusercontent.com/4366699/130471690-f01ee289-1ecb-4cd2-ae6a-5bb4f3105619.png)
Decompiled APK of app 
[PowerWatchdogAPK.zip](https://github.com/custom-components/ble_monitor/files/7032903/PowerWatchdogAPK.zip)
Filtered traffic HCI log.
[btsnoop_hci_HughesAutoformer.log](https://github.com/custom-components/ble_monitor/files/7032888/btsnoop_hci_HughesAutoformer.log)
Unfiltered HCI from Android Phone Running the app. (MAC: 44:a6:e5:44:a6:6a)
[btsnoop_hci.log](https://github.com/custom-components/ble_monitor/files/7032890/btsnoop_hci.log)

**Comment by Ernst79** [comment]
I think you first need to find out if the ble advertisements are passively send by the device, or that it requires a connection, before sending data. BLE monitor only supports the first. The last situation should only send data to the connected device, normally you cannot read this with another device at the same time (at least this is what I understand).

Next, we need some data, preferable with the report_unknown option of BLE monitor or with a hcidump ( see the faq for instructions). If you can send these, we can see if we can make sense of it.

**Comment by lewi3069** [comment]
Alright, thanks for the quick response. I will work to provide that information.

**Comment by lewi3069** [comment]
report_unknown logs.
[home-assistant.zip](https://github.com/custom-components/ble_monitor/files/7035216/home-assistant.zip)

Using the Bluetooth LE Scanner app looks like it sends some data without connection, but more with connection. Going to do some testing with two devices to see if that data is one device connected limited.

**Comment by lewi3069** [comment]
Did some testing and you are correct, only one device can be connected at the same time. This isn't a huge issue if HA can manage the device. That would be preferred as it would extend connectivity outside of the Bluetooth range if internet is available.

**Comment by Ernst79** [comment]
I think in your case the device passively sends messages to make it discoverable, it is just saying “hello, I’m here, please make a connection to get the real useful data”.

BLE monitor is not supporting setting up connections it only supports passively listening. I would recommend using ESPhome, https://esphome.io/components/sensor/ble_client.html. Also check this page which explains the difference between passive listening and actively requesting BLE data by querying a Characteristic.  https://esphome.io/components/ble_client.html

**Comment by lewi3069** [comment]
That makes complete sense. Thanks for the info, I'll take a look at getting ESPhome working with this device.

**Comment by tylerdempsey1** [comment]
> That makes complete sense. Thanks for the info, I'll take a look at getting ESPhome working with this device.

I am working on trying the something can you let me know how this worked out for you and how you were able to receive the bluetooth data?
