### ISSUE TITLE
Feature request: time update for LYWSD02

### ISSUE THREAD

**Issue by elektrinis** [custom-components/ble_monitor#483]
LYWSD02 is a really nice, high contrast and sharp display with clock, humidity and temperature.
Clock, however, is not ideally accurate, as all clocks are. It drifts over time and one's "smart home" can become very high maintenance to update these clocks manually via MiHome app every month or so. Also there's an issue with daylight saving, when you need the time to update +1 hour or -1 hour over night.
Please include this feature! :)

Edit: I see there is a similar (still open) request on ESPhome as well:
https://github.com/esphome/feature-requests/issues/643

**Comment by Ernst79** [comment]
Unfortunately, BLE monitor is not able to send data, it can only passively listen to the BLE advertisements (by design). There are no plans to extend functionality with sending data and/or active connections to devices. Sorry.

**Comment by elektrinis** [comment]
Thanks for info.
Are there any alternatives though? Does any other integration supports sending data?

**Comment by Ernst79** [comment]
ESPHome does, but you have to figure out the correct Characteristics. 

See 
https://esphome.io/components/sensor/ble_client.html

and 
https://esphome.io/components/ble_client.html
