### ISSUE TITLE
Init issues

### ISSUE THREAD

**Issue by HectorHumanes** [custom-components/ble_monitor#486]
Hi guys, I'm having issues trying to start the integration. The integration doesn't start and gives the following message in logs:

Unable to prepare setup for platform ble_monitor.sensor: Platform not found (cannot import name 'ELECTRIC_POTENTIAL_VOLT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

I'm using Home Assistant core-2021.7.1 and I've both tried BLE Monitor v5.0.0 and Beta 5.1.0 without sucess. 

Any clues about what the problem is?

**Comment by Ernst79** [comment]
You will have to update to 2021.8. Versions above 4.5.2 require 2021.8, due to implementation of the new long term statistics for BLE monitor sensors.

**Comment by HectorHumanes** [comment]
OMG what a quick response! I'm gonna try to to this. BTW many thanks for the help :)

**Comment by HectorHumanes** [comment]
Solved! Many thanks again dude :)
