### ISSUE TITLE
Measurement glitch upon reboot

### ISSUE THREAD

**Issue by mat4444** [custom-components/ble_monitor#489]
Hello,
I observe a sort of glitch with all my temperature measurements (Xiaomi temperature/humidity sensor : LYWSDCGQ/01) right after a reboot.
![Sans titre](https://user-images.githubusercontent.com/53400792/131468858-8716ae92-6151-4c49-8cd9-ccd729c11ff5.png)
The amplitude of the spike is variable from time to time and from device to device, however, it's always there. I am pretty sure it's the first time I observe this behavior.
Has anything change in the code recently that could explain that ?
Thanks!

**Comment by Ernst79** [comment]
During the first minute (period), it will update on every measurement, and not do averaging. This has the advantage that the sensor is earlier available after a restart, but has the disadvantage that you show. During the first measurements, you have measurements between 22.1 and 22.3 apparently. After that, it will do averaging of all measurements during each period (60 seconds). 

An hybrid solution could be to implement a moving average during the first period.

**Comment by mat4444** [comment]
Thank you for your explanation - that does make sense.
However, is it a recent change with this integration ? I don't remember seeing this behavior with previous versions of the BLE integration.

**Comment by Ernst79** [comment]
It was added on the 18th on June 2021 in BLE monitor 3.3.2

https://github.com/custom-components/ble_monitor/releases/tag/3.3.2

**Comment by mat4444** [comment]
Thanks @Ernst79
