### ISSUE TITLE
[bug] Huge battery consumption, constant polling BLE

### ISSUE THREAD

**Issue by vsimanin** [custom-components/ble_monitor#502]
After the update on September 6th, the battery consumption of the devices went huge. I didn't notice it right away, but today the information from the sensors shocked me. The new Xiaomi watch was discharged by half in less than a week. During the analysis, we found out that the battery consumption is due to the constant polling of devices! The data is updated every 5-20 seconds (random time). I cannot influence this by changing any of the settings. Please help. There are more than 10 BLE devices in the house, the batteries are leaking.
None of the settings changed, there was only the addition of a new device, but this happened before September 6.

https://photos.app.goo.gl/4ch9fV1CKWcYffX46

**Comment by vsimanin** [comment]
![Screenshot_20210909-193102](https://user-images.githubusercontent.com/9263449/132729504-be8d2ffd-4759-467e-b5fe-46aec84522bc.jpg)
![Screenshot_20210909-193116__01](https://user-images.githubusercontent.com/9263449/132729509-385886a4-52e8-4f4d-a738-dbd909144101.jpg)
![Screenshot_20210909-193125__01](https://user-images.githubusercontent.com/9263449/132729511-ea6004b1-64d7-43ea-8304-569da24decd2.jpg)

**Comment by Magalex2x14** [comment]
#503
