### ISSUE TITLE
[bug?!] ble monitor crashes home assistant?!

### ISSUE THREAD

**Issue by 50494554524F** [custom-components/ble_monitor#504]
just upgraded my system...
- raspberry pi 4
- home assistant os 6.3
- home assistant core 2021.9.5
- ble monitor 5.2.1

i can't be 100% sure but using ble monitor now crashes home assistant after 1 hour or so... disabling only ble monitor and keeping other custom component there are no problems and home assistant runs as usual

thanks

**Comment by Ernst79** [comment]
We need more info, based on this info, I have no idea. Possibly a failure with your Bluetooth (Firmware upgrade). Anything in the logs? Try enabling debug logging. Try a full system restart (not only HA).

**Comment by 50494554524F** [comment]
i din't change anything, just upgrade home assistant and ble monitor... support suggested to try to disable components, and i have problems if ble monitor is the only component running
yes, after a crash you have to restart removing power plug...

nothing in the logs...

**Comment by 50494554524F** [comment]
added

```
logger:
  default: critical
  logs:
    custom_components.ble_monitor: debug
```

to provide you a log, home assistant didn't crash anymore... murphy, let's see if this resolve :D

**Comment by 50494554524F** [comment]
another crash... reading the log after a reboot i see home assistant core was still running and collecting data. 

fronted and ssh crashed, samba add-on crashed too...

**Comment by 50494554524F** [comment]
using only

```
logger:
  default: critical
```

no more crashes in 24h... sorry, you can delete this 3d

**Comment by Ernst79** [comment]
If it is solved, you can close the issue yourself

**Comment by 50494554524F** [comment]
sorry, i'm back with new tests... again, i don't know if the problem is ble_monitor or homeassistant updates but these are the steps to reproduce the problem...

- raspberry pi 4 8GB
- home assistant os 6.4 64bit
- home assistant core 2021.9.6
- home assistant supervisor 2021.9.0
- ble monitor 5.3

fresh install of home assistant os, it can run 24h with no problems... no integrations, components or code were added

i just add ble_monitor in configuration.yaml and reboot
```
ble_monitor:

  discovery: false
  
  decimals: 2
```
it crashes home assistant... no integrations, components or other code were added, just these 3 lines

now i'm going to test with another microsd and 32bit version...

thanks

**Comment by Ernst79** [comment]
Perhaps you have a hardware issue with the internal Bluetooth. You could try an external Bluetooth dongle and disable the internal one. 

I don’t think it’s a BLE Monitor bug, as we do see more issues at the moment, it’s more likely a Bluetooth bug/failure. This can be anything, software/firmware/hardware. Hard to say

**Comment by 50494554524F** [comment]
on your input i tried with external dongle and seems stable now... searched a bit, raspberry suffers interferences but it worked really well before last updates...

**Comment by 50494554524F** [comment]
going back to os 5.11 on board bluetooth is/seems stable... core, supervisor and ble_monitor can be upgraded to the latest version

**Comment by Ernst79** [comment]
So, conclusion is that it is something in the HA OS. 
In these HA OS updates, there are often firmware updates for Bluetooth, see e.g. https://www.home-assistant.io/blog/2021/06/11/home-assistant-os-release-6/#raspberry-pi 

Strange thing is that I use HA OS 6.4 myself, with a Rasberry Pi 4, internal bluetooth without any issue.

**Comment by 50494554524F** [comment]
i suppose, my knowledge of linux is near to zero at the moment... couldn't find anything on internet... (different chips on board?!)
