### ISSUE TITLE
can't delete devices

### ISSUE THREAD

**Issue by dingausmwald** [custom-components/ble_monitor#507]
In short: since the update today (ble monitor 5.2.1, home assistant core-2021.9.5) i cant delete devices anymore with the common way (integration - configuration - select device - enter a "-" in mac address). Devices disappear like expected from the device menu in ble monitor config, but not in device list in home assistant. After opening ble config, devices appear again.

Long: i lately (two weeks) installed a bluetooth dongle (https://www.amazon.de/gp/product/B095P2DFWN/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1) to extend my range. I turned off the onboard bluetooth (raspberry pi 4b, 4gb, Home Assistant OS).

Soon got (after about 12 hours) the known "RuntimeError: Event loop stopped before Future completed" bug with the new dongle.

Did some updates (i do frequently when updates appear, most stupid thing i can do, since every week something new is broken, !curse you home assistant universe)

i discovered 2 unknown devices (mac adresses) after reading the advice to disable some ble monitor configurations (mainly discovery, active scan). I was able to delete those devices immediately after sending the changes.

The runtime error went away, thought i finally solved my problem. Not entirely sure if this was the solution, since like said, i update frequently.

Now, with the new update (discovery and active scan still disabled) those devices +1 appeared again with the difference that i cant delete them anymore. Restarted whole system more than once. No change.

**Comment by Ernst79** [comment]
I was able to reproduce it. The device comes back very fast. I’ll look into it.

**Comment by dingausmwald** [comment]
Thank you. My first guess is that the new BinarySensorEntityDescription thing isnt adressed in the device remove procedure.

Another strange thing: the 3 unknown devices are all marked as Manufacturer: ATC Model: ATC (ATC_MiThermometer LYWSD03MMC). The MAC adresses all look strange too:

00000000A47F
00000000BE7F
00100202440E

Strange because all my (with pvvx 3.2 flashed, custom advertising) devices start with A4C138 (only way for me to find out was to use the TelinkMiFlasher.html from pvvx github site with experimental chrome settings, damn this tool has some serious problems).

To answer your question: One of the devices had an voltage entry of 2 or something after the update. The other entities where empty. After the delete attempt all are empty, yes. No updates anymore. But i am still concerned that the initial RuntimeError will come back. Maybe this whole ghost devices is another, different bug (special to the custom firmware from pvvx)?

**Comment by Ernst79** [comment]
It is known that the old device and sensors isn’t completely deleted, you have to manually remove the sensors and than run a service to to remove the device after that. See the FAQ https://custom-components.github.io/ble_monitor/faq#how-to-remove-devices-and-sensors. This is a point that can be improved, I know.

but it’s strange that device comes back in the menu, this is strange and was not like before. I can see that if you delete it, and return to the first menu, it is gone, but after closing the menu and reopening it, it is back.

**Comment by dingausmwald** [comment]
Thank you for the hint with the delete procedure. I knew this a half year back, but forgot it. This is confusing, questioning what the delete device option in the ble config menu is for in the first place.

I did all this (with the devices still in the ble config menu) and the devices are gone forever (so it seems), even after a restart of hass core and a whole system reboot. We will see with the next ble monitor update. Thank you, my problem is solved now. Sorry for you that yours (even if its little considering the "workaround"?) is still there.

**Comment by Ernst79** [comment]
Great, I think I will have to look into fixing the delete procedure, it should be possible to make BLE monitor delete the config entry, delete the HA entities and then delete the device, without users having to do these steps manually. Please leave this issue open as a reminder for myself to finally fix this right 😄
