### ISSUE TITLE
New Device: Mijia Kettle Pro (Global version)

### ISSUE THREAD

**Issue by lelemm** [custom-components/ble_monitor#509]
Hi guys, just tried to add my Mijia Kettle Pro to ble_monitor (i thought it was supported), and for my surprise, my version is not supported.
Here is the log:

2021-09-14 10:35:21 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser.xiaomi] Unknown Xiaomi device found. Data: 111695fe3058e00901e1298338c1a4280100

May be it's just a different device code from the original kettle?

Can you take a look? Thanks!

**Comment by lelemm** [comment]
Well, tried to add the device_id myself to test it

added the device_id:
    0x9e0: "Mijia Kettle Pro",

LOG:
2021-09-14 11:11:38 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser.xiaomi] Advertisement doesn't contain payload, adv: 111695fe3058e00902e1298338c1a4280100

Is that normal for the other xiaomi kettles or is this might be specific for this model?

**Comment by Ernst79** [comment]
We tried to add this earlier, but it seems that this kettle is requiring an active connection. 

https://github.com/custom-components/ble_monitor/issues/398

This is not possible with BLE monitor, as we only support passive listening to BLE advertisements

**Comment by lelemm** [comment]
Got it. Will try other solutions. Thanks ;)
