### ISSUE TITLE
YLYK01YL in 5.3.1

### ISSUE THREAD

**Issue by chertvl** [custom-components/ble_monitor#514]
Hello.
After updating to 5.3.1 my yeelight remotes does not working anymore. I have 3 sensors for each (2 binaries and 1 action), so binaries is works, but action sensor is unknown state always.
Rolled back to 5.2.1 version and all works perfectly.
Can you check this bug please?

HA OS, 2021.9.5, RPI 4b, BLE Monitor 5.3.1,  2pcs remotes YLYK01YL.

**Comment by Ernst79** [comment]
I found the bug, the "button" (press type) was not being processed anymore. 5.3.2 fixes this issue.
I've added a test as well, to prevent this bug from happening in the future (hopefully).
