### ISSUE TITLE
BLE not working with Home Assistant 2021.9.4

### ISSUE THREAD

**Issue by RobinCutshaw** [custom-components/ble_monitor#516]
I just did a clean install of HA 2021.9.4, installed HACS 1.15.2, and through HACS, installed ble_monitor 5.3.2.  The logs show:

2021-09-18 18:36:32 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

Configuration>Integrations>Add does not show ble.  There are no log entries from ble_monitor, even with custom_components.ble_monitor: debug.

**Comment by Ernst79** [comment]
Try hitting F5 a couple of times. And search for "Passive BLE Monitor" when you try to add the integration.

**Comment by RobinCutshaw** [comment]
Did not work on Mac/Chrome.  It did work on Windows/Chrome after the F5.  Did not show up before hitting F5.

**Comment by Ernst79** [comment]
I think it is some cache issue in your browser. I close the issue, as it is solved, I assume. Otherwise, feel free to reopen the issue.
