### ISSUE TITLE
integrating Medisana scale BS444 and other models 

### ISSUE THREAD

**Issue by RomanKlein777** [custom-components/ble_monitor#523]
Hello,
your ble_monitor is one of the best features for home assistant! :)
Can you integrate please Mesisana Bluettoth scales? There are more models but works similar BS440, BS444 - all weight and body mass. 

Here is list of repositories (basically rPi, Bluetooth and python) - so implementing into your integration should be not that difficult.

Good luck :+1: 
https://github.com/keptenkurk/BS440
https://keptenkurk.wordpress.com/2016/02/07/connecting-the-medisana-bs440-bluetooth-scale/
https://github.com/jovandeginste/medisana-bs
https://github.com/andreaaizza/bs430

**Comment by Ernst79** [comment]
Hi @RomanKlein777 

Unfortunately, this sensor requires an active connection to be set up and sending some commands to the scale, to make it send data. Passive BLE monitor is only listening passively, so it can't setup connections. There are no plans to support this in the near future. So, I will close this request unfortunately. 

As an alternative, you could use ESPhome as BLE client https://esphome.io/components/ble_client.html, which supports sending characteristics. But you will need to figure out the characteristics to send and receive, but your second link has already done this for you.
