### ISSUE TITLE
Lock N100

### ISSUE THREAD

**Issue by NikiHard** [custom-components/ble_monitor#527]
Hey. Is there an instruction on how to connect Lock N100?

**Comment by Ernst79** [comment]
It should automagically connect, as it passively receives all messages. If not, check that you don't have reception issues. The FAQ gives some tips and tricks.

**Comment by NikiHard** [comment]
The fact is that temperature sensors are detected, but the lock is not.

**Comment by Ernst79** [comment]
Some things you can check are:
- Is it added to MiHome (preferably China region)?  
- Is it within the (bluetooth) range of the dongle/bluetooth radio (possibly reinforced concerete walls blocking the signal?)
- Is discovery enabled in the BLE monitor options

**Comment by NikiHard** [comment]
I have it connected to the Aqara app, because this is the eu version of the lock

**Comment by Ernst79** [comment]
It could be that is sends different advertisements when connected to the Aqara app, compared to MiHome. Could you make a HCIDUMP of some messages. You can do this with the following command (does not work on Home Assistant OS though, due to OS limitations). 

```
sudo hcidump --raw hci > dump.txt
```

**Comment by NikiHard** [comment]
[dump1.txt](https://github.com/custom-components/ble_monitor/files/7277867/dump1.txt)

**Comment by Ernst79** [comment]
No "xiaomi" messages (it should contain `16 FE 95`). Try again when locking your door for example.

**Comment by NikiHard** [comment]
[dump4.txt](https://github.com/custom-components/ble_monitor/files/7277937/dump4.txt)
5 times opened closed, mac: E2:09:BA:81:CB:0C Notifications arrive on the ipad

**Comment by NikiHard** [comment]
It does not connect to mihome, at first I tried on different regions

**Comment by Ernst79** [comment]
hmmm, too bad. I will have a look if I can make some sense of the BLE advertisements. I will add a note in the docs that the EU version seems to be not supported.

**Comment by Ernst79** [comment]
I just checked the Aqara website, but the EU version is a Zigbee version. BLE is only used to make a initial connection, as far as I understand. The docs already mention that only the Bluetooth version is supported. 

![image](https://user-images.githubusercontent.com/24375847/135895937-2a63537b-e291-4afb-9d9d-2a968dd4f3eb.png)

**Comment by NikiHard** [comment]
No, I turned off the Internet on the tablet and notifications came via Bluetooth

**Comment by Ernst79** [comment]
But what version do you have, the N100 Zigbee Edition (with both Zigbee and Bluetooth) or the Mi Home edition (Bluetooth only). Or do you have a different version which isn't in the table above.

**Comment by NikiHard** [comment]
ZigBee edition, it works apple home via bluetooth

**Comment by Ernst79** [comment]
ok, clear. I'll look into the BLE advertisements, but apparently these Zigbee/EU sensors have a different format for the BLE communication.

**Comment by Ernst79** [comment]
I tried to understand the BLE advertisements, but it seems to be some strange format Below my first attempt to understand it

`043E4C0202000146358D4CCBC617` normally contains the MAC, but not in this case

The following advertising data can be split up in Advertising Data (AD) elements. Each element is (normally) formatted as follows:
- 1st byte: length of the element (excluding the length byte itself) (in hex, so e.g. 13 in hex is 19 in decimals)
- 2nd byte: AD type – specifies what data is included in the element
- AD data – one or more bytes - the meaning is defined by AD type

`020106` length 2, AD type 01 = flags, 06 means Bit 1 : “LE General Discoverable Mode” Bit 2: “BR/EDR Not Supported.”
`1309436F6E74726F6C20666F7220534231383330` --> length 19, `09` means Complete Local Name = `Control for SB1830`
`BC0001` `0CCB81BA09E2` `1F`--> length 188???? This seems to be wrong, non-standard. It does however contain the MAC reversed
`020106` length 2, AD type 01 = flags, 06 means Bit 1 : “LE General Discoverable Mode” Bit 2: “BR/EDR Not Supported.”
`16FF4C0006310030D2CD925BE8060091020202A72B2802` --> this will be the useful data normally
`0408536D61` length 4, 08 means shortened Local Name = `Sma`
`C0` --> RSSI = `-64`

So, we have a short name `Sma`, a long name `Control for SB1830`. We have a strange part starting with `BC`, which is normally the length but not in this case. And we have a long bytestring that contains the data probably. `16FF4C0006310030D2CD925BE8060091020202A72B2802`

That's it for now. I'll look further later

**Comment by NikiHard** [comment]
This is not a lock

**Comment by Ernst79** [comment]
All the above info is from one message, j

**Comment by NikiHard** [comment]
Maybe you still need a log?

**Comment by Ernst79** [comment]
Not yet, I will try a different message. I just picked one.

**Comment by Ernst79** [comment]
But are you sure about the MAC address.?

**Comment by Ernst79** [comment]
Aha, that’s called randomized Mac. Unfortunately that wil make it impossible to implement, I’m afraid

**Comment by NikiHard** [comment]
As I understand it, it resets when you untie it from the apple homekit

**Comment by Ernst79** [comment]
Ok, that changes it, I’ll try further tomorrow.

**Comment by NikiHard** [comment]
Can send another log?

**Comment by NikiHard** [comment]
Sorry for taking so long, the command hcidump --raw hci> dump2.txt did not work for me

[dump2.txt](https://github.com/custom-components/ble_monitor/files/7760303/dump2.txt)

**Comment by Ernst79** [comment]
Can't find any message from your device in the dump, unfortunately.

**Comment by Ernst79** [comment]
I think your version of the lock uses the following to communicate:

> The lock even contains a certified Apple MFi chip, thanks to which it is possible to seamlessly connect with Apple devices.

So, I think the initial communication is done via BLE, but when everything is set up, it is using the MFi chip to communicate with Apple Homekit.

**Comment by Ernst79** [comment]
Closing this issue, as this version can't be supported unfortunately. See my previous post.

**Comment by almirus** [comment]
@Ernst79, Hi please explain how this version of the lock communicates with an Android phone, as it doesn't have HomeKit and Zigbee, so it must be using Bluetooth protocol.

**Comment by Ernst79** [comment]
There are two versions of the N100, one is Bluetooth only, the other is Bluetooth (for the initial setup) and Zigbee. 
![image](https://github.com/custom-components/ble_monitor/assets/24375847/f7c0027e-9740-4f50-a5f4-0075839cdc93)

**Comment by almirus** [comment]
@Ernst79 via Bluetooth 
![image](https://github.com/custom-components/ble_monitor/assets/16898685/35d2c25c-7183-4c74-9ebe-037a410321f6)
![image](https://github.com/custom-components/ble_monitor/assets/16898685/e120f2f4-7f1b-4e96-88f0-71e83c59e6b4)

**Comment by Ernst79** [comment]
The first "device" is using the iBeacon format (company id `0x004C`), the second "device" is using company id `0x4D4C` which is not an official company id (as in, it is not registered at the Bluetooth organization). the strange this is that it isn't using the Xiaomi Mibeacon format. (the N100 that is implemented in BLE monitor was using the Mibeacon format with `0xFE95` as UUID. 

When looking at the data of `0x4D4C` in your screenshot (`801E0F130100 B3C225F44DE2`) you can see that the second part contains your MAC address (reversed per two characters `E24DF425C2B3` The first part may contain data, but you will have to figure out which byte means what.
