### ISSUE TITLE
problem with batt_entities in 2021.10.1

### ISSUE THREAD

**Issue by pilot1981** [custom-components/ble_monitor#528]
Hi,
I'm using this configuration.yaml:

ble_monitor:
  discovery: False
  batt_entities: True
  bt_interface: 'B8:27:EB:A0:08:89'
  devices:
    - mac: '74:a3:4a:c0:16:78'
      name: 'Mosquito'

but when I go to check configuration before to upgrade to 2021.10.1 I obtain this warning:

WARNING:custom_components.ble_monitor:The 'batt_entities' option near /tmp/config/configuration.yaml:669 is deprecated, please remove it from your configuration

I lost some breaking changes...how I have to change configuration.yaml?

**Comment by Ernst79** [comment]
Just remove the line `batt_entities: True` from your config. They are now always generated (and can be turned of if you want in HA itself).
