### ISSUE TITLE
Can you add support for bluemaestro tempo disc?

### ISSUE THREAD

**Issue by tempesta-home** [custom-components/ble_monitor#530]
Please, I think it should be quite similar to what you've already done.

Here some link of interest:
[https://jenswilly.dk/2019/06/blue-maestro-sensor-openhab-and-homekit/](url)
[https://community.home-assistant.io/t/support-for-tempo-disc-bluetooth-temperature-humidity-and-dew-point-monitor-and-logger/169145](url)

**Comment by Ernst79** [comment]
I've created a 5.5.0-beta release which adds support for the Tempo Disc THPD and THD sensor. Please give it a try and let me know if it works, as I had to do some assumptions on the BLE advertisement format.

**Comment by Ernst79** [comment]
Can you try with 5.5.1-beta. I changed the parser to use network big endian (`!`) in stead of little endian (`<`)

![image](https://user-images.githubusercontent.com/24375847/137359797-9d1fa834-a74e-4b5a-bbd0-03860dd4d980.png)

Strange thing is that they say it should be little endian in their docs, but the 2nd link you gave is also using network big endian  (`!`)

**Comment by tempesta-home** [comment]
mmmmm 5.5.1-beta not good.  

![image](https://user-images.githubusercontent.com/63846985/137371317-5aeca099-5e4c-48de-9580-3cae9590830b.png)

No errors or other messages in the log

**Comment by Ernst79** [comment]
It’s a common issue, see #295. We still don’t understand the problem, it seems to be related to the Bluetooth firmware. Strange thing is that not most people do not have this issue, while others do. I also have a raspberry 4 and no issues at all.but please discuss this issue in #295.
