### ISSUE TITLE
Slow response of movement sensors

### ISSUE THREAD

**Issue by dbuezas** [custom-components/ble_monitor#532]
I have some RTCGQ02LM Xiaomi motion sensors running both in this and the [Xiaomi Gateway 3](https://github.com/AlexxIT/XiaomiGateway3) integration.

The state of the devices from this integration takes at least 1 second more than with the other one. Has anybody else also experienced this? I'm using a (ZEXMTE long range BT5.0 dongle)[https://de.aliexpress.com/item/1005002931530115.html?spm=a2g0s.9042311.0.0.1aed4c4diEzauY] on an Odroid N2+

**Comment by Ernst79** [comment]
I'm closing this topic, as no one has responded in the last months. Perhaps asking it on the forum will give you more responses.
