### ISSUE TITLE
Support for MiScale-clone from XiaoGui 

### ISSUE THREAD

**Issue by harmpter** [custom-components/ble_monitor#537]
Hi there! I'd like to propose this product.
I'll happily provide more data if necessary!

**Product:**
https://aliexpress.com/item/1005001980216067.html

**My scale's MAC address**
5F:5A:29:E5:E0:94
5F5A29E5E094

**Home Assistant Log**
https://pastebin.com/raw/5xa7Psin
I weighed myself once while logs were being collected.

![Screenshot_20211027-005942889](https://user-images.githubusercontent.com/62850893/138973098-96fc7171-1558-46a9-b367-cb14e6be43c2.jpg)

**"As Array:" from more screenshots:**
'[CO, **75, 02, 76,** 00, 00, 00, 02, 20, 5F, E5, EO, 94]'
'[CO, **8D, 02, 69,** 00, 00, 00, 02, 20, 5F, E5, EO, 94]'
'[CO, **D3, 02, 7E,** 00, 00, 00, 02, 20, 5F, E5, EO, 94]'

**Comment by crixionz** [comment]
Didn't see this, sorry. Yes, it works very well 19/20 times. If one day I figure out under which exact circumstances it doesn't work (if any), I'll reopen. Thank you so so much for putting all the work in! 
If at any time you need some more data/logs from this scale, hit me up! :) Thank you!
