### ISSUE TITLE
govee temperature entity fails when reported temperature drops below 32f ( 0c )

### ISSUE THREAD

**Issue by krayj** [custom-components/ble_monitor#539]
I have 6 govee H5075 BLE climate sensing devices to test with. This repros on all of them.

[repro]
1. have a govee H5075 BLE device successfully connected to the BLE_Monitor integration and verify it's working
2. place a sensor in an environment that is below 0c. 
3. wait for the temperature to cross the 0c ( 32f ) boundary into negative numbers

[results]
1. the temperature entity essentially breaks and receives no more updates via the integration.
2. the entity history graph shows the temperature flatlined at exactly 32f ( 0c )
3. when connecting to the device with the govee app via bluetooth, I can see that it is successfully recording much lower temperatures, so I know the device is working
2. The humidity entity for the same device keeps updating regularly and keeps working fine, which is evidence that communication is succeeding and the device is reporting data
3. The battery entity for the same device keeps updating regularly and keeps working fine, which is evidence that the communication is succeeding and the device is reporting data 
4. it does not matter whether I'm using the "use median" setting enabled or disabled (I have tried both)

[additional notes]

1. I think that this device reports its actual temperature in Celsius and that when it starts reporting a negative number that it breaks something in the integration. 

2. I should also point out that I was previously using the govee-specific HACS integration without issues and only started experiencing this issue when I decommissioned my use of the govee integration and replaced it with this one... so I have high confidence there is nothing wrong with my physical sensor device and that the problem is directly related to this integration.

3. The manufacturer of this sensor claims it's capable of accurately reporting temperatures as low as -5f (which would be -20.55c). I've personally seen it successfully report temps as low as 0f to 5f range (with the previous integration)

4. after enabling debugging in configuration.yml, I'm seeing some pretty wild entries for this sensor:

2021-10-28 12:39:09 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Data measuring sensor received: {'firmware': 'Govee', 'temperature': -1384.71, 'humidity': 7.9, 'battery': 63, 'rssi': -54, 'mac': 'A4C138674C11', 'type': 'H5072/H5075', 'packet': 'no packet id', 'data': True}

(connecting via the govee app is showing something in the 4.5f (-15.2c) temp range, so the value -1384.71 is not inline with what the actual sensor is reporting)

[expectation]
the integration should not fail when the sensor reports data in negative numbers

**Comment by Ernst79** [comment]
Thanks, we just need to change the /100 to /10000. Will change that tomorrow. You can also do it manually in the mean time, see my previous post.

**Comment by krayj** [comment]
I don't see a /100 anywhere in that code block. I see a " / 10000 " and I see a " / -100".

Here's the original
```
    if packet_value & 0x800000:
        return float((packet_value ^ 0x800000) / -100)
    return float(packet_value / 10000)
```

I assume you mean change it to something like this?
```
    if packet_value & 0x800000:
        #change /-100 to /-10000
        return float((packet_value ^ 0x800000) / -10000)  
    return float(packet_value / 10000)
```

**Comment by Ernst79** [comment]
Yes, indeed. I meant /-100

**Comment by Ernst79** [comment]
No problem, 5.7.5 has been released just now with this Fix.
