### ISSUE TITLE
Add support for Airnut Sports air monitor

### ISSUE THREAD

**Issue by bluefoxlee** [custom-components/ble_monitor#541]
**Description**:
The products was come from China, and it seems the company close down the product line which make those products almost useless (without cloud server). _Airnut fun_ is wifi version, someone manage to figure out to hack it to point it to own server to make it work. Unfortunately I got bluetooth version _Airnut Sports_, and trying to see if there is any way to connect it to Home Assistant to make it more useful.
Wonder if it's possible to add support. Thanks.

**Product**:
[Photo and spec](https://drive.google.com/file/d/1PiDdypuaGbtwHdPOZMgpx3Oz9x_sACWM/view?usp=sharing)
Can't even find product on official website. 

**Product MAC address**:
24:71:89:C9:28:70
(serach for 7028c9897124 from log.)

**Home Assistant Log**:
Removed other items from logs. However can't really see much info from log. only last 2 characters change during the period. 
[Debug Log](https://drive.google.com/file/d/1o0B2gsvzD6QOB0NDFepcZUwyCWhmCZBW/view?usp=sharing)
[Ble Scan Raw data](https://photos.app.goo.gl/GLj6PP62ayWuZgpX9)
[Bluetooh LE scaner](https://photos.app.goo.gl/U8xMVUD5knM9GxJY9)

**Comment by Ernst79** [comment]
In the Debug log, I only see the "Flag" (type 01) (020106) and the "UUID" (type 02) (0302E0C0). UUID is specifying the manufacturer (although I didn't find it in the list (https://btprodspecificationrefs.blob.core.windows.net/assigned-values/16-bit%20UUID%20Numbers%20Document.pdf). In the print screens I do see some more data, which is not in the Debug Log. Did you use the latest version of BLE monitor, I made a fix to also display these advertisements. 

In the printscreen I see
- type 09, which is the name of the device (Airnut Sport C92870)
- type 12, is the "slave connection interval Range", see the picture below 
- type 0A, which is the TX power level

![image](https://user-images.githubusercontent.com/24375847/139639931-2d4a3f81-a4eb-4ae9-aecb-ecb5efdb18b0.png)

![image](https://user-images.githubusercontent.com/24375847/139640376-a7ac080b-0110-4e23-a1f4-4025fcf295cb.png)

Based on this info, I think this device needs a connection to be set up, to get more info from the device. This is not supported by BLE monitor. You might try it with ESPHome, which allows to make connections to devices. 

https://esphome.io/components/ble_client.html

**Comment by bluefoxlee** [comment]
> Based on this info, I think this device needs a connection to be set up, to get more info from the device. 
You should be right. It have done with setup due to product discontinued. App is not working at moment.

Got it, I will make a try of esphome then, and see if I can open it to check the chip as well.
Thanks for the help and reply.

**Comment by Ernst79** [comment]
I'm closing this issue here, as this sensor can't be supported in BLE monitor, For further support I suggest to ask on the HA forum (especially in the ESPHome topics).

**Comment by bluefoxlee** [comment]
Thanks @Ernst79 
Can't really get any further message with esphome connection. Android app is working, so hope I can get some useful info from there. 
Thanks for the help.
