### ISSUE TITLE
report_unknown - Invalid config -  Got False

### ISSUE THREAD

**Issue by andrewjswan** [custom-components/ble_monitor#550]
In configuration.yaml i have `report_unknown: False` but in new version `ble_monitor` i have error when configuration check...
I try set `report_unknown: Off` but have the some error...
```
Invalid config for [ble_monitor]: value must be one of ['ATC', 'BlueMaestro', 'Brifit', 'Govee', 'Kegtron', 'Mi Scale', 'Moat', 'Off', 'Other', 'Qingping', 'Ruuvitag', 'SensorPush', 'Teltonika', 'Thermoplus', 'Xiaogui', 'Xiaomi', 'iNode'] for dictionary value @ data['ble_monitor']['report_unknown']. Got False. (See /config/configuration.yaml, line 60).
```

**Comment by andrewjswan** [comment]
ble_monitor version `5.9.0`

**Comment by Malvu** [comment]
Same for me

**Comment by Malvu** [comment]
> Fixed in 5.9.1

Always present in 5.9.1

Passive BLE monitor integration
BLE monitor passively monitors BLE sensors (Xiaomi, Qingping, ATC, BlueMaestro, Brifit, Govee, Kegtron, Moat, iNode, Yeelight, RuuviTag, SensorPush, Teltonika and Thermoplus)

**Comment by Ernst79** [comment]
Is this error right after the update in HACS, when you try to restart HA, or is this still the case after a restart of HA. You might have to do a "forced" restart of HA, e.g. by rebooting the entire system, before the new version is loaded. 

To explain why: right after the update, it still has 5.9.0 in memory, 5.9.1 is only loaded after a complete restart.

**Comment by Malvu** [comment]
> Is this error right after the update in HACS, when you try to restart HA, or is this still the case after a restart of HA. You might have to do a "forced" restart of HA, e.g. by rebooting the entire system, before the new version is loaded.
> 
> To explain why: right after the update, it still has 5.9.0 in memory, 5.9.1 is only loaded after a complete restart.

After a total deletion and a reinstallation it works again correctly!

I find it a shame not to have the battery information feedback on the HHCCJCY01 module by Xiaomi.

Sincerely, Pierre

**Comment by Ernst79** [comment]
Sorry about the inconvenience. 

Battery info is missing, as it requires a connection to get this data fro the MiPlant sensor. BLE monitor is however a passive component, only passively listening to BLE messages that are send by the sensor and not actively asking for data. Setting up a connection would require a significant rewrite of this component. You can use the built in component in HA to get this info.

https://www.home-assistant.io/integrations/miflora/
