### ISSUE TITLE
CGPR1

### ISSUE THREAD

**Issue by pvvx** [custom-components/ble_monitor#551]
![image](https://user-images.githubusercontent.com/12629515/141243440-468a2acf-9f55-4146-8b59-8e875acfa0c9.png)

Encrypted - Only after registering with Mi-Home!

CGPR1 is in the original unencrypted Qingping BLE ad format. In this mode, the light and battery value is transmitted every second.
And all events are sent in an unprotected Qingping format. OTA works without bindkey.

logs/Info: https://pvvx.github.io/CGPR1/

After registering with Mi-Home - completely switches to mijia mode only:

- Disables transmission of Qingping advertisements in unencrypted format.
- Disables OTA without bindkey.
- Does not transmit sensor values every second. Just an empty ad Mijia.

Switching to Qingping mode is done by pressing the button for a very long time until the LED stops flashing.

**Comment by Ernst79** [comment]
Thanks, I’ll update the docs this weekend.

**Comment by pvvx** [comment]
custom_components/ble_monitor/ble_parser/qingping.py does not have a complete Qingping parser.
Only the CGPR1 firmware contains a list of Qingping devices:
QP_MODULE: CGG1, CGH1, CGG1H, AJA01, CGP1W, CGP1N, CGP1L, CGD1, CGSPR1, CGDN1, CGM1, CGDK2, CGDK2-1, CGPR1, CGF1N, CGF1L, CGF1W, CGP23W, CGP23N, CGP23L, CGP22W, CGP22N, CGP22L, CGC1

**Comment by Ernst79** [comment]
Added CGPR1 qingping advertisement support in 6.0.1-beta. Thanks for reporting it.
