### ISSUE TITLE
ble_monitor fails to startup under HA core-2021.11.4

### ISSUE THREAD

**Issue by kevindorff** [custom-components/ble_monitor#564]
Since upgrading (last night) to Home Assistant `core-2021.11.4` (from `2021.10`), at Home Assistant startup I get an error related to `ble_monitor`. I don't find any other integrations reporting errors.

I'm running Home Assistant `core-2021.11.4` (latest as of today) on Home Home Assistant OS `6.6` (latest as of today). I am running `ble_monitor` `5.9.1` - installed (and updated) via `HACS`.   **Update:** see a later comment after I upgraded to `ble_monitor` `6.0.1`.

My `configuration.yaml`

```
ble_monitor:
  discovery: True
  bt_interface:
    - 'E4:5F:01:3F:EB:33'
  active_scan: True
```

The error that is reported

```
Logger: homeassistant.config_entries
Source: custom_components/ble_monitor/__init__.py:398
Integration: Passive BLE monitor (documentation, issues)
First occurred: 12:59:00 PM (1 occurrences)
Last logged: 12:59:00 PM

Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ble_monitor/__init__.py", line 319, in async_setup_entry
    blemonitor = BLEmonitor(config)
  File "/config/custom_components/ble_monitor/__init__.py", line 398, in __init__
    "binary": janus.Queue(),
AttributeError: module 'janus' has no attribute 'Queue'
```

What I've tried: I commented out my configuration stanza and deleted the Integration with hopes I could reinstall it and perhaps resolve what seems to be a dependency issue. Upon restart, it was removed from the Integrations (but only if I deleted the ble_monitor config stanza). I re-added the integration (providing the same config discussed above) in the first time setup UI. Then I got the same `janus`/`Queue` error above during the startup of `ble_monitor`. I again restarted Home Assistant and still get this error.

I've reviewed 
* my configuration vs current documentation
* the Home Assistant 2021.11 release notes
* current issues here within ble_monitor 
* Recent discussion in the ble_monitor forum

and don't see any similar reports. Hopefully it's not just some silly issue on my side, but I feel like I've worked to rule that out.

**Comment by kevindorff** [comment]
I was running `ble_monitor` `5.9.1` which I believe was current last night. I'm testing `6.0.1` right now.

**Comment by kevindorff** [comment]
After upgrading to `ble_monitor` `6.0.1` the error changed slighly

```
Logger: homeassistant.config_entries
Source: custom_components/ble_monitor/__init__.py:403
Integration: Passive BLE monitor (documentation, issues)
First occurred: 1:06:50 PM (1 occurrences)
Last logged: 1:06:50 PM

Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ble_monitor/__init__.py", line 324, in async_setup_entry
    blemonitor = BLEmonitor(config)
  File "/config/custom_components/ble_monitor/__init__.py", line 403, in __init__
    "binary": janus.Queue(),
AttributeError: module 'janus' has no attribute 'Queue'
```

**Comment by Ernst79** [comment]
I can't reproduce the issue, same version, same HA OS and core. Also haven't seen other people having this issue so far, so I agree its probably some dependency issue on your end.  Could you try the following.

- Remove config (copy it somewhere)
- Remove integration from HA
- Remove integration from HACS
- Check that the folder `custom_components/ble_monitor` is empty
- Restart HA
- Add BLE monitor in HACS
- Restart HA
- Add the integration via the UI

**Comment by borpin** [comment]
> My `configuration.yaml`
> 
> ```
> ble_monitor:
>   discovery: True
>   bt_interface:
>     - 'E4:5F:01:3F:EB:33'
>   active_scan: True
> ```

Just configure via the UI (as @Ernst79 saya but not explicitly) - this isn't required anymore (I believe).

**Comment by Ernst79** [comment]
Both should work, YAML or configuration in the UI. HA promotes UI configuration, and I use that myself, but we still support YAML config. But I do not always test YAML. 

Anyway, the part where the error occurs is independent of the choice YAML or UI config. I think there is something wrong with the Janus pypi  package dependency in the case of @kevindorff .

**Comment by kevindorff** [comment]
@Ernst79 I carefully followed the detailed uninstall, reinstall steps and they made no difference. I get the same integration error.

**Comment by kevindorff** [comment]
I use `Portainer` to open a `/bin/bash` shell to the homeassistant container and ran

```
bash-5.1# pip3 list | grep -i janus
janus                             0.6.2
WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

**Comment by Ernst79** [comment]
That looks ok. I have no idea. I’ll do some googling, but it’s running ok on my end, so hard to debug.

**Comment by kevindorff** [comment]
What I tried next
* Using `portainer` `bash` shell on homeassistant, I  ran `pip3 install --no-deps --force-reinstall janus`
* Restarted HA

My problem seems to be resolved.

**Comment by Ernst79** [comment]
Ah, great. I guess something went wrong during the installation of Janus the first time. It’s probably not uninstalled when removing ble_monitor. Good to hear it is solved.
