### ISSUE TITLE
Changing TMAX to support temperatures over 60°C

### ISSUE THREAD

**Issue by alexvillehart** [custom-components/ble_monitor#567]
Seeing that currently this component stops reporting temperature values above 60°C to prevent abnoram spikes if the device is not a kettle, now that Ruuvitags are supported, which have a maximum temperature up to +85°C. I see that the TMAX should be increased to Ruuvitags maximum value or define a separate maximum value only for Ruuvitags.

I have my sensor in my Sauna which routinely gets up to 75°C, this would help a lot.

**Comment by Ernst79** [comment]
Fixed in 6.1.1-beta
