### ISSUE TITLE
User input malformed

### ISSUE THREAD

**Issue by floow77** [custom-components/ble_monitor#569]
Hello,
I migrated my device rpi3 to rpi4 but after restore the configuration of BLE integration is on failure.
When I try to reconfigure it, I have this error:
« User input malformed »

how can I solve it ?
Thanks

**Comment by Ernst79** [comment]
Which version of ble monitor do you have? Is it up to date. Try to remove it, also from hacs, and reboot. Than reinstall it.

**Comment by floow77** [comment]
It’s v6.0.1.
I tried your advice but the issue is still there

**Comment by Ernst79** [comment]
Can you make a printscreen of the ble monitor options window?

**Comment by ivanrajkovic** [comment]
I have the same problem. Arch arm linux running on rpi4, it had an update from linux-raspberrypi4 to linux-rpi kernel. Home assistant log gives this error:
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ble_monitor/__init__.py:262
Integration: Passive BLE monitor (documentation, issues)
First occurred: 6:20:51 PM (1 occurrences)
Last logged: 6:20:51 PM

Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ble_monitor/__init__.py", line 262, in async_setup_entry
    list(BT_INTERFACES.values()).index(bt_mac)
ValueError: 'DC:A6:32:B4:E4:7E' is not in list

**Comment by floow77** [comment]
thanks @ivanrajkovic 
I have exactly the same error.

but hciattach command seems to be KO:
hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
bcm43xx_init
Failed to write reset command
Can't initialize device: Success

I tried to downgrade ble integration but my issue is still here

For your edit3: how can I find a old config.txt ? I don't have a backup.

**Comment by ivanrajkovic** [comment]
Are you sure that your bluetooth adapter is working? Which OS are you using?
What is the output of : 
$ bluetoothctl list
If you don't see your bluetooth adapter you can try adding
dtparam=krnbt=on
in your /boot/config.txt and see if it work after restart. You should also delete ble_monitor integration again and add it again after restart.

**Comment by floow77** [comment]
After check, bluetooth adapter doesn't work.
I try to add "dtparam" in config.txt but $ bluetoothctl list return always nothing.

```
# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on
dtparam=krnbt=on
```

I'm using Raspbian v10.

**Comment by ivanrajkovic** [comment]
Well, it looks like we had a same problem - no bluetooth device - but for different reasons. I can't really help you with Raspbian, just try to check the basic things:
- in bluetooth module loaded?
- what do you get from rfkill? can it see the bluetooth device and is it maybe disabled?
- are you running bluetooth service?

Apart from that, I think that your problem is not really connected to the ble_monitor and this issue should be closed, you can try to get help at Raspbian forums.

**Comment by floow77** [comment]
I deleted ble integration and reinstall it.
So it works
