### ISSUE TITLE
Error setting up entry Bluetooth Low Energy Monitor for ble_monitor

### ISSUE THREAD

**Issue by Megachip** [custom-components/ble_monitor#570]
Replacing my rpi4 with another one. Is ble address stored in db? 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ble_monitor/__init__.py", line 262, in async_setup_entry
    list(BT_INTERFACES.values()).index(bt_mac)
ValueError: 'DC:A6:32:1E:BC:8E' is not in list
```

```
# bluetoothctl list
Controller DC:A6:32:4B:00:1E homeassistant [default]
```

Same on version 6.0.1 and 6.1.1

Maybe related to #569

**Comment by Ernst79** [comment]
Try changing the BLUETOOTH interface in the ble monitor settings, your new Pi4 Bluetooth adapter will have a different MAC address.

**Comment by Megachip** [comment]
> Try changing the BLUETOOTH interface in the ble monitor settings, your new Pi4 Bluetooth adapter will have a different MAC address.

![image](https://user-images.githubusercontent.com/487352/144016423-1fa46e1a-2b1b-4ee3-b039-e62acda9758b.png)
tried, getting 
![image](https://user-images.githubusercontent.com/487352/144016519-559e30dd-5056-4b19-8788-3502c68daea6.png)

**Comment by Ernst79** [comment]
Can you show the full options menu, especially the `report_unknown` field? Try to change that field to `Off`

**Comment by Megachip** [comment]
> Can you show the full options menu, especially the `report_unknown` field? Try to change that field to `Off`

<img width="387" alt="image" src="https://user-images.githubusercontent.com/487352/144060669-4d2d7460-1e23-429d-8f0d-28d498098924.png">
field is/was off.
also tried to choose blank on devices (and now also on report unknown) ... no logs on save (or anytime)

**Comment by Ernst79** [comment]
Hmm, strange. Try to uninstall ble monitor from HA and from hacs. Restart HA and install it again. Do not skip the restart, to make sure everything is unloaded correctly.

**Comment by Megachip** [comment]
> Hmm, strange. Try to uninstall ble monitor from HA and from hacs. Restart HA and install it again. Do not skip the restart, to make sure everything is unloaded correctly.

Will I lose the existing monitored devices, or are they kept on uninstall-reinstall?
Where is the configuration stored? can't I just change the Address of the BLE Device?

**Comment by Ernst79** [comment]
I thought the issue was that you were not able to change the Address of the Bluetooth interface? If you can change it, please do. 

Regarding your first question, yes, you will loose the existing monitored devices, so make a note of the settings in the BLE monitor options, especially of the encryption keys. Most sensors are automatically added again, but if you have used encryption keys, you will have to re-add them.

**Comment by Megachip** [comment]
> I thought the issue was that you were not able to change the Address of the Bluetooth interface? If you can change it, please do.

Not via GUI, see Errors. But it must be configured somewhere in file or database. Maybe just changeing that entry.

**Comment by Ernst79** [comment]
It is stored in core.config_entries in the folder .storage. But I would be extremely cautious with editing directly in the config_entries database, never tried this, it could break your HA installation. 

![image](https://user-images.githubusercontent.com/24375847/144252591-21c55227-b9aa-46e4-b25d-7ae509e4640a.png)

**Comment by Megachip** [comment]
@Ernst79 can I somehow help to debug the issue? e.g. increasing the logging? "User input malformed" isn't much saying :(

**Comment by Ernst79** [comment]
I would reinstall it, as I explained before. This is the safest way.

**Comment by Megachip** [comment]
> I would reinstall it, as I explained before. This is the safest way.

Maybe... but loosing all of my data/informations isn't an option for me ;) So changed the interface mac, which solved my issue.

But it's not solving the issue, that GUI isn't able to do (like also reported in the other ticket). I do not feel like uninstall and reinstall (and reconfigure) "everything" is a "good" solution for the issue of changing interfaces. So maybe this should kept in an aditional issue? - maybe reproducing is easy, just replace the physical interface - or the interface in configuration ;)
