### ISSUE TITLE
Can't Find interface/adapter

### ISSUE THREAD

**Issue by Z02X** [custom-components/ble_monitor#571]
The result I get for MAC address of the Bluetooth interface/adapter is: 00:00:00:00:00:00 (hci0)

I also am getting this error:
HCIdump thread: OS error (hci0): [Errno 19] error while attempting to bind on interface 0: No such device

I tried setting it manually in the config but I am not confident I have the correct MAC address. I also am unsure if my Bluetooth interface/adapter is supported, it is fairly old, likely v2. If that's a reasonable possibility I can just get a new one.

**Comment by Ernst79** [comment]
This error means that it can't find a Bluetooth interface on your system. You could check yourself with the following command:

`hciconfig`

This should show your Bluetooth adapter, if available. I can have a look if you post the result here.

**Comment by Z02X** [comment]
Thank you for the quick response! I get command not found, using the `Terminal & SSH` add on on Home Assistant OS, not sure how to run commands of of the machine otherwise. I tried `bluetoothctl list` and got no results. Should I keep trying to find a way to run `hciconfig`? I am unsure if it is not on Home Assistant OS or is a limitation of the `Terminal & SSH` add on.

**Comment by Magalex2x14** [comment]
Bluetooth LE is only supported from Bluetooth specification version 4.0. You need a fresher adapter...

**Comment by Z02X** [comment]
> 

Thank you I will order a new one now. Thank you everyone for getting back to me so quickly.
