### ISSUE TITLE
New device Oregon Scientific IDTW218H

### ISSUE THREAD

**Issue by thekimera** [custom-components/ble_monitor#577]
Hi, 

I'm already using the component with some xiaomi thermometers and it's great! 
Now I wanted to also connect my Oregon Scientific wheather station that happens to be BLE so I'm creating this request.

I've extracted the information using gatttool, hope it's enough.

The device is announcing by the name IDTW218H and the model is NMTBAR218HG-01

There's a post where data is extracted from a similar station [here](https://www.instructables.com/Connect-Raspberry-Pi-to-Oregon-Scientific-BLE-Weat/)

Gatttool output: [IDTW218H.txt](https://github.com/custom-components/ble_monitor/files/7668592/IDTW218H.txt)

Thank you in advance!

**Comment by Ernst79** [comment]
Sorry for the late response. It looks like this device requires a connection to be set up. This is not supported, as BLE monitor only passively listens to ble data, it is not “asking” devices to send data. I would recommend you to have a look at ESPhome. ESPhome has a module to set up a connection and to ask for specific characteristics. 

https://esphome.io/components/sensor/ble_client.html

**Comment by thekimera** [comment]
Hi @Ernst79 , that's is a great advice! I'm new to ble world and bit overwhelmed. Thank you for the time, I will check the ble_client.
