### ISSUE TITLE
New Device: Oral-b toothbrush

### ISSUE THREAD

**Issue by alasdair-mott** [custom-components/ble_monitor#583]
Spotted the original request under #226 which was closed after no response from the person who raised it

Attached is the output when i ran the code under your response [home-assistant.log](https://github.com/custom-components/ble_monitor/files/7714838/home-assistant.log)

I'm new to coding and git but happy to **try** and branch to implement if someone can give me a bit of a steer.

Thanks

**Comment by alasdair-mott** [comment]
A8:1B:6A:B6:73:71

**Comment by alasdair-mott** [comment]
Just logged back into HA to realise this logs all unknown devices and my log file was 6 gig (oops). i also realised i was possibly running the log when the toothbrush wasnt in action. Reset and re run with a cycle through functions etc so hopefully a bit more data in there now. 
[home-assistant.log](https://github.com/custom-components/ble_monitor/files/7715078/home-assistant.log)

**Comment by Ernst79** [comment]
I had some time to look into into it. There seem to be some useful data.  

this is the format of a BLE message
`0e ff dc00 03210b 03 28 0000 07010004b0`

`0e` = 14 in decimals This is the length of the advertisment (in bytes)
`ff` means AD type 'Manufacturer Specific Data'
`dc 00` is the company identifier, this translates to 0x00DC, which is the [identifier of Proctor & Gable](https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/)
`03210b` ??? Stays constant, possibly an indication of the device type
`03` Variable, changes between `02` and `03` (ON/OFF?)
`28` Variable, changes between `00`, `04`, `08`, `20`, `28` and `c0`
`0000` Variable, increases with one, each second, when one. probably the time you are brushing your teeth
`07` Variable, changes between `01` till `07` (BRUSH MODE?)
`01` Variable, increases with 3, but sometimes stops
`04` Constant, always `04`
`b0` = RSSI (-80 dB)

So, there seems to be something useful, but we need to figure out what is what. I'll prepare a debug version to get some sensors, to make it easier for you to find out what is what.

**Comment by Ernst79** [comment]
I think we can "borrow" some info from here

https://github.com/Hypfer/Cybele/blob/master/lib/devices/OralBToothbrushDevice.js

**Comment by Ernst79** [comment]
Ok, it seems to make sense, 

`043e1e020100007173b66a1ba8120201050effdc0003210b0220000507011004bd`

results in 

```
result  {'firmware': 'Oral-B', 'state': 'idle', 'pressure': 32, 'time': 5, 'mode': 'turbo', 'sector': 'sector 1', 'sensor_6': 16, 'sensor_7': 4, 'rssi': -67, 'mac': 'A81B6AB67371', 'type': 'Series 7000', 'packet': 'no packet id', 'data': True}
```

`043e1e020100007173b66a1ba8120201050effdc0003210b0220000507011004bd`

results in 

```
result  {'firmware': 'Oral-B', 'state': 'running', 'pressure': 0, 'time': 8, 'mode': 'whitening', 'sector': 'sector 1', 'sensor_6': 26, 'sensor_7': 4, 'rssi': -74, 'mac': 'A81B6AB67371', 'type': 'Series 7000', 'packet': 'no packet id', 'data': True}
```

I don't know what the last two bytes before RSSI are, they are not used in the package I linked to. I'll prepare a toothbrush sensor with some attributes, perhaps we can find out.

**Comment by Ernst79** [comment]
Could you try 6.4.0-beta? Please check the attributes of the binary sensor, to figure out the meaning of sensor_a and sensor_b. It should also display things like the state, pressure, counter, mode, sector, etc.

**Comment by alasdair-mott** [comment]
a bit of context which i think is relevant, the toothbrush times 4 x 30 second increments with the idea being the minimum total time is 120 seconds.

sensor_a seems to increment up to 100 (%?) as the timer reaches a multiple of 30 then resets to 0
sensor_b always stays at 4 - i have a memory that the 4*30 seconds can be changed to 2*60s or something similar - im going to have a dig and see if i can find how to change it and test to see if it changes the output.

**Comment by Ernst79** [comment]
ok, excellent. Are the other attributes working as expected?

**Comment by alasdair-mott** [comment]
They seem to be although I'll confess I'm not experienced with binary
sensors in the way it's coming into HA.

**Comment by Ernst79** [comment]
Ah, that's a good thing to check. A binary sensor is only showing `on` or `off`. 
What I programmed now, is that it is `on` when it the STATE = 3 (= running). In all other cases, it is `off`. 
If you want it different, let me know. See below for all possible STATES. 


```
STATES = {
    0: "unknown",
    1: "initializing",
    2: "idle",
    3: "running",
    4: "charging",
    5: "setup",
    6: "flight menu",
    113: "final test",
    114: "pcb test",
    115: "sleeping",
    116: "transport"
}
```

**Comment by Ernst79** [comment]
Any update?

**Comment by alasdair-mott** [comment]
Apologies, I'm away from my system over the festive period, it'll likely be
into the new year before I can test further.

**Comment by Ernst79** [comment]
No problem, enjoy the holidays!

**Comment by Ernst79** [comment]
I’ve updated the binary sensor, it should work now as described (I made a mistake in the previous release, causing the binary sensor to be off all the time). Also updated the two attributes. Let me know if it is OK now.

**Comment by Ernst79** [comment]
6.4.3 has been released with support for this device, as final.

**Comment by KitHubek** [comment]
is possible to add battery level ? At oralB app is possible to see this in %

**Comment by Ernst79** [comment]
I think battery information is only available by connection to the device. This is not supported by BLE monitor unfortunately (as it is passively listening). As far as I can see, the passive BLE advertisements do not contain battery data.

**Comment by KitHubek** [comment]
:/ but thanks for information.

**Comment by Competizione** [comment]
For me it will be also a benefit to see the charging state to create an reminder if I forgot to charge it and run into out of power when I will use it. But its just a nice to have. This means after x minutes of use after charging I will get a reminder. Maybe a work around for the missing battery level.
