### ISSUE TITLE
Unkown BLE_monitor

### ISSUE THREAD

**Issue by Next9999** [custom-components/ble_monitor#586]
Great Work
Very Happy to have that feature

i have many Unkown BLE_monitor that show up....Govee, Ruuvitag

Tks again for the work

**Comment by Ernst79** [comment]
Could you describe what your issue exactly is, it’s not clear to me. Any errors in the HA log?

**Comment by Ernst79** [comment]
Closing this issue, due to no response. Feel free to reopen, if the issue isn't solved and provide some more information.
