### ISSUE TITLE
Feasycom BLE Beacon erroneously "checked in"??

### ISSUE THREAD

**Issue by danielbrunt57** [custom-components/ble_monitor#587]
The beacon is plugged into my car's USB port which is parked in my garage and there's supposedly no power with the car off but it was just seen.  Should I have my car checked?????
![image](https://user-images.githubusercontent.com/49846893/147225071-3f67009c-85ec-461a-8f9f-b822136410f7.png)
![image](https://user-images.githubusercontent.com/49846893/147225383-0857c657-b3b9-42fd-b3d8-2272278345bd.png)

**Comment by Ernst79** [comment]
I think your car goes out during the night to meet other cars 😃

I don't know what kind of car you have, but perhaps it does some updating during the night, during which some power is turned on. To be honest, I have no idea, BLE monitor can only report "home" when a BLE advertisement from a defined MAC is received. The only other thing I could imagine that a restart of HA during the night could cause this, for some reason. Did HA restart at 2.00 h?

**Comment by danielbrunt57** [comment]
LOL! Maybe it's lonely?!?!
No, HA did not restart.  Was sitting here on the computer when the garage door opened.  Nothing explainable in HA.
I just posted on the Honda Clarity forum as another strange issue occurred with the car on the weekend.  Between Friday night and Sunday night all 4 windows opened... https://www.clarityforum.com/threads/some-extreme-weirdness-happening.1765/
Something weird is going on with it...possessed??
Hope you enjoy the laugh...

**Comment by Thrilleratplay** [comment]
@danielbrunt57 Unrelated to ble_monitor and HA, you mention your car is in a garage but are there other similar cars in the area that are parking on the street or in driveways?  Someone may be breaking into cars using a wireless transmitter to roll down the windows/unlock doors.

**Comment by danielbrunt57** [comment]
Thanks and ! will certainly take that into consideration but I don't think that's what happened.
1. I don't think it's possible to wirelessly roll down windows.  Unlock doors yes, but the car was still fully locked and nothing was taken.
2. It doesn't explain the BLE beacon powering up and broadcasting earlier today.

**Comment by danielbrunt57** [comment]
I was just visiting the Clarity forum checking my post (no reads yet) but I started reading other new posts and in this one https://www.clarityforum.com/threads/obd-ii-sensor-goes-to-sleep-and-cant-get-up.1762/ there is mention that when remote climate is engaged, the USB ports are alive...
> Well okay one more exception, when running remote climate the HV system is active, because both the heater and the AC compressor run off of the HV battery. I am not sure but I think the 12V battery gets charged during remote climate. Interesting sidenote, the USB ports provide power when running remote climate.
The only flaw in this being a possibility earlier today is that the remote climate option does not work when the car is plugged in and charging from a Level I charger, which mine was and still is...

**Comment by danielbrunt57** [comment]
"As for the windows, if you press the unlock button on the fob, then press it again and hold it, all four of the windows will come down." - This explains all 4 windows being down!
"The only time that I know of that the USB ports are powered is when the car is on, or when running remote climate." - I just tested this and the BLE tracker/USB port did not power up.  So still a mystery...
