### ISSUE TITLE
QingPing CGPR1 shows wrong and fixed status

### ISSUE THREAD

**Issue by zhengxiaobu** [custom-components/ble_monitor#591]
QingPing CGPR1 sensor can be connected, but shows wrong and fixed status all the time like below.
<img width="308" alt="截屏2021-12-27 下午5 56 55" src="https://user-images.githubusercontent.com/29325925/147460117-22350c13-37e3-4ef3-a971-0adc4ca32c20.png">
Tried a few times, but got same results. Motion cannot be trigger, illuminance stucks at 15lx every time...
Encryption key is gotten via Xiaomi Cloud Tokens Extractor.

**Comment by Ernst79** [comment]
When was the last update?

![image](https://user-images.githubusercontent.com/24375847/147462817-88fa51b9-40db-49aa-91d0-1c11e2cc61ac.png)

What is the battery level (sorry, my Chinese isn't that good :-) )

**Comment by zhengxiaobu** [comment]
I'm so sorry for waiting so long... Battery level shows "unknown", motion detector shows "not activated". Their last updates are all as the same as my HomeAssistant's start time.

**Comment by Ernst79** [comment]
I suspect that it's a bad reception issue, it just isn't receiving any update (except the restore state during HA restarts). Is it possible to move the sensor closer to your HA machine? Try the tips in the FAQ about reception issues.

**Comment by zhengxiaobu** [comment]
I'm back again... There is nothing different after I move the device just next to my HA host pi. (T_T)
I tried to delete and re-added this device, but it gave me the same result as I mentioned above.

**Comment by Ernst79** [comment]
Strange. You could try to re-add it to MiHome and after syncing with the cloud, extract the new encryption key.

**Comment by zhengxiaobu** [comment]
Problem solved! Thank you for your great works!

**Comment by Ernst79** [comment]
the token sometimes changes. e.g. when you change the battery or accidently press the pair button.
