### ISSUE TITLE
New Device Request -- RadonEye RD200

### ISSUE THREAD

**Issue by yieldhog** [custom-components/ble_monitor#593]
Hi -- would love to see this aded to BLE Monitor. A couple of people have created their own python and ESP32/ESPHome scripts, but would love to have it all in one spot for ease of maintenance:

Python: https://github.com/ceandre/radonreader/blob/master/radon_reader.py
ESPHome: https://github.com/BrewNinja/RadonEye-ESP32

**Comment by Ernst79** [comment]
This device requires a connection to be set up, which is not supported by BLE monitor. BLE monitor can only listen passively.
