### ISSUE TITLE
Govee H5075 unit confusion

### ISSUE THREAD

**Issue by fovea1959** [custom-components/ble_monitor#601]
I have a single Govee H5075.

Using the UI, I have the device configured in HA for Fahrenheit, it shows the temperature as 23 F (the current temperature is 23 C).

If I change the configuration to show Celsius, it shows the temperature as 75 F (which *is* the temperature, but I asked for Celsius?)

**Comment by Ernst79** [comment]
Temperature units can be confusing. There are two settings, one for what you want to see in HA, and one for what is being send by the sensor. 

1. What you see in HA can be set with Configuration, Settings, General

![image](https://user-images.githubusercontent.com/24375847/148114901-e941a3b3-5e60-4e17-94ed-7919b73b5a44.png)

2. What the sensor broadcasts can be set in the BLE monitor options --> select your device in the devices drop down menu. 

![image](https://user-images.githubusercontent.com/24375847/148116260-463fa3de-ca42-4faa-af56-7382e5fd8ce7.png)

Govee sensors send data in Celsius, so leave the 2nd setting to °C. 

If you want to see Fahrenheit in HA, set the first setting to F (this is what you want to see) and the second setting to °C (this is what the sensor sends into the air). HA will convert the °C to F automagically.

**Comment by fovea1959** [comment]
Ah. Makes perfect sense once explained. Thank you!
