### ISSUE TITLE
2 devices successful but two are not...

### ISSUE THREAD

**Issue by danielbrunt57** [custom-components/ble_monitor#603]
I can add and track my BLE tracker in my Honda and also a BT RGB light controller for my aquarium but I've added my Honda HandsFreeLink BT MAC (type: Car Speaker-AAC) and also my Honor Magic watch MAC and they do not track and I am wondering why...

![image](https://user-images.githubusercontent.com/49846893/148168258-9eb2d0e4-6da8-41e9-8c7e-47e504536b4b.png)
![image](https://user-images.githubusercontent.com/49846893/148168547-5bf40912-d707-443e-9cc5-fbf038635236.png)

**Comment by Ernst79** [comment]
Perhaps these devices aren't Bluetooth Low Energy Devices, but normal Bluetooth. 
I see that the Honor Magic watch 2 does support BLE, but it might be randomizing its MAC, changing every few seconds/minutes.

**Comment by danielbrunt57** [comment]
The Honda HandsFreeLink does not appear to be BLE but Honor Magic is and it's MAC (ac:e3:42:71:9e:e9) has been seen by my phone since 2021-07-05 20:01:59.   No worries, would be nice to track my watch though!

![Screenshot_20220104_234232_com pzolee bluetoothscanner](https://user-images.githubusercontent.com/49846893/148179320-7bb12453-e4df-4a29-9d85-2ff624fc0fc4.jpg)

**Comment by Ernst79** [comment]
Is the watch connected to some app? I remember that a BLE device that is connected to some other device, can only communicate directly between these two devices. There are two types of BLE communication, passive, just broadcasting into the air, which can be read by any other device (this is what BLE monitor is listening to) and by connecting to it, limiting the communication to communication between the two devices. Closing the app should make the watch to return to the first type of communication.

**Comment by danielbrunt57** [comment]
Hmmm..  it is connected to my phone so that is likely the issue...

**Comment by Ernst79** [comment]
You could investigate it by making a HCIdump for several minutes (save it to a file), and than look into is if you can find your MAC in one of the advertisements. If the MAC is `ac:e3:42:71:9e:e9`, you have to search for `e9 9e 71 42 e3 ac` (reversed per two characters).
