### ISSUE TITLE
Configure Oral B 7000

### ISSUE THREAD

**Issue by Imadox** [custom-components/ble_monitor#604]
Hello,

How we can configure Oral B device ?
I get only two sensors 
![image](https://user-images.githubusercontent.com/4663939/148207808-8ae3d74b-9154-4b49-a63e-7bec53c0bc0a.png)

**Comment by Ernst79** [comment]
You can find additional info about the state when you select the toothbrush sensor and look at the sensor attributes. 

What do you want to "configure", things like turning it on? That won't be possible, as BLE monitor is a passive component, only listening to data that is send by the toothbrush. However, you can use automations in HA to automate other things, like turn the light off, 2 minutes after the toothbrush became "Inactif"
