### ISSUE TITLE
New Device Request - Samsung Smart Tag

### ISSUE THREAD

**Issue by KitHubek** [custom-components/ble_monitor#610]
https://www.samsung.com/us/mobile/mobile-accessories/phones/samsung-galaxy-smart-tag-1-pack-black-ei-t5300bbegus/

Using BLE 5.0

![smarttag](https://user-images.githubusercontent.com/91805313/148588325-d7e9c0e4-e03d-4452-a114-7e74e727cfd5.jpg)

**Comment by Ernst79** [comment]
I don't think this device works with a fixed mac address. According to the docs, they say that it can only be connected to a Galaxy phone. You could try to see if you can catch some BLE advertisement with a BLE scanner.

**Comment by KitHubek** [comment]
is ble scanner app on android devices? If yes, i can check what You want

**Comment by Ernst79** [comment]
Yes, you could also use the android app Bluetooth LE Scanner to collect data.

https://play.google.com/store/apps/details?id=uk.co.alt236.btlescan

**Comment by KitHubek** [comment]
ok, installed. Smart tags are on list

**Comment by Ernst79** [comment]
Can you post some printscreens by making a scan, stop the scan and click on the smart tag entry. I need all the data from that screen. Do NOT click on connect (as BLE monitor won't be able to connect).

**Comment by KitHubek** [comment]
![Screenshot_20220107-203902_Bluetooth LE Scanner](https://user-images.githubusercontent.com/91805313/148598042-1b2ea6a8-d62d-45b2-baf7-17ebbc254049.jpg)

**Comment by Ernst79** [comment]
Ok, there is some service data 

```
17 16 5A FD 15 0E D0 00 67 16 90 25 29 0E 72 B3 00 00 00 C7 C7 3C AC
```

You will first need to figure out if the `Device address` (2nd line) stays constant. Could you try a few times to see if the MAC stays the same over time?

**Comment by KitHubek** [comment]
ok, now scan again and :( addres changed

**Comment by Ernst79** [comment]
Ah, I was already afraid of that. Unfortunately, that means that we can't add it to BLE monitor, we need a fixed MAC address.

**Comment by KitHubek** [comment]
ok, understand. thanks for support
