### ISSUE TITLE
BLE monitor URL not accepted

### ISSUE THREAD

**Issue by koentelg** [custom-components/ble_monitor#613]
I have a RaspoberryPI 4 8Gb, with home-assistant installed, i use  core 2021.12.8 and supervisor 2021.12.2 when i add the URL i get an error see image. And i don't know how do i enable bleutooth in homeassistant.
![Schermafbeelding 2022-01-07 095801](https://user-images.githubusercontent.com/76107578/148640065-67a173b5-3989-45b4-835c-ba84920d650a.png)

**Comment by Ernst79** [comment]
You can't install it as a Add-on. You will have to install it with HACS.
