### ISSUE TITLE
New Device Request: Inkbird IBT-4XS

### ISSUE THREAD

**Issue by error33-priv** [custom-components/ble_monitor#616]
Hi, could you add support for the following device? https://inkbird.com/products/ibt-4xs
![Screenshot_20220108-215005_Bluetooth LE Scanner](https://user-images.githubusercontent.com/76244512/148659675-438e4735-de5e-44e3-8097-5df03dcc3545.jpg)

Let me know if you need any further information!

**Comment by jds11111** [comment]
I have the IBT-4XP version, which apparently is just the waterproof version of this one. I wanted to provide more info, but the log files in HA just baffle me.  They seem to be spread all over. Where am I supposed to get this one?  From /config/home_assistant.log I don't see anything:
```
config $ more home-assistant.log |grep ble_monitor
2022-01-08 16:20:41 INFO (MainThread) [custom_components.ble_monitor] Attention! Option report_unknown is enabled for Inkbird sensors, be ready for a huge output
2022-01-08 16:20:41 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.ble_monitor
2022-01-08 16:20:41 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.ble_monitor
2022-01-08 16:20:41 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.ble_monitor
2022-01-08 16:33:29 INFO (MainThread) [custom_components.ble_monitor] Attention! Option report_unknown is enabled for Off sensors, be ready for a huge output
2022-01-08 16:33:29 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.ble_monitor
2022-01-08 16:33:29 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.ble_monitor
2022-01-08 16:33:29 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.ble_monitor
```

**Comment by Ernst79** [comment]
Try to use report_unknown: Other, this will collect all incoming BLE data. Also try to find the MAC address of the sensor, this will make it easier to find your sensor data.

**Comment by Ernst79** [comment]
@error33-priv could you also show a printscreen of the parts where you scroll down.

**Comment by error33-priv** [comment]
![Screenshot_20220109-103912_Bluetooth LE Scanner](https://user-images.githubusercontent.com/76244512/148677062-f134de1a-f601-48fe-9e28-b8357231ae2d.jpg)

There you go!

**Comment by Ernst79** [comment]
Please try 6.9.0-beta, I think both devices will work.

**Comment by error33-priv** [comment]
Had the device turned on for 30min, not showing up in HA - I'll provide some logs tomorrow.

**Comment by Ernst79** [comment]
Ok, just send me some ble data and I’ll have a look.

**Comment by error33-priv** [comment]
[home-assistant.log](https://github.com/custom-components/ble_monitor/files/7835995/home-assistant.log)

Log attached - thank you for your support!

**Comment by Ernst79** [comment]
Thx, I found the issue, try with 6.9.2.

**Comment by error33-priv** [comment]
It's working, awesome! Thank you very much!

**Comment by Ernst79** [comment]
@jds11111 Can you let me know if it works for your sensor as well?

**Comment by jds11111** [comment]
Sorry, I have been out sick for several days, so am a bit behind. i updated to the latest, 6.9.4 I think, but it shows up in integration as unloaded.

**Comment by Ernst79** [comment]
No problem. When you are better, can you try to collect some BLE data with `report_unknown: Other`, or, if that doesn't work, with the Bluetooth LE Scanner app on android, like in the printscreens from @error33-priv

**Comment by jds11111** [comment]
I can't collect any data because the new integration won't even load in HA. That is a bigger problem right now.

**Comment by Ernst79** [comment]
That's a HACS issue, see #622 (with solution)

**Comment by jds11111** [comment]
Thanks @Ernst79 that fixed it. I will try the new version later.

**Comment by jds11111** [comment]
I can confirm that v6.9.4 works with Inkbird IBT-4XP !
Many thanks @Ernst79 .

**Comment by galapogos01** [comment]
Any idea what the pairing code is for these devices? 0000 and 1234 don't seem to work. Thanks!

**Comment by Ernst79** [comment]
I don't think you need a pairing code to make it work with BLE monitor
