### ISSUE TITLE
Request ; Support for Tile Pro Tracker

### ISSUE THREAD

**Issue by klona** [custom-components/ble_monitor#619]
Hi, 
Thanks a lot for your work and sharinf and support.
I got a Tile Pro device not recognized
https://fr.tile.com/product/686603/pro-2-pack

Attached the dump file.
Please let me know if you need any other information.

/Klona
[dump_Tile_Pro.txt](https://github.com/custom-components/ble_monitor/files/7835288/dump_Tile_Pro.txt)

**Comment by Ernst79** [comment]
I think Tile trackers have a random, changing MAC address, so this won't work with BLE monitor. BLE monitor requires a fixed MAC address.

**Comment by klona** [comment]
Hi,
logged on last 24h and still the same MAC. Removed battery on Tile Pro and back with same MAC.
Will wait a few days and let you know if still the same.

**Comment by Ernst79** [comment]
ok, thanks, if it fixed, we can try to add it.

**Comment by klona** [comment]
Still MAC fix adress today so it seems good.
Thanks for the tip I did'nt notice you can add any device that way.
it's added and will do some testing, but it's already tracked as "Home" what is true !
Tell me if I can help in any way to add it definitively.

Thanks,
Klona

**Comment by Ernst79** [comment]
The current device tracker is just home when it sees the specified MAC, regardless of the device you use. It’s away after a certain time not having received an update from the device (time can be set in the options). Works on any device, as long as it has a fixed MAC. 

For the tile pro, it also sends some data, called the service data. In your case, it has send `02 00 48 0d 3b 82 89 5d 9e e4`. This is a byte string, so it has to be read per two characters. We need to figure out if this data means something, and if so, what it means. Most of the times, google gives some hints. I had a quick look, not found something yet. Will do a more thorough search later.

**Comment by klona** [comment]
Yes, i had it on the home / away behaviour.
The tile is on a 2 min update time it seems, so I set on device settings  : tracker scna interval : 60 & device tracker consider home : 180
And i dont get anymore false away state.
My need it to add Tile on my 2 trascan, and automate some aleert when we forget to put it or to get it back (what is all the time...). So 3 min is enough.

for value hidden in the service data, it cant be a lot, as Tile do not report anything in the android Tile app. Not even battery level...
Is that possible to get the signal level ?

Thanks,
Klona

**Comment by Ernst79** [comment]
can you get some more BLE data, to see which data changes, e.g. when you move. Try to make notes when you move e.g. to match things with the HA time stamps. 

Signal strength is RSSI, this is already included in the attributes of the device_tracker

**Comment by klona** [comment]
Hi, sorry was badly busy on work..
i did some testing, bu really not easy to guess anything..
Please find attached what I was able to extract. 
Wasn't able to find any pattern but not expert at all..

And I got plenty of bluetooth devices around me, so a lot of shit in the logs..
A nice feature would be able to filter logs for one unknown device based on MAC.

[trace.txt](https://github.com/custom-components/ble_monitor/files/7896239/trace.txt)

**Comment by Ernst79** [comment]
Can you try it with 7.3.3-beta. I looks like it uses the iBeacon format, which is added in 7.3.1-beta. 

Please check the temperature and humidity, as it seems to give strange results.

**Comment by Ernst79** [comment]
7.3.8 has been released, should be recognized as iBeacon
