### ISSUE TITLE
Setup failed for ble_monitor: Integration not found.

### ISSUE THREAD

**Issue by taczirjak** [custom-components/ble_monitor#622]
After upgrading to 6.9.2, logs show Setup failed for ble_monitor: Integration not found.
Home Assistant 2021.12.8

**Comment by Ernst79** [comment]
See #615 

It's an issue in HACS 1.19.0, which copies the installation files to the wrong place. 

HACS 1.19.2 solves the issue. Just update HACS first, restart HA and than "redownload" BLE monitor again by clicking on the three dots --> "redownload"

Files will than move back to the place where they should be.

**Comment by McGiverGim** [comment]
I had the same problem and your solution worked for me. Thanks!

**Comment by KitHubek** [comment]
the same here, but update hacs and redownload BLE integration fixed problem. thanks

**Comment by inferusvv** [comment]
I've redownloaded repository but still can't see it in Integrations. HACS 1.19.3

**Comment by Ernst79** [comment]
Did you restart HA after the HACS installation?

Also check the folder /config/custom_components/ble_monitor/ble_monitor/ and move all files to /config/custom_components/ble_monitor/

**Comment by inferusvv** [comment]
Yes. I even redownloaded HACS, restarted, redownloaded BLE, restarted..

And here is my /config/custom_components/ble_monitor folder:
![Снимок экрана 2022-01-12 в 17 49 14](https://user-images.githubusercontent.com/3227120/149162947-972f0352-8b0c-4f4b-b9e0-8a00ae1e9f32.png)

Integrations:
![Снимок экрана 2022-01-12 в 17 50 15](https://user-images.githubusercontent.com/3227120/149163148-fb8bcf86-63b9-4279-bcb0-88c044b37158.png)

**Comment by Ernst79** [comment]
Ok, files are on the correct location, try hitting F5 a couple of times

**Comment by inferusvv** [comment]
@Ernst79 OMG, seems to be it helped :D Thank you and sorry for bothering

**Comment by Ernst79** [comment]
no problem, just a browser cache issue
