### ISSUE TITLE
Inkbird IBS-TH1

### ISSUE THREAD

**Issue by Flexz** [custom-components/ble_monitor#623]
Hi! Could you add support for this sensor?

MAC 49:21:08:30:67:A0
Readings from Engbird app:
Temp -6.5
Hum 34%
Bat 84%

> 2022-01-10 17:49:54 INFO (Thread-3) [custom_components.ble_monitor.ble_parser] Unknown advertisement received: 043e1302010000a06730082149070201060302f0ffbc
> 2022-01-10 17:49:54 INFO (Thread-3) [custom_components.ble_monitor.ble_parser] Unknown advertisement received: 043e1302010000a06730082149070201060302f0ffbc
> 2022-01-10 17:49:57 INFO (Thread-3) [custom_components.ble_monitor.ble_parser] Unknown advertisement received: 043e1302010000a06730082149070201060302f0ffbc
> 2022-01-10 17:49:57 INFO (Thread-3) [custom_components.ble_monitor.ble_parser] Unknown advertisement received: 043e1302010000a06730082149070201060302f0ffbc
> 2022-01-10 17:50:01 INFO (Thread-3) [custom_components.ble_monitor.ble_parser] Unknown advertisement received: 043e1302010000a06730082149070201060302f0ffbc
> 2022-01-10 17:50:01 INFO (Thread-3) [custom_components.ble_monitor.ble_parser] Unknown advertisement received: 043e1302010000a06730082149070201060302f0ffbc

There are more unknown messages, not sure if these are from the Inkbird. I've attached the full log.
[ble.unk.log](https://github.com/custom-components/ble_monitor/files/7840092/ble.unk.log)

**Comment by Ernst79** [comment]
Can you try to collect some other data with `active_scan: True` in YAML / enable Active Scan in the options if you use UI configuration. 

These messages do not contain data, but I remember that for the IBS-TH2, we had to enable active scan (see #605) to get the longer advertisments. I think you will need `report_unknown: Other` to get the messages.

**Comment by Flexz** [comment]
I've enabled active_scan and got longer messages

> Unknown advertisement received: 043e1302010000a06730082149070201060302f0ffbc
> Unknown advertisement received: 043e1302010000a06730082149070201060302f0ffbc
> Unknown advertisement received: 043e1c02010400a067300821491004097370730aff3708240f01bc075408bb
> Unknown advertisement received: 043e1c02010400a067300821491004097370730aff3708240f01bc075408bb

Full log attached

[ble.unk2.log](https://github.com/custom-components/ble_monitor/files/7841047/ble.unk2.log)

**Comment by Ernst79** [comment]
Thanks, will add it tonight

**Comment by Flexz** [comment]
Hey, you're right. Looks like I've missed an update for ble_monitor. Having update flags scattered in different places in HA is confusing sometimes

**Comment by Ernst79** [comment]
I have renamed it to IBS-TH in 6.9.3. If you have already added this device, it will keep the old name (to prevent HA errors). If you want to use the new name, try to delete it and re-add it.
