### ISSUE TITLE
Govee B5178 reports outdoor humidity as 2nd temperature

### ISSUE THREAD

**Issue by fovea1959** [custom-components/ble_monitor#625]
Just received my B5178.

After adding it to the configuration, I have most of the usual sensor.ble\_{sensor}\_{MAC} entries, as well as sensor.ble\_{sensor}\_outdoor\_{MAC}

However the outdoor humidity appears to be reporting as sensor.ble_temperature_{MAC}_2 instead of the expected sensor.ble\_humidity\_outdoor\_{MAC}.

The units for it still seem to be humidity (%), and it has the humidity icon.

![image](https://user-images.githubusercontent.com/5349196/148886027-9173a40a-6763-4e48-adbf-45635a534220.png)

**Comment by Ernst79** [comment]
Thanks, fixed in 6.9.4

**Comment by fovea1959** [comment]
I'm just curious, what was the commit? I wanted to see what the fix looked like.

**Comment by Ernst79** [comment]
commit: https://github.com/custom-components/ble_monitor/commit/bc0afa2da8d36e5f18ce8cfb27d0283192d6464f
