### ISSUE TITLE
Device tracker after restart

### ISSUE THREAD

**Issue by Hydci** [custom-components/ble_monitor#627]
Hello, I use your components to track presence with 2 nut however I noticed that after a restart if one of the two monitored devices is not present the status remains unknown despite the state after restart option is checked, is this an expected behavior or a problem?

**Comment by Ernst79** [comment]
this is an issue, I will look into it.

**Comment by Ernst79** [comment]
I tried to reproduce the issue, but I don't see this behavior. It is restored fine after a restart. 

Can you check the following. There are two places where you can set the restore_state option. You can set it as a general, overall, setting, in the first screen you see when you open the options menu of BLE monitor

![image](https://user-images.githubusercontent.com/24375847/149386650-07d38213-1369-4fdc-b26f-af1e41526451.png)

And there is a second option in the menu when you select the specific device. This last setting will overrule the general setting, if you set it to something other than `Default`. Can you check both settings and post here how these two settings are set? 

![image](https://user-images.githubusercontent.com/24375847/149386806-729b8ba6-dccf-4214-bf56-1026e75fb34c.png)

**Comment by Hydci** [comment]
I therefore looked at what you told me in the general parameters the box and ticked and in the parameters of the device followed it is default so I do not understand why it does not work at worst if instead of putting unknown it gives me was away that would work around the problem

**Comment by Hydci** [comment]
I tried over and over and over again the same problem ...

Option device restore states default or true it's the same after restarting the status remains unavaible

to create the problem:
1) Off the device tracker
2) Restart HA (configuration ==> parameter ==> reboot)
3) Status is unavaible

Why the status of the device tracker does not go away and remains unavaible

**Comment by Ernst79** [comment]
I have no idea, I tried it myself, it works fine. What kind of device do you use (shouldn't really matter, to be honest)? My settings are at the end of the video. In the video, I show the state (away), do a restart and show the state again (still away). Battery is removed from the device.

https://user-images.githubusercontent.com/24375847/149522192-d8b225a2-8ff0-4238-a923-f70867b7a1ab.mp4

**Comment by Hydci** [comment]
My settings are the same as you.
Yes I see for you that it works, I tried to delete and redo the device but the same it does not work.
my presence and manage by this [https://www.amazon.fr/Nut-localisateur-portemonnaie-portefeuille-t%C3%A9l%C3%A9commande/dp/B01MA5WFJR](url)

**Comment by Ernst79** [comment]
The only difference is that I use a device that also has sensors (temperature sensors). I will try to reproduce it with a BT device that isn't a (HA) sensor as well.

**Comment by Hydci** [comment]
All right, I'm waiting for your return

**Comment by Hydci** [comment]
Hello I come to the news for the state unavailable problem after the restart to know if a fix had been found ?

**Comment by Ernst79** [comment]
Sorry, not yet. Have been busy working on some other things (and bought a new house, which also takes some time 😄 I'll try to look into it a.s.a.p.

**Comment by Ernst79** [comment]
I have tried it again, with a device that is not a sensor, but still no problem. It just restores `Away` after a restart. 

Unfortunately, this makes it impossible for me to debug. I have no idea why it isn't working in your case.

**Comment by Hydci** [comment]
Hello,
Thank you for looking unfortunately I do not know where the problem comes from either I noticed that after a start if it was absent it was not even in the list of devices in the c integration It's a misunderstanding, thanks for watching anyway

**Comment by Ernst79** [comment]
What do you mean by, it wasn't even in the list of devices? In the BLE monitor options, in the pull down menu "devices" ? Or when you are in the integration menu in HA, and click on "x devices" on the BLE monitor tile?

**Comment by Hydci** [comment]
Sorry m'y english is not good 

Here Or when you are in the integration menu in HA, and click on "x devices" on the BLE monitor tile?

**Comment by Ernst79** [comment]
No problem, pictures can help

In which list don't you see your device after a restart?

1. Here when you click on devices
![image](https://user-images.githubusercontent.com/24375847/152319756-c5f0f69d-f3b5-4465-8618-3c437aed80ad.png)

or
 
2. when you click on configure and than look in this list. 
![image](https://user-images.githubusercontent.com/24375847/152319972-55acd466-79e0-46a8-a415-b8ae102ad1d1.png)

**Comment by Hydci** [comment]
the screenshots on a good idea, so the answer is the first screenshot (number 1)

**Comment by Ernst79** [comment]
That's strange. Could you make a printscreen of the BLE monitor options and of the device options. Like in my 2nd printscreen. And one after selecting the MAC of the device and clicking on submit (of the new window that opens).

**Comment by Hydci** [comment]
If I understand correctly you want this
![add-on config](https://user-images.githubusercontent.com/36527391/152339946-5771ff5a-5b89-45ca-a56a-f28e7c5774e9.png)
![device config](https://user-images.githubusercontent.com/36527391/152339970-bdabd17e-4479-4a68-a332-845135d7dbfa.png)

**Comment by Ernst79** [comment]
Could you try to change the MAC address of the device to track to capital (upper case) letters, (`01:5C:5E:11:5D:68`)? Just to see if it makes any difference

**Comment by Ernst79** [comment]
I think your issue might be fixed in beta version 7.9.0-beta. It had something to do with the lower case MAC address. Could you check if it works for you (keep the lower case MAC in your configuration)? Let us know if it works for you.

**Comment by Ernst79** [comment]
I think this issue is fixed in 7.9.2. If it isn't fixed, you can reopen this issue.

**Comment by KameDomotics** [comment]
@Hydci
 Which Nuts do you use? I have these but they don't work with the integration.

![IMG_8280](https://github.com/custom-components/ble_monitor/assets/47695661/7041907d-f128-435e-b2d5-dff781835d01)
