### ISSUE TITLE
Inkbird IBT-6X six probes bbq thermometer

### ISSUE THREAD

**Issue by marcomiani** [custom-components/ble_monitor#630]
Hi,
I have a Inkbird IBT-6X compatible bbq thermometer.
I modified the source code ( the logic and the data format is the same as the iBBQ-2 only with four more values)  and I have it up and running in my home assistant installation.

This is a sample adv packet ( only one probe connected at position 1, my device mac is 18:93:d7:35:35:59 )
`0x0201060302F0FF17FF000000001893D7353559D200F6FFF6FFF6FFF6FFF6FF050969424251051218003801020A00`
as you can see in the manufacturer specific data segment there are  four bytes at zero, six bytes for the device mac address and six bytes couples for the probes temperature.

can it be integrated?  do you prefer a pull request or more samples ?

thank you 
Marco

**Comment by Ernst79** [comment]
This is all the info i need, thx. Will add it coming week.

**Comment by Ernst79** [comment]
Added in 7.1.0, please close the issue if it all works

**Comment by marcomiani** [comment]
tested, works fine. thank you
