### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by jump396** [custom-components/ble_monitor#633]
Hi all,
i've some problems with temperature/humidity sensors in the past week, i don't know if dependt from last updates...

```
Logger: homeassistant
Source: custom_components/ble_monitor/sensor.py:577
Integration: Passive BLE monitor (documentation, issues)
First occurred: 08:25:24 (1 occurrences)
Last logged: 08:25:24

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ble_monitor/sensor.py", line 224, in async_run
    entity.collect(data, period_cnt, batt_attr)
  File "/config/custom_components/ble_monitor/sensor.py", line 577, in collect
    <= data[self.entity_description.key]
KeyError: 'temperature'
```
there are 2 Thermoplus and 1 MHO-C401 (Azarton), all with original firmware.
ASAP i will post debug data log.

**Comment by Ernst79** [comment]
We need to do some debugging. Could you try the following: Edit the file `/config/custom_components/ble_monitor/sensor.py`, replace the following part on line 575-579

```python
        if (
            not self._lower_temp_limit
            <= data[self.entity_description.key]
            <= self._upper_temp_limit
        ):
```

with the following

```python
        try: 
            test = data[self.entity_description.key]
        except KeyError:
            _LOGGER.error("failing data is %s", data)
        if (
            not self._lower_temp_limit
            <= data[self.entity_description.key]
            <= self._upper_temp_limit
        ):
```

After that, restart HA. After it fails, there will be another error in your logs, starting with "failing data is ....". Can you post that line here.

**Comment by jump396** [comment]
As your request:

failing data is {'firmware': 'Inkbird', 'temperature probe 1': 40.5, 'temperature probe 2': 26.6, 'temperature probe 3': 0, 'temperature probe 4': 26.9, 'temperature probe 5': 0, 'temperature probe 6': 0.8, 'rssi': -68, 'mac': '931200000215', 'type': 'iBBQ-6', 'packet': 'no packet id', 'data': True}

**Comment by Ernst79** [comment]
Do you own a Inkbird iBBQ-6 sensor (or your neighbour)?  Its a BBQ thermometer with 6 probes

**Comment by jump396** [comment]
Yes i do, it is a Thermoplus - Lanyard Hygrometer

**Comment by Ernst79** [comment]
Ok, the iBBQ-6 and Thermoplus Hygrometer apparently have a similar BLE format. I will look into it, to make sure they are being parsed separately.

**Comment by jump396** [comment]
ok @Ernst79 many thanks

**Comment by Ernst79** [comment]
Could you please try with 7.1.1-beta

**Comment by jump396** [comment]
I tried with 7.1.1 beta and it's working fine now

**Comment by jump396** [comment]
All right for me, I close the issue.
Many thanks to @Ernst79
