### ISSUE TITLE
device mi smart kettle pro mjhwsh02ym miketv12  not find

### ISSUE THREAD

**Issue by Shaderz** [custom-components/ble_monitor#640]
hello, i have a device mi smart kettle pro mjhwsh02ym  https://aliexpress.ru/item/1005002929525906.html
but not find my device in BLE

how me to adding my kettle  to home assistant?

**Comment by Ernst79** [comment]
Unfortunately, the pro version can’t be supported, as it is requirement a connection, which is not supported. See also https://github.com/custom-components/ble_monitor/issues/398

**Comment by GrubyRabbit** [comment]
It is still not supported?

**Comment by Ernst79** [comment]
No, See the above response. This device needs a connection, which is not possible with BLE Monitor. No plans to add that in the future, as we are moving everything to the official Home Assistant integrations. 

I think it will be easier to implement it in the xiaomi-ble integration, as that one does support connections (it currently connects to the plant sensor, to get the battery). Make a request on the HA forum.

**Comment by GrubyRabbit** [comment]
Thank you for response.

**Comment by asruda** [comment]
@Shaderz @GrubyRabbit 
I have the same xiaomi kettle pro. For the past few months, I haven‘t been able to find a way to control the pro version kettle in HA. 
So, I put together my own solution. It might be useful for you – feel free to try: https://github.com/asruda/mi_kettle_pro

**Comment by Shaderz** [comment]
> [@Shaderz](https://github.com/Shaderz) [@GrubyRabbit](https://github.com/GrubyRabbit) I have the same xiaomi kettle pro. For the past few months, I haven‘t been able to find a way to control the pro version kettle in HA. So, I put together my own solution. It might be useful for you – feel free to try: https://github.com/asruda/mi_kettle_pro

wow! very good! ))   Thanks, I've already installed the solution, and lo and behold, it works!   :)
