### ISSUE TITLE
issue when setup integration

### ISSUE THREAD

**Issue by robertomontinaro80** [custom-components/ble_monitor#642]
I've just installed repository by HACS. and selected passive ble monitor from integration. But when setup steered I receive an error without India and home assistant is not able to start. I see that custom component s folder has been created but the all home assistant doesn't start. I've already installed other custom components without problems...does this happen to someone else? Could you check if integration is ok in HACS please? Thanks
My sensor is Xiaomi mi temperature humidity monitor 2 (the little one squared)

**Comment by Ernst79** [comment]
I can't try at the moment, but I haven't received similar issues. Did you restart HA after the installation in HACS? Can you post the exact error from the HA logs?

**Comment by robertomontinaro80** [comment]
> I can't try at the moment, but I haven't received similar issues. Did you restart HA after the installation in HACS? Can you post the exact error from the HA logs?

just retried and again the same error. of course I restarted Ha after being downloaded the repository.
below the screenshot
![Screenshot_2022-01-21-20-31-04-635_io homeassistant companion android](https://user-images.githubusercontent.com/96392935/150589003-5e1e8e9a-7b35-45b3-8ebd-a0f209ca0ca7.jpg)

**Comment by Ernst79** [comment]
Any errors in the logs?, try to enable debug logging otherwise, this might give more clues. 

I notice the message `Connection lost. Reconnecting` Are you sure it's online?

**Comment by robertomontinaro80** [comment]
> Any errors in the logs?, try to enable debug logging otherwise, this might give more clues.
> 
> I notice the message `Connection lost. Reconnecting` Are you sure it's online?

HA lose connection after that error and I'm not able to reconnect. I have to delete the integration folder created in custom_components before and then restart HA...debug log I think they are activated and no errors showed there. :(

**Comment by robertomontinaro80** [comment]
> Any errors in the logs?, try to enable debug logging otherwise, this might give more clues.
> 
> I notice the message `Connection lost. Reconnecting` Are you sure it's online?

I see this log in HA, after that error:

`Logger: homeassistant.components.mitemp_bt.sensor
Source: components/mitemp_bt/sensor.py:152
Integration: mitemp_bt (documentation, issues)
First occurred: 10:50:09 AM (10 occurrences)
Last logged: 10:52:19 AM

Polling error Exit read_ble, no data (<Thread(SyncWorker_0, started 3024090176)>)
Polling error Could not read data from Mi Temp sensor 58:2D:34:36:4E:30
`

**Comment by Ernst79** [comment]
To be honest, I have no idea. 

Are you using mitemp_bt integration as well? Try to use only one BLE integration at the same time. 
Is mitemp_bt working?
 Perhaps an issue with your Bluetooth adapter.
Is your device connected to WiFi? Try an Ethernet cable temporary, WiFi is sometimes blocked by BLE signals.

**Comment by robertomontinaro80** [comment]
I've just updated to 7.5.0 but I can't see data from my Xiaomi mi temperature humidity monitor (the little one squared sensor)...I just see the level battery but unknown value for temp and humidity...no logs in my HA. Is it everything ok?

**Comment by robertomontinaro80** [comment]
Oh sorry...right now the sensor updated it's values. Everything is ok for me with the update. Thanks anyway

**Comment by Ernst79** [comment]
Yes, these sensors are a bit slow, up to 10 minutes.
