### ISSUE TITLE
HCI0 MAC change without losing the configuration

### ISSUE THREAD

**Issue by vtb77** [custom-components/ble_monitor#643]
Hello:

I use Home Assistant OS and have switched from the Raspberry Pi 3B+ to a Raspberry Pi 4.

Obviously, when changing the hardware, the MAC of the BLE changes.

Well, I configured the BLE devices from the UI interface. When restoring the HA backup in the new Raspberry, the configuration has the old MAC and no matter how much I mark in the configuration that it is configured with the new MAC, I get the error that the MAC of the BLE does not match the one configured. How can I change the MAC without losing the settings? Wouldn't it be possible that when it is configured through the UI interface, the HCI0 reference is saved instead of the MAC?

Thank you.

**Comment by Ernst79** [comment]
Could you post the exact error from the logs? A workaround is to modify it directly in the registry, but this is a bit tricky and could result in a non-working HA is you do it wrong.

**Comment by Ernst79** [comment]
Should be fixed in 7.3.5-beta

**Comment by vtb77** [comment]
Hello:

Thanks for the prompt response.

I will look for how to install the beta version that you indicate.

On the other hand, the error that appears once I have restored an HA backup on another Raspberry and trying to change the BLE interface is the following.

![Sin título](https://user-images.githubusercontent.com/71189405/151009132-8fc88d45-6914-48f7-ad20-8627aedf2758.png)

Thank you.

**Comment by Ernst79** [comment]
You can install the latest beta, currently 7.3.7-beta. You can do that in hacs, on the ble monitor card click on the three dots and than reinstall. Enable beta version and you should be able to select a beta version

**Comment by vtb77** [comment]
Hello:

Great, I've tried the latest beta version and it worked.

Thanks and good job.

Greetings.
