### ISSUE TITLE
LYWSD03MMC update rate

### ISSUE THREAD

**Issue by taha-yassine** [custom-components/ble_monitor#644]
I have an LYWSD03MMC temperature and humidity sensor and here is what my temperature graph looks like. Points are separated by roughly 10 minutes and sometimes the reported value displayed on the sensor doesn't match the value shown in HA. The sensor is about 2 meters away from my RPI4 running HA so RSSI is great (-55 dBm). Ideally I would like to collect measurements every minute or so to mitigate the lag. What can I do to improve resolution ? 
![image](https://user-images.githubusercontent.com/40228615/150623727-512804a1-5187-4037-9ff5-0e4ed460c54d.png)

**Comment by Ernst79** [comment]
The default firmware sends only one message per 10 minutes, exactly as you describe. To increase the interval, you have to use ATC firmware, in which you can set the interval to whatever you like. Flashing the sensor is easy, with an online tool. For more info, check https://github.com/atc1441/ATC_MiThermometer

the alternative firmware is fully supported by BLE monitor.

**Comment by taha-yassine** [comment]
Awesome, works perfectly. Thanks!
