### ISSUE TITLE
Xiaomi Mi Electric Toothbrush

### ISSUE THREAD

**Issue by Denis-blr** [custom-components/ble_monitor#645]
Hi, 
Please add the Xiaomi Mi Electric Toothbrush (Model: soocare.toothbrush.m1) to your Passive BLE Monitor integration. It's inconvenient to constantly use Mi Home to monitor the battery charge. :)

**Comment by Ernst79** [comment]
@Denis-blr I need some data from the toothbrush, to be able to add it. You can find instructions in the FAQ how to get this data. 

https://custom-components.github.io/ble_monitor/faq#my-sensor-is-not-in-the-list-of-supported-ones-how-to-request-implementation

**Comment by tunip** [comment]
Maybe this helps:
https://github.com/freenetwork/ble-in-xiaomi/blob/master/doc/devices/soocare.toothbrush.m1.md

**Comment by Ernst79** [comment]
@tunip Thanks for the link, but it looks like the toothbrush requires a connection, which is not supported in BLE monitor (as we passively listen to BLE advertisements). The link also states that advertisement data is not send by the toothbrush. So this unfortunately means we can't add support at the moment.
