### ISSUE TITLE
New device request, iBBQ one probe version

### ISSUE THREAD

**Issue by t-n** [custom-components/ble_monitor#660]
Hi!
I've got a bbq probe that reports as iBBQ (sold by Rubicson here in Sweden) 

I got it to work with locally by extending the Inkbird iBBQ implementation and just changing it to expect a single temperature value and adding 0x0D to the man_spec_data[0] check.

Device dump 043e2102010000d7652e9aec28150201060302f0ff0dff0000000028ec9a2e65d7f000b5

**Comment by Ernst79** [comment]
Yes, sure. Will add it asap

**Comment by Ernst79** [comment]
Added in #661 

Do you have a link to a picture of this device (for the docs)? Not sure which one it is,

**Comment by t-n** [comment]
Thanks for adding! 

But I believe you forgot to add iBBQ-1 to MEASUREMENT_DICT and MANUFACTURER_DICT in const.py :)

And a picture of it https://www.pricerunner.se/product/1200x630/1913081101/Rubicson-Wireless-Grill-with-Bluetooth-Stektermometer.jpg

**Comment by Ernst79** [comment]
You're right, I apparantly forgot to save `const.py`. Fixed in 7.3.9.
