### ISSUE TITLE
Honeywell BT Smoke JTYJGD03MI unknown

### ISSUE THREAD

**Issue by skywluke** [custom-components/ble_monitor#664]
Hi! I have Honeywell BT Smoke JTYJGD03MI. I try to intergate it, but it looks the entities are reported 'unknown'. The ble smoke detector entity always clear. I use BLE KEY, am i right?
![image](https://user-images.githubusercontent.com/44024933/151137951-c77d44e8-9760-4e16-a7bc-a8d42d4ff7be.png)

**Comment by Ernst79** [comment]
Yes, you will need to enter your encryption key. Please check it again if it hasn't changed. This sometimes happens, e.g. when you replace battery.

**Comment by skywluke** [comment]
Thanks for answer. I cheked it with token_extractor, but it isn't changed.

**Comment by Ernst79** [comment]
It could than be an issue with reception (range, SSD blocking Bluetooth signal).

**Comment by skywluke** [comment]
Reconnect to mihome, and extract new token, and it's working! Thank You for support! :-)
