### ISSUE TITLE
New Device:  Xiaomi Mijia Mi Smart Door Lock Youth Edition MJZNMSQ01YD

### ISSUE THREAD

**Issue by krzakx** [custom-components/ble_monitor#667]
Hi all.
I am looking forward to use MJZNMSQ01YD door lock with ble_monitor integration.
Would like ask you how to contribute in adding support of it. Any comunication investigation needed ? 

Currently supported doors lock are:
-  Xiaomi Aqara ZNMS17LM (N200)
- Xiaomi Aqara ZNMS16LM (N100)

which do broadcast properties like:

FINGERPRINT *
LOCK *
BATTERY
RESULT *
KEY ID *
ACTION *
METHOD *
ERROR *
TIMESTAMP *
RSSI *

Would that mean supporting the ZNMSQ01YD (from topic title) would be likely possible?

**Comment by Ernst79** [comment]
Most likely we can add it. We have a FAQ article how you can help me to get the data 

https://custom-components.github.io/ble_monitor/faq#my-sensor-is-not-in-the-list-of-supported-ones-how-to-request-implementation

**Comment by Ernst79** [comment]
Could you try 7.4.0-beta? Based on the info here https://github.com/AlexxIT/XiaomiGateway3/issues/481 I made an educated guess, so it might work with 7.4.0-beta

**Comment by krzakx** [comment]
I've just tried out with following logs:

`Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.ble_monitor.ble_parser.xiaomi
Source: custom_components/ble_monitor/ble_parser/xiaomi.py:821
Integration: Passive BLE monitor (documentation, issues)
First occurred: 13:57:57 (2 occurrences)
Last logged: 13:58:32

No encryption key found for device with MAC CD:BE:1C:99:E4:47`

**Comment by Ernst79** [comment]
This means that it works, but that it requires an encryption key. The FAQ explains how to get this key. 

https://custom-components.github.io/ble_monitor/faq#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key

**Comment by krzakx** [comment]
Thank you for support.
So I've extraxted encryption key but do not know where I can put it now. Sorry if this is doubt questions.
I thought I would be able to find device in /config/configuration.yaml but this is not a case.
Anyway I do belive I could somehow add/override current device conf with my Token Key. Could you guide me please?

**Comment by Ernst79** [comment]
I assume you have set up BLE monitor via GUI configuration. go to configuration, integrations and click on configure on the BLE monitor card. This will open the options, at the bottom there is a pull down menu with all the MAC addresses of devices that have been added, one of these is your LOCK. Select this one and click submit. This will open a new menu where you can enter your encryption key. Click submit twice and you are done.

**Comment by krzakx** [comment]
Thanks for continous support.
So one step further as new entity has shown like:
ble fingerprint CDxx1C99xxxx (MAC)
ble lock CDxx1C99xxxx (MAC)

but now I got this warning:

```
Logger: custom_components.ble_monitor.ble_parser.xiaomi
Source: custom_components/ble_monitor/ble_parser/xiaomi.py:817
Integration: Passive BLE monitor (documentation, issues)
First occurred: 14:59:20 (12 occurrences)
Last logged: 15:05:44

Encryption key should be 16 bytes (32 characters) long
```

**Comment by Ernst79** [comment]
It means that you have copied the wrong key. It's a bit confusing, I assume you have used Xiaomi Cloud Token extractor. Look for `BLE KEY`, this is the one you need. Make sure it has 32 characters, not 24.

**Comment by krzakx** [comment]
hmy.... there is  no `BLE KEY` entry.

Please see: https://ibb.co/3v5tLzm

**Comment by Ernst79** [comment]
The TOKEN is not the key you need (that's the confusing part). Did you add it to MiHome? This is required to make it generate the BLE KEY. MiHome should also be connected to the Xiaomi Cloud, to story the key in the cloud.

**Comment by krzakx** [comment]
Yes, I've added it to MiHome and it is connected to Chinese cloud server and even I've just made frimware update from 2.2.6._1090 to 2.2.6_1110 so it its very likely that Xioami Cloud connection is working (have some minimal doubts as 90% is Chinese and most operation I do intuitive).

I've also made some discussion and [mod on token_extractor.py](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/57) but results are not satisfying.
```

{'did': '1012157342', 'token': 'de344ee340e8ff38a059a3c6', 'longitude': '0', 'latitude': '0', 'name': 'Zamek', 'pid': '6', 'localip': '185.239.42.71', 'mac': 'CD:BE:1C:99:E4:47', 'ssid': '', 'bssid': '', 'parent_id': '', 'parent_model': '', 'show_mode': 1, 'model': 'loock.lock.v6', 'adminFlag': 1, 'shareFlag': 0, 'permitLevel': 16, 'isOnline': False, 'desc': '', 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'fw_version': '2.2.6_1110', 'needVerifyCode': 0, 'isPasswordEncrypt': 0}, 'uid': 193087701, 'pd_id': 1257, 'password': '', 'p2p_id': '', 'rssi': 0, 'family_id': 0, 'reset_flag': 0}
   NAME:     Zamek
   ID:       1012157342
   BLE KEY:  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
   MAC:      CD:xx:1C:99:xx:xx
   IP:       185.239.42.71
   TOKEN:    de344ee340e8ff38a0xxxxxx
   MODEL:    loock.lock.v6
   ---------
```

**Comment by Ernst79** [comment]
Could you try the following

In the file `custom_components/ble_montitor/ble_parser/xiaomi.py` change line747-750

from 

```python
    # check that data contains object
    if frctrl_object_include != 0:
        # check for encryption
        if frctrl_is_encrypted != 0:
```

to 

```python
    if frctrl_object_include != 0:
        # check for encryption
        if device_type in ["LYWSD03MMC"]:
            _LOGGER.error("info: %s, encryption: %s, data: %s", sinfo, frctrl_is_encrypted, data.hex())
        if frctrl_is_encrypted != 0:
```

Restart HA and copy the error lines from your log here. It will show me if the device has encryption and which type (legacy or V4/V5 encryption). You can remove it afterwards

**Comment by Ernst79** [comment]
I've included this device also in 7.4.1-beta. But please have a look at my previous post

**Comment by Ernst79** [comment]
Added in 7.5.0. Let me know when you have figured out the encryption type.

**Comment by pafftis** [comment]
Sorry not to breed topics by device.
I have a lock XMZNMST02YD
Which works through the integration of AlexxIT/XiaomiGateway3.
But it does not transmit all the castle statuses. Gives only open or closed door. And who exactly opened it with the help of a fingerprint does not transmit. Can your integration transmit fingerprint data?

**Comment by Ernst79** [comment]
Not sure, but most likely it will report the same as e.g. ZNMS16LM
https://custom-components.github.io/ble_monitor/by_brand#xiaomi-aqara

It has a `key_id`, which might be telling you who has used the lock, but I don't have this device myself, so can't confirm.

**Comment by Ernst79** [comment]
XMZNMST02YD is added in 7.5.1. Let me know the encryption type

**Comment by krzakx** [comment]
After brief pause, I'am back with the hope ;)

```
Logger: custom_components.ble_monitor.ble_parser.xiaomi
Source: custom_components/ble_monitor/ble_parser/xiaomi.py:754
Integration: Passive BLE monitor ([documentation](https://github.com/custom-components/ble_monitor), [issues](https://github.com/custom-components/ble_monitor/issues))
First occurred: 18:44:45 (3 occurrences)
Last logged: 18:46:21

info: MiVer: 4, DevID: 0x4e9 : MJZNMSQ01YD, FnCnt: 29, Not bound, Safety certification, encryption: 1, data: 131695fe4844e9041dbe0547629bf3ae483e42b5
info: MiVer: 4, DevID: 0x4e9 : MJZNMSQ01YD, FnCnt: 31, Not bound, Safety certification, encryption: 1, data: 131695fe4844e9041fc7d2c6a6e013a336029777
info: MiVer: 4, DevID: 0x4e9 : MJZNMSQ01YD, FnCnt: 33, Not bound, Safety certification, encryption: 1, data: 131695fe4844e904211d77966019396807d9e93b
```

**Comment by Ernst79** [comment]
Thanks, It's encryption version 4

```
MiVer: 4, DevID: 0x4e9 : MJZNMSQ01YD, FnCnt: 49, Not bound, Safety certification
result  ({'rssi': -86, 'mac': 'A4C1380283F4', 'type': 'MJZNMSQ01YD', 'packet': 49, 'firmware': 'Xiaomi (MiBeacon V4 encrypted)', 'data': False}, None)
Decryption failed: MAC check failed
```

So, this means that you will have to get your encryption key with method 1, 3 or 4, as described in the FAQ (method 2 is only for LYWSD03MMC).

https://custom-components.github.io/ble_monitor/faq#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key

**Comment by krzakx** [comment]
Method 1 - no BLE KEY entry, just double checked it.
Method 2 - here I am not able to sucessfully connect to device, even from smartphone or laptop
Laptop logs:

```
21:09:20: Disconnected.
21:09:20: Searching for devices
21:09:25: Connecting to: null
21:09:28: Detected Mi Thermometer
21:09:28: NotFoundError: No Characteristics matching UUID 00000019-0000-1000-8000-00805f9b34fb found in Service with UUID 0000fe95-0000-1000-8000-00805f9b34fb.
21:09:28: Reconnect 1 from 5
21:09:28: Detected Mi Thermometer
21:09:28: NotFoundError: No Characteristics matching UUID 00000019-0000-1000-8000-00805f9b34fb found in Service with UUID 0000fe95-0000-1000-8000-00805f9b34fb.
21:09:28: Reconnect 2 from 5
21:09:28: Detected Mi Thermometer
21:09:28: NotFoundError: No Characteristics matching UUID 00000019-0000-1000-8000-00805f9b34fb found in Service with UUID 0000fe95-0000-1000-8000-00805f9b34fb.
21:09:28: Reconnect 3 from 5
21:09:28: Detected Mi Thermometer
21:09:28: NotFoundError: No Characteristics matching UUID 00000019-0000-1000-8000-00805f9b34fb found in Service with UUID 0000fe95-0000-1000-8000-00805f9b34fb.
21:09:28: Reconnect 4 from 5
21:09:28: Detected Mi Thermometer
21:09:28: NotFoundError: No Characteristics matching UUID 00000019-0000-1000-8000-00805f9b34fb found in Service with UUID 0000fe95-0000-1000-8000-00805f9b34fb.
21:09:28: Reconnect 5 from 5
21:09:28: Detected Mi Thermometer
21:09:28: NotFoundError: No Characteristics matching UUID 00000019-0000-1000-8000-00805f9b34fb found in Service with UUID 0000fe95-0000-1000-8000-00805f9b34fb.
21:09:28: Something went wrong, to many reconnect's
```

Method 3 - I do currently investigating and here in advanced would like to ask if you guys know for what purpose are those _plugins_ https://nl.kapiba.ru/mihome/pluglist?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=pl&_x_tr_pto=wapp - I do see my [loock.lock.v6](https://nl.kapiba.ru/mihome/files/plugins/1000279.zip) device on list.

**Comment by Ernst79** [comment]
I don't know, I have used it once, but it was hard to get it working, but I succeeded in the end. I was also a bit worried about installing Russian apps at that time, but it worked in the end, and I don't think I was hacked 😄. If you don't trust things, I would try to ask some help from the 2nd method here https://github.com/atc1441/ATC_MiThermometer. Maybe there is an easy fix for the error you see.

**Comment by vevsvevs** [comment]
> Thanks, It's encryption version 4
This lock model is from 2019, it shouldn't have any encryption, imo.

> and I don't think I was hacked
Oh, you definitely were ))

**Comment by Ernst79** [comment]
@vevsvevs The BLE advertisement contains a byte that says if it uses encryption or not (and a lot of other useful info). In BLE monitor, the following code is used to extract this info.  

```
    frctrl = data[4] + (data[5] << 8)
    frctrl_mesh = (frctrl >> 7) & 1  # mesh device
    frctrl_version = frctrl >> 12  # version
    frctrl_auth_mode = (frctrl >> 10) & 3
    frctrl_solicited = (frctrl >> 9) & 1
    frctrl_registered = (frctrl >> 8) & 1
    frctrl_object_include = (frctrl >> 6) & 1
    frctrl_capability_include = (frctrl >> 5) & 1
    frctrl_mac_include = (frctrl >> 4) & 1  # check for MAC address in data
    frctrl_is_encrypted = (frctrl >> 3) & 1  # check for encryption being used
    frctrl_request_timing = frctrl & 1  # old version
```

The `frctrl_is_encrypted` part is telling me that it does use Encryption. The ble data also looks encrypted. 

`131695fe4844e9042b5a4bc0de23108397fa2ea8`

E.g. the fingerprint sensor should show `0x0006`, the lock sensor should show `0x000b`. I don't see these in the BLE advertisement, which makes me pretty sure it is encrypted.

**Comment by rezmus** [comment]
@Ernst79 yes, it is encrypted. lock use different (secure) api endpoint for pairing, other than ble sensors. most methods can't be used to get the key. however @vevsvevs already found api endpoint we should log during bind to get beacon key.

**Comment by Ernst79** [comment]
@rezmus Thanks. I don't have this device myself, but @krzakx will probably help to test, I assume.

**Comment by Ernst79** [comment]
I understood from @rezmus in https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/57 that you can't use xiaomi cloud token extractor to get your key, because it uses `secure ble bind`. The only way to get your key is method 3 or 4 from the FAQ https://custom-components.github.io/ble_monitor/faq#how-to-get-the-mibeacon-v4v5-encryption-key, I think. 
@rezmus, is this a right assumption that method 3 and 4 are the only way to get the encryption key?
