### ISSUE TITLE
VegTrug unknown battery status

### ISSUE THREAD

**Issue by sergeybelozorov** [custom-components/ble_monitor#669]
I connect my VegTrug to BLE Monitor. All sensor working well, except battery. Battery status is unknown.
Model HHCCJCY01

![Screenshot_20220127_164305_io homeassistant companion android](https://user-images.githubusercontent.com/94930734/151370542-8940f858-ef9c-432f-b0a1-b2bc828c393e.jpg)

**Comment by Ernst79** [comment]
from the documentation: 

> No battery info with firmware v3.2.1. Battery sensor is only supported when using BLE gateway to forward the BLE advertisements with ESPHome to BLE monitor.

**Comment by sergeybelozorov** [comment]
Thnx
