### ISSUE TITLE
Support for H5071?

### ISSUE THREAD

**Issue by PerfectBake420** [custom-components/ble_monitor#670]
I have a Govee H5071 and was hoping to integrate it. Is there any support for that model?

**Comment by Ernst79** [comment]
Not yet, but it's probably easy to add. I just need some BLE advertisement data from you. The FAQ explains how to get this in this article. https://custom-components.github.io/ble_monitor/faq#my-sensor-is-not-in-the-list-of-supported-ones-how-to-request-implementation

Try with `report_unknown: Govee` first, if that doesn't work, make a log with `report_unknown: Other`.

**Comment by Ernst79** [comment]
You most likely will have to use report_ unknown: Other

just post a log here and I will find the advertisements I need

**Comment by PerfectBake420** [comment]
I will get you this information when I get a usb bluetooth adapter. I didnt think i would need 1. I have it on the wifi already and thought it would just read it. I did download the bluetooth le android app and got this information:

Govee_H5071_A059
MAC: e3:60:59:21:a0:59
Updated: 2022-01-29 20:41:00
RSSI: -74.0db / -71.0db
UUID: 494e5445-4c4c-495f-524f-434b535f4857
MAJOR: 20816
MINOR: 22944
TX POWER: -62
DISTANCE: 2.67m
DESCRIPTOR: Near

**Comment by Ernst79** [comment]
BLE monitor is BLE only. I need a scan record from this sensor, which you e.g. can get with Bluetooth LE scanner on android. But we can also wait till you have your Bluetooth adapter, no problem.

**Comment by PerfectBake420** [comment]
I should have it tomorrow evening. I did post the information from the Bluetooth LE Scanner on Android. Thank you for you assistance

**Comment by PerfectBake420** [comment]
Wait until a number of “BLE ADV from UNKNOWN” messages accumulate in the log.

where do i find the log they want?

**Comment by Ernst79** [comment]
In the home assistant log

**Comment by PerfectBake420** [comment]
Here is the log. The device i have is a govee h5071 thermostat/humidistat

[home-assistant.log](https://github.com/custom-components/ble_monitor/files/7997847/home-assistant.log)
 
Here is the info I got from Bluetooth LE Android App:
Govee_H5071_A059
MAC: e3:60:59:21:a0:59
Updated: 2022-01-29 20:41:00
RSSI: -74.0db / -71.0db
UUID: 494e5445-4c4c-495f-524f-434b535f4857
MAJOR: 20816
MINOR: 22944
TX POWER: -62
DISTANCE: 2.67m
DESCRIPTOR: Near

**Comment by Ernst79** [comment]
The messages only show the following data

`020106` --> Flags, not interesting
`07030a18f5fe88ec` --> 16-bit Service Class UUIDs ???
`1109476f7665655f48353037315f41303539` --> Full name: Govee_H5071_A059

Normally, Govee puts its data in a `xxFFxxxx` packet. 16-bit service class UUIDs are normally only two bytes long, like `0303AABB` , so lets analyze it:

`07030a18f5fe88ec`
`07` = length (7 bytes after `07`)
`03` = indicator for 16-bit service class UUIDs
`0a18` = 16-bit service class UUID (normally)
`f5fe` = ???? 0xFEF5 = 
`88ec` = This is normally used as company identifier for Govee. 

So, it might be that it is just sending "hello, I'm here" to set up an connection (I read it also uses wifi). Or we somehow didn't catch the correct data packet.

**Comment by PerfectBake420** [comment]
Yes it is on the wifi also. It connects via Bluetooth for settings then uses wifi to send out phone notifications. The main connection is bluetooth as it is needed to make any changes to the unit.  I will see if I can find any other information that you will need. Thank you again for your assistance

**Comment by PerfectBake420** [comment]
Here is the full log. I hope it helps. I did see it pop up in the entities area. I can get readings from it. It shows up as a H5051 and the temp and hum updates are far inbetween eachother. 
[home-assistant.log](https://github.com/custom-components/ble_monitor/files/8033307/home-assistant.log)

**Comment by PerfectBake420** [comment]
Your totally right. I forgot I turned those off after sending the last log. I apologize for that. 

[home-assistant.log](https://github.com/custom-components/ble_monitor/files/8034695/home-assistant.log)

**Comment by PerfectBake420** [comment]
Bump to bring the dev back

**Comment by Ernst79** [comment]
Did you give it a try ?

**Comment by PerfectBake420** [comment]
I did not give it a try. It does work, it is just slow to update and if I restart HA, it comes in at as high as 22,000 degrees lol. The RH is almost always correct. It shows up as a H50501 instead of the H5071. I just accepted it as is. Thank you

**Comment by Ernst79** [comment]
Thanks. Are you using the latest version of BLE monitor? This strange values during restart were fixed in the most recent update, but if you still have this issue, let us know. But first check for updates in HACS.

**Comment by Ernst79** [comment]
Excellent. I'll add the sensor to the docs and device name.

**Comment by Ernst79** [comment]
Changed the device name in 5.9.3 to H5051/H5071
