### ISSUE TITLE
Temperature and humidity sensor iBeacon showing strange results

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#673]
I'm don't thing that the temperature and humidity readings of iBeacon sensors are showing the right results. 

![image](https://user-images.githubusercontent.com/24375847/151675137-cce17c42-5eb4-4e58-b632-206cf374b0b1.png)

The humidity in the room is around 55%, iBeacon sensor is showing 15%. 
Temperature is showing -33°C, but it's certainly not freezing in the room (+20°)

**Comment by Ernst79** [comment]
this is an example of a BLE advertisement I receive (the part that goes into the iBeacon.py parser). 

`1aff4c00021550765cb7d9ea4e2199a4fa879613a492d2182c14ce`

In your test examples, major and minor were 100 (`0x0064`) and 0 (`0x0000`). In the above data, I get: 

major = `d218`
minor = `2c14`

Which will be big numbers. 

I haven't figured out which device this actually is, I think it's an iPhone, have to check.

**Comment by dmamontov** [comment]
Not all devices support humidity and temperature. Only certain ones change major and minor d depending on temperature. I think you can make them lectured by default.

**Comment by JeroenDB89** [comment]
Hello, also major and minor are not correctly parsed in home assistant, according to Apple documentation these are unsigned integers, but are parsed as a signed integer. https://developer.apple.com/documentation/corelocation/determining_the_proximity_to_an_ibeacon_device

![image](https://user-images.githubusercontent.com/49206062/151699656-c3004b0f-0dc2-4c1a-84b0-d99860ec8d94.png)

**Comment by dmamontov** [comment]
> Hello, also major and minor are not correctly parsed in home assistant, according to Apple documentation these are unsigned integers, but are parsed as a signed integer. https://developer.apple.com/documentation/corelocation/determining_the_proximity_to_an_ibeacon_device
> 
> ![image](https://user-images.githubusercontent.com/49206062/151699656-c3004b0f-0dc2-4c1a-84b0-d99860ec8d94.png)

In this case, you need an example of a package, they are correctly calculated. But maybe there is additional information in your package.

**Comment by Ernst79** [comment]
An unsigned int is a simple as changing 

`        (major, minor, power) = unpack(">hhb", data[22:27])`

to 

`        (major, minor, power) = unpack(">HHb", data[22:27]) `

for positive values, this makes no difference, for negative values, it does

**Comment by dmamontov** [comment]
well, if this was meant, everything is simple) One of these days I will throw off a big PR)

**Comment by Ernst79** [comment]
Yes, I found this somewhere on the interweb: 

> the values of major and minor are both stored and advertised as 16-bit unsigned integers.

So, just change it to capital H is how it should be. I’ll wait for the PR, thanks

**Comment by JeroenDB89** [comment]
Changed this in the code on my HA config folder and now it works correctly, maybe also the temperatures/humidity will be parsed correctly now.
I started experimenting with the iBeacon protocol, as this is a standard BLE example on how to use BLE on an Espressif ESP32 in Arduino IDE. Your work comes in handy to send my own data (without setting up connections on wifi/zigbee/normal bluetooth) to HA on a raspberry pi just by adapting this example and changing continuously the major/minor data. Everybody can sniff my data, but no problem for me. 
By using multiple UUID's on the same controller/MAC I can also send alternatingly multiple sensor values.
https://circuitdigest.com/microcontroller-projects/esp32-based-bluetooth-ibeacon

**Comment by Ernst79** [comment]
The 16-bit unsigned integer is added in 7.4.0. Temperature and humidity remains strange. 

![image](https://user-images.githubusercontent.com/24375847/151704635-2b93a695-359f-4fca-ab3f-5b5669406020.png)

**Comment by Roofcatbusy** [comment]
I've installed ble_monitor yesterday and also observe strange iBeacon data. What is strange for me is that RSSI is quite high, and I am pretty sure that there is no iBeakon stuff in my kitchen. I suspect taht it may be incorrectly parsed ads from my smart kettle but I don't understand how to prove this version

**Comment by dmamontov** [comment]
they always have a strong signal and if your teapot does not have an apple manufacturer identifier, then it is unlikely that it is.

**Comment by Ernst79** [comment]
You might find out which device it is by looking at the MAC address. But I would just ignore the temperature and humidity,

**Comment by dmamontov** [comment]
Can I make them disabled by default?

**Comment by Roofcatbusy** [comment]
@Ernst79 thanks for quick reply, but it changes mac address constantly below is half a day history of one of such sensors. 
![image](https://user-images.githubusercontent.com/24388956/154674589-9f6193be-6947-45b8-9ed7-7b3adbff487b.png)

**Comment by Ernst79** [comment]
@dmamontov. Yes, that is possible. I did something similar here for (all) binary sensors with ATC firmware. It will only disable newly added entities (existing entities will remain enabled), which is ok. 

https://github.com/custom-components/ble_monitor/blob/5cffa891250366ddd105c43f0155f03b45065adb/custom_components/ble_monitor/binary_sensor.py#L324-L330

**Comment by Ernst79** [comment]
Temperature and Humidity are now disabled by default in 7.8.1-beta. When the final is released, this issue will be closed.

**Comment by teras** [comment]
Hello all. I have the same problem. The system marks them as hidden and of course still have wrong values. Is there any way to make them display the correct ones?
I was trying to follow the discussion here but couldn't find how to do this.

Thank you!

**Comment by mabusdogma** [comment]
![Image](https://github.com/user-attachments/assets/1920fd4f-9a23-4a4b-bbf4-eaff7d7fdca8)
So, what's the solution for these weird readings in temperature and humidity?

**Comment by Ernst79** [comment]
There isn’t a solution, so far. sorry.
