### ISSUE TITLE
Balance Xiaomi: error in Home assistant

### ISSUE THREAD

**Issue by Nemesis24** [custom-components/ble_monitor#677]
To help, this is the error i have on my log.
Thanks for all.

The unit of sensor.ble_weight_eee6b5cae0d1 (kg) does not match the unit of already compiled statistics (). Generation of long term statistics will be suppressed unless the unit changes back to . Go to https://my.home-assistant.io/redirect/developer_statistics to fix this

The unit of sensor.ble_non_stabilized_weight_eee6b5cae0d1 (kg) does not match the unit of already compiled statistics (). Generation of long term statistics will be suppressed unless the unit changes back to . Go to https://my.home-assistant.io/redirect/developer_statistics to fix this

**Comment by Ernst79** [comment]
Did You change the unit in the xiaomi mi home app?

**Comment by Nemesis24** [comment]
Not in mihome app, but in the xiaomi mifit app, yes this in Kg unit ans not in lb unit.

**Comment by Ernst79** [comment]
The scale also sends the unit of measurement, so if you change that in the app, the unit of measurement will also change in HA from lbs to kg. This is confusing for long term statistics, of course, hence you get the error. I would try to remove the sensor in bLE monitor and restart HA. Next time it will pick up the correct unit of measurement, hopefully without the error

**Comment by Ernst79** [comment]
Closing this issue. If you still have this issue, feel free to reopen it.
