### ISSUE TITLE
Support for Xiaomi Philips Bluetooth Motion Sensor Night Light

### ISSUE THREAD

**Issue by kanemari** [custom-components/ble_monitor#68]
hi there,

I previously posted about this in the 'suggestions' thread and was asked to open up a separate topic.

https://www.aliexpress.com/item/32986151863.html

I have a few of these devices, but its very difficult to find out any definitive technical information on them. They connect to the mihome app and can be controlled and grouped together in scenes. I would like to be able to integrate them into HA so that they could potentially have sensor, light and illumination entities that could be controlled natively.

Pushing bluetooth cmds instead of receiving them passively via LE might be outside the scope of this component, but I figure no harm in asking!

**Comment by Magalex2x14** [comment]
Hello!

I think that this custom component is not suitable for working with such devices. The component does not provide for device control (and is unlikely to be in the future). The only thing that could be done is to get some kind of data. As I understand it, this lamp has a built-in proximity sensor. Even if it regularly sends the state of this sensor, then in HA we will receive this data with a delay (due to the periodic nature of the component’s operation, see the period option) - in the case of “measuring” sensors this is normal and even has some advantages, but in the case of "switching" sensors, this approach may not be acceptable.

In any case, our FAQ [contains](https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation) a description of the steps to collect the necessary information.

**Comment by Magalex2x14** [comment]
In version 0.7.0-beta, the component is redone for real-time processing, which allows you to immediately receive changes in the status of "switching" sensors.
To implement support for Xiaomi Philips Bluetooth Motion Sensor Night Light, I need a dump of messages, which you can get according to this [instruction](https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation).

**Comment by kanemari** [comment]
cool. I had a dig around and found that someone seems to have implemented this in a dev branch of ESPHome but it was never approved. it might provide some useful background info?

https://github.com/esphome/esphome/pull/951
https://t.me/kapiba_room/11

I have added in the report_unknown flags and am trying to trigger it to collect some data. nothing is showing up so far, will need to check whats going on.

**Comment by Magalex2x14** [comment]
Yes, I know about the solution in ESPHome, but I haven't looked at the code yet.
I'll talk to vevsvevs.

**Comment by Magalex2x14** [comment]
Just bookmark, so as not to lose (there is a link to the dump): https://github.com/esphome/feature-requests/issues/551

**Comment by kanemari** [comment]
the thing that isnt mentioned here is that while the light broadcasts an event when triggered, it is also able to receive a broadcast that will activate it. I have set up 2 of these devices as a group using the MiHome app, and triggering one with motion will trigger the other via BLE. It is likely that the Mihome BLE gateway is broadcasting the packets, but I havent been able to capture anything yet. I have set the logs to debug as per the instructions and nothing shows up for unknown devices.

is there another way to capture BLE data?

**Comment by Magalex2x14** [comment]
Other ways are command line utilities:
the most convenient for me is hcidump
```shell
hcidump hci0 --raw > dump.txt
```
or btmon
```shell
btmon -t -w dump.txt
```

**Comment by Magalex2x14** [comment]
Perhaps the problem is with the `whitelist` option... Try disabling it, if enabled.

**Comment by Magalex2x14** [comment]
> I have set up 2 of these devices as a group using the MiHome app, and triggering one with motion will trigger the other via BLE.

Perhaps this is done using directed advertisements, but the "normal" interface cannot accept them ("zero" filter policy is `Accept all advertisements, except directed advertisements not addressed to this device (0x00)`), I did not find even a hint of the possibility of changing this.
Apparently, to receive such a message we need a sniffer ...

**Comment by Magalex2x14** [comment]
In case anyone has an interest in implementing support for this device:
- it is possible to implement receiving events from the proximity sensor (maybe also battery level, but this needs clarification)
- since version 0.8.3 the component updates the state of binary sensors in real-time
- you can speed up the implementation by adding a dump obtained using the `report_unknown` option

**Comment by Ernst79** [comment]
This sensor is implemented in ESPhome as MUE4094RT. The PR in which the sensor is added is this one: https://github.com/esphome/esphome/pull/1027. Perhaps you can use something from there?

**Comment by Magalex2x14** [comment]
Yeah, I know. But I wanted to clarify the presence of interest, because we cannot test it. And I also want to look at the full messages from the device, because only a part of it gets into the ESPHome log.

**Comment by Ernst79** [comment]
@kanemari I recently added support for the MJYD02YL motion sensor bed light. I think your device works pretty much similar, I've fixed the bug why some of these messages were not found with `report_unknown` for this device, according to the ESPHome implementation this device had the same issue, which is now resolved. 

If you are still interested, I can add support for the sensors at least, but I will need a log generated with `report_unknown`. If that doesn't work, there is another way to get the data, But let me know if you (or someone else) is still interested.

**Comment by kanemari** [comment]
@Ernst79 for sure - I went and got a cheap BLE sniffer device to try and packet capture but it ended up a lot harder than I thought and I gave up. Will definitely try with the above improvements and see if I can get anything in the logs.

**Comment by Ernst79** [comment]
Ok, please try. If nothing shows up with `report_unknown`, you can try the following as an alternative. 

Look up the following lines in `__init__.py` in the ble_monitor folder

```
        if xiaomi_index != -1:
            # parse BLE message in Xiaomi MiBeacon format
```

Change it to the following

```
        if xiaomi_index != -1:
            # parse BLE message in Xiaomi MiBeacon format
            _LOGGER.error("Data: %s", data.hex())
```

Restart HA and you will get a lot of errors in you log with `Data:` followed by a long number. Wait about half an hour and copy the lines from the log here in this issue (you can add a txt file). You can remove the line when you are finished.

**Comment by kanemari** [comment]
report_unknown didnt work as nothing new showed up. made the logger error edit and have attached the log file (with non ble related messages removed).

I didnt let it run for 30 mins because I have a far reaching bluetooth receiver and seemingly pick up a lot of noise from other neighbourhood devices. but I did stand right next to the lights for a couple of minutes and constantly trip them so as to hopefully generate traffic.

[home-assistant.log](https://github.com/custom-components/ble_monitor/files/5925246/home-assistant.log)

**Comment by Ernst79** [comment]
After filtering out all known devices, I found two types of measurements that are "new". (last two lines) . I think you have two of these sensors. 

```
-----------------------------------------------------------------------------------------------------------------------------------------------------------
HCI  Evt Len Sub Num Evt  Peer -------MAC-------   Len Len Type Val Len  AD  Xiaomi Frame Product Frame ------MAC--------   -----PAYLOAD-------------  RSSI
type code    evt rep type addr                             flag         type  UUID   ctrl   ID    cnt                      Type  Len  Temp   Hum   Batt
 A    B  C    D  E    F    G          H            I   J    K   L   M    N     O      P     Q      R           S            T     U    V      W     X   Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 04   3e 25  02  01   00   00  21 93 35 34 2d 58   19  02   01  06  15   16  95 fe  50 20  aa 01   70   21 93 35 34 2d 58   0d 10 04  ee 00 98 02       c3   LYWSDCGQ
 04   3e 22  02  01   00   00  f0 c5 18 38 c1 a4   16               15   16  95 fe  50 30  5b 05   69   f0 c5 18 38 c1 a4   0d 10 04  fc 00  44 02      ce   LYWSD03MMC
 04   3e 1c  02  01   02   01  02 80 8a 04 36 e3   10  02   01  06  0c   16  95 fe  40 30  dd 03   bf                       03 00 01 01                 bb   MUE4094RT
 04   3e 1c  02  01   02   01  0c 39 b2 e8 70 de   10  02   01  06  0c   16  95 fe  40 30  dd 03   24                       03 00 01 01                 c6   MUE4094RT
```

These messages occur a lot, but always have the same PAYLOAD (`03000101`). I compared it to the ESPHome commit and it contains the right product type (`dd 03`), so these are the right devices we are looking for. 

What I need is a message from the log when it reports no movement. Can you make one more log, after at least 2 minutes without movement. You only have to copy a line that ends on something slightly different than `03 00 01 01 xx`. I guess a `01` will change to `00` or vice versa. (xx = RSSI value,)

As there is room for three measurements, please also check if the numbers change when you 
- make it dark in the room (versus light in the room)
- turn on the light of the device itself (versus light off).

Please write down which measurement corresponds to which change. Not sure if it reports the last two, but the other motion sensor does.

**Comment by Ernst79** [comment]
Based on the ESPhome info, I assume that it is the last `01` that indicates motion. I prepared the [MUE4094RT branch](https://github.com/custom-components/ble_monitor/tree/MUE4094RT/custom_components/ble_monitor). 

Could you take the following steps to test. 
- Install 1.0.1-beta first
- Next copy the code from the file `__init__.py` and `const.py` from the [MUE4094RT branch](https://github.com/custom-components/ble_monitor/tree/MUE4094RT/custom_components/ble_monitor). Overwrite the content of the files in the ble_monitor folder. 
- Restart HA
- Check if your sensor is added to HA and write down the MAC address
- Change the reset_timer option to 0 seconds in the device settings of this specific sensor (Important for the test!)
- Check if it works and let me know after how much time the sensor turns off after you stop moving.

**Comment by kanemari** [comment]
have some new logs for the previously mentioned scenarios. What appears should be in the following order:-
1. movement detected state
2. illumination change for lights on
3. illumination change for lights off
4. movement detected state
5. hopefully a 'no movement' state if one is sent

[home-assistant.log](https://github.com/custom-components/ble_monitor/files/5932106/home-assistant.log)

The time the light stays on doesnt seem to change after changing the reset_timer value? I am only able to set light brightness and a 'lights on' timer via the xiaomi app onto the device directly. Additionally, as you may see from the logs, I have a noisy qingping BLE wifi gateway. I think this sends BLE 'light on' trigger packets to the other light I have paired, so when one goes on, the other follows even if it doesnt specifically detect motion, and vice versa.

It would be cool if the BLE light trigger packet could be reconstructed and sent from HA to a device via a switch entity

**Comment by Ernst79** [comment]
Thanks, 

First, a remarks about the light. 

> The time the light stays on doesnt seem to change after changing the reset_timer value?

The `reset_timer` is the time after which HA tells that the motion sensor should display `motion clear` in Home Assistant. This is an additional message, compared to the ones send by the sensor itself, as the sensor can send it after a different time than you want (e.g. the other motion sensor sends it after 2 minutes). The sensor doesn't send anything to the light. 

But lets start with the basics. What we first need to know is what the sensor sends. For this, you need to install the file `__init__.py` and `const.py` from the [MUE4094RT](https://github.com/custom-components/ble_monitor/tree/MUE4094RT/custom_components/ble_monitor) branch (I assume you did). Next you need to turn off the `reset_timer` by setting it to `0`, to make sure we only use messages from the sensor itself. Restart HA and then check in HA what the motion sensors displays. 

What I'm looking for is a **confirmation** for
- [ ] Is a motion sensor added to HA
- [ ] is the motion sensor in HA showing `Motion detected` when you move 
- [ ] is the motion sensor in HA showing `Clear` after you don't move for some time (and check how long this takes). 

I also checked your last log. After filtering out all the other sensors, I see messages in the Xiaomi format (`1695fe`) and Qingping format (`16cdfd`) 

**Xiaomi messages**
All xiaomi messages are still the same (except the counter and the RSSI value). I don't think you have received a "motion clear" message" (all are still `03 00 01 01 xx` at the end). But if the sensor shows `motion clear` after no more moving for a while, there is no need for further looking into this. But I need a confirmation from you if it works (or not)

**Qingping messages**
I will look into these, to see if they contain useful information. Can you tell me the actual device code or a link to the product?

**Comment by kanemari** [comment]
this is a link to the product
https://www.aliexpress.com/i/33020095651.html

and to answer your questions:-
 Is a motion sensor added to HA
- yes

 is the motion sensor in HA showing Motion detected when you move
- yes. there is also an error in the log
```
ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.ble_motion_e336048a8002 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/ble_monitor/binary_sensor.py", line 469, in async_update
    self._start_timer = self._device_state_attributes["last motion"]
KeyError: 'last motion'
```
 is the motion sensor in HA showing Clear after you don't move for some time (and check how long this takes).
- no, its either 'unavailable' on restart until it detects motion, or permanently set to 'detected' after it detects motion - it doesnt seem to reset to an idle state.

**Comment by Ernst79** [comment]
Thanks, that's the feedback I need. I've created an update, please try again. I've changed `binary_sensor.py` and `__init__.py`, same branch. 

https://github.com/custom-components/ble_monitor/tree/MUE4094RT/custom_components/ble_monitor

**Comment by kanemari** [comment]
I updated the above 2 files and tried again. The previous error is gone from the logs but the behaviour is the same. The sensor still doesn't return to idle / clear state. Stays permanently in 'detected' state.

What else should I try?

**Comment by Ernst79** [comment]
OK, than my assumption about the format of the advertisement was wrong. We can have two cases, I guess. Either the sensor doesn't send anything when there is no motion, or it sends an off message in another format that I guessed. 

To find out, I need a log for a significant period, lets say a part of e.g. the evening where you move, and a night without movement. 

To limit the amount of lines in your log, I created an update of `__init__.py`, where I added logging only for this device. 
https://github.com/custom-components/ble_monitor/tree/MUE4094RT/custom_components/ble_monitor

The log lines are on error level, so it will be added without setting you log level to debug. It is also NOT needed to enable report_unknown. 

I added the two lines on line 647 and 648

```
            if device_type == b'\xDD\x03':
                _LOGGER.error("Data from MUE4094RT: %s", data.hex())
```
This writes a line with the received data in the log send by MUE4094RT devices only. You can remove these lines when you are finished and post the log in a txt file here.

**Comment by kanemari** [comment]
approx 24 hours of logs attached. you should see 4 distinct MAC addresses. hopefully this sheds some light on it (pun intended) :)

[home-assistant.log](https://github.com/custom-components/ble_monitor/files/5943124/home-assistant.log)

**Comment by Ernst79** [comment]
It certainly sheds a light :-). I can see you went to bed at 22.43, woke up shortly at 02.48 and the morning started at 08.11. 

The sensor only sends `motion detected` messages, there are no `motion clear` messages.

If I'm correct, you can just use the version you have right now, but you have to set the `reset_timer` option to something other than 0, set it e.g. to 30 seconds. You can experiment with the value what suits you best.

**Comment by kanemari** [comment]
set the timer to the same value set directly on the light via the xiaomi app (15s). all seems to be working well. many thanks!

**Comment by Ernst79** [comment]
@kanemari, your sensor is not yet added to 1.0.2, so please do not update. I will prepare a 1.0.3-beta later today.

**Comment by Ernst79** [comment]
Done, could you do a final check on 1.0.3-beta, if all works ok.

**Comment by Ernst79** [comment]
Added in 1.0.3.
