### ISSUE TITLE
High load from iBeacon uuid sensor on database

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#687]
As reported on the forum, the iBeacon is still giving a high load on the database. See https://community.home-assistant.io/t/passive-ble-monitor-integration/303583/361?u=ernst

In this issue, I try to reproduce this behavior and make some notes. 

Step 1. Deleted the Database to start with a new fresh empty DB
Step 2. Restarted HA, running a database scan once per 10 minutes. 
Step 3. After 20 minutes I have the following number of number of state updates. Seems to be the `uuid` sensor only. 

![image](https://user-images.githubusercontent.com/24375847/152177905-68d6f66e-ea0e-4aec-b52a-502bce3e47f3.png)

Step 4. After 30 minutes, `uuid` has increased with 500 state updates, temperature and humidity only with 9 (one per minute, so 9-10 is as expected). 

![image](https://user-images.githubusercontent.com/24375847/152179497-4bcfd0f3-0a20-481d-b1be-339cb5e7b429.png)

Step 5. After 40 minutes, `uuid` has increased with 650 state updates, temperature and humidity only with 10 (one per minute, so 9-10 is as expected). 

![image](https://user-images.githubusercontent.com/24375847/152181617-1caf43bb-e980-4367-9d95-9dcbb4c535a3.png)

Step 5. Checked the states, of MAC, major and minor, these had a state change 38 minutes ago, uuid has had a state update 4 seconds ago. 

**Conclusion**
`uuid` sensor state is updated on every advertisement, while it should change on a change of the `uuid` (@dmamontov just copying you in, to let you know, I will also have a look myself to see if I can find out why).

**Comment by dmamontov** [comment]
So I checked now. uuid is written only once at startup. measured power as expected, the average is calculated.

Maybe it's another apple device? which for some reason changes the uuid, and according to the statistics from the screenshots it is clear that the uuid is changing and not the mac.

**Comment by Ernst79** [comment]
The strange thing is that I don't see any change of the `uuid`. It has been the same for hours. But the last update is constantly saying a few seconds ago. 

![image](https://user-images.githubusercontent.com/24375847/152193669-3bdb2967-e131-4e2e-99a7-b082b6f6309c.png)

**Comment by dmamontov** [comment]
Found. I'll send you a PR now.

**Comment by dmamontov** [comment]
https://github.com/custom-components/ble_monitor/pull/688

**Comment by Ernst79** [comment]
Excellent, I also found that the `uuid` key didn't follow the if statement., but hadn't started solving it. Great, I'll do a final test tonight and will release it tonight.

**Comment by Ernst79** [comment]
Fixed in 7.5.0
