### ISSUE TITLE
support for Qingping Air Monitor Lite?

### ISSUE THREAD

**Issue by fokcuk** [custom-components/ble_monitor#699]
I am currently using WIFI integration via MiHome, but noticed that its sending some BLE info as well.
Dont have the skills to analyze it. But did the captures via hcidump

[ble_dump1.log](https://github.com/custom-components/ble_monitor/files/8000323/ble_dump1.log)
[bt_dump_air_quality.pcap.log](https://github.com/custom-components/ble_monitor/files/8000327/bt_dump_air_quality.pcap.log)

**Comment by Ernst79** [comment]
No problem, I will look at them this weekend

**Comment by Ernst79** [comment]
These files do not look like HCIdumps. 

Please check this FAQ article how you can collect the data that I can use. 

https://custom-components.github.io/ble_monitor/faq#my-sensor-is-not-in-the-list-of-supported-ones-how-to-request-implementation

**Comment by fokcuk** [comment]
The dump1.log file is done with this command:
 hcidump --raw hci -w ble_dump1.log while I had lescan running

**Comment by fokcuk** [comment]
I have done this file before with "> dump.txt" but wireshark could not open it, so I have redone it with -w option
[dump.txt](https://github.com/custom-components/ble_monitor/files/8001094/dump.txt)

**Comment by fokcuk** [comment]
you can do "hcidump -r ble_dump1.log" to get similar output (so I have read).
Just could not work out how to decode the data

**Comment by Ernst79** [comment]
Yes, the last file is what I need, thanks. Will look into it later

**Comment by Ernst79** [comment]
I was able to extract some data. 3 data parts, the first is temperature and humidity (assuming that it works like the other Qingping sensors. 

`0x01` --> Temperature + Humidity
`1f01 3801` --> data
`1f01` --> `0x011f` --> 287 --> 'temperature': 28.7
`3801` --> `0x0138` --> 312 --> 'humidity': 31.2

The second seem to contain two binary sensors (0/1). 
`0x12` --> ???
`01000100` --> data
`0100` --> 1 Not sure what this represents. Most likely something like "on" I also see advertisements with 0 ("off")
`0100` --> 1 Not sure what this represents. Most likely something like "on" I also see advertisements with 0 ("off")

The third contains a value, not sure if it is CO2, PM2.5, PM10? Note that e.g. for temperature, they divide it by 10 to get the actual number, so could also be 48.8 or something else. 
`0x13` --> ???
`e801`  --> `0x01e8` --> 488 --> ???

**Comment by fokcuk** [comment]
Thats exciting! =) do you mind pasting and highlighting areas on the capture for the data you are reading, so that I can cross check it when it changes?
488 is most likely CO2, as PM2.5/10 would be either 0 or 1 in my house. But I can check it with a match, just need to know what to look out for

**Comment by Ernst79** [comment]
Yes, sure. 

```
> 04 3E 2B 02 01 00 00 A5 80 8F E6 48 54 1F 02 01 06 1B 16 CD 
  FD 08 0E A3 80 8F E6 48 54 01 04 1F 01 38 01 12 04 01 00 01 
  00 13 02 E8 01 BB
```

It all starts at `16 CD FD` (where `FD` is on the next line, so search for `16 CD`), which is Qinpping

`16 CD FD 08 0E A3 80 8F E6 48 54 01 04 1F 01 38 01 12 04 01 00 01 00 13 02 E8 01 BB`

The first package starts at the 12th byte after `16`

`01 04 1F 01 38 01 12 04 01 00 01 00 13 02 E8 01 BB`

this can be split up in 

`01 04 1F 01 38 01` (type 1, length 4, and than 4 bytes (2 for temperature, 2 for humidity)
`12 04 01 00 01 00` (type 12, length 4, and than 4 bytes (most likely 2 binary values)
`13 02 E8 01 BB` (type 13, length 2, most likely one value from 2 bytes. (`01E8`)

I also found another message that doesn't start with 16 CD FD. Looking into that now. 

You can also have a look here, for some possibilities. this is your device, my first guess is that type 13 is CO2
https://github.com/rytilahti/python-miio/blob/069bee8fd81e939ffc2782ac80f3fd67aaed816d/miio/airqualitymonitor_miot.py

**Comment by fokcuk** [comment]
[dump2.txt](https://github.com/custom-components/ble_monitor/files/8003277/dump2.txt)
Reference values (should have done it in the beginning):
temp - 28C
humi - 32%
CO2 - between 1101 and 1079 (in the end)
PM2.5/10 - both at 3
Battery - 100%

**Comment by Ernst79** [comment]
{'rssi': -68, 'temperature': 27.6, 'humidity': 32.4, 'value 1': 3, 'value 2': 3, 'value 3': 1097}

**Comment by fokcuk** [comment]
great! Let me play with matches =)
[dump3.txt](https://github.com/custom-components/ble_monitor/files/8003371/dump3.txt)

Hard to catch it, but the last captures should have around 112/113 or there abouts. The larger value of the two is PM10

**Comment by Ernst79** [comment]
{'rssi': -52, 'temperature': 29.0, 'humidity': 33.2, 'PM2.5': 113, 'PM10': 113, 'co2': 1005}

**Comment by fokcuk** [comment]
thats the one!

**Comment by Ernst79** [comment]
ok, will create the sensors tonight. Thanks for checking

**Comment by fokcuk** [comment]
Fantastic! Thank you for your help!

**Comment by fokcuk** [comment]
Interesting that its also sending to Xiaomi data
![image](https://user-images.githubusercontent.com/84503931/152539955-f4b1ed07-ba03-4845-94a5-4bac52fe02fd.png)

**Comment by Ernst79** [comment]
Yes, that is normal for Qingping, They also work with Xiaomi Mi Home, so they often send in both formats. Will have a look at that later, sometimes one is more precise than the other.

**Comment by fokcuk** [comment]
What we have already is good enough =) was just thinking that maybe it sends battery data there. Or maybe I do another capture with the device running just on battery, not charger connected - maybe it will start sending info when % drops

**Comment by Ernst79** [comment]
It does, `0a 10` is the battery indicator

**Comment by fokcuk** [comment]
[dump_battery2.txt](https://github.com/custom-components/ble_monitor/files/8003809/dump_battery2.txt)
Not as chatty on the battery power. Should have ended at 95% battery

**Comment by Ernst79** [comment]
There is something strange with the MAC. 

```
> 04 3E 2B 02 01 00 00 A5 80 8F E6 48 54 1F 02 01 06 1B 16 CD 
  FD 08 0E A3 80 8F E6 48 54 01 04 19 01 58 01 12 04 05 00 05 
  00 13 02 90 03 B9
```

On line 1, you can find the MAC reversed per byte) in the 8th-13th byte (`A5 80 8F E6 48 54`) (by definition)
Qingping always adds the MAC in the data twice, second one is always on line two, 4th till 9th byte (`A3 80 8F E6 48 54`)

As you can see, the first byte is different, while normally, it's the same. In the code I had a check. will write something for your device to only check the last 5 bytes.

**Comment by fokcuk** [comment]
The one ending in A3 is MAC for wifi

**Comment by Ernst79** [comment]
![image](https://user-images.githubusercontent.com/24375847/152570463-debc8c26-2fa2-4bbd-a200-6035be1701d4.png)

**Comment by Ernst79** [comment]
Added in 7.5.2. 

Please let it run for 24 hours and let me know it the battery has been changed from Unknown to a value.

**Comment by fokcuk** [comment]
Works fantastically =) apart from the battery. It's not that important as it's plugged in 99% of the time and settings by default turn the device off in 30 minutes on battery power. 
In the capture I could not find a match (was grepping on the value while it was capturing). So don't know if it even sends the value or not

**Comment by Ernst79** [comment]
I'll remove battery in the next version.

**Comment by MrMarble** [comment]
I bought this device because of this integration, but I'm having trouble making it work. The device connected almost instantly without problems, but after a couple of hours all the sensors are at 0.

Maybe I can help with the integration. What do you need?

![imagen](https://user-images.githubusercontent.com/4268580/152988930-edc1ecba-94d4-4eae-b72a-ed3130470542.png)

**Comment by Ernst79** [comment]
Not sure why this happens, can you make an HCIdump of the BLE advertisements, to check if the device is sending this 0 data?

**Comment by MrMarble** [comment]
> Not sure why this happens, can you make an HCIdump of the BLE advertisements, to check if the device is sending this 0 data?

Here is the dump file, I used `sudo hcidump --raw hci > dump.txt`  
[dump.txt](https://github.com/custom-components/ble_monitor/files/8024045/dump.txt)

**Comment by MrMarble** [comment]
Wireshark couldn't open the last one (I used the command mentioned in the FAQs) here is one using the parameter -w

[dump2.txt](https://github.com/custom-components/ble_monitor/files/8024246/dump2.txt)

**Comment by Ernst79** [comment]
The first HCIdump is ok for me to check the data

**Comment by MrMarble** [comment]
> @MrMarble - can you please use a filter for the device MAC address?
> 
> ```
> hcitool lewladd XX:XX:XX:XX
> hcitool lescan --whitelist
> ```
> 
> and while its running in another terminal do hcidump command
> 
> If you dont know its mac, try `hcitool lescan` first this will also confirm if it sends anything
> 
> There is also an interesting resource here: https://pvvx.github.io/ATC_MiThermometer/Advertising.html When you click the button it will ask you to choose a device - see if Qingping Monitor is in the list. If it is, select it. It will start showing you some data - it can decode temp and humi sensors

It seems to be working correctly now, here is what I have done:

I went to the page you mentioned, but the device was not listed, I proceeded to reset the network settings on the device (by holding down the bar at the top until a wifi icon appeared), almost instantly the device appeared on the web listing, I checked home assistant and all the data is now coming through. Maybe turning it on did not complete the pairing, as it was far away.

If you are still interested in seeing a dump I have no problem doing so.

**Comment by fokcuk** [comment]
Love BLE5 - can see it on the other side of the house =)

**Comment by Ernst79** [comment]
@[MrMarble](https://github.com/MrMarble) No need to send the HCIdump if it is working now.

**Comment by damamaty** [comment]
I had to change the source code in qingping.py (line 12) to get it (qingping air monitor lite CGDN1 Firmware 4.2.1) working. Before it was logging "UNKNOWN Qingping DEVICE".

from:
`    if msg_length > 12 and data[4] in [0x08, 0x48]:`
to:
`    if msg_length > 12 and data[4] in [0x08, 0x48, 0x88]:`

Example data I got:
`b'\x1b\x16\xcd\xfd\x88\x0e\x90\xcb(\x8c\xcf\x04\x01\x04\x06\x01\xbd\x00\x12\x04\x14\x00\x15\x00\x13\x02\xce\x02'`

**Comment by Ernst79** [comment]
Thanks, will change that

**Comment by Ernst79** [comment]
Added `0x88` in 7.6.0

**Comment by fokcuk** [comment]
@Ernst79 - noticed you did not remove the battery readings? or its in cache?

**Comment by Ernst79** [comment]
It has been removed, forgot to mention it in the release notes, 

https://github.com/custom-components/ble_monitor/blob/51142d5c594e25eb32407a7b0c385af0a9edae8a/custom_components/ble_monitor/const.py#L798

You will have to manually remove the sensor from HA. First thing you can try is to just delete the battery sensors, if HA allows you to. If not, you will have to remove the entire device from BLE monitor. After removing it, you can add it again, and it should not add the battery anymore.

**Comment by fokcuk** [comment]
It does not bother me all that much to go into so much trouble =)
