### ISSUE TITLE
Platform ble_monitor does not generate unique IDs

### ISSUE THREAD

**Issue by McGiverGim** [custom-components/ble_monitor#700]
I have this log in Home Assistant:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:593
Integration: Sensor (documentation, issues)
First occurred: 07:45:46 (5 occurrences)
Last logged: 07:45:46

Platform ble_monitor does not generate unique IDs. ID t_Mi Flora Potos already exists - ignoring sensor.miflora_potos_temperatura
Platform ble_monitor does not generate unique IDs. ID m_Mi Flora Potos already exists - ignoring sensor.miflora_potos_humedad
Platform ble_monitor does not generate unique IDs. ID c_Mi Flora Potos already exists - ignoring sensor.miflora_potos_conductividad
Platform ble_monitor does not generate unique IDs. ID l_Mi Flora Potos already exists - ignoring sensor.miflora_potos_luminosidad
Platform ble_monitor does not generate unique IDs. ID rssi_Mi Flora Potos already exists - ignoring sensor.miflora_potos_senyal
```

It seems the sensors are not updating the values neither, I don't know if it is related or not.

**Comment by Ernst79** [comment]
The easiest way to solve this is to delete your sensor from BLE monitor, and make sure all entities are deleted (also with `_2` at the end. Restart HA and add it afterwards.

**Comment by migor7** [comment]
I confirm this issue. Deleting sensors and entities solves the problem before the first reboot

**Comment by McGiverGim** [comment]
Yes, this works. Something must have been wrong at some update to generate the duplication of entities.

This can be closed or left open if it can help someone or if this must be fixed in code to be sure it does not happen again.

**Comment by Ernst79** [comment]
I leave it open for a few days, if more people have this issue, please report it here. 

If no more people will report this issue the coming days, I will close it on 14-2, otherwise, I will further investigate it.
