### ISSUE TITLE
Qingping Air Monitor Lite Issues

### ISSUE THREAD

**Issue by MrMarble** [custom-components/ble_monitor#707]
Hello, I'm having some issues making this sensor work. I've read (and participated) in the related issue #699 discussing the implementation. I'm writing this to document every step I've made in order to help the development, as well asking for help.

### Update the firmware

Following @fokcuk https://github.com/custom-components/ble_monitor/issues/699#issuecomment-1032699224 regarding updating the device; I downloaded the Qingping+ Android app, the Device wasn't showing at first, I had to reset the network settings to enter "pairing mode" after which the App detected the device and proceeded with the pairing. Two firmware updates later the device has the version 4.2.1 which is reportedly the latest one at the time of writing this. Because of this, I had to reset the network settings again to disconnect from the app, so the device would broadcast Bluetooth data again.

### Issues

After some debugging hours seems like the device stops broadcasting data through BLE roughly 1h after the network settings reset.
I've checked https://pvvx.github.io/ATC_MiThermometer/Advertising.html and the device is showing at first, but after said time it is no longer listed.

I've recorded two hcidumps, one while the device wasn't transmitting information (at least I could not see it) and the other while resetting the network, so it would pick it up.
Also, I set the log config as said in the FAQs and this is the result filtering for the device mac (54:48:E6:8F:83:13) which showed this error and I don't know if it's related with this custom component or not.

<details>
<summary>Home assistant error</summary>

```log
2022-02-09 10:14:26 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that uses str (diagnostic) for entity category. This is deprecated and will stop working in Home Assistant 2022.4, it should be updated to use EntityCategory instead. Please report this issue.
Stack (most recent call last):
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/src/homeassistant/homeassistant/__main__.py", line 203, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 191, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 119, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
self._run_once()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
handle._run()
File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
entry = entity_registry.async_get_or_create(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 401, in async_get_or_create
entity_category=_convert_to_entity_category(entity_category),
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 103, in _convert_to_entity_category
return convert_to_entity_category(value, raise_report=raise_report)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 214, in convert_to_entity_category
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 74, in report
_LOGGER.warning(msg, stack_info=True)
```
</details>

After restarting home assistant, the device appears in the list, but all the sensors are `unknown`
Here are the dumps, I used these commands:
```bash
# lescan wasn't working without resetting the interface
sudo hciconfig hci0 down
sudo hciconfig hci0 up

sudo hcitool lewladd 54:48:E6:8F:83:13
sudo hcitool lescan --whitelist

# Other terminal
sudo hcidump --raw hci -w dump.txt
```
[not broadcasting hcidump.txt](https://github.com/custom-components/ble_monitor/files/8033927/not.broadcasting.txt)
[network reset hcidump.txt](https://github.com/custom-components/ble_monitor/files/8033928/network.reset.txt)
[home assistant log.txt](https://github.com/custom-components/ble_monitor/files/8033940/home.assistant.log.txt)

If more information is needed, I'm willing to help

**Comment by fokcuk** [comment]
Time it. Make sure you are on mains power, not battery, as it will will cut power after a certain time.
I have mine paired to MiHome, as I was using its integration in HA first. Use China Mainland to register the device. From there you can control some settings. 
I was using Qingping app just to patch and check initial configuration.
There were some mentions in the discussion that it would drop wifi, but I never experienced that possibly due to updates.

**Comment by MrMarble** [comment]
> Time it. Make sure you are on mains power, not battery, as it will will cut power after a certain time. I have mine paired to MiHome, as I was using its integration in HA first. Use China Mainland to register the device. From there you can control some settings. I was using Qingping app just to patch and check initial configuration. There were some mentions in the discussion that it would drop wifi, but I never experienced that possibly due to updates.

The device is always connected to main power, not battery. Will try MiHome app to see is there are any improvements

**Comment by Ernst79** [comment]
I don't think the HA error is related to BLE monitor.

**Comment by MrMarble** [comment]
Two hours since I synced the device with the MiHome App and so far is working. Maybe it needs to be connected for BLE to work?

**Comment by Ernst79** [comment]
7.6.0 has a small improvement, it now should receive more BLE advertisements.

**Comment by MrMarble** [comment]
So far is working great, after some testing seems like BLE is only working when it is paired with a companion app. If I reset the network and leave the device unpaired, the BLE stops working after an hour.

I will close the issue because it is working now. Thanks for creating this component!
