### ISSUE TITLE
FR: Please, add battery sensor for Nut Tracker

### ISSUE THREAD

**Issue by Spirituss** [custom-components/ble_monitor#708]
It is possible to read it via, for example, BLE Client (github://myhomeiot/esphome-components). It would be great to see it in the Passive BLE as well.

**Comment by Ernst79** [comment]
Do you have a BLE advertisement with the battery data?

**Comment by Spirituss** [comment]
> Do you have a BLE advertisement with the battery data?

I know that BLE Client reads this data, hope, via BLE advertisement. I will try to identify the address of it.
