### ISSUE TITLE
Support Inkbird IBS-P02 Pool thermometer

### ISSUE THREAD

**Issue by ecos34** [custom-components/ble_monitor#712]
I have an Inkbird pool thermometer model IBP-P02 sometimes referred to as IBS-P02B.
It is a floating pool thermometer that has lcd display and displays 2 temps and battery status.
It connects to my phone using bluetooth and engbird software.
The engbird software reports it as 49:21:09:07:14:58   47% battery and currently 26.32c v1.6.0

Here is the log from HA
[haslog.txt](https://github.com/custom-components/ble_monitor/files/8052448/haslog.txt)

Could you please have a look to see if it can be added?
Thank you very much.
Eric

**Comment by Ernst79** [comment]
I only see very short BLE advertisements from the thermometer

`043e1302010000581407092149070201060302f0ffe3`

It only contains 
`020106` = Flag
`0302f0ffe3` = Service Class UUID

So, it looks like it is basically only broadcasting "I'm here". This might mean that it most likely needs a connection to be set up, before it will communicate the data (which is not supported in BLE monitor). But you might want to try again without having the engbird app open (wait a while after closing the app, before you try), sometimes it stops communicating the "free to the air" BLE messages, when connected to an phone/app.

**Comment by ecos34** [comment]
Hi Ernst,
I think you are correct.
I have tried again as suggested, but can only see the short broadcast.
[haslog.zip](https://github.com/custom-components/ble_monitor/files/8054657/haslog.zip)

I will see if I can find a different thermometer.
Thanks for having a look..
Eric
