### ISSUE TITLE
Mi Scale shows inverted on / off status (Off when On and vice versa)

### ISSUE THREAD

**Issue by codyc1515** [custom-components/ble_monitor#713]
Hi there

I have a Mi Scale that is showing an inverted on & off status, so it shows Off when On and vice versa.

Any thoughts on how to approach solving this?

Cody

![D4AAF4FE-BD02-4BE2-B3F7-D6696CA5EF06](https://user-images.githubusercontent.com/50791984/153691920-a5e111dd-abc4-4b08-9e7d-70e0bfe7c212.png)

**Comment by Ernst79** [comment]
The sensor is actually not showing if it is on or off, but it is telling you if the weight is removed or not. So, if the weight is removed, it is True. The wording “scales turned on” should actually be “weight removed is True”. I will check if it is possible to change this.

**Comment by Ernst79** [comment]
I can't find any device category that should be able to represent "weight removed" better

But the main thing is that you changed the sensor name from "ble weight removed" to "Scales", which is something different. As explained, the sensor represents whether the weight is removed from the scale (On) or not (Off). It does not represent the On/Off state of the scale. 

I propose we change it to a device class "occupancy", which shows clear (on) and detected (off). We can than rename the sensor to "weight on scale".

**Comment by Ernst79** [comment]
I'm closing this issue. I think it's just a matter of renaming the sensor to what it represents (weight removed) in stead of `scales`.
