### ISSUE TITLE
iBeacon presence detection sensor

### ISSUE THREAD

**Issue by fokcuk** [custom-components/ble_monitor#714]
Hi
Can I please request for the entities to have a presence detection sensor? Impossible to know if the device is still there or not

**Comment by Ernst79** [comment]
Isn't that possible already with the option "track device"

![image](https://user-images.githubusercontent.com/24375847/153716596-25ccd5a5-cd21-4d27-853c-eac3e5155681.png)

**Comment by fokcuk** [comment]
where do you see it? I am pretty sure I have seen it before, but I cannot find it now

**Comment by Ernst79** [comment]
Go to the BLE monitor tile in integrations 
--> configure 
--> select your device in de the devices menu (at the bottom), 
--> submit 
--> In the new menu, you can set the option. Also set the two other options below, 

![image](https://user-images.githubusercontent.com/24375847/153716912-b538ffe5-15dd-4490-abba-86436eb7c420.png)

**[](https://custom-components.github.io/ble_monitor/configuration_params#consider_home)tracker_scan_interval**
(positive integer)(Optional) To reduce the state updates in Home Assistant and not spam your Home Assistant, it is advised to set a scan interval. After a BLE advertisement is received and the state has been updated, Home Assistant Scan will not update the state during the set interval to safe resources. The setting is in seconds. Default value: 20

**consider_home**
(positive integer)(Optional) This option sets the period with no data after which the device tracker is considered to be away. The setting is in seconds. Default value: 180

**Comment by fokcuk** [comment]
ah! Great! Does it create a new entity/sensor for tracking? Was expecting to find one but nothing really happened, maybe because it has not detected it yet?

**Comment by Ernst79** [comment]
If it is detected, it should add a `device_tracker` yes

**Comment by fokcuk** [comment]
hm... which one is which?
![image](https://user-images.githubusercontent.com/84503931/153717686-f5b372b9-4cfe-4dfe-9a60-848a54e03dd2.png)

**Comment by Ernst79** [comment]
@dmamontov I also have this behavior. I get a sensor with capitals and with lower case. It looks like it starts with the capital letters, but later changes to lower case and creates new entities. 

![image](https://user-images.githubusercontent.com/24375847/153718201-863c1300-d456-4dcc-80c5-6bb079cc7e19.png)

**Comment by dmamontov** [comment]
today far from the computer, but tomorrow I can look)

**Comment by Ernst79** [comment]
sure, no hurry.

**Comment by fokcuk** [comment]
yes, thanks guys. It must have created the upper case one before the device was actually detected. Once detected it created a new entity
