### ISSUE TITLE
Abnormal CPU usage

### ISSUE THREAD

**Issue by IMcA77** [custom-components/ble_monitor#717]
Noticed that my HA was using way above average cpu since the start of Feb.
![cpuavgmonth](https://user-images.githubusercontent.com/78562168/153940232-12e701c8-b5e4-4dbc-861c-0ba9c1a4fff6.jpg)

Finally managed to narrow it down to ble-monitor. CPU usage seems to gradually climb until it maxes out one core. Restarting HA cures it for a while but it always comes back.
Found out that simply disabling the ble-monitor in integrations brought the cpu down to normal almost instantly.

See Glances after integration has been running for a day and then 30 seconds after disabling the integration:

![glaces](https://user-images.githubusercontent.com/78562168/153940962-c48f6b8c-e859-45d9-b672-6d9420235fef.jpg)
![glaces2](https://user-images.githubusercontent.com/78562168/153940977-25d1bc92-f69c-4325-8459-ca66738f0428.jpg)

What kind of logs could I provide to diagnose the issue?

**Comment by Magalex2x14** [comment]
I also noticed the same thing yesterday.
See the discussion here (under the commit): https://github.com/custom-components/ble_monitor/commit/5a0741d4f4d3ae3b3bc70fe47e66b27150a04a6c
For a solution, try the current code from the master branch (just replace the files in the ble_monitor folder).
I found another problem in the library we are using (not related to the discussed here problem), so today / tomorrow there will be a fix, and I think then we will make a bugfix release.

**Comment by Magalex2x14** [comment]
Tell me also, how many BT-adapters do you have, and have there been any replacements/rearragements with them lately?

**Comment by IMcA77** [comment]
There are 2 adapters connected, 1 is selected via UI.
Noticed I also have duplicate macs in config_entry as mentioned in the commit
![config](https://user-images.githubusercontent.com/78562168/153951701-39b18d9f-5477-474d-8d8e-930547ec2454.jpg)

**Comment by Magalex2x14** [comment]
@IMcA77 thank you.

@Ernst79 I also updated btsocket requirement because of this https://github.com/ukBaz/python-btsocket/issues/1 (this problem has no serious symptoms).
Do you have a plan to make a new release soon? I am slightly concerned about the #717.

**Comment by Ernst79** [comment]
I'll create a new release now.
