### ISSUE TITLE
Brand Midea new BLE sensor support

### ISSUE THREAD

**Issue by olarodes** [custom-components/ble_monitor#718]
I bought a suit of Midea new arrival BLE device, including a Wi-Fi night-light with BLE gateway (MTD1.5-M/K-04), a BLE motion & light sensor (SS-B1), a BLE wireless button (SS-S1), a BLE TH sensor (SS-T1) and a BLE  window/door sensor (SS-D1).

The list price of this suit is CNY 299 (less than USD 50), but it is easily to buy these four sensor & one gw in offline physical store at a pretty good price (CNY 90 ≈ USD 15).

I am looking forward to add these accessible sensor into Hass.

[home-assistant.log](https://github.com/custom-components/ble_monitor/files/8076972/home-assistant.log)

The uploaded attachment is the log file during choosing report unknow as "other". Only three sensor (M&L, button & TH) is working. Because the window/door sensor was fixed in a distant room. 

Another key point to notice is that the name of BLE devices are all “Midea”, informed by Midea official doc. 
However, I just find only two BLE device named "Midea" with mac 04:D6:F4:1C:B8:97 and A4:C1:38:40:14:2D.
I suppose they are ML & TH sensor, while I cannot tell exactly.

Is there sufficient information here for you?
If not, I could continuously update info. in need.
Thank you！

**Comment by Ernst79** [comment]
First analysis. 

I see two different types of messages for `04:D6:F4:1C:B8:97`

**message type 1**
`020106` --> Flag
`06096d69646561` --> Complete local name = Midea
`12ffa806013739303939423538313333323533` --> manufacturer specific data, looks like it's the same every message, so probably not measurement data

**message type 2**
`0d1625fd020110a9690100000000`
`0effa806015f1c3297b81cf4d60400`

The `0d1625fd020110a9690100000000` looks the most promising data, the second one mostly consists of your MAC address (reversed). 

I'll create a beta version which allows you to filter only for Midea messages. Hopefully, you can make another log with that, with `report_unkown: midea`, which should filter only for the Midea messages.

**Comment by Ernst79** [comment]
Could you try to create a new log with 7.8.0-beta and report_unknown set to `midea`. Try to change the state of e.g. the light and motion sensor during the log, so I can check which bytes change. If possible, also make a now when you changed what, if possible.

**Comment by olarodes** [comment]
Thanks for your effort!

[home-assistant2.log](https://github.com/custom-components/ble_monitor/files/8101543/home-assistant2.log)

It is the log file about reporting midea device with 7.8.0-beta.

When I first started, only one device with ```MAC: 04:D6:F4:1C:B8:97``` has been advertising. 
After I changed the state and placement of all three sensor, it was still being. 
I tried to shut off the night-light gateway, then device with ```MAC: 04:D6:F4:1C:B8:97``` disappeared.
Instead, three devices named "midea" was advertising.
They are ```MAC: A4:C1:38:10:0A:57```, ```MAC: A4:C1:38:40:14:2D``` and ```MAC: A4:C1:38:20:0B:FA```.

After taking out the BLE sensor one by one from a sealed metal box (simple EM screen), I do can distinguish those tree sensors.
The sensor with ```MAC: A4:C1:38:10:0A:57``` is the wireless button (SS-S1).
The sensor with ```MAC: A4:C1:38:40:14:2D``` is the temperature & humidity sensor (SS-T1).
The last one with ```MAC: A4:C1:38:20:0B:FA``` is the motion & light sensor (SS-B1).

The problem still exists. No matter what I do to change the state of sensor (blocking the light, pressing the button once or twice, moving, holding the thermometer), the advertising message never change.
The shorter message ```0d1625fd020110a9690100000000``` is shared by four devices, including 3 sensor and 1 gateway.
It might be something like "group ID".
The longer message from 4 devices with same prefix ```12ffa8060137393``` . As you say,  it's the same every message from each device, so might not measurement data. Maybe "device ID", I guess.

Is there something wrong? Two types of message are both something constant like ID.
What can I do next？

Thank you again.

**Comment by olarodes** [comment]
> Thanks for your effort!
> 
> [home-assistant2.log](https://github.com/custom-components/ble_monitor/files/8101543/home-assistant2.log)
> 
> It is the log file about reporting midea device with 7.8.0-beta.
> 
> When I first started, only one device with `MAC: 04:D6:F4:1C:B8:97` has been advertising. After I changed the state and placement of all three sensor, it was still being. I tried to shut off the night-light gateway, then device with `MAC: 04:D6:F4:1C:B8:97` disappeared. Instead, three devices named "midea" was advertising. They are `MAC: A4:C1:38:10:0A:57`, `MAC: A4:C1:38:40:14:2D` and `MAC: A4:C1:38:20:0B:FA`.
> 
> After taking out the BLE sensor one by one from a sealed metal box (simple EM screen), I do can distinguish those tree sensors. The sensor with `MAC: A4:C1:38:10:0A:57` is the wireless button (SS-S1). The sensor with `MAC: A4:C1:38:40:14:2D` is the temperature & humidity sensor (SS-T1). The last one with `MAC: A4:C1:38:20:0B:FA` is the motion & light sensor (SS-B1).
> 
> The problem still exists. No matter what I do to change the state of sensor (blocking the light, pressing the button once or twice, moving, holding the thermometer), the advertising message never change. The shorter message `0d1625fd020110a9690100000000` is shared by four devices, including 3 sensor and 1 gateway. It might be something like "group ID". The longer message from 4 devices with same prefix `12ffa8060137393` . As you say, it's the same every message from each device, so might not measurement data. Maybe "device ID", I guess.
> 
> Is there something wrong? Two types of message are both something constant like ID. What can I do next？
> 
> Thank you again.

**Comment by Ernst79** [comment]
There are two types of BLE communication, 

1. the sensor sends data into the air and any device can read the data. 
2. the sensor requires a connection to be set up, After the connection is established, the sensor and the receiving device communicate directly by asking for certain data (cannot be read by other devices at the same time). 

Based on the information you gave, it looks like it uses the 2nd type of communication. This is not supported by BLE monitor unfortunately. You could use ESPHome BLE client for that. https://esphome.io/components/ble_client.html
