### ISSUE TITLE
Support for Sensirion SHT31

### ISSUE THREAD

**Issue by roesel** [custom-components/ble_monitor#719]
First of all, thank you for you amazing work. I have been using this component for a while for some Xiaomi BLE devices and it works flawlessly. Recently, I got my hands on a Sensirion SHT31 development kit, which is much more precise and fast than anything else I have tried, link [here](https://developer.sensirion.com/archive/platforms/sht31-smart-gadget-development-kit/).

Would it be possible to use ble_monitor for this? If so, what could I do to make it work? 

Thank you and I hope I didn't miss something in the docs about this device.

**Comment by pvvx** [comment]
> Would it be possible to use ble_monitor for this?

[This device  software](https://github.com/Sensirion/SmartGadget-Firmware) does not transmit data in advertising packages.  Connection required.

> If so, what could I do to make it work?

Add the data transfer code in the advertise packages. Use the formats available in 'ble_monitor'.

**Comment by roesel** [comment]
Thanks for your answer @pvvx ! I understand that the problem is that this device does not transmit advertising packages. 

> Add the data transfer code in the advertise packages.

However, I am afraid I do not understand what exactly you mean by this. Should I be trying to change the code running on the device somehow, or the code of 'ble_monitor' itself? Would you be able to elaborate a little bit on this? 

Thanks again, I really appreciate it.

**Comment by pvvx** [comment]
Requires  change the code firmware as in the implementation from:
https://github.com/Sensirion/shtc3_ble_beacon

**Comment by Ernst79** [comment]
@roesel There are two ways to send BLE data, method 1 is just sending it out into the air, method 2 is only send data when you ask the device to send data. BLE monitor only supports the first method, so the device has to send the data periodically. Apparently you are able to change the firmware of this sensor, so you could try to make the sensor send the data periodically.

**Comment by roesel** [comment]
@Ernst79 Thanks for the explanation! At this point, I don't think I would be able to change the firmware of the device myself. So for now, I'll have to be happy with reading the display :). If you (or anyone else) know an integration that might work with this sensor, please let me know!

**Comment by Ernst79** [comment]
You might be able to use ESPHome BLE cliets, which is able to set up a connection to a device. 

https://esphome.io/components/ble_client.html

I'm closing this issue here. as BLE monitor wont be able to support this device, as we can't make a connection.
