### ISSUE TITLE
Integration generates entity attributes with spaces in their names causing potential trouble downstream

### ISSUE THREAD

**Issue by mleiber** [custom-components/ble_monitor#723]
The BLE integration generates entity attributes with blanks/spaces in their names. Examples for Govee and Xiaomi Temperature sensors are:
```
sensor type
mac address
last packet id
last mean of
```
When trying to use them in the front-end, e.g. as filters for ```custom:auto-entities``` they seem to not work as expected.

I believe the names should have underscores **_** instead of blanks in their names.

**Comment by Ernst79** [comment]
It looks like you're right. I checked some other integrations, and they all seem to have underscores in the attributes. I will create a fix.

**Comment by Ernst79** [comment]
Fixed in 7.8.2

**Comment by borpin** [comment]
@Ernst79 did you do this as a breaking change? I check for the attribute "sensor type" in templates /Node-Red for instance so all these will break :(

**Comment by Ernst79** [comment]
Yes, it was mentioned as a breaking change. Sorry for the inconvenience,
but I had to change it, as it caused issues and I would like to stick to HA
standards as much as possible.

Op ma 21 feb. 2022 om 10:13 schreef Brian Orpin ***@***.***>:

**Comment by borpin** [comment]
Hi, yes saw that subsequently - thanks :)

**Comment by mleiber** [comment]
Thanks for the quick fix. Just checked, the issue I had with custom:auto-entities and the use of attribute filters is now gone.
