### ISSUE TITLE
GCLS002 - "UNKNOWN dataobject `0x100B` in payload"

### ISSUE THREAD

**Issue by mundschenk-at** [custom-components/ble_monitor#727]
I'm running an ESPHome BLE gateway with some plant sensors (both big and small ones). I've enabled the reporting of unknown advertisements. I get a lot of the following messages: 
```
[custom_components.ble_monitor.ble_parser.xiaomi] MiVer: 2, DevID: 0x3bc : GCLS002, FnCnt: 205, Request timing, Not bound, Old version certification, Capability: 0xd, No encryption, Object data: 0b100100, UNKNOWN dataobject in payload! Adv: 131695fe7120bc03cd6d666d8d7cc40d0b100100
```

**Comment by Ernst79** [comment]
I had a look, and it sends a packet with 
- object ID `0x100B` (reverse the first two bytes of the Object data in the log line you have send). 
- length `01` (3rd byte)
- value `00` 4th byte

Questions is what object ID `0x100B` represents. 

Normally, Xiaomi has its data well defined on this page: https://iot.mi.com/new/doc/embedded-development/ble/object-definition (use google translate). But the table skips `0x100B`. So, I don't know what this data actually is? 

![image](https://user-images.githubusercontent.com/24375847/154797282-e6b4dab5-26f5-46f0-ac4e-dfae6c9d05cd.png)

Also Xiaomi Gateway 3 integration doesn't use this object ID (https://github.com/AlexxIT/XiaomiGateway3/blob/master/custom_components/xiaomi_gateway3/core/converters/mibeacon.py). 

So, what you can try is to look at the last two numbers of the `Object data` (in the LOG line `00`) and check if it changes at a certain event (motion, light/dark, ....). My first guess (and just a wild guess) it could be light/dark indicator). But you will have to check before we can add it as a sensor.

**Comment by mundschenk-at** [comment]
I thought it might be the battery level (thought that would likely be 100 % still), but I'll check if it changes with covering the sensor or something.

**Comment by Ernst79** [comment]
The current value is 0, so I was guessing it’s some binary value (on/off, light/dark, …/…)

**Comment by mundschenk-at** [comment]
Doesn't look like it's light/darkness, I put a cardboard box over one of the sensors, no change in the advertisement.

**Comment by Ernst79** [comment]
ok, than I have no idea what it represents. Perhaps it is a low battery indicator, which becomes 1 is it has a low battery?

**Comment by mundschenk-at** [comment]
Then we will see in a few months 😅

**Comment by Ernst79** [comment]
I’m closing this issue for now, let me know if you ever find out the meaning.
