### ISSUE TITLE
(New Device) Vanmoof Electric Bikes

### ISSUE THREAD

**Issue by djfanatix** [custom-components/ble_monitor#728]
Is support for Vanmoof Electric bikes possible?
To read the battery level, etc.?

see: https://github.com/quantsini/pymoof

**Comment by Ernst79** [comment]
I'm afraid not, it requires a connection to be set up, before it will start communicating. This is not supported by BLE monitor. You could try ESPhome BLE Client (https://esphome.io/components/ble_client.html)
