### ISSUE TITLE
Device level report_unknown isn't available in UI

### ISSUE THREAD

**Issue by mrand** [custom-components/ble_monitor#735]
Not sure if this intentional or is missing on accident.  I was trying to enable device level unknown reporting, per

https://custom-components.github.io/ble_monitor/configuration_params#configuration-parameters-at-device-level

But could not find it in my UI.  Looking closer, I see it isn't the in the screen cap on that page.  If it isn't intended to be in the UI, perhaps consider adding a note that it's only available using YAML config.

**Comment by Ernst79** [comment]
You're too fast, I haven't released that change yet. Will do that tonight.

**Comment by mrand** [comment]
Ah! No worries. Now makes more sense, cause it is flagged as an invalid option in HA's YAML checker also.   :-)
