### ISSUE TITLE
New Device: Oral-B SmartSeries 7000 toothbrush

### ISSUE THREAD

**Issue by theliquid** [custom-components/ble_monitor#740]
Hi,

I just realized that ble_monitor recognized my Oral-B SmartSeries 7000 toothbrush out of the box:
![grafik](https://user-images.githubusercontent.com/7244373/155212571-c6df307c-0592-4738-84f7-51ec20d0437a.png)

Do you need any more information for official support?

**Comment by Ernst79** [comment]
What do you mean with “ official support”?

**Comment by theliquid** [comment]
That more attributes can be used as entities? Or can I do this myself without any code change?

**Comment by Ernst79** [comment]
You mean that the attributes can be used as sensors? You can use a template sensor for that.

**Comment by theliquid** [comment]
Yes. Thanks, I will look into this.
