### ISSUE TITLE
Custom fw LYWSD03MMC, CGG1, MHO-C401, CGDK2 and events (Mi format)

### ISSUE THREAD

**Issue by pvvx** [custom-components/ble_monitor#741]
**Custom fw LYWSD03MMC, CGG1, MHO-C401, CGDK2.**

It is not possible to enable transmission of events like "door opened" or "switch on" in the protocol "mi":
In the transmission mode in the "Mi" format, there is no reception of advertising with an event from the reed switch (the door is open) and the key (switch: on/off).

Temperature, humidity and battery status are accepted:
![image](https://user-images.githubusercontent.com/12629515/155375929-45502c72-75d7-4679-ae97-813bcd53f192.png)

Advertising Data:
    Service Data - 16 bit UUID Xiaomi Inc. (0xfe95),  Length: 12, Data: 40506f06e912100101
Switch: 01 
    Service Data - 16 bit UUID Xiaomi Inc. (0xfe95),  Length: 12, Data: 40506f06e919100100
Door: opened
    Service Data - 16 bit UUID Count 24 (0x2aeb),  Length: 6,  Data: 000005
Count 24 bits: 5 
|len|type|uuid|fnctrl|devid|cnt|dataid|dlen|data| |len|type|uuid|data|
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|0c|16|95fe|4050|6f06|e9|1210|01|01| |06|16|eb2a|000005|
|0c|16|95fe|4050|6f06|e9|1910|01|00| |06|16|eb2a|000007| 

What needs to be corrected in adv-events or ble_monitor to work in "mi" format?

**Comment by Ernst79** [comment]
Just checking that I understand your question. You want to send “door opening” and “switch” events in Xiaomi MiBeacon format from a sensor with ATC firmware, and you want BLE monitor to process this data. Is that yant you want to achieve?

**Comment by pvvx** [comment]
Yes.
A variant with a reed switch in several modifications is being worked out - a counter and an opening sensor.
How to transfer the meter (water / electricity) is generally unclear.

**Comment by pvvx** [comment]
Events Announced:
 https://iot.mi.com/new/doc/embedded-development/ble/object-definition 
General Event: Door ID: 0x0007 -  But there is no such thing in the ble_monitor.

**Comment by Ernst79** [comment]
One thing that needs to be done is adding a switch and opening sensor in const.py for the different sensors, in the last list in this line (do the same for the other sensor types as well)

https://github.com/custom-components/ble_monitor/blob/d77b1f1d5f15d0e3867deb260250fe040c2caa71/custom_components/ble_monitor/const.py#L779

We also need to modify this a bit, where it is disabling the opening and switch binary sensor by default. 

https://github.com/custom-components/ble_monitor/blob/d77b1f1d5f15d0e3867deb260250fe040c2caa71/custom_components/ble_monitor/binary_sensor.py#L327

I can make these changes for you, no problem

**Comment by pvvx** [comment]
Will this break compatibility with other "mi" devices?

**Comment by Ernst79** [comment]
No, don't think so. 

You can use this if you want `0x0007`

```
def obj0007(xobj):
    # Door
    open_obj = xobj[0]
    if open_obj == 0:
        opening = 1
        status = "opened"
    elif open_obj == 1:
        opening = 0
        status = "closed"
    elif open_obj == 2:
        opening = 1
        status = "timeout is not closed"
    elif open_obj == 3:
        opening = 0
        status = "knock on the door"
    elif open_obj == 4:
        opening = 1
        status = "breaking the door"
    elif open_obj == 5:
        opening = 0
        status = "door is stuck"
    else:
        opening = 0
        status = None
    return {"opening": opening, "status": status}
```

**Comment by Ernst79** [comment]
Note that Home Assistant has an "Opening" sensor and a "Door" sensor. I'm using 0x1019 as an "opening" sensor, as it generally is a door/window sensor. So I use the Opening sensor, 

Note that in Xiaomi format, open = 0, in Home Assistant open = 1 (True)

**Comment by pvvx** [comment]
Thanks!
I will try to solve the problem of passing values from a door or window sensor (reed switch) without the need to change the code in third-party applications.
No changes to 'ble_monitor' are required yet.

There is only one unsolvable problem - how to transfer data from impulse counters. It is relevant for any DIA device. The current variants, described in [ha_ble](https://custom-components.github.io/ble_monitor/ha_ble), do not have this option.

**Comment by Ernst79** [comment]
I will add a counter sensor this weekend, no problem
