### ISSUE TITLE
Inkbird / iBBQ battery level, maybe?

### ISSUE THREAD

**Issue by mrand** [custom-components/ble_monitor#742]
At first glance it appears battery level might be available as well.  If it's easy to do, would you consider adding it?
https://github.com/8none1/pybq/blob/master/bbq.py

(which might have been based on this initial research?)
https://gist.github.com/uucidl/b9c60b6d36d8080d085a8e3310621d64

**Comment by Ernst79** [comment]
Battery info is only send after setting up a connection between the sensor and receiver. This isn’t possible with BLE monitor unfortunately.
