### ISSUE TITLE
Deactivating Discover devices and sensors automatically has no effect

### ISSUE THREAD

**Issue by mb-software** [custom-components/ble_monitor#743]
Hello,
I have "discover devices and sensors automatically" deactivated and cleaned up all unneeded devices and entities. But still the integration adds all detected bluetooth devices again immediatelly.
This together with the growing number of supported devices and especially with IBeacons, this integration became a nightmare for me and I had to deactivate it completely. Due to the many sensors created for IBeacons (which I don't want to use at all) I get very quickly over 100 entities spamming my HA....

**Comment by Ernst79** [comment]
Can you show your configuration of BLE monitor? I can’t reproduce the behavior you describe

**Comment by mb-software** [comment]
well, it's only this checkbox as described, it is not checked:
![image](https://user-images.githubusercontent.com/36257766/155701814-564c2ede-6762-4461-bc19-d25cec699eff.png)
when I use the service to clear BLE monitor entries, all deactivated devices are removed for a short time. But after only few seconds they appear again.

**Comment by Ernst79** [comment]
But if you scroll down, which sensors are displayed on the pull down menu under "devices". 

You will have to delete the sensors from that list as well, by selecting a MAC, submit, select "delete device" and submit twice

**Comment by mb-software** [comment]
Thanks, that did the trick. I was following the description in the FAQ which did not mention this "delete device" option in the UI....-

**Comment by Ernst79** [comment]
I have updated the docs.
