### ISSUE TITLE
Error setting up entry Bluetooth Low Energy Monitor

### ISSUE THREAD

**Issue by jmbaggs** [custom-components/ble_monitor#751]
I've been running this with no issues since January but I think one of the latest updates broke something. 

I'm running Home Assistant in VirtualBox VM on Windows 10. I'm using the integration to monitor some temp & humidity sensors 

This is my first time using this system to report an issue so please let me know if there is anything else you need

First I get this: 

This error originated from a custom integration.

Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:316
Integration: Passive BLE monitor (documentation, issues)
First occurred: 4:12:49 PM (1 occurrences)
Last logged: 4:12:49 PM

Bluetooth adapter with MAC address 00:E0:4C:1A:E7:63 was not found. It is therefore changed back to the default adapter. Check the BLE monitor settings, if needed.

Then this: 

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ble_monitor/__init__.py:374
Integration: Passive BLE monitor (documentation, issues)
First occurred: 4:12:49 PM (1 occurrences)
Last logged: 4:12:49 PM

Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ble_monitor/__init__.py", line 374, in async_setup_entry
    list(BT_INTERFACES.values()).index(DEFAULT_BT_INTERFACE)
ValueError: 'disable' is not in list

**Comment by Ernst79** [comment]
It’s telling you that it can’t find a Bluetooth adapter. Are you sure the Bluetooth dongle/adapter can be used by the OS. I know that on Linux, this can happen after an update. Most of the times, a restart is sufficient. Not sure for VM, but did yo try to restart?

**Comment by jmbaggs** [comment]
No problems using the dongle with the OS since I got it. I've been running Home Assistant with BLE integration for weeks with no problems. 

This first happened yesterday. Rebooting the VM did not fix the problem. I eventually deleted the integration and re-added it. That worked fine until about an hour ago when it broke again. This time rebooting did fix the problem. 

I had also been getting some hci0 timeout errors earlier in the week but everything seemed to continue working properly.

**Comment by Ernst79** [comment]
Are you using more than one Bluetooth integration on your system or are you using Bluetooth for something else at the same time?

**Comment by Ernst79** [comment]
Did you had a look at my last post?

**Comment by Ernst79** [comment]
Fixed the error in 8.1.1.
