### ISSUE TITLE
Xiaomi MI Temperature and Humidity Monitor 2 gives incorrect values.

### ISSUE THREAD

**Issue by burne101** [custom-components/ble_monitor#754]
Discovering and setting up was no problem, but once configured the sensor (via the ble_monitor integration) informs me that is 128.2ºC and 112.2%RH in my room. The display on the sensor itself says 21.1ºC and 65%RH

(https://www.google.com/search?q=Xiaomi+MI+Temperature+and+Humidity+Monitor+2)

**Comment by Ernst79** [comment]
That is really strange, as BLE monitor filters out temperatures above 60°C. What settings do you use the temperature unit in the BLE monitor settings --> devices?

**Comment by Ernst79** [comment]
Did you had a change to look at my request for your settings?

**Comment by Ernst79** [comment]
Closing this issue due to no response. Feel free to reopen the issue, in case you have additional information.
