### ISSUE TITLE
Support for InkBird IBS-M1 would be great!

### ISSUE THREAD

**Issue by randrcomputers** [custom-components/ble_monitor#758]
Any chance of adding support for the InkBird IBS-M1?

**Comment by Ernst79** [comment]
Yes, most likely this is possible. But ones some ble advertisements for that. Instructions how you can get these are in the faq

https://custom-components.github.io/ble_monitor/faq#my-sensor-is-not-in-the-list-of-supported-ones-how-to-request-implementation

**Comment by randrcomputers** [comment]
This is actually no longer needed all sensors i had (qty4) now work direct to HA so hub(IBS-M1) is no longer needed at all!
