### ISSUE TITLE
New device support - will submit as merge request

### ISSUE THREAD

**Issue by sergey-kalin** [custom-components/ble_monitor#760]
Hey,

```
manufacturer: Relsib
name: Hygro thermometer with CO2 sensor
model: EClerk Eco
```
https://relsib.com/uploads/products/compress/1561458148_signalizator-kachestva-vozduha-eclerk-eco-a.jpg

I own that device. Requested protocol from manufacturer, implemented and tested:
![image](https://user-images.githubusercontent.com/97535544/156881888-c475cf5c-40b4-4629-8fdb-c2f8e03eacc4.png)
(numbers bit different due to median applied on component side)

Willing to submit device support with MR to your project :)

Attaching as diffs to the ticket just in case, so you can merge on your own. One for protocol and one for docs:
[patch0001-protocol.diff.zip](https://github.com/custom-components/ble_monitor/files/8190589/patch0001-protocol.diff.zip)
[patch0002-docs.diff.zip](https://github.com/custom-components/ble_monitor/files/8190590/patch0002-docs.diff.zip)

**Comment by Ernst79** [comment]
Thanks, will add it.

**Comment by Ernst79** [comment]
Added in 7.9.5. Thanks again for your contribution
