### ISSUE TITLE
Support for Switchbot Thermometer and Hygrometer (MeterTH S1)

### ISSUE THREAD

**Issue by grantbowering** [custom-components/ble_monitor#764]
Product page: https://www.switch-bot.com/products/switchbot-meter

With BLE monitor in passive scan, I only get `043e1` messages, which aren't very helpful:
```
BLE advertisement received from MAC/UUID ce07223569f2: 
043e1902010001f269352207ce0d02010609ff5900ce07223569f2c7
```

But if I check `Use active scan in stead of passive scan`, then I also receive `043e2` messages with the service data:
```
BLE advertisement received from MAC/UUID ce07223569f2: 
043e2802010401f269352207ce1c11071bc5d5a50200b89fe6114d22000da2cb0916000d54006400990ec7
```

So it looks like this sensor will work in active scan mode 😃
(More log data: [Switchbot Meter BLE advertisements.txt](https://github.com/custom-components/ble_monitor/files/8193585/Switchbot.Meter.BLE.advertisements.txt))

Best part is, there's already python code to interpret these bytes:
https://github.com/bbostock/Switchbot_Py_Meter/blob/c5cb0daff787a0a8c6e519d49797c96a5e6c6816/meters.py#L70-L77
```
                        if value.startswith('000d'):
                            byte2 = int(value[8:10],16)
                            battery = (byte2 & 127)
                            byte3 = int(value[10:12],16)
                            byte4 = int(value[12:14],16)
                            byte5 = int(value[14:16],16)
                            tempc = float(byte4-128)+float(byte3 / 10.0)
                            humidity = byte5
```
I double-checked this code (ported to C#; I don't really speak python or this issue would just be a pull request 😳) and it translated the above-logged data accurately to what was on my device's screen. 👍

I'm also attaching .md and .jpg files to this issue, just to save the implementer some time. 🙂
[Switchbot_MeterTH-S1.md](https://github.com/custom-components/ble_monitor/files/8193619/Switchbot_MeterTH-S1.md)
![Switchbot_MeterTH-S1](https://user-images.githubusercontent.com/2152220/156944023-901b0bb3-e0e7-4caf-8236-a1ebd25aae05.jpg)

**Comment by Ernst79** [comment]
I do not understand how they get these 8 bytes. You have 6 bytes + 1 byte RSSI after `000d`

`000d  54006400990e  c7`

When I look at the data, I see only 6 bytes??? (the last byte is always RSSI (by definition)

`5400` --> `0054` in little endian = 84 (humidity?)
`6400` --> `0064` in little endian = 100 (battery?)
`990e` --> `0e99` in little endian = 3737 (temperature after dividing by 100????)

In the code below, they are talking about 8 bytes (8 till 16), 

```python
                        if value.startswith('000d'):
                            byte2 = int(value[8:10],16)
                            battery = (byte2 & 127)
                            byte3 = int(value[10:12],16)
                            byte4 = int(value[12:14],16)
                            byte5 = int(value[14:16],16)
                            tempc = float(byte4-128)+float(byte3 / 10.0)
                            humidity = byte5
```

Could you tell me what the temperature/humidity was at the moment you made the BLE advertisement

**Comment by Ernst79** [comment]
I managed to decode it, I think

```
result  ({'temperature': 25.0, 'humidity': 14, 'battery': 100, 'rssi': -57, 'mac': 'CE07223569F2', 'type': 'MeterTH S1', 'packet': 'no packet id', 'firmware': 'Switchbot', 'data': True}, None)
```

**Comment by Ernst79** [comment]
Please try 7.9.6-beta. Should be added

**Comment by Ernst79** [comment]
Added in 7.9.6 as final. Fixed the temperature reading that was wrong in the beta.
