### ISSUE TITLE
Voltage, higher decimal precision

### ISSUE THREAD

**Issue by jhbruhn** [custom-components/ble_monitor#765]
The b-parasite sensor reports it's battery state via a voltage attribute. Currently, there is only one decimal of precision, which allows for some guess about the state, but only on a macro level. One or more two decimals after the point would be nice to be able to guess the battery charge more accurately.

**Comment by Ernst79** [comment]
You can set the number of decimals in the BLE monitor options --> devices --> select your sensor MAC --> number of decimals. This does however count for all entities of that device than, so also for temperature, humidity, etc. 

![image](https://user-images.githubusercontent.com/24375847/157190825-39736406-ed19-4107-a7e1-99fe5ff4ccdd.png)

The difficulty with making individual number of decimals per measurement type is that we will get huge menu's, it would require a setting for every sensor type that is supported in BLE monitor, which is a lot.

**Comment by jhbruhn** [comment]
That works for me, thanks!
