### ISSUE TITLE
Air Mentor PRO 2

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#768]
### Discussed in https://github.com/custom-components/ble_monitor/discussions/767

<div type='discussions-op-text'>

<sup>Originally posted by **JonScaife** March  8, 2022</sup>
Hi
Thanks for the great work on this.  I'm using it to monitor BLE plant sensors all over the house and it works really well.
I wondered if you were accepting requests for other devices to consider supporting?  I have an "Air Mentor Pro 2" which uses BLE.  Someone has got it working with Samsungs "SmartThings" platform and I was able to connect to it from the bluetooth command line within HA, but my distinct lack of programming knowledge seems to have been too big a barrier to actually pulling meaningful data from it.  If you are accepting requests please consider this device!
The code for the SmartThings implementation is at https://community.smartthings.com/t/successfully-integrated-air-quality-monitor-air-mentor-pro-2-in-smartthings-using-raspberry-pi/79574
Many thanks</div>

**Comment by Ernst79** [comment]
Yes, looks very well possible. Based on the info in the link, I think it sends two messages. 

**first message**

`043E1B02010000A5808FE648540F0201060BFF222100b91963332d0145CC`

I managed to translate this to:

```
result  ({'TVOC': 185, 'temperature': 24.99, 'temperature calibrated': 19.89, 'humidity': 61.34, 'IAQ': 325, 'rssi': -52, 'mac': '5448E68F80A5', 'type': 'Air Mentor Pro 2', 'packet': 'no packet id', 'firmware': 'Air Mentor', 'data': True}, None)
```

**second message** 

`043E1B02010000A5808FE648540F0201060BFF21212710000300030000CC`

```
result  ({'co2': 10000, 'pm25': 3, 'pm10': 3, 'battery': 0, 'voltage': 0, 'rssi': -52, 'mac': '5448E68F80A5', 'type': 'Air Mentor Pro 2', 'packet': 'no packet id', 'firmware': 'Air Mentor', 'data': True}, None)
```

The battery and voltage sensor are most likely something else, the python script in the link you gave doesn't use this. My guess one of these is is something like "charging" or "connected to the main power" I will create a test version for you to find out. coming days. .

**Comment by Ernst79** [comment]
![image](https://user-images.githubusercontent.com/24375847/157329477-a07d78bf-172f-45ef-b62e-997289c16c46.png)

**Comment by Ernst79** [comment]
@JonScaife Please try 7.9.6-beta to test. Could you check the battery and voltage sensor, if you can figure out what it represents. Most likely not battery and voltage, but something else (e.g. charging/not charging or something completely different) 

In the python code from the link you gave, I see `[CO O3]` so, perhaps carbon-monoxide and ....

**Comment by Ernst79** [comment]
Added in 7.9.6 as final. Removed the voltage and battery sensor, as they don't seem to be functional.

**Comment by JonScaife** [comment]
Wow - thanks - you did this so fast I didn't even manage to come back to check on the request before it was completely done.  I will update and get it in use now.  Thanks so much for such a speedy reply and implementation - amazing!

**Comment by Ernst79** [comment]
Can be that the phone uses an active connection. Perhaps empty battery? or did you change something in your HA setup (new USB connected devices that mess up the Bluetooth signal, especially SSD's)

**Comment by JonScaife** [comment]
Hi - thanks for the super quick response.  I've identified the change that causes the problem.  If I turn off "Discover devices and sensors automatically" the sensors all go unknown and stay unknown.  If I turn it back on and reload the app on the phone the values all repopulate
I suspect the app/phone is using an active connection somehow prompting the device to provide an update which I'm assuming explains why the app has to be running for it to work.  Not sure why it needs "Discover devices and sensors automatically" enabled though.  I prefer to have that turned off or it gradually picks up loads of devices as people walk past in the street with iPhone / headphones etc etc
