### ISSUE TITLE
r4s support?

### ISSUE THREAD

**Issue by Psytoshgen** [custom-components/ble_monitor#773]
Hi, is there any chance to get Ready4sky support?
I got RMC-M223S and integration can see it like iBeacon
![cc052ace58b22db01d4a23ffd9207540-53997193](https://user-images.githubusercontent.com/94195788/157840414-8cd8e867-ad52-4f88-ba01-661ea5ec6013.jpg)

I think you can find some information in this repo
https://github.com/mavrikkk/ha_kettler

**Comment by Ernst79** [comment]
Unfortunately not. It is require-ing a connection to be set up, which is not possible with BLE monitor. BLE monitor can only passively listen to BLE advertisements, not asking for it. 

You can use [ESPhome BLE client](https://esphome.io/components/ble_client.html) for setting up a connection and communicate with the kettle.
