### ISSUE TITLE
Add support for Geberit AquaClean toilet 

### ISSUE THREAD

**Issue by elRadix** [custom-components/ble_monitor#774]
I have a Geberit AquaClean Tuma model,  someone already created a BT framework.
Is it possible that you can support for this BT toilet?

https://github.com/thomas-bingel/geberit-aquaclean

Let me know. what you need more data in order to provide you the logs. and how to get the logs?

**Comment by elRadix** [comment]
Here some output

`Device Name: Geberit AC PRO
Device Address: 10:08:2C:2C:08:DD

Services:--------------------------
Unknown service (3334429d-90f3-4c41-a02d-5cb3a03e0000)
	Unknown characteristic (3334429d-90f3-4c41-a02d-5cb3a13e0000)
	Unknown characteristic (3334429d-90f3-4c41-a02d-5cb3a23e0000)
	Unknown characteristic (3334429d-90f3-4c41-a02d-5cb3a33e0000)
	Unknown characteristic (3334429d-90f3-4c41-a02d-5cb3a43e0000)
	Unknown characteristic (3334429d-90f3-4c41-a02d-5cb3a53e0000)
	Unknown characteristic (3334429d-90f3-4c41-a02d-5cb3a63e0000)
	Unknown characteristic (3334429d-90f3-4c41-a02d-5cb3a73e0000)
	Unknown characteristic (3334429d-90f3-4c41-a02d-5cb3a83e0000)


GAP (00001800-0000-1000-8000-00805f9b34fb)
	Device Name (00002a00-0000-1000-8000-00805f9b34fb)
	Appearance (00002a01-0000-1000-8000-00805f9b34fb)
	Peripheral Privacy Flag (00002a02-0000-1000-8000-00805f9b34fb)
	Reconnection Address (00002a03-0000-1000-8000-00805f9b34fb)
	Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)
	Service Changed (00002a05-0000-1000-8000-00805f9b34fb)


Device Information (0000180a-0000-1000-8000-00805f9b34fb)
	System ID (00002a23-0000-1000-8000-00805f9b34fb)
	Model Number String (00002a24-0000-1000-8000-00805f9b34fb)
	Serial Number String (00002a25-0000-1000-8000-00805f9b34fb)
	Firmware Revision String (00002a26-0000-1000-8000-00805f9b34fb)
	Hardware Revision String (00002a27-0000-1000-8000-00805f9b34fb)
	Software Revision String (00002a28-0000-1000-8000-00805f9b34fb)
	Manufacturer Name String (00002a29-0000-1000-8000-00805f9b34fb)
	IEEE 11073-20601 Regulatory (00002a2a-0000-1000-8000-00805f9b34fb)
	PNPID (00002a50-0000-1000-8000-00805f9b34fb)


--------------------------`

**Comment by Ernst79** [comment]
Unfortunately this won't be possible. This device requires a connection to be set up, which is not possible with BLE Monitor. You could try ESPhome BLE Sensor to connect and read the characteristics.
