### ISSUE TITLE
Unable to remove unplugged Bluetooth adapter by Web UI

### ISSUE THREAD

**Issue by abu9** [custom-components/ble_monitor#778]
Hi,  I just replaced my BLE adapter and want to update my config by UI. I got an error message when submit the config due to the old adapter still enable but the item is disappeared so that I can't do anything.

**Comment by Ernst79** [comment]
Did you fully restart the system? Can you enable debug logging for BLE monitor in HA to see where it fails?

**Comment by abu9** [comment]
I got a debug msg ```Bluetooth adapter with MAC address xxx was not found. It is therefore changed back to the default adapter. Check the BLE monitor settings, if needed.``` , it remind me the issue occurs when i lost the default BLE adapter by some kernel drive issue. There is no BLE adapter on my machine. So i decided to use ESPHome BLE gateway to forward BLE adv. After that I did something below:
1. Reboot HA core
2. Try to mark 'Don't use Bluetooth adapter' option and submit by UI
4. Error shows unable to connect previous adaptor or something similar, i can't remember what exactly the message say because the log file has been overwrite

**Comment by Ernst79** [comment]
Ok, I will look into it.

**Comment by Ernst79** [comment]
I can reproduce the issue. It should have selected "Don't use Bluetooth adapter" automatically. Will look further into it. 

![image](https://user-images.githubusercontent.com/24375847/159062634-06b163b6-92ff-4a87-8612-d68c2a356fe5.png)

**Comment by Ernst79** [comment]
Fixed in 81.1
