### ISSUE TITLE
iBBQ-6 - Sensor values above 100C show as unknown in HASS

### ISSUE THREAD

**Issue by wildekek** [custom-components/ble_monitor#779]
I have an issue where sensors that read values > 100 degrees C on my Inkbird iBBQ-6 show up as "unknown" in HASS. I did some testing with with different sensor ports, but I am pretty sure it is the value causing the issue.

Debug log:
`DEBUG (MainThread) [custom_components.ble_monitor.sensor] Data measuring sensor received: {'firmware': 'Inkbird', 'temperature probe 1': 107.0, 'temperature probe 2': 84.0, 'temperature probe 3': 0, 'temperature probe 4': 0, 'temperature probe 5': 0, 'temperature probe 6': 0, 'rssi': -70, 'mac': '0035FFDAC988', 'type': 'iBBQ-6', 'packet': 'no packet id', 'data': True}
2022-03-17 17:22:50 DEBUG (Thread-100) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird Data: 2e044803f6fff6fff6fff6ff
2022-03-17 17:22:50 DEBUG (MainThread) [custom_components.ble_monitor.sensor]`

In the case mentioned above, the values of 'temperature probe 1' shows as "unknown" in HASS, all other show just fine.

My install:
BLE_monitor version: 8.0.5-beta
HASS OS: 7.5
HASS core: core-2022.3.5

**Comment by Ernst79** [comment]
Ah, I see the issue. Add iBBQ-6 in this list, will fix it next release

https://github.com/custom-components/ble_monitor/blob/c3e5051940c636543817ba22b11ba00c7d266d47/custom_components/ble_monitor/const.py#L117

**Comment by wildekek** [comment]
It works, you rock!

**Comment by Ernst79** [comment]
Fixed in 8.1.0. Thanks for your sponsoring!
