### ISSUE TITLE
New device support （ZN-2CO5）

### ISSUE THREAD

**Issue by louliangsheng** [custom-components/ble_monitor#780]
Can you support this device, AIR QUALITY MONITOR 2CO5（ZN-2CO5）.
Here is its product link: https://alexnld.com/product/zn-2co5-wall-mounted-3-in-1-air-quality-monitor-co2-carbon-dioxide-hcho-formaldehyde-tvoc-detector-digital-temperature-humidity-meter/
its iOS app:  https://apps.apple.com/cn/app/rcxazair-quality-detector/id1577124598

**Comment by Ernst79** [comment]
Please check this page on how to get some data from the sensor. We need this data to see if we can add support.

https://custom-components.github.io/ble_monitor/sensor_request

**Comment by louliangsheng** [comment]
Hello, my detector just arrived today, this is the log I got.
[home-assistant.log](https://github.com/custom-components/ble_monitor/files/8314475/home-assistant.log)
