### ISSUE TITLE
[New Sensor]: Aranet4 HOME sensor

### ISSUE THREAD

**Issue by atallo** [custom-components/ble_monitor#789]
### Sensor Description

Aranet4 HOME sensor. (measures CO2 level, temperature, relative humidity and atmospheric pressure)

### Additional information

Aranet4 HOME is an air quality monitor that measures CO2 level, temperature, relative humidity and atmospheric pressure.

Product info: https://aranet.com/product/aranet4-sensor/  
Product datasheet: https://cdn.bfldr.com/FS48XT6B/at/k9b9wjnv8f455crkp7846j/Aranet4_datasheet_WEB.pdf
Python commandline implementation: https://github.com/Anrijs/Aranet4-Python

Thanks!

### BLE advertisements

```shell
TODO: Let me know if it's needed and it doesn't come with the python program attached.
```

**Comment by Ernst79** [comment]
Based on the links you provided, it looks like this device requires a BLE connection to be set up, before it can read the data. This is not supported with BLE monitor. You could give it a try to see if the device also sends data without connection, but most likely is does not. Feel free to reopen this issue if you do find data, but for now, I assume it doesn't. 

See this page on how to get the data. https://custom-components.github.io/ble_monitor/sensor_request

You could use ESPhome BLE client for BLE devices that use a connection.

**Comment by atallo** [comment]
You're right. I just double checked. Use BLE but need registration.

I think it's more like https://github.com/custom-components/sensor.airthings_wave than your component.

Thanks. Sorry.
