### ISSUE TITLE
[Bug]: MiScale v2: no way to get weight measure without measuring the impedance

### ISSUE THREAD

**Issue by impankratov** [custom-components/ble_monitor#791]
### What happened?

Hi, first of all thanks to all the contributors for this great integration.

Due to recent changes in miscale parser here:
https://github.com/custom-components/ble_monitor/commit/4b108603c1862e4d0cddcbee6b248e1775b6070c#diff-7e93f7c05a7b642fc792122d0eee18185f11a786c6f96badc6cc1cc472aab1fbR78-R81
there's no way to get weight measurement in case impedance measurement wasn't completed.

New behaviour seems limiting, because from now on to get my weight measurement I have to wait extra time until impedance measurement is done.

What was the reason for limiting the events?

Maybe it's better to update parser for MiScale2 that way so it will:
1. update weight when `is_stabilized and (weight_removed == 0)`
2. update impedance when `is_stabilized and (weight_removed == 0) and has_impedance`?

**Comment by Ernst79** [comment]
@borpin Can you have a look at this proposal?

**Comment by borpin** [comment]
> New behaviour seems limiting, because from now on to get my weight measurement I have to wait extra time until impedance measurement is done.

- If you wait for the full cycle - all 4 sensors updated with correct `impedance` value in the non_stabilized sensor
- If you wait for just a stabilized weight - no impedance. available Only weight_removed and non_stabilized sensors update. Impedance is unavailable.
- If unstabilized weight - Only weight_removed and non_stabilized sensors update. Impedance is unavailable

> What was the reason for limiting the events?
The weight on it's own is no use when calculating other measures so by updating the weight sensor only, it caused issues calculating the other measurements. The 2 sensors need to be updated together as they are linked data.

**Suggestion**
Introduce an additional sensor for `stabilized_weight` that is updated when a stabilized weight is received.

**Comment by Ernst79** [comment]
@impankratov is that something that works for you? If so, I will add a stabilized weight sensor.

**Comment by impankratov** [comment]
@Ernst79 yes, that would be great 👍

**Comment by Ernst79** [comment]
Added a stabilized weight sensor in 8.2.1. The docs are also updated with a short explanation of the different weight sensors we have now.
