### ISSUE TITLE
[New Sensor]: Magic lantern

### ISSUE THREAD

**Issue by sevagjb** [custom-components/ble_monitor#795]
### Sensor Description

magic lantern

### Additional information

[[e.g. a link to product details, etc.](https://apps.apple.com/us/app/magic-lantern/id1479587050)](https://apps.apple.com/us/app/magic-lantern/id1479587050)
https://play.google.com/store/apps/details?id=wl.smartled.rgb&hl=en&gl=US
this is a ble app to control hexagon panel i like to ask you to add this code to be able controlling the lights in HA 

### BLE advertisements

```shell
i use the app on iOS device
```

**Comment by Ernst79** [comment]
I don't think this can be added, as BLE monitor is not able to connect to specific devices. It can only listen to sensors. I doubt that this device will send data without connection.

**Comment by sevagjb** [comment]
> I don't think this can be added, as BLE monitor is not able to connect to specific devices. It can only listen to sensors. I doubt that this device will send data without connection.

thanks for the conform
