### ISSUE TITLE
[New Sensor]: Inkbird IBS-TH1 is not recognized

### ISSUE THREAD

**Issue by arnonsha** [custom-components/ble_monitor#796]
### What happened?

Trying to add a new Inkbird IBS-TH1 senseor. I got its mac id from the Engbird app. However I cannot see it in the GUI "ADD device" option.

I read it requires "active_scan: True" but I don't see this option anywhere.

I then tried adding the following configuration /config/configuration.yaml

```ble_monitor:
  devices:
    - mac:   '49:22:02:20:01:C0'
      name: 'Boiler'
      active_scan: True
```

I get an error when checking the configuration file:
_Invalid config for [ble_monitor]: [active_scan] is an invalid option for [ble_monitor]. Check: ble_monitor->ble_monitor->devices->0->active_scan. (See /config/configuration.yaml, line 33)._

So, I guess I am doing something wrong.... Any ideas ?

### Sensor type

Inkbird IBS-TH1

**Comment by Ernst79** [comment]
Active scan should be set at a higher level, so in the UI

![image](https://user-images.githubusercontent.com/24375847/160134254-ce3ee134-9342-4d43-9861-0ba41b3a7b98.png)

or in YAML

```yaml
ble_monitor:
  active_scan: True
```

You can only set active scan at global level, as it is a property of the BLE adapter, not of the sensor.

**Comment by arnonsha** [comment]
Thank you for the prompt response. 
I managed to add a xioami sensor through the GUI. But cannot see the Imkbird sensor there.
I also don't see the "active scan" option in GUI. Maybe I am running an old version ?
I installed through HACS. Version is 8.1.1

**Comment by Ernst79** [comment]
can you hit F5 a couple of times. And please make a printscreen of the menu, 

8.1.1 is the latest version.

**Comment by arnonsha** [comment]
Thank you for the screentshot.
Looks like I missed this option. After checking it I can now see my inkbird sensor.

Question:
Since I have 2 sensros, can I configure the active scan individually for each sensor, or is it a global setting ?

**Comment by arnonsha** [comment]
OK, thanks for explaining. Closing the issue as all is OK now.
