### ISSUE TITLE
[New Sensor]: Tilt Hydrometer

### ISSUE THREAD

**Issue by jay-jay-s** [custom-components/ble_monitor#798]
### Sensor description:

Tilt Hydrometer (brewing equipment): A free-floating digital hydrometer and thermometer for continuous real-time monitoring.

https://tilthydrometer.com/

### Information about the device:

Is this enough information to add Tilt to BLE Monitor?

https://kvurd.com/blog/tilt-hydrometer-ibeacon-data-format/
https://www.davidbritch.com/2021/07/get-data-from-tilt-hydrometer-on-arduino.html
https://iotexpert.com/tilt-hydrometer-advertising-scanner-part-3/

**Comment by Ernst79** [comment]
Yes, that is enough information, and it is possible to add this device. Will look into it.

**Comment by Ernst79** [comment]
Please try 8.3.1-beta

**Comment by jay-jay-s** [comment]
> Please try 8.3.1-beta

Yes, it's working! I have a fermentation process going on and the readings match with Tilt's own mobile app: current gravity 1.049 and temperature 26,1 C.

Thank you!

**Comment by Ernst79** [comment]
Added as final in 8.4.0. 

Please delete your device once, as I had to make a change which affects your sensor as well. See the release notes of 8.4.0 for instructions.
