### ISSUE TITLE
[Bug]: Add integration

### ISSUE THREAD

**Issue by mycanaletto** [custom-components/ble_monitor#802]
### What happened?

Hello,

I have a problem on a new HASS OS installation

The component is well installed via HACS but when I try to add it in the integrations it does not appear.

Version
core-2022.3.7
Version la plus récente
core-2022.3.7

**Comment by Ernst79** [comment]
You mean that you dont see it in the menu where you add the integrations? Try to hit F5 a couple of times

**Comment by mycanaletto** [comment]
I installed this HA on another network where there was nothing and it is OK. Maybe the other two installations would interfere. Thanks
