### ISSUE TITLE
[Bug]: Door events are missing from the N100 lock sensors

### ISSUE THREAD

**Issue by chris-chensy** [custom-components/ble_monitor#811]
### What happened?

When I was debugging the N100 lock sensors with #797, I've found the door lock sent out a new packet message with meaningful information. The script does not capture it. 
Please refer to the packet code below. The event 0007 should be a door event, which tells whether or not the door is closed or open etc. according to the documentation.
The code returns the following payload:
{'rssi': -58, 'mac': 'F7AAF9527653', 'type': 'ZNMS16LM', 'packet': 218, 'firmware': 'Xiaomi (MiBeacon V4)', 'data': True}

### Sensor type

Lock

### Relevant log output

```shell
043E2602010001537652F9AAF71A020106161695FE50449E06DA537652F9AAF70700050275324062C6
```

**Comment by Ernst79** [comment]
Thanks. I see. 

`0700050275324062`

`0700` = `0007` = door event
`05` = length
`02` = probably the door event

Strange thing is that the Xiaomi docs don't say anything about the other 4 bytes (`75324062`)

![image](https://user-images.githubusercontent.com/24375847/161417236-518374b5-93a0-44d2-b77c-63e28c097269.png)

**Comment by Ernst79** [comment]
Fix is on its way. In the meantime, can you have a look at #807, can you confirm that the "lock" state is reversed (it shows locked when it is unlocked and vice versa)?

**Comment by Ernst79** [comment]
Please try with 8.5.0-beta. Please note that the lock state has been reversed, see the release notes. Please let me know if this is correct.

**Comment by Ernst79** [comment]
Updated beta is available, it now also adds a door sensor to the ZNMS17LM. 

Can you let me know if the "lock" state now works ok for you with this beta?

**Comment by Ernst79** [comment]
8.5.2 has been released, with a door sensor
