### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Capellan1975** [custom-components/ble_monitor#814]
### What happened?

При загрузке интеграции появляется сообщение: "Не удалось загрузить мастер настройки: undefined
![Безымянный](https://user-images.githubusercontent.com/43037064/161917115-9bee9084-8511-490c-86ef-3f9c9b36aeff.jpg)
"

**Comment by Ernst79** [comment]
Please use the English language if you need support. Only @Magalex2x14 is able to understand Russian.

**Comment by Magalex2x14** [comment]
The problem was solved after clearing the browser cache (I saw the corresponding talks in the Russian-language telegram channel today morning).
