### ISSUE TITLE
[Bug]: Activating BLE monitor with Flic Addon don't work

### ISSUE THREAD

**Issue by Philou06** [custom-components/ble_monitor#815]
### What happened?

I have several [Flic buttons](https://flic.io/) that also works with bluetooth using Flic Addon in HA but after installing ble_monitor, Flic is no more works... I also have to disable Flic Addon to make BLE monitor devices works so I guess there is a conflict in using simultaneously two component with the RPI integrated bluetooth, can that be solved by BLE monitor or do  I have to add another bluetooth device for BLE monitor?

### Relevant log output

```shell
flicd log:
Available HCI devices found:
hci0
Trying hci0
hci0 is busy, shutting down and retrying...

BLE_monitor:
Logger: root
Source: custom_components/ble_monitor/__init__.py:736
Integration: Passive BLE monitor (documentation, issues)
First occurred: 16:08:11 (9 occurrences)
Last logged: 16:24:14

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 736, in run
    self._event_loop.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1806, in send_scan_request
    if self._use_ext_scan():
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1791, in _use_ext_scan
    return (self._supported_commands[37] & 0x60) == 0x60
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Philou06** [comment]
Thx for your reply, I already tried this with an additional USB Bluetooth key, so now BLE monitor is on hci0 (native rpi bt) and Flic is on the new added usb key on hci1 and the result is that Flic is working fine but not BEL monitor, it seems that hci0 is disabled due the added bt key, is that something possible?

**Comment by Ernst79** [comment]
Try a full system reboot first, 
Enable debug logging for BLE monitor to give us some more insight in what is going wrong. The FAQ explains how to enable debug logging https://custom-components.github.io/ble_monitor/faq#debug

**Comment by Philou06** [comment]
I tried a full system reboot too, not better...

I added this to configuration.yaml:
```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: debug
```

Here the log about Hci0 since I added my Bluetooth key (currently on Hci1 and work for Flicd):
<img width="394" alt="image" src="https://user-images.githubusercontent.com/81933852/162205977-23f8953e-840e-4ea1-9ede-6df30af34729.png">
```
Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:351
Integration: Passive BLE monitor ([documentation](https://github.com/custom-components/ble_monitor), [issues](https://github.com/custom-components/ble_monitor/issues))
First occurred: 14:30:09 (1 occurrences)
Last logged: 14:30:09
Bluetooth interface hci0 is not available
```
and for the second one:
```
Logger: custom_components.ble_monitor.bt_helpers
Source: custom_components/ble_monitor/bt_helpers.py:54
Integration: Passive BLE monitor ([documentation](https://github.com/custom-components/ble_monitor), [issues](https://github.com/custom-components/ble_monitor/issues))
First occurred: 14:30:03 (1 occurrences)
Last logged: 14:30:03

hci0 (00:15:E9:7B:5F:83) have no BT LE capabilities and will be ignored
```

My BLE configuration:
```
# BLE monitor
ble_monitor:
  hci_interface: 0
  bt_auto_restart: True
  active_scan: False
  discovery: False
  period: 60
  use_median: False
  decimals: 1
  log_spikes: False
  restore_state: True
  report_unknown: False
  devices:
    # sensor
...
```

**Comment by Philou06** [comment]
Ok but there is a lot of lines so I put them in a file:
[logsBLE_monitor.txt](https://github.com/custom-components/ble_monitor/files/8444392/logsBLE_monitor.txt)

Current configuration:
# BLE monitor
ble_monitor:
  hci_interface: 
    - 1
    - 0

**Comment by Magalex2x14** [comment]
@Philou06 please also tell us with which ble_monitor version this log was captured.

**Comment by Philou06** [comment]
<img width="204" alt="image" src="https://user-images.githubusercontent.com/81933852/162267320-940259eb-9bc7-4b8b-ae3b-ba5726ffae0d.png">

**Comment by Philou06** [comment]
The added key is an old one but I used it for Flicd on Hci1 and it worked fine but with this new key Hci0 is disabled.

I will later buy a new BT USB key and retry too see if I can use the 2 components together...

**Comment by Magalex2x14** [comment]
The Flic SDK for Linux repository states that it only works with BT4.0 adapters.
It also [states the need for exclusive access](https://github.com/50ButtonsEach/fliclib-linux-hci#high-level-description) to the bt-adapter.
Weird situation, yes... I still don't understand what exactly is going on in your system.. We need a deeper diagnosis. Unfortunately, Home Assistant OS is very limited in this regard...

**Comment by Philou06** [comment]
Don't know the version of my adapter but it works fine with Flicd.
Now I have desactivated BLE monitor until I buy a new adapter.
I also have to investigate why it disable the Rpi BT on Hci0 when adding a BT USB key because it could works if each one use a different BT adapter.

Here what Flicd addon says on start:
```
Available HCI devices found:
hci0
Trying hci0
hci0 is busy, shutting down and retrying...
Successfully bound HCI socket
Flic server is now up and running!
Initialization of Bluetooth controller done!
Accepted new client
```
That perhaps says that he need exclusive access.

**Comment by Ernst79** [comment]
I assume this issue has been solved with the new adapter. Closing the issue therefore. If not, let me know by reopening the issue.

**Comment by Philou06** [comment]
Sorry for late answer, I was out for a long time... 
I bought a new Bluetooth adapter but meanwhile, after some HA OS & Core updates, Flicd works no more, even alone on a fresh new installation, so I decided to use them only directly on my phone and now I can use BLE monitor on HA for my temperature sensors and they are working well, thanks for your help!
