### ISSUE TITLE
[Bug]: undefined

### ISSUE THREAD

**Issue by michaelmain24** [custom-components/ble_monitor#819]
### What happened?

https://imgur.com/a/htE1wNP

I downloaded ble_monitor in hacs today
undefined always appears when trying to integrate
Also tried clearing browser cache
but still appear undefined
how to handle please help me

**Comment by Ernst79** [comment]
Is there anything in the logs?

**Comment by michaelmain24** [comment]
> Is there anything in the logs?

https://imgur.com/a/rea6n1L

**Comment by Ernst79** [comment]
Seems to be the same issue as in #814

Try to
- clear browser cache
- hit F5 a couple of times
- try in incognito mode or with another browser

**Comment by michaelmain24** [comment]
> Seems to be the same issue as in #814
> 
> Try to
> 
> * clear browser cache
> * hit F5 a couple of times
> * try in incognito mode or with another browser

I finally found out that my network environment was not set up properly
thanks for your help

**Comment by alexhermida** [comment]
Hi @Ernst79 ! I'm facing the same issue. Don't want to open a new issue if it's not necessary. I've tried different browsers in my computer, incognito mode and also from the mobile. The only progress I made was getting stuck in the modal instead the undefined. Error. Are there any other logs I can check apart from the main ones in `Configuration - Logs`?

Thank you for the integration.

**Comment by Ernst79** [comment]
You could try to enable debug logging at debug level. Did you restart HA?
