### ISSUE TITLE
[Bug]: Govee H5075 - Temperature readings seem to have switched to Celsius by themselves

### ISSUE THREAD

**Issue by nahuelarg86** [custom-components/ble_monitor#820]
### What happened?

Added a Govee H5075 sensor to HA with mostly default settings. The sensor was discovered without any issues, and I started to track it. It was working fine, set up in Fahrenheit for temperature. However, all of a sudden, the temp graph dropped, and the readings started to show super low. For instance, the temp in my house is about 70 f, and when the drop happened, it started showing about 20 f.
The temperature in the device's screen shows Fahrenheit, and as I was following the trend on HA graph, I came to the realization that the temp HA is showing is in Celsius, although it is configured in Fahrenheit. I converted a couple of values, and sure enough, it was the same. If I switch it to Celsi
us in the device's configuration, then it drops even lower.
I haven't removed and re-paired the device yet, but I wanted to see if anyone has any input.
Thanks!

![Screenshot 2022-04-08 192006](https://user-images.githubusercontent.com/103232241/162548871-af829fbe-9143-4ddb-9211-29d5f642131c.jpg)

### Sensor type

Govee H5075

**Comment by Ernst79** [comment]
The **BLE monitor device setting** should be in Celsius. This setting is to tell HA in which unit Govee sends its data (over BLE). Govee always sends its data in Celsius, as far as I know. 

HA will take care of the conversion to Fahrenheit, depending on your regional settings.

I have seen that there is a change in HA 2022.4, where you can also set the temperature unit for an individual sensor differently. https://www.home-assistant.io/blog/2022/04/06/release-20224/#adjusting-unit-of-measurement-for-sensors

This makes it that you will have to check three places.
- ble monitor setting, devices —> Celsius
- HA general settings —> Fahrenheit
- Enitity properties —> Fahrenheit

**Comment by nahuelarg86** [comment]
Hey, thanks for the insight. I tried the first option, switching ble monitor to Celsius, and it did fix it. The strange thing for me is that the first time I added the ble device I selected Fahrenheit and it was working fine, but then I had the problem without me touching any setting. Could have been HA update that messed the settings up?

**Comment by Ernst79** [comment]
There have been some changes regarding temperature conversion. Good to hear your issue is solved.
