### ISSUE TITLE
Latest update broke my inkbird pool temp sensor

### ISSUE THREAD

**Issue by randrcomputers** [custom-components/ble_monitor#832]
### What happened?

Installed newest version and now pool temp displays unknown. seems IBS-TH2/P01b is no longer working at all if you need logs let me know

### Sensor type

IBS-TH2/P01b

**Comment by Ernst79** [comment]
Can you make some logs with report unknown for this device?

**Comment by randrcomputers** [comment]
I will monitor and report back

**Comment by Ernst79** [comment]
There were some name changes, lately for these sensors, perhaps these have messed up things. a bit. Just reopen the issue in case you still encounter problems
