### ISSUE TITLE
[New Sensor]: Allwins IBeacon

### ISSUE THREAD

**Issue by barkdadof4** [custom-components/ble_monitor#834]
### Sensor Description

Allwins

### Additional information

Thin Noric nrf52832 ble 5.0 beacon accelerometer temperature humidity ibeacon

Mac address for Allwins iBeacon d0d5e036ce2

[dump.txt](https://github.com/custom-components/ble_monitor/files/8514385/dump.txt)
9

### BLE advertisements

```shell
04 3E 2A 02 01 00 01 29 CE 36 E0 D5 D0 1E 02 01 06 1A FF 4C 
  00 02 15 FD A5 06 93 A4 E2 4F B1 AF CF C6 EB 07 64 78 25 00 
  01 00 02 D8 CC
```

**Comment by Ernst79** [comment]
This sensor indeed uses iBeacon format, but I don't think they get the data from this iBeacon message.

However, there are also other messages with manufacturer specific data, which look more promising

```
> 04 3E 2B 02 01 04 01 29 CE 36 E0 D5 D0 1F 08 09 61 6C 6C 77 
  69 6E 73 13 16 18 03 18 5F 29 09 00 00 00 00 00 00 00 00 00 
  00 00 00 00 00 CC 
```

`0809616c6c77696e73` = name of the sensor (allwins)
`13161803185f2909000000000000000000000000` = data

`13` = length
`16` = manufacturer specific data
`1803` = UUID
`185f2909000000000000000000000000` = the data.

So, lets assume each byte is a number
`18` = 24 (temperature?)
`5f` = 95 (battery?)
`29`= 41 (humidity?)
`09` = 9 (acceleration?)

Can you get some more data, for which you also write down the actual measurements (e.g. from the app), to figure out what is what. There are also a lot of zero's, these could also have a meaning if they ever change.

**Comment by barkdadof4** [comment]
New dump file Temp is 21.25 Humidity is 33.25
[dump.txt](https://github.com/custom-components/ble_monitor/files/8522715/dump.txt)

**Comment by barkdadof4** [comment]
When using Wireshark I have notice the each device sends two advertisements one with the device name and one without the device name. I think the one without the name is where the data is.

**Comment by Ernst79** [comment]
The ones without name are iBeacon format. This is just a long UUID with a "major and minor value + power. 

Besides the earlier mentioned `13161803....` advertisements, I also see advertisements with `11160318.....`, e.g. 
`11160318D0D5E036CE29000100020603E864`

`11` = length
`16` = manufacturer specific data
`0318` = UUID
D0D5E036CE29000100020603E864 = the data.

Again , I can't find a quick relation between the bytes and 21.25 or 33.25. I will look into it better later

So, lets assume each byte is a number
18 = 24 (temperature?)
5f = 95 (battery?)
29= 41 (humidity?)
09 = 9 (acceleration?)

**Comment by barkdadof4** [comment]
For the Allwins device here is the service data changing when I move it between a cool location and a warm location.

22 16b Service Data 18032315283b000000000000000000000000
22 16b Service Data 18032315283b000000000000000000000000
22 16b Service Data 18032315283b000000000000000000000000
22 16b Service Data 18032315283b000000000000000000000000
22 16b Service Data 18032315283b000000000000000000000000
22 16b Service Data 1803241a283b000000000000000000000000
22 16b Service Data 1803241a283b000000000000000000000000
22 16b Service Data 1803241a283b000000000000000000000000
22 16b Service Data 1803241a283b000000000000000000000000
22 16b Service Data 1803241a283b000000000000000000000000
22 16b Service Data 1803241a283b000000000000000000000000
22 16b Service Data 18032512281c000000000000000000000000
22 16b Service Data 18032512281c000000000000000000000000
22 16b Service Data 18032512281c000000000000000000000000
22 16b Service Data 1803251a2745000000000000000000000000
22 16b Service Data 1803251a2745000000000000000000000000
22 16b Service Data 1803251a2745000000000000000000000000
22 16b Service Data 1803251a2745000000000000000000000000
22 16b Service Data 180325062700000000000000000000000000
22 16b Service Data 180325062700000000000000000000000000

Thanks for the help.

**Comment by barkdadof4** [comment]
I will work on a longer log on Monday Thanks.

**Comment by barkdadof4** [comment]
Here is a 2 minute dump.  Moved the device from 24.15 C to 28.125 at 30 second intervals.
 
[dump.txt](https://github.com/custom-components/ble_monitor/files/8557922/dump.txt)


Thanks

**Comment by barkdadof4** [comment]
Maybe something in here
[DeviceDownload.zip](https://github.com/custom-components/ble_monitor/files/8558587/DeviceDownload.zip)

**Comment by barkdadof4** [comment]
Just bumping wondering if there is any hope for this sensor?

Thanks

**Comment by Ernst79** [comment]
Sorry, took a while, busy with the house. 

Let's look at the data, after removing the irrelevant data. . 

```
13 16 18 03 18 42 2C 0F
13 16 18 03 18 3B 2C 0A
13 16 18 03 18 3B 2C 0A
13 16 18 03 18 39 2C 06
13 16 18 03 18 46 2C 06
13 16 18 03 19 15 2C 25
13 16 18 03 19 47 2C 35 
13 16 18 03 19 4E 2C 13
```

`13` = length of the data (including the trailing `00`'s
`16` = 16 bits UUID
`18 03` = UUID 
The remaining part could be the data. Looks like it are two values, each of 2 bytes

**1st two bytes**
bytes to from `18 42` up to `19 4E`
`18 42` in hex is 6210 in decimals
`19 4E` in hex is 6478 in decimals

**2nd two bytes**
bytes vary between `2C 06` up to `2C 35 `
`2C 06` in hex is 11270 in decimals
`2C 35 ` in hex is 11317 in decimals

I don't see a clear relation between these numbers and e.g. temperature (24.15 C to 28.125). I tried Fahrenheit as well.

**Comment by barkdadof4** [comment]
Ok thenks
