### ISSUE TITLE
[New Sensor]: Thermo Beacon

### ISSUE THREAD

**Issue by barkdadof4** [custom-components/ble_monitor#836]
### Sensor Description

Thermo Beacon

### Additional information

I think I have this one by using the TermoBeacon.py app from [rnlgreen](https://github.com/rnlgreen)
Mac address 912000002af4

[dump.txt](https://github.com/custom-components/ble_monitor/files/8514498/dump.txt)

### BLE advertisements

```shell
04 3E 29 02 01 00 00 F4 2A 00 00 20 91 1D 02 01 06 03 02 F0 
  FF 15 FF 10 00 00 00 F4 2A 00 00 20 91 93 0B 8D 01 13 02 A1 
  AA 6F 00 CA
```

**Comment by Ernst79** [comment]
Isn't this one not already working. My debugging parser is parsing this one as 

```
result  ({'voltage': 2.963, 'temperature': 24.8125, 'humidity': 33.1875, 'battery': 96.30000000000001, 'rssi': -54, 'mac': '912000002AF4', 'type': 'Lanyard/mini hygrometer', 'packet': 'no packet id', 'firmware': 'Thermoplus', 'data': True}, None)
```

**Comment by barkdadof4** [comment]
Yes ran python3 -m aioblescan -T today and work great.  With all my code I am use Bluez and it seem that I am not truly getting the raw packet data.

Here is my code:
#!/usr/bin/python
from __future__ import print_function

from time import gmtime, strftime, sleep
from bluepy.btle import Scanner, DefaultDelegate, BTLEException
import sys
import binascii

#Enter the MAC address of the sensors
Sensors = {"91:20:00:00:2a:f4": "TB1"}
#Sensors = {"d0:d5:e0:36:ce:29": "Allwins"}
#Sensors = {"dd:34:02:06:d0:6c": "kpro"}

class DecodeErrorException(Exception):
     def __init__(self, value):
         self.value = value
     def __str__(self):
         return repr(self.value)
         
class ScanDelegate(DefaultDelegate):
    def __init__(self):
        DefaultDelegate.__init__(self)

    def handleDiscovery(self, dev, isNewDev, isNewData):
        if isNewDev:
            #print ("Discovered device", dev.addr)
            pass
        elif isNewData:
            #print ("Received new data from", dev.addr)
            pass

retry_count = 100
scanner = Scanner().withDelegate(ScanDelegate())

try:
    while (retry_count > 0 ):
        print ("Scanning...")
        devices = scanner.scan(2.0)

        retry_count -= 1

        for dev in devices:
            if dev.addr in Sensors:
                for (adtype, desc, value) in dev.getScanData():
#                    if ("7777" in value):
                        print ("Device", binascii.hexlify(dev.rawData).decode())
                        print(adtype, desc, value)
                        print("\n")
except DecodeErrorException:
    print("Decode Exception")
    pass

This is my results
Device 0201060303aafe1216aafe21010f0e071b181f1bff82ffd103b8091680206d01000000000d094b4250726f5f323134383130
1 Flags 06
Device 0201060303aafe1216aafe21010f0e071b181f1bff82ffd103b8091680206d01000000000d094b4250726f5f323134383130
3 Complete 16b Services 0000feaa-0000-1000-8000-00805f9b34fb
Device 0201060303aafe1216aafe21010f0e071b181f1bff82ffd103b8091680206d01000000000d094b4250726f5f323134383130
22 16b Service Data 80206d0100000000
Device 0201060303aafe1216aafe21010f0e071b181f1bff82ffd103b8091680206d01000000000d094b4250726f5f323134383130
9 Complete Local Name KBPro_214810

Trying to go a little deeper in understanding.  I don't understand why I don't see packet information like what is in the HCI dump or the Wireshak captures I do on my windows machine.  Is Bluez masking?  AM I completely missing something?  If so what?

Running the aioblescan I see the payload information is different then what I get when using Bluez.

Again Thanks for your help
Bryon

**Comment by barkdadof4** [comment]
Reading through and trying to understand aioblescan.  Will work to try and understand so I can use this.

**Comment by Ernst79** [comment]
In BLE monitor, we use the raw data collected with aioblescan, and use the parser to translate it to readable data. Perhaps BLE monitor gives some hints. Look in this file

https://github.com/custom-components/ble_monitor/blob/master/custom_components/ble_monitor/__init__.py

**Comment by Ernst79** [comment]
I see that with Bluez, you only get the Payload, not the header. The header is a fixed part of the BLE message and contains (amongst others) the MAC address

https://www.novelbits.io/deep-dive-ble-packets-events/

**Comment by barkdadof4** [comment]
No changes needed thanks for the help
