### ISSUE TITLE
[New Sensor]: Can you please add support for Govee H5054 

### ISSUE THREAD

**Issue by dinan5** [custom-components/ble_monitor#837]
### Sensor Description

Govee H5054  - Water Detector

### Additional information

e.g. a link to product details, etc.

**Comment by Ernst79** [comment]
If you can give me some BLE messages along with the measured data, I probably can add this sensor. Instructions how to get BLE data from the H5054 can be found here. 

https://custom-components.github.io/ble_monitor/sensor_request

**Comment by Ernst79** [comment]
did you had a change to collect some data?

**Comment by dinan5** [comment]
Hi, I was going to update the case tonight. I wound up buying a different sensor, thank you for your diligence.

On May 2, 2022, at 16:55, Ernst Klamer ***@***.***> wrote:

﻿

did you had a change to collect some data?
