### ISSUE TITLE
[New Sensor]: Yinmik BLE-9908

### ISSUE THREAD

**Issue by kitcho1** [custom-components/ble_monitor#838]
### Sensor Description

Yinmik BLE-9908 pH/PPM/EC/Temp Water Quality Tester

### Additional information

https://www.aliexpress.com/item/1005003784454381.html

The manufacturer supplies an android/ios app that is supposed to read BLE values from this device (I have not used this app): http://www.zghuiquan.com/app/yinmik.apk

### BLE advertisements

```shell
Device Name: BLE-9908
Device Address: C0:00:00:00:1A:BA

Services:--------------------------
GAP (00001800-0000-1000-8000-00805f9b34fb)
	Device Name (00002a00-0000-1000-8000-00805f9b34fb)
	Appearance (00002a01-0000-1000-8000-00805f9b34fb)
	Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)
	Service Changed (00002a05-0000-1000-8000-00805f9b34fb)


Device Information (0000180a-0000-1000-8000-00805f9b34fb)
	System ID (00002a23-0000-1000-8000-00805f9b34fb)
	Model Number String (00002a24-0000-1000-8000-00805f9b34fb)
	Serial Number String (00002a25-0000-1000-8000-00805f9b34fb)
	Firmware Revision String (00002a26-0000-1000-8000-00805f9b34fb)
	Hardware Revision String (00002a27-0000-1000-8000-00805f9b34fb)
	Software Revision String (00002a28-0000-1000-8000-00805f9b34fb)
	Manufacturer Name String (00002a29-0000-1000-8000-00805f9b34fb)
	IEEE 11073-20601 Regulatory (00002a2a-0000-1000-8000-00805f9b34fb)
	PNPID (00002a50-0000-1000-8000-00805f9b34fb)


Unknown service (0000180f-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (00002a19-0000-1000-8000-00805f9b34fb)


Unknown service (0000ff01-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000ff02-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000ff10-0000-1000-8000-00805f9b34fb)
```

HCIDump

HCI sniffer - Bluetooth packet analyzer ver 5.50
device: hci0 snap_len: 1500 filter: 0x2
< 01 02 10 00 
> 04 0E 44 01 02 10 00 FF FF FF 03 CC FF EF FF FF FF EC 1F F2 
  0F E8 FE 3F F7 8F FF 1C 00 04 00 61 F7 FF FF 7F F8 FF FF FF 
  FF 07 08 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 
< 01 02 10 00 
> 04 0E 44 01 02 10 00 FF FF FF 03 CC FF EF FF FF FF EC 1F F2 
  0F E8 FE 3F F7 8F FF 1C 00 04 00 61 F7 FF FF 7F F8 FF FF FF 
  FF 07 08 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 
< 01 02 10 00 
> 04 0E 44 01 02 10 00 FF FF FF 03 CC FF EF FF FF FF EC 1F F2 
  0F E8 FE 3F F7 8F FF 1C 00 04 00 61 F7 FF FF 7F F8 FF FF FF 
  FF 07 08 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00

**Comment by Ernst79** [comment]
Your BLE advertisements seem to be somewhat misformed. I miss the header, but also the RSSI byte (last byte). Can you make another hcidump, by following these instructions. 

https://custom-components.github.io/ble_monitor/sensor_request#getting-ble-advertisements-with-a-hcidump

**Comment by kitcho1** [comment]
Here's the output

[dump.txt](https://github.com/custom-components/ble_monitor/files/8534149/dump.txt)

**Comment by Ernst79** [comment]
This BLE data is containing three parts 

020106 = flags 
03020D18 = UUID (0D18)
0A09424C452D3939303800 = Name: BLE-9908 

this means that the sensor is only broadcasting its name, and that a connection is required to get the data. This is not supported by BLE monitor. You can try ESPhome BLE client to make a connection and read the characteristics.
