### ISSUE TITLE
Request to add Govee 5185 dual probe meat thermometer

### ISSUE THREAD

**Issue by dawdydawdy** [custom-components/ble_monitor#839]
Advertisements and guesses at positions of data, though formatting is not working
Name="Govee_H5185_490A" Probe1 Temp="09-60" Probe2 Temp="0B-54"
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-09-60-FF-FF-FF-FF-0B-54-FF-FF-FF-FF
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-FC-FF-FF-FF-FF-0B-54-FF-FF-FF-FF
probe1=~75degree F=09-60	probe2=~ 84F=0A-F0
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-09-60-FF-FF-FF-FF-0A-F0-FF-FF-FF-FF
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-09-60-FF-FF-FF-FF-0A-8C-FF-FF-FF-FF
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-FC-FF-FF-FF-FF-0A-8C-FF-FF-FF-FF
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-FC-FF-FF-FF-FF-0A-28-FF-FF-FF-FF
probe1~73f=08-FC		   probe2~79f=0A-8C
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-FC-FF-FF-FF-FF-0A-8C-FF-FF-FF-FF
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-98-FF-FF-FF-FF-0A-28-FF-FF-FF-FF

01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-FC-FF-FF-FF-FF-09-c4-FF-FF-FF-FF
Changed probe1 set temp to 200f	
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-FC-24-74-FF-FF-09-60-FF-FF-FF-FF
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-FC-24-74-FF-FF-09-60-FF-FF-FF-FF
probe1=~72f=08-98 probe1 set temp=200f=24-74	          probe2=09-50
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-98-24-74-FF-FF-09-60-FF-FF-FF-FF
Change probe2 set temp = 160 degree f
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-69-08-FC-24-74-FF-FF-09-60-1B-BC-FF-FF
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-69-08-FC-24-74-FF-FF-09-60-1B-BC-FF-FF
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-69-08-98-24-74-FF-FF-09-60-1B-BC-FF-FF
clear set temps for both probes probe1 ~72 F             Probe2 =~75 F
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-FF-08-FC-FF-FF-FF-FF-0A-28-FF-FF-FF-FF
probe 1 =                                                                       ~72 &         probe2=~79
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-FF-08-98-FF-FF-FF-FF-0A-8C-FF-FF-FF-FF
                                                                   probe 1 =   ~72 &          probe2=~81
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-FF-08-98-FF-FF-FF-FF-0A-28-FF-FF-FF-FF
                                                                     probe 1 = ~72 &         probe2=~79
01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-FF-08-98-FF-FF-FF-FF-0A-8C-FF-FF-FF-FF

**Comment by Ernst79** [comment]
Can you post a full BLE advertisement?

**Comment by Ernst79** [comment]
It will work better, if you use Celsius :-)

Example

`01-06-03-51-85-FF-32-49-0A-01-00-01-01-E4-C1-66-08-FC-FF-FF-FF-FF-0A-28-FF-FF-FF-FF`

probe1: 73F = 23°C `08-FC` = 2300 --> 2300/100 = 23
probe2: 79F = 26°C `0A-8C` = 2600 --> 2600/100 = 26

**Comment by Ernst79** [comment]
When you can send me the full BLE advertisement, I can add it for you.

**Comment by dawdydawdy** [comment]
Not sure how to capture full advertisement.

**Comment by Ernst79** [comment]
That is explained here

https://custom-components.github.io/ble_monitor/sensor_request

**Comment by dawdydawdy** [comment]
Sorry for the delay, i wasn't getting any logging until I used "Other"

Probe 1 ~ 75F  Probe 2 ~79F No Set Temp on either probe set
2022-04-21 17:30:59 INFO (Thread-3)
[custom_components.ble_monitor.ble_parser] Unknown advertisement received:
043e2b020100010a49323633d81f0201060303518517ff32490a01000101e4c1ff0960ffffffff0a28ffffffffc5
2022-04-21 17:31:00 INFO (Thread-3)
[custom_components.ble_monitor.ble_parser] Unknown advertisement received:
043e2b020100010a49323633d81f0201060303518517ff32490a01000101e4c1ff0960ffffffff0a28ffffffffd1
2022-04-21 17:31:01 INFO (Thread-3)
[custom_components.ble_monitor.ble_parser] Unknown advertisement received:
043e2b020100010a49323633d81f0201060303518517ff32490a01000101e4c1ff0960ffffffff0a28ffffffffcc
2022-04-21 17:31:02 INFO (Thread-3)
[custom_components.ble_monitor.ble_parser] Unknown advertisement received:
043e2b020100010a49323633d81f0201060303518517ff32490a01000101e4c1ff0960ffffffff0a28ffffffffd1

Probe 1 Set Temp = 160F  Probe1 ~75F  Probe 2 Set Temp = 200F  Probe2 ~79F
2022-04-21 17:55:52 INFO (Thread-3)
[custom_components.ble_monitor.ble_parser] Unknown advertisement received:
043e2b020100010a49323633d81f0201060303518517ff32490a01000101e4c19609c41bbcffff0a282474ffffca
2022-04-21 17:55:53 INFO (Thread-3)
[custom_components.ble_monitor.ble_parser] Unknown advertisement received:
043e2b020100010a49323633d81f0201060303518517ff32490a01000101e4c19609c41bbcffff0a282474ffffd1
2022-04-21 17:55:54 INFO (Thread-3)
[custom_components.ble_monitor.ble_parser] Unknown advertisement received:
043e2b020100010a49323633d81f0201060303518517ff32490a01000101e4c19609c41bbcffff0a282474ffffcd
2022-04-21 17:55:55 INFO (Thread-3)
[custom_components.ble_monitor.ble_parser] Unknown advertisement received:
043e2b020100010a49323633d81f0201060303518517ff32490a01000101e4c19609c41bbcffff0a282474ffffd1

**Comment by Ernst79** [comment]
Thanks, I look into it soon

**Comment by Ernst79** [comment]
PR is in #848, will be released soon

**Comment by Ernst79** [comment]
Added in 8.6.3

**Comment by dawdydawdy** [comment]
Awesome, works great, thanks!

**Comment by Ernst79** [comment]
I forgot to add the set "alarm" temperatures, will add them in the next release, together with H5182

**Comment by Ernst79** [comment]
alarm sensors are added in 8.6.4
