### ISSUE TITLE
REQ: Support Xiaomi Roidmi Handeld Vacuum

### ISSUE THREAD

**Issue by paoloantinori** [custom-components/ble_monitor#84]
Some models of Xiaomi Roidmi handheld vacuums support BLE.
You can pair them with your phone where you can read some data from and modify other aspects.
The most useful feature would be the status of the battery.

They do not use Xiaomi Home but this other app.
https://play.google.com/store/apps/details?id=com.roidmi.smartlife&hl=en

I was trying to find more a way to read data by myself from this, but I'm struggling.

So I tried turning on the `mitemp_bt` platform. This is what it's in the logs:

<details>
  <summary><b>Click to expand</b></summary>
<pre><code>
2020-06-16 16:35:51 INFO (SyncWorker_5) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -57, MAC: 7811DCA6599A, ADV: 043e25020100009a59a6dc1178190201060502f5fed0ff0f1695fe312048021c9a59a6dc117809c7
2020-06-16 16:35:51 INFO (SyncWorker_5) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -55, MAC: 7811DCA6599A, ADV: 043e25020100009a59a6dc1178190201060502f5fed0ff0f1695fe312048021c9a59a6dc117809c9
2020-06-16 16:35:51 INFO (SyncWorker_5) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -56, MAC: 7811DCA6599A, ADV: 043e25020100009a59a6dc1178190201060502f5fed0ff0f1695fe312048021c9a59a6dc117809c8
</code></pre>
</details>

Here you can find a couple of screenshots from `bettercap`:

![Screenshot from 2020-06-16 17-25-44](https://user-images.githubusercontent.com/1520602/84794424-836d1080-aff6-11ea-8a70-159fc6e41f03.png)
![Screenshot from 2020-06-16 17-25-56](https://user-images.githubusercontent.com/1520602/84794433-87009780-aff6-11ea-886d-f2d3abffd6b8.png)

I couldn't guess if the information already visible there is already what is needed

I'm available for some testings and probing if you guys see that we can get something out of this.

**Comment by Magalex2x14** [comment]
Hello. Sorry for the long silence.
I will look at the data you received. Everything will depend on whether these messages contain any useful data.
I will let you know.

**Comment by Magalex2x14** [comment]
Sorry guys, there is no useful information in your BLE advertisements...
```
Xiaomi service data        Frame CTRL        DeviceID     MsgCNTR                MAC             Capability             RSSI
         1695fe               3120             4802          08             cccdd6dc1178           09                     b3
```
Бит присутствия данных всегда установлен в 0 (второй бит первого байта Frame CTRL).

**Comment by impankratov** [comment]
No problem, thanks anyway for the attempt!

**Comment by Magalex2x14** [comment]
I close it for now.
