### ISSUE TITLE
Missing documentation for Oral-B toothbrushes

### ISSUE THREAD

**Issue by AgenttiX** [custom-components/ble_monitor#844]
According to the [readme](https://github.com/custom-components/ble_monitor/blob/master/README.md), Oral-B toothbrushes are supported, but they are not mentioned in the [list of supported devices](https://custom-components.github.io/ble_monitor/by_brand) in the documentation. Which models are supported at the moment, and how does the data they send differ by model? Is there a difference in the data sent by e.g. the Genius X series and the iO series? I'm looking to collect as much data as possible to Home Assistant and deciding which model to get.

It seems that at least the [Oral-B SmartSeries 7000 is supported](https://github.com/custom-components/ble_monitor/issues/740) and there is a [pull request](https://github.com/custom-components/ble_monitor/pull/842) for supporting the Oral-B iO Series 7. [This](https://github.com/custom-components/ble_monitor/blob/master/custom_components/ble_monitor/ble_parser/oral_b.py) seems to be the file responsible for parsing the data.

Unfortunately the official [Oral-B API documentation](https://developer.oralb.com/) seems to be down at the moment.

**Comment by codyc1515** [comment]
Hi.

It does seem the documentation is missing. I am not quite sure why.

For now only two models are technically supported - SmartSeries 7000 and iO Series 7. You will likely still be able to see on / off state but some of the attributes may be mapped wrongly if you have a different model to the two above.

From checking the web archive it seems that the Oral-B Developer website was shut down in 2018. I was not aware of the site till now.

Thank you

**Comment by Ernst79** [comment]
Will update the docs in a couple of days

**Comment by Ernst79** [comment]
Docs are fixed. The markdown language that is used for the docs is quite sensitive for number of spaces. It was missing two spaces on several lines, which caused the docs not to show up.

**Comment by nepozs** [comment]
@AgenttiX @codyc1515 
Oral-B Developer Program is closed (probably forever)
https://web.archive.org/web/20180309064608/https://developer.oralb.com/
but I've found some documentation from 2016 (maybe could be usefull?):
https://web.archive.org/web/20160415220442/https://developer.oralb.com/documentation
