### ISSUE TITLE
Sinocare CF516 BodyFat Scale1 [New Sensor]: 

### ISSUE THREAD

**Issue by pedro8082** [custom-components/ble_monitor#845]
### Sensor Description

BodyFat Scale 1

### Additional information

Sinocare CF516  Intelligent Body Fat Scale (maybe identical to DIGOO DG-CF516) . Mac address CF:E5:07:01:25:0C .  Below some details extracted using a BLE app via mobile.
Thanks for the support
![IMG-3531](https://user-images.githubusercontent.com/61947604/165182437-82afd914-7a5b-41ac-8cf3-19f36032cf0e.PNG)
![IMG-3532](https://user-images.githubusercontent.com/61947604/165182439-3c4757e4-36d9-4fa0-b203-b2aebb881f7b.PNG)
![IMG-3533](https://user-images.githubusercontent.com/61947604/165182441-8755577a-4df2-42db-8f95-ba3ebcd7bfa3.PNG)
![IMG-3534](https://user-images.githubusercontent.com/61947604/165182442-1d0ed468-d43c-4ae7-ad0a-62754537ade0.PNG)
![IMG-3535](https://user-images.githubusercontent.com/61947604/165182445-9daa477a-7197-42d3-bf89-a21f073a4af5.PNG)
![IMG-3528](https://user-images.githubusercontent.com/61947604/165182446-32902d1b-9edc-40b6-b90d-b02d21fe23e2.PNG)
![IMG-3529](https://user-images.githubusercontent.com/61947604/165182449-82e02c1b-63da-4ac0-aba8-73c560a20591.PNG)
![IMG-3530](https://user-images.githubusercontent.com/61947604/165182451-9a724088-9503-4afa-b9dc-b6c8f0a9ea91.PNG)
.

### BLE advertisements

```shell
2022-04-25 23:48:41 INFO (Thread-4) [custom_components.ble_monitor.ble_parser] Unknown advertisement received: 043e2a020100000c250107e5cf1e0201060502f0ff121814ff64ffcfe50701250ccf000068010000000001a7ba
```

**Comment by Ernst79** [comment]
The information in the printscreen is the information you get after connecting to the scale. BLE monitor is not able to connect to devices, so we can't use that information. 

The BLE advertisement that you send in the last message is perhaps more usefull, but we have to figure out which data is where. I therefore want to ask you to make a longer log with BLE advertisements, to see which number change, and which ones not. This most of the the times gives a clue where we have to look. We have to focus on the last part. It also helps if you write down the measured weight, and other data dat is reported by the scale. 

`14ff64ffcfe50701250ccf000068010000000001a7`

`14` = length (14 in hex is 20 in dec --> 20 bytes)
`ff` = manufacturer specific data
`64ff` company id`
`cfe50701250ccf000068010000000001` = the data
`a7` = RSSI

**Comment by Psytoshgen** [comment]
can you also add younmai color scales? I think they use same protocols with xiaomi
i found some info here https://github.com/oliexdev/openScale/issues/71

Also got some info from phone
![IMG_0605](https://user-images.githubusercontent.com/94195788/168317641-bf5d3fb9-54fb-46a2-82cd-26bc0ebc9826.png)
![IMG_0606](https://user-images.githubusercontent.com/94195788/168317644-9b2fb178-e134-4eed-b895-bd9148400d32.png)
![IMG_0607](https://user-images.githubusercontent.com/94195788/168317652-b7c5078a-7ab7-4569-ab18-ce28c2c5d91d.png)
![IMG_0608](https://user-images.githubusercontent.com/94195788/168317653-d9e9a24d-3adc-4665-81f4-362d2b5daf68.png)
![IMG_0609](https://user-images.githubusercontent.com/94195788/168317655-ba36e229-f2fb-4e7d-81db-bd9b42a69f29.png)
![IMG_0610](https://user-images.githubusercontent.com/94195788/168317657-06369a17-0fee-4403-b313-a05ae245d150.png)
![IMG_0611](https://user-images.githubusercontent.com/94195788/168317665-f57e534c-4733-41b0-b3b1-2563ee97cb75.png)
![IMG_0612](https://user-images.githubusercontent.com/94195788/168317668-dcb340c7-29e1-48c8-80d7-d440c0d23bfe.png)
![IMG_0613](https://user-images.githubusercontent.com/94195788/168317669-418a2c5f-b462-49ea-9644-7b1f82e9d0c3.png)
