### ISSUE TITLE
[New Sensor]: Mikrotik TG-BT5-OUT and TG-BT5-IN

### ISSUE THREAD

**Issue by zayigo** [custom-components/ble_monitor#858]
### Sensor Description

Mikrotik bluetooth tags with built-in accelerometer and temperature sensor

### Additional information

Mikrotik uses a custom advertisement format for their BLE tags, specifically the [TG-BT5-OUT (accelerometer and temperature)](https://mikrotik.com/product/tg_bt5_out) and the [TG-BT5-IN  (only accelerometer)](https://mikrotik.com/product/tg_bt5_in).

They provide a detailed [description of packet structure](https://help.mikrotik.com/docs/display/UM/MikroTik+Tag+advertisement+formats) but for convenience, I've also created a [spreadsheet](https://docs.google.com/spreadsheets/d/1VOzCIZ23mWTSnyOBrrew0H_JvwGhH7ABltNZZsrajto/edit?usp=sharing) with the data captured from my device.

From [their app](https://play.google.com/store/apps/details?id=com.mikrotik.android.bt5&hl=en&gl=US) it's possible to enable encryption (using "AES-ECB" as stated in the documentation) but I can't figure out where to find or set the encryption key.

### BLE advertisements

```shell
04 3E 22 02 01 03 00 DD 7B 14 6E 2C DC 16 15 FF 4F 09 01 00 10 A9 00 00 FD FF 01 00 00 80 6B E8 66 00 00 62 D5

04 3E 22 02 01 03 00 DD 7B 14 6E 2C DC 16 15 FF 4F 09 01 00 EF 78 FF FF FF FF 02 00 00 80 BB E8 66 00 00 63 D0
```

**Comment by Ernst79** [comment]
Sorry, took a little while to look into it, but it looks possible to add this. I'm working on the parser, almost finished. The result:

`({'firmware': 'Mikrotik', 'version': 1, 'user data': 0, 'temperature': -128.0, 'acceleration x': 0.0, 'acceleration y': 255.98828125, 'acceleration z': 0.00390625, 'battery': 98, 'rssi': -43, 'mac': 'DC2C6E147BDD', 'type': 'TG-BT5', 'packet': 'no packet id', 'data': True}, None)`

Have to look into the uptime and flags, to see if it makes sense to send this data as well.

**Comment by Ernst79** [comment]
Added the flags stuff as well, will implement them as binary sensors. 

`({'firmware': 'Mikrotik', 'version': 1, 'user data': 0, 'temperature': -128.0, 'acceleration x': 0.0, 'acceleration y': 255.98828125, 'acceleration z': 0.00390625, 'acceleration': 255.9882812798037, 'uptime': 6744171, 'battery': 98, 'switch': 0, 'tilt': 0, 'free fall': 0, 'impact x': 0, 'impact y': 0, 'impact z': 0, 'rssi': -43, 'mac': 'DC2C6E147BDD', 'type': 'TG-BT5-IN', 'packet': 'no packet id', 'data': True}, None)`

**Comment by zayigo** [comment]
> I guess temperature = `00 80` (= -128°) means that it is not supported (TG-BT5-IN)?

Yes, that's correct

**Comment by Ernst79** [comment]
Thanks for the sponsoring 😄 Almost finished. final test is running now
