### ISSUE TITLE
[Bug]: Govee Temp/Hygro H5179 Sensor not working after HACS update 

### ISSUE THREAD

**Issue by elnas** [custom-components/ble_monitor#859]
### What happened?

Govee Temp/Hygro H5179 Sensor not working after HACS update 

### Sensor type

Govee Temp/Hygro H5179

### Relevant log output

```shell
Unknown Device
```

**Comment by Ernst79** [comment]
I need some more info to be able to help you. Please post the full error messages, including the long number (if present). 

Also tell me from which version you did the update and which version you have now.

**Comment by elnas** [comment]
Hello,
I used Passive BLE monitor integration version 8.6.1 and made the update to
version 8.6.3.
I have resolved to use 8.6.1 again and have not made any changes since that
last one worked for me.
The integration on 8.6.3 did not recognize my MiScale and Govee
integrations.

**Comment by Ernst79** [comment]
I had a quick look at the differences between 8.6.1 and 8.6.3, but do not have a clue yet. 

Can you do the following
1. install the latest version. 
2. Enable report_unknown for the specific device in the BLE monitor options of the sensor. 
3. Enable debug logging for BLE monitor.

For detailed instructions, see https://custom-components.github.io/ble_monitor/sensor_request

Post some of the BLE messages (long numbers) from the log here, to help me figure out what is wrong. Thanks

**Comment by Ernst79** [comment]
I'm closing this issue. If the latest version isn't working, please reopen the issue, after you have made a debug log as described above.
