### ISSUE TITLE
[Bug]: xiaomi mjyd02s-a didn't show any data

### ISSUE THREAD

**Issue by Psytoshgen** [custom-components/ble_monitor#862]
### What happened?

Good day!
cant see any data
![Точечный рисунок](https://user-images.githubusercontent.com/94195788/168306223-81953783-0cdf-4299-ac43-0192111ce454.jpg)
here what i found from phone. 

![IMG_0623](https://user-images.githubusercontent.com/94195788/168306487-0e986e8d-3008-4526-b4dc-40491c405c11.png)
![IMG_0617](https://user-images.githubusercontent.com/94195788/168306491-92d391d7-2202-494e-bbe6-1f56be8b1ec4.png)
![IMG_0618](https://user-images.githubusercontent.com/94195788/168306492-ff7b9122-cb3c-4de4-a3a5-bb7fa6b192bf.png)
![IMG_0619](https://user-images.githubusercontent.com/94195788/168306494-55ef3339-c183-42e1-afe9-160579524216.png)
![IMG_0620](https://user-images.githubusercontent.com/94195788/168306497-2c5fecb6-d39e-4b1e-9271-6d614afa2a65.png)
![IMG_0621](https://user-images.githubusercontent.com/94195788/168306502-9f69cc89-2add-4d2d-a986-f886ea2c3c27.png)
![IMG_0622](https://user-images.githubusercontent.com/94195788/168306503-c9f02faf-d212-4a25-9191-d2cf4803ac71.png)
Can you fix it?

**Comment by Ernst79** [comment]
Did you enter the encryption key?

**Comment by Psytoshgen** [comment]
> Did you enter the encryption key?

Not sure where to find it. In December version worked without any keys. Many devices was found as Ibeacon, I’ve just renamed them as I need.

**Comment by Ernst79** [comment]
This sensor does require an encryption key, according to the docs. The faq explains how to get the encryption key.
