### ISSUE TITLE
[Bug]: Unable to set up any config via web

### ISSUE THREAD

**Issue by qa-p-r** [custom-components/ble_monitor#868]
### What happened?

When I initially download the Passive BLE it doesn't show any configuration (like outlined in the documentation). After I install i neither can find a way to configure it. Clicking it opens up the repository, whereas opening the three dot menu does not show any configuration. 

Any tips?

note: the menu is the same after i restart my raspberry, i just tried to re-install it thinking i missed the config.

https://imgur.com/d7gmFSl

**Comment by Ernst79** [comment]
Your printscreen shows pending restart? Are you sure the restart worked?

**Comment by qa-p-r** [comment]
Yup, as noted the list of options was the same after restart, thus i re-installed it and it was still the same. After i restarted the red outline disappeared

What should be the name of the option?

**Comment by Ernst79** [comment]
You need to go to **configuration** --> **devices and services** --> integrations tab --> 

![image](https://user-images.githubusercontent.com/24375847/169403148-005bc37e-03cd-4fd7-aad9-ed8d0bc62223.png)

**Comment by Ernst79** [comment]
Is your problem solved? If so, please close the issue with the button below

**Comment by qa-p-r** [comment]
![0248690B-8C7E-4FAE-906F-F28A89EE28C8](https://user-images.githubusercontent.com/10826482/170280278-49cc35c0-5091-4a22-ba53-b8c2ff45de3d.png)

**Comment by qa-p-r** [comment]
integration view again…

![8A6573BB-97B4-4DCB-8265-EB65726D7BA1](https://user-images.githubusercontent.com/10826482/170280981-39c380da-6e95-4ee5-bf9b-c27a494b9d76.png)
![67C4C0E7-675C-4736-AF22-B5BF03CE815D](https://user-images.githubusercontent.com/10826482/170280999-ea97633d-94e7-430c-8b59-bacbfaba7ca0.png)

**Comment by Psytoshgen** [comment]
Can i leave here another config bug (to not start issue thread)? with latest firmware got "undefined" error when click configure. tried reinstall, not worked.
Hass supervised installed in docker in kali linux.
![1](https://user-images.githubusercontent.com/94195788/171036826-245aa4de-9446-41db-877c-54654448a4c7.jpg)
![Точечный рисунок](https://user-images.githubusercontent.com/94195788/171036849-af361730-80ed-4678-aec8-78058a51deec.jpg)

**Comment by Ernst79** [comment]
anything in the logs? Did you install 8.7.1? 8.7.0 had an bug.

**Comment by Psytoshgen** [comment]
> anything in the logs? Did you install 8.7.1? 8.7.0 had an bug.

yay =) now all fixed in 8.71 thank yu so much =)

**Comment by Ernst79** [comment]
I assume all is fixed now. If not, feel free to reopen the issue.

**Comment by qa-p-r** [comment]
> Did you click on the add integration button and search (and install) BLE monitor. In the last screenshot. If you don’t see it, hit F5 a couple of times and/or clear the browser cache.

Forgot to reply, but after 10th restart it finally came up in the place you mentioned. First two times i tried looking into there i found nothing.

**Comment by Ernst79** [comment]
No problem. Most of the times it's a browser cache problem, which can be solved by hitting F5 10 times. good to hear it is solved
