### ISSUE TITLE
[Bug]: module 'janus' has no attribute 'Queue'

### ISSUE THREAD

**Issue by homeyjoenka** [custom-components/ble_monitor#869]
### What happened?

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/ble_monitor/__init__.py:513
Integration: Passive BLE monitor (documentation, issues)
First occurred: 15:45:45 (3 occurrences)
Last logged: 17:55:06

Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ble_monitor/__init__.py", line 405, in async_setup_entry
    blemonitor = BLEmonitor(config)
  File "/config/custom_components/ble_monitor/__init__.py", line 513, in __init__
    "binary": janus.Queue(),
AttributeError: module 'janus' has no attribute 'Queue'

**Comment by Ernst79** [comment]
I guess something went wrong with the installation of the dependencies. Try to reinstall BLE monitor.

**Comment by homeyjoenka** [comment]
1 week ago works al perfect but now to last updat not its problems but we have now reinstall but problem its not going

**Comment by Ernst79** [comment]
Very strange. It looks like janus is not installed or you have an older version. I'm not sure what system you have, but you might be able to install it manually. It should use v1.0.0, which is the latest version of janus.

**Comment by homeyjoenka** [comment]
And what its janus?

**Comment by Ernst79** [comment]
janus is an external package, what should be installed automagically, just like the other python packages. 

https://pypi.org/project/janus/

If you use e.g. HA core, you can install it with `pip install janus`
However, if you use Home Assistant Os (like most people do), you can't do this. The only thing you can try in that case, is removing and reinstalling BLE monitor and hope that it will install along (as it should).

**Comment by Ernst79** [comment]
You need to log in with SSH to you virtual environment (venv) where you have installed Home Assistant (core). Log in as the same user that runs home assistant. After you have logged in, run `pip install janus`

**Comment by homeyjoenka** [comment]
i have OS

**Comment by Ernst79** [comment]
That makes it difficult. Try the following. Edit the file config/custom_component/ble_monitor/manifest.json 

change this line

`    "janus>=1.0.0",`

to

`    "janus==0.6.1",`

restart HA, this will install an old version of Janus. Next, Change it back to what is was, and restart again. This should install 1.0.0 again.

**Comment by homeyjoenka** [comment]
2x == for 0.6.1?

**Comment by Ernst79** [comment]
Yes

**Comment by homeyjoenka** [comment]
not working its wrong
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/ble_monitor/__init__.py:513
Integration: Passive BLE monitor (documentation, issues)
First occurred: 22:00:13 (1 occurrences)
Last logged: 22:00:13

Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ble_monitor/__init__.py", line 405, in async_setup_entry
    blemonitor = BLEmonitor(config)
  File "/config/custom_components/ble_monitor/__init__.py", line 513, in __init__
    "binary": janus.Queue(),
AttributeError: module 'janus' has no attribute 'Queue'

**Comment by Ernst79** [comment]
I have no other ideas. I also haven’t seen similar issues, so it’s hard to say what is wrong. @Magalex2x14 do you have an idea what could be the problem

**Comment by Ernst79** [comment]
There hasn't been any activity in this issue. We are closing it, to keep the issue tracker clean. Feel free to reopen if the problem still exists.

**Comment by distinq** [comment]
Since this weekend I have the same issue. Noticed the queue error as stated above along with the  following error in my logs:
`
Logger: homeassistant.util.package
Source: util/package.py:85
First occurred: 10:49:15 (4 occurrences)
Last logged: 10:49:21

Installed version for aioblescan resolved to None
Installed version for janus resolved to None
`

I am running HA on OS on a RPi4. I managed to get it fixed by adjusting the requirements for both packages to the previous version, and setting it back to the most current one again.
