### ISSUE TITLE
[New Sensor]: M365 E-Scooter

### ISSUE THREAD

**Issue by c-mahn** [custom-components/ble_monitor#872]
### Sensor Description

Xiaomi Mi Electric Scooter M365 E-Scooter

### Additional information

There are multiple Apps for phones in order to see information like charging status, range and current speed. Would it be possible to get this status information inside HA?
There are some examples for the protocol on github:
https://github.com/maisi/M365-Power
https://github.com/salvamr/m365-ble-msg-builder
https://github.com/CamiAlfa/M365-BLE-PROTOCOL

Since the scooter turns off automatically after several minutes of finishing charging, there is no need to have it shutdown the scooter. I would just like the idea of creating myself a charging-limit in combination with a smart outlet.

### BLE advertisements

```shell
Device Name: cmahn.de
Device Address: CD:34:17:4C:15:31

Services:--------------------------
GAP (00001800-0000-1000-8000-00805f9b34fb)
	Device Name (00002a00-0000-1000-8000-00805f9b34fb)
	Appearance (00002a01-0000-1000-8000-00805f9b34fb)
	Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)


Unknown service (6e400001-b5a3-f393-e0a9-e50e24dcca9e)
	Unknown characteristic (6e400003-b5a3-f393-e0a9-e50e24dcca9e)
	Unknown characteristic (6e400002-b5a3-f393-e0a9-e50e24dcca9e)


Unknown service (0000fe95-0000-1000-8000-00805f9b34fb)
	Service Discovery Protocol (SDP) (00000001-0000-1000-8000-00805f9b34fb)
	User Datagram Protocol (UDP) (00000002-0000-1000-8000-00805f9b34fb)
	TCP (00000004-0000-1000-8000-00805f9b34fb)
	UPNP Protocol (00000010-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (00000013-0000-1000-8000-00805f9b34fb)
	Hardcopy Data Channel Protocol (00000014-0000-1000-8000-00805f9b34fb)


--------------------------
```

**Comment by Ernst79** [comment]
Hi, this scooter require a connection to be set up, which is not supported with BLE monitor. You could try ESPhome BLE client, as it can send and read "characteristics"
