### ISSUE TITLE
[Bug]: Detected integration that uses deprecated `async_get_registry`

### ISSUE THREAD

**Issue by Psytoshgen** [custom-components/ble_monitor#878]
### What happened?

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 16:24:58 (2 occurrences)
Last logged: 16:26:50

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for ble_monitor using this method at custom_components/ble_monitor/device_tracker.py, line 117: dev_registry = await device_registry.async_get_registry(hass)
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for ble_monitor using this method at custom_components/ble_monitor/config_flow.py, line 554: devreg = await self.hass.helpers.device_registry.async_get_registry()

**Comment by Ernst79** [comment]
Thanks, fixed in 8.7.0
