### ISSUE TITLE
[New Sensor]: mamaRoo baby bouncer

### ISSUE THREAD

**Issue by deformedchild** [custom-components/ble_monitor#883]
### Sensor Description

Baby bouncer

### Additional information

Hi any chance some one can add this to the builds
A mqtt adapter has been made but I have know idea how to get it working so hopefully all commands needed are already there
https://github.com/chrisrosset/mamaroo-mqtt

**Comment by Ernst79** [comment]
I think this device requires a connection, as you have to enter the MAC address of the device. This is not supported in ble monitor, as it passively scans for ble messages. But I might be wrong. Can you collect some ble messages? Instructions are in the documentation.

**Comment by Ernst79** [comment]
Feel free to reopen if you have additional data
