### ISSUE TITLE
[New Sensor]: xmzncxb01qm smart strip - consumption status

### ISSUE THREAD

**Issue by MoMolap** [custom-components/ble_monitor#884]
### Sensor Description

Xiaomi Mijia Mi Smart Power Strip Extension v2 5 Socket

### Additional information

I would like to know if you can add the smart power strip. I understand that we can not control it (turning the switch on and off) but i assume this BLE smart strip is emitting BLE packets payload that can be read. 

Especially, i am interested in power consumption data.

(https://home.miot-spec.com/spec/qmi.plug.psv3)

### BLE advertisements

```shell
Device Name: qmi.plug.psv3
Device Address: 68:AB:BC:0A:AA:A3

Services:--------------------------
GATT (00001801-0000-1000-8000-00805f9b34fb)
	Service Changed (00002a05-0000-1000-8000-00805f9b34fb)


GAP (00001800-0000-1000-8000-00805f9b34fb)
	Device Name (00002a00-0000-1000-8000-00805f9b34fb)
	Appearance (00002a01-0000-1000-8000-00805f9b34fb)
	Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (00002aa6-0000-1000-8000-00805f9b34fb)


Unknown service (0000fe95-0000-1000-8000-00805f9b34fb)
	TCP (00000004-0000-1000-8000-00805f9b34fb)
	UPNP Protocol (00000010-0000-1000-8000-00805f9b34fb)
	Hardcopy Notification Protocol (00000016-0000-1000-8000-00805f9b34fb)
	VCTP Protocol (00000017-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (00000018-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000001a-0000-1000-8000-00805f9b34fb)
	CMPT Protocol (0000001b-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000001c-0000-1000-8000-00805f9b34fb)
```

**Comment by MoMolap** [comment]
[dump.txt](https://github.com/custom-components/ble_monitor/files/8833001/dump.txt)

**Comment by rezmus** [comment]
it is ble mesh device iirc.

**Comment by Ernst79** [comment]
Will look into it next week, but I doubt it will be possible. But let’s see.

**Comment by Ernst79** [comment]
I've checked it, it is indeed a BLE mesh device. This means that we can't support it, as we can't connect to the device with BLE monitor. BLE monitor is passively listening to BLE messages, but the message is telling us that it requires a connection to be set up to get the data. You could try ESPhome BLE client for reading characteristics.

**Comment by MoMolap** [comment]
Thanks for looking into it.

Morgan Billard

+81(0)80-4013-0475
