### ISSUE TITLE
[Bug]: AttributeError: module 'aioblescan' has no attribute 'create_bt_socket'

### ISSUE THREAD

**Issue by AscendedGravity** [custom-components/ble_monitor#891]
### What happened?

I recently noticed that my BLE devices stopped reporting. I'm running HA Core 2022.6.4 in a docker container on a RPi 4. I am using the Pi's built-in bluetooth. Also on the latest ble_monitor build. Running bluetoothctl scan shows the devices and their data. Adding the log below.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 709, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
AttributeError: module 'aioblescan' has no attribute 'create_bt_socket'
```

**Comment by Ernst79** [comment]
I have no idea, creat_bt_socket should be available, 

https://github.com/frawau/aioblescan/blob/670a0301e8af82960e2aa8db04933994780f854e/aioblescan/aioblescan.py#L1686

perhaps try to delete and reinstall ble monitor

**Comment by AscendedGravity** [comment]
> I have no idea, creat_bt_socket should be available,
> 
> https://github.com/frawau/aioblescan/blob/670a0301e8af82960e2aa8db04933994780f854e/aioblescan/aioblescan.py#L1686
> 
> perhaps try to delete and reinstall ble monitor

After a few re-installs and reboots it's working. Very odd since it's running in a container. Thanks!
