### ISSUE TITLE
[Bug]: Documentation not compatiable with latest HA/HACS

### ISSUE THREAD

**Issue by weakify** [custom-components/ble_monitor#893]
### What happened?

Here:

https://custom-components.github.io/ble_monitor/Installation#step-3a-configuration-in-the-user-interface

It says "go to Configuration in the side menu in Home Assistant", but what the user should do is got to the "HACS" tab.
Then it says the configuration UI should open which does not happen in latest HA.

![image](https://user-images.githubusercontent.com/57955992/173191604-26692531-0e79-46ed-b7fa-7b46900e741c.png)

Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

**Comment by Ernst79** [comment]
No, don’t go to hacs, you need to go settings, devices and services, integrations, ble monitor card.

**Comment by Ernst79** [comment]
I have updated the instructions, to be in line with the latest HA version.
