### ISSUE TITLE
[Bug]: Documentation suggestion do not work

### ISSUE THREAD

**Issue by weakify** [custom-components/ble_monitor#894]
### What happened?

I run
```
sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\``
```
and

```
sudo getcap `readlink -f \`which python3\``
```

in the ssh terminal.

sudo and getcap are not installed and which python3 returns an empty string

![image](https://user-images.githubusercontent.com/57955992/173196857-bbb899f0-7d47-4b01-8352-eccefccf5c98.png)

**Comment by Ernst79** [comment]
What kind of installation do you have? normally you should be able to run stuff as sudo. Only with a full HA installation (incl HA OS) you are not allowed to use sudo. But than you don’t need this command. 

Installation of sudo is out of the scope of the instructions, we assume that people know how to do that (with help from google).

**Comment by weakify** [comment]
Yes I use HA OS installation. I agree that installation of sudo is out of scope.
I am new to HA and did not understand what it actually meant with regard to my installation.

```
This is usually only needed for alternative installations of Home Assistant that only install Home Assistant core. 
```

**Comment by Ernst79** [comment]
No problem, see for more information about the different installations this page

https://www.home-assistant.io/installation/

you have the first (Home Assistant OS), for which the command is not needed (it isn’t even possible to run, as you encountered)
