### ISSUE TITLE
[Bug]: Installation fails with "config flow" error

### ISSUE THREAD

**Issue by nickdos** [custom-components/ble_monitor#895]
### What happened?

Installed via HACS and did a restart. Attempted to install via "Add integration" - found this integration and clicked install.

The installation shows spinning icon for over a minute and then show the error message: `Config flow could not be loaded: undefined`. 

Nothing appears in my log. I'm running `Home Assistant Supervised` (2022.05.3) with latest version of HA (2022.6.5).

**Comment by Ernst79** [comment]
Try to hit F5 a couple of times or clear your browser cache.

**Comment by nickdos** [comment]
Thanks for the suggestion - clearing cache did not fix it. I also tried another browser as well as using incognito mode (fresh login no shared cache, cookies, etc.) and all failed with the same error. Still nothing in logs.

**Comment by Ernst79** [comment]
hmm, I'll try to test it later this week on my development system.

**Comment by Ernst79** [comment]
Just tested it, but I don't see any errors during installation. I'm running HA Os myself, don't have a supervisor installation. Perhaps try to remove it from HACS and reinstall it again? other thing you can try is to enable debug logging for BLE monitor, this might give me additional hints what is wrong (and what not).

**Comment by nickdos** [comment]
Could be a strange artifact of my system, so if no one else reports this, just file it under "one off". I'm currently using an ESP32 to communicate with my BLE sensor so I'm not desperate to get this component working - was more of an interest in comparing it to the ESP32, for better long term reliability.

**Comment by Ernst79** [comment]
On the ha forum, there is a user with a similar issue, but he gets a message about pyric not being available. Not sure why, as we don’t use pyric as far as I know.

2022-06-14 19:56:43 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration ble_monitor: No module named ‘pyric’

**Comment by SergeantPup** [comment]
@nickdos I think I'm experiencing the same issue, or at least a symptom of the same issue.  I have had passive BLE monitor working in the past.  It's been removed for a minute.  I just tried to re-add it and it does not find passive BLE in the integrations list after restart.  I've tried multiple times and it's just not there.  The custom component folders are definitely in my system and I know the screens that are supposed to come next, something is just blocking it.

**Comment by Ernst79** [comment]
Did you clear the cache and hit F5 a couple of times.

**Comment by SergeantPup** [comment]
lol, I can't believe that just worked.  thanks

**Comment by Ernst79** [comment]
@nickdos the issue that was reported on the HA forum was caused by the Snap version of HA. After installing the HA in a docker container. Are you using a "Snap version of HA".

**Comment by nickdos** [comment]
> @nickdos the issue that was reported on the HA forum was caused by the Snap version of HA. After installing the HA in a docker container. Are you using a "Snap version of HA".

No, I'm using a normal supervised version. Host OS is slightly out of date though (reports its now unsupported - Debian Buster). 

![image](https://user-images.githubusercontent.com/532845/174536622-fcb2144d-e015-4f0b-b7f6-b4592258a847.png)

**Comment by glenviewjeff** [comment]
Also having this problem. There's a long delay with the spinner that says "Please wait while Passive BLE monitor is being setup," and then after about one or two minutes I get the "Config flow could not be loaded: undefined" error. I am running on Home Assistant Blue/Odroid-N2+.

**Comment by Ernst79** [comment]
Most of the times, it is a browser cache issue, which can be solved by hitting F5 a couple of times.

**Comment by Ernst79** [comment]
Try to remove and reinstall it, restart HA and hit F5 a couple of times

**Comment by silentnyte** [comment]
I had this issue also with HACS installation. Remove and reinstalling fixed the issue.

**Comment by Salamandar** [comment]
Indeed, it fixed it for me too. weird.
