### ISSUE TITLE
[New Sensor]: Thermopro TP359 (thermometer/hygrometer)

### ISSUE THREAD

**Issue by Guspaz** [custom-components/ble_monitor#898]
### Sensor Description

ThermoPro TP359 Bluetooth Wireless Thermometer Hygrometer and Humidity Monitor

### Additional information

Product page: https://buythermopro.com/product/thermopro-tp59-bluetooth-wireless-thermometer-hygrometer-humidity-monitor/

I own three of these. They just sit there all day sending out their data every ~2 seconds or so, no encryption. I'm not 100% sure if they were broadcasting like this before I added them to the ThermoPro iPhone app, I had already added them to the app by the time I wrote the code to parse the advertisements.

I had previously written some code to parse their advertisements and shove the data into sensors in my Hue hub, so I've already figured out the data format for the temperature and humidity.

In the included BLE advertisements, I gave the sensor readings at the time of the capture. That information is:

Mac address:
- 870cf2487e48 (reversed, I guess?)

Position of mac address (0-based):
- 16

Humidity info:
- stored as integer in hex
- value in hci advertisement is, 38% = "26", 53% = "35"
- position (0-based) is 102

Temperature info:
- stored as integer of temp * 10 in hex in reverse byte order
- value in hci advertisement is, 25.4c = "fe 00", 25.5c = "ff 00"
- position (0-based) is 98

They are probably also broadcasting the battery level and maybe other info, but the battery level is not visible on the device's screen (other than a low battery icon that shows up when the battery is low), and the battery level is only reported very roughly in the iPhone app (1 to 3 bars in a battery icon) so I didn't have any reference to use to figure it out. All I can tell you is that when I took the hci captures, the battery low icon was off and it had 2/3 bars in the app, and after I did the captures, I hit the light button on the unit and the battery low icon appeared and it dropped to 1/3 in the app. So the battery state was presumably somewhere just barely above 1/3 at the time of capture.

### BLE advertisements

```shell
HCI advertisement (25.4C, 38% humidity):
043e330d01130000870cf2487e480100ff7fd6000000000000000000190d0954503335392028304338372902010507ffc2fe0026012c

HCI advertisement (25.5C, 53% humidity):
043e330d01130000870cf2487e480100ff7fd8000000000000000000190d0954503335392028304338372902010507ffc2ff0035012c
```

**Comment by Guspaz** [comment]
I hacked in support for the TP359 into ble_monitor (see attached file for a copy of ble_monitor with all the changes that I've made). Major giant huge caveats: I don't know python (at all), so I just used surrounding code as a reference. I'm sure I did everything wrong, and I cheated on the device detection by just hardcoding the names of my devices (which includes part of the mac address) into the if statements (they don't appear to have any uuid, the comp_id is grabbing one of the temperature bytes so isn't valid, and it's all in man_spec_data, and I don't know python so I don't know how to check if a string starts with "TP359"). That said, it works, so it might be useful to you as a reference since it reads the temperature and humidity from the units and gets them into home assistant. In terms of which bytes to grab for the temp/humidity.

[ble_monitor.zip](https://github.com/custom-components/ble_monitor/files/8912523/ble_monitor.zip)

**Comment by Ernst79** [comment]
Thanks, I will have a look later this week. Have been a bit busy with other things, but I will look into it

**Comment by Guspaz** [comment]
Tested and verified working. Upon replacing my hacked version with the official version, two my three sensors updated their reported manufacturer/firmware to "Thermopro" while one of them still shows the old value that I had used in my hack as "ThermoPro". All three are continuing to update as expected, however.

**Comment by Ernst79** [comment]
Just remove the device in the ble monitor settings. It will probably be readded with the correct name.
