### ISSUE TITLE
[New Sensor]:  Use ESPHOME BLE Scanner as source

### ISSUE THREAD

**Issue by diginfo** [custom-components/ble_monitor#905]
### Sensor Description

ESPHOME

### Additional information

Just wondering whether it would be possble to use an esphome device as the scanner instead of the built-in bluetooth radio ?

https://esphome.io/components/text_sensor/ble_scanner.html

Many Thanks

**Comment by Ernst79** [comment]
Yes, that is possible. There is a page in the explanation in the documentation

https://custom-components.github.io/ble_monitor/parse_data

Just forward the BLE messages with [ESPHome BLE gateway](https://github.com/myhomeiot/esphome-components) and enable track devices for a specific MAC address in BLE monitor and you should be good to go.
