### ISSUE TITLE
Govee H5074 Issues

### ISSUE THREAD

**Issue by jazz127** [custom-components/ble_monitor#909]
Hello.  Firstly, thanks for this awesome module - it's really helping my with my HA Setup goals.

I have a number of Govee Hygrometers with different models - H5074, H5101, H5075 mainly.  The H5101 & H5075 work wonderfully - I get data points every few minutes at least.  Unfortunately, with the H5074, I'm lucky to see data once an hour, it chops and changes around so much, very very sporadic.

I don't think it's a signal issue, this happens if the H5074 is right next to the receiver, RSSI sits around 40.  The 5101&5075 are a lot further away and run about 100.

Using other tools, I can see the advertisements for the 5074 models floating around in the air regularly.  My setup is a NUC running KVM, I have the onboard Intel bluetooth in the Host ubuntu (that i see the advertisements on) and another adapter passed through to my HA OS appliance VM. So technically I'm using different cards to verify the advertisements are being received at the moment (I can't get the intel to work when passed through via KVM). 

I have enabled the Active Scanning - the 5074's didn't really work at all until i manually added the MAC address as a device in BLE config page.  After I added them, i started getting the sporadic data.  I actually added them manually to enable unknown advertisement logging - i couldn't believe it when i started seeing SOME data. I'm also catching messages like this from the H5074's fairly regularly 

2022-06-27 22:48:27 INFO (Thread-3) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID a4c1389c232c: 043e330d011300002c239c38c1a40100ff7fb000000000000000000019020106030388ec1109476f7665655f48353037345f32333243

Not sure if it will be helpful but I also get 2x "Apple iBeacon" devices registered.  These are rather weird to me - the MAC address seems to constantly change between various devices (inc my 5074s and other govee MAC addresses).  

Is anyone able to provide any assistance or ideas on how I can get my H5074's working more reliably?  Thank you very much in advance!

**Comment by Ernst79** [comment]
iBeacons constantly change their mac, that is why we add them based on the uuid. This is normal behavior and is related to privacy, I thought.

i will have a look at the ble message later today. If you can collect some more, it might give us a clue what is wrong.

**Comment by Ernst79** [comment]
I had a look at the BLE advertisement. The data is always in the part after the zeros. 

`020106` = flags
`030388ec` = UUID16 (88EC is common for Govee)
`1109476f7665655f48353037345f32333243` = Name

The name translates to `Govee_H5074_232C` (hex to text). 

So, this message doesn't contain data, only the name of the device. 

Perhaps you can make a longer log with more BLE advertisements.

**Comment by Ernst79** [comment]
any change to get some more data?

**Comment by Ernst79** [comment]
Could you try 9.0.1. There has been a fix for Govee Sensors that add extra bytes to the data. It might be your issue, not sure, but its worth to try.

**Comment by jazz127** [comment]
Terribly sorry for my slow reply.  a few things

- 9.0.1 doesn't seem to change the situation.  That said, the logging and other things this brought are fantastic!
- Thanks for explaining the name above, makes much more sense!
- I do still think that somehow my system might be missing advertisements on my H5074 but i can't say i have conclusive data on this yet as at the end of the day, the sensors do show up in ble_monitor and eventually update

One theory I do have is that maybe the display & detail of the data is clouding my judgment here - it seems that a 5074 entry is only showing one decimal point in the logs whereas other models show more (examples below).  Perhaps because there isn't as much variance, somewhere along the line of the module/HA, the point isn't recorded/shown because the there isn't any change in the data? 

2022-07-18 18:23:58 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Data binary sensor received: {'firmware': 'Govee', 'temperature': 21.4, 'humidity': 51.38, 'battery': 100, 'rssi': -102, 'mac': '', 'type': 'H5074', 'packet': 'no packet id', 'data': True}

2022-07-18 18:24:42 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Data binary sensor received: {'firmware': 'Govee', 'temperature': 25.7615, 'humidity': 61.5, 'battery': 96, 'rssi': -58, 'mac': '', 'type': 'H5072/H5075', 'packet': 'no packet id', 'data': True}

**Comment by Ernst79** [comment]
Closing this issue to keep things clean. In case this issue is still relevant, please reopen it.
