### ISSUE TITLE
[Bug]: Requirements for ble_monitor not found: ['pycryptodomex>=3.15.0'].

### ISSUE THREAD

**Issue by moritz-john** [custom-components/ble_monitor#912]
### What happened?

I am using the Docker `Home-Assistant-Core` in Unraid.
After updating the `Passive BLE Monitor` HACS integration to newest version (8.9.2) I get the following eror:

```
ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration ble_monitor: Requirements for ble_monitor not found: ['pycryptodomex>=3.15.0'].
``` 

I tried to using the container console and use `pip uninstall pycryptodomex` and then `pip install pycryptodomex` to get the newest version but all I get is errors.

I noticed that the version 3.15.0 is mentioned in [this pull request](https://github.com/custom-components/ble_monitor/pull/911).

I tried reinstalling `Passive BLE Monitor integration` but this also did not help.

___

**EDIT:** downgrading `Passive BLE monitor` to version `8.9.1` makes everything work again, so I guess the problem lies with version `8.9.2`.

___

### Relevant log output

[errors.txt](https://github.com/custom-components/ble_monitor/files/9018718/errors.txt)

**Comment by alesoft73** [comment]
@moritz-john 
Edit manifest.json in this mode for now... Work for me ;)

{
  "domain": "ble_monitor",
  "name": "Passive BLE monitor",
  "config_flow": true,
  "documentation": "https://github.com/custom-components/ble_monitor",
  "issue_tracker": "https://github.com/custom-components/ble_monitor/issues",
  "requirements": [
    "pycryptodomex",
    "janus>=1.0.0",
    "aioblescan>=0.2.13",
    "btsocket>=0.2.0",
    "pyric>=0.1.6.3"
  ],
  "dependencies": [],
  "codeowners": ["@Ernst79", "@Magalex2x14", "@Thrilleratplay"],
  "version": "8.9.2",
  "iot_class": "local_polling"
}

**Comment by Ernst79** [comment]
can confirm the issue. will revert it

**Comment by moritz-john** [comment]
Thank you, version `8.9.3` works for me again.
