### ISSUE TITLE
[New Sensor]: Oclean X Pro Elite

### ISSUE THREAD

**Issue by Draghmar** [custom-components/ble_monitor#915]
### Sensor Description

Oclean X Pro Elite

### Additional information

Oclean X Pro Elite is a electric toothbrush with wireless charging. It should have BT on all the time - manual says that. It has 32 levels of power, 4 types of cleaning, adjustable time (2:00 being default) and can monitor how well you clean your teeth, showing that both as a percent and visual aid for each side.

I've used the recommended android app and nRF Connect as well, so there is some txt and few screenshots. I hope it's enough
![Screenshot_20220701-093133](https://user-images.githubusercontent.com/275348/176998461-e684960b-d055-4eb0-a9ec-636c78688a5b.jpg)
![Screenshot_20220701-093139](https://user-images.githubusercontent.com/275348/176998463-1a322dc1-102a-4e2b-ae64-eba472f73e0d.jpg)
![Screenshot_20220701-093149](https://user-images.githubusercontent.com/275348/176998464-467e0fe9-0179-4b27-88de-95730bcdec26.jpg)
![Screenshot_20220701-093154](https://user-images.githubusercontent.com/275348/176998465-a993e40b-3997-43a7-a7ae-2c9cd51fbfef.jpg)
![Screenshot_20220701-093159](https://user-images.githubusercontent.com/275348/176998467-c1e15e3c-b01c-4588-a87d-5918a5db2ff1.jpg)
![Screenshot_20220701-093206](https://user-images.githubusercontent.com/275348/176998468-585f5936-4767-4d9f-a68d-1f94c90d62f4.jpg)
![Screenshot_20220701-092815](https://user-images.githubusercontent.com/275348/176998469-dd7399ba-93be-4920-91b5-1d12924b0f27.jpg)
![Screenshot_20220701-092820](https://user-images.githubusercontent.com/275348/176998471-f7aaa6ff-daf0-44a1-8dd3-76b8b91ba4be.jpg)
.

### BLE advertisements

```shell
Device Name: Oclean X Pro Elite

Services:--------------------------
GAP (00001800-0000-1000-8000-00805f9b34fb)
 Device Name (00002a00-0000-1000-8000-00805f9b34fb)
 Appearance (00002a01-0000-1000-8000-00805f9b34fb)
 Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)


IMMEDIATE_ALERT (00001802-0000-1000-8000-00805f9b34fb)
 Alert Level (00002a06-0000-1000-8000-00805f9b34fb)


LINK_LOSS (00001803-0000-1000-8000-00805f9b34fb)
 Alert Level (00002a06-0000-1000-8000-00805f9b34fb)


Unknown service (0000180f-0000-1000-8000-00805f9b34fb)
 Unknown characteristic (00002a19-0000-1000-8000-00805f9b34fb)


Unknown service (8082caa8-41a6-4021-91c6-56f9b954cc18)
 Unknown characteristic (9d84b9a3-000c-49d8-9183-855b673fbb85)
 Unknown characteristic (5f78df94-798c-46f5-990a-855b673fbb86)
 Unknown characteristic (5f78df94-798c-46f5-990a-855b673fbb87)
 Unknown characteristic (5f78df94-798c-46f5-990a-855b673fbb88)
 Unknown characteristic (5f78df94-798c-46f5-990a-855b673fbb89)
 Unknown characteristic (5f78df94-798c-46f5-990a-855b673fbb90)


Unknown service (0000fef5-0000-1000-8000-00805f9b34fb)
 Unknown characteristic (8082caa8-41a6-4021-91c6-56f9b954cc34)
 Unknown characteristic (724249f0-5ec3-4b5f-8804-42345af08651)
 Unknown characteristic (6c53db25-47a1-45fe-a022-7c92fb334fd4)
 Unknown characteristic (9d84b9a3-000c-49d8-9183-855b673fda31)
 Unknown characteristic (457871e8-d516-4ca1-9116-57d0b17b9cb2)
 Unknown characteristic (5f78df94-798c-46f5-990a-b3eb6a065c88)
 Unknown characteristic (61c8849c-f639-4765-946e-5c3419bebb2a)
 Unknown characteristic (64b4e8b5-0de5-401b-a21d-acc8db3b913a)
 Unknown characteristic (42c3dfdd-77be-4d9c-8454-8f875267fb3b)
 Unknown characteristic (b7de1eea-823d-43bb-a3af-c4903dfce23c)


Device Information (0000180a-0000-1000-8000-00805f9b34fb)
 Manufacturer Name String (00002a29-0000-1000-8000-00805f9b34fb)
 Model Number String (00002a24-0000-1000-8000-00805f9b34fb)
 Serial Number String (00002a25-0000-1000-8000-00805f9b34fb)
 Hardware Revision String (00002a27-0000-1000-8000-00805f9b34fb)
 Firmware Revision String (00002a26-0000-1000-8000-00805f9b34fb)
 Software Revision String (00002a28-0000-1000-8000-00805f9b34fb)


--------------------------
```

**Comment by Ernst79** [comment]
Oclean X toothbrushes require a connection, which is not supported in BLE monitor. Please check this issue, where a similar request was done. In the last post, they give an option to get some data with ESPhome. 

See https://github.com/custom-components/ble_monitor/issues/280

Unfortunately, this toothbrush can't be supported in BLE monitor

**Comment by Draghmar** [comment]
Oh, ok. Didn't know about that. Thanks for the info.
