### ISSUE TITLE
[New Sensor]: Ruveno Smart Door Lock

### ISSUE THREAD

**Issue by jasonwragg** [custom-components/ble_monitor#917]
### Sensor Description

Ruveno Smart Door Lock

### Additional information

(https://www.amazon.co.uk/gp/product/B08CB1YM23)
Ruveno Smart Door Lock, Biometric Fingerprint Door Lock, Smart Door Handle, WiFi Bluetooth APP Security Simplified Deadbolts Fingerprint Door Handle(White)

**Comment by Ernst79** [comment]
I need some more info, like BLE advertisements, before I can check if it is possible to add this device. Please check this page on how to collect this information

https://custom-components.github.io/ble_monitor/sensor_request

**Comment by Ernst79** [comment]
Ill have a look soon. Busy with some rebuilding in the house

**Comment by Ernst79** [comment]
Sorry, forgot about this issue. First analysis

Manufacturer specific data
`12ff0503021240b000f4f953657f8a43b9f0f7`

`12` = length
`ff` = manufacturer specific data
`0503`= company id
`021240b000f4f95365` = data
`7f8a43b9f0f7` = mac (reversed per 2 char)

So, lets see what changes in the data part, I see two different data parts in your log
`021240b000f4f95365`
`020236b000f4f95365`

so only the 2nd and 3rd byte change from `1240` to `0236` Hard to tell what the data means.

**Comment by Ernst79** [comment]
Any update on this issue?

**Comment by Ernst79** [comment]
There hasn't been any activity in this issue. We are closing it, to keep the issue tracker clean. Feel free to reopen if the problem still exists.
