### ISSUE TITLE
[Bug]: ble_monitor potentially incompatible with Home Assistant 2022.7 (Python 3.10 and removes pybluez)

### ISSUE THREAD

**Issue by Guspaz** [custom-components/ble_monitor#931]
### What happened?

Home Assistant 2022.7 was just released. I noticed in the breaking changes list (https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes) that the upgrade to Python 3.10 breaks pybluez support (which apparently has not been updated in years) and thus it has been removed. My understanding is that ble_monitor relies on pybluez (the FAQ includes an instruction to install it). So my current assumption is that the ble_monitor integration is incompatible with the new release of Home Assistant. I haven't verified this directly, as I don't want to upgrade to 2022.7 and risk breaking ble_monitor since it's pretty integral to my home's climate control.

**Comment by Guspaz** [comment]
If ble_monitor does not currently use pybluez, then consider this a bug report that the FAQ needs to be updated to remove the pybluez installation instruction :)

**Comment by bdraco** [comment]
The general advice is to switch to using bleak as thats likely going to be the path forward

**Comment by Ernst79** [comment]
BLE monitor is running fine on HA 2022.7.0, we don’t use bluepy, I will update the documentation.

About bleak. The home assistant devs (Balloob himself) are currently working on a new Bluetooth integration that will take care of the data collecting (with the Bluetooth receiver but also with e.g. ESPhome). This will probably based on bleak. The idea is that the data can be used by different integrations, including ble monitor. So, the idea is that in the future, we will remove the ble data collecting from BLE monitor, and use the built in integration, after it is finished. I’m in contact with balloob, he is also aware of this widely used integration, and I will take care that things keep on working, either in BLE monitor, or in Home Assistant.

**Comment by met67** [comment]
> BLE monitor is running fine on HA 2022.7.0, we don’t use bluepy, I will update the documentation.

Yes, please! You could also add a specific FAQ on this issue (I also was refraining to update to 2022.7 for this...)

**Comment by Ernst79** [comment]
Documentation has been updated and FAQ article is added.
