### ISSUE TITLE
BM2 car battery Monitor 

### ISSUE THREAD

**Issue by Next9999** [custom-components/ble_monitor#933]
### Sensor Description

BM2 car battery Monitor 

### Additional information

https://www.amazon.ca/Bluetooth-Battery-Monitor-Voltage-Wireless/dp/B074ZCM6YC/ref=asc_df_B074ZCM6YC?tag=bingshopdesk-20&linkCode=df0&hvadid=80745476895215&hvnetw=o&hvqmt=e&hvbmt=be&hvdev=c&hvlocint=&hvlocphy=&hvtargid=pla-4584345031344429&psc=1

### BLE advertisements

```shell
Device Name: Battery Monitor
Device Address: 44:EA:D8:31:07:AF

Services:--------------------------
GAP (00001800-0000-1000-8000-00805f9b34fb)
	Device Name (00002a00-0000-1000-8000-00805f9b34fb)
	Appearance (00002a01-0000-1000-8000-00805f9b34fb)
	Peripheral Privacy Flag (00002a02-0000-1000-8000-00805f9b34fb)
	Reconnection Address (00002a03-0000-1000-8000-00805f9b34fb)
	Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)
	Service Changed (00002a05-0000-1000-8000-00805f9b34fb)


Device Information (0000180a-0000-1000-8000-00805f9b34fb)
	System ID (00002a23-0000-1000-8000-00805f9b34fb)
	Model Number String (00002a24-0000-1000-8000-00805f9b34fb)
	Serial Number String (00002a25-0000-1000-8000-00805f9b34fb)
	Firmware Revision String (00002a26-0000-1000-8000-00805f9b34fb)
	Hardware Revision String (00002a27-0000-1000-8000-00805f9b34fb)
	Software Revision String (00002a28-0000-1000-8000-00805f9b34fb)
	Manufacturer Name String (00002a29-0000-1000-8000-00805f9b34fb)
	IEEE 11073-20601 Regulatory (00002a2a-0000-1000-8000-00805f9b34fb)
	PNPID (00002a50-0000-1000-8000-00805f9b34fb)


Unknown service (0000fff0-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff1-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff2-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff3-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff4-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff5-0000-1000-8000-00805f9b34fb)


Unknown service (f000ffc0-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc1-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc2-0451-4000-b000-000000000000)


--------------------------

```

**Comment by Ernst79** [comment]
**BLE advertisements**
`:-(` 

Hmmm, lets look into my Cristal ball and implement it.... Just kidding, but without BLE data, I can't do much. check this page on how to get the data.

**Comment by Next9999** [comment]
Device Name: Battery Monitor
Device Address: 44:EA:D8:31:07:AF

Services:--------------------------
GAP (00001800-0000-1000-8000-00805f9b34fb)
	Device Name (00002a00-0000-1000-8000-00805f9b34fb)
	Appearance (00002a01-0000-1000-8000-00805f9b34fb)
	Peripheral Privacy Flag (00002a02-0000-1000-8000-00805f9b34fb)
	Reconnection Address (00002a03-0000-1000-8000-00805f9b34fb)
	Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)
	Service Changed (00002a05-0000-1000-8000-00805f9b34fb)


Device Information (0000180a-0000-1000-8000-00805f9b34fb)
	System ID (00002a23-0000-1000-8000-00805f9b34fb)
	Model Number String (00002a24-0000-1000-8000-00805f9b34fb)
	Serial Number String (00002a25-0000-1000-8000-00805f9b34fb)
	Firmware Revision String (00002a26-0000-1000-8000-00805f9b34fb)
	Hardware Revision String (00002a27-0000-1000-8000-00805f9b34fb)
	Software Revision String (00002a28-0000-1000-8000-00805f9b34fb)
	Manufacturer Name String (00002a29-0000-1000-8000-00805f9b34fb)
	IEEE 11073-20601 Regulatory (00002a2a-0000-1000-8000-00805f9b34fb)
	PNPID (00002a50-0000-1000-8000-00805f9b34fb)


Unknown service (0000fff0-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff1-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff2-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff3-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff4-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff5-0000-1000-8000-00805f9b34fb)


Unknown service (f000ffc0-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc1-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc2-0451-4000-b000-000000000000)


--------------------------
[Bluetooth LE Device GATT Results (Battery Monitor, 44_EA_D8_31_07_AF).txt](https://github.com/custom-components/ble_monitor/files/9064714/Bluetooth.LE.Device.GATT.Results.Battery.Monitor.44_EA_D8_31_07_AF.txt)

**Comment by Next9999** [comment]
second sensor

Device Name: Battery Monitor
Device Address: 78:04:73:09:15:7C

Services:--------------------------
GAP (00001800-0000-1000-8000-00805f9b34fb)
	Device Name (00002a00-0000-1000-8000-00805f9b34fb)
	Appearance (00002a01-0000-1000-8000-00805f9b34fb)
	Peripheral Privacy Flag (00002a02-0000-1000-8000-00805f9b34fb)
	Reconnection Address (00002a03-0000-1000-8000-00805f9b34fb)
	Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)
	Service Changed (00002a05-0000-1000-8000-00805f9b34fb)


Device Information (0000180a-0000-1000-8000-00805f9b34fb)
	System ID (00002a23-0000-1000-8000-00805f9b34fb)
	Model Number String (00002a24-0000-1000-8000-00805f9b34fb)
	Serial Number String (00002a25-0000-1000-8000-00805f9b34fb)
	Firmware Revision String (00002a26-0000-1000-8000-00805f9b34fb)
	Hardware Revision String (00002a27-0000-1000-8000-00805f9b34fb)
	Software Revision String (00002a28-0000-1000-8000-00805f9b34fb)
	Manufacturer Name String (00002a29-0000-1000-8000-00805f9b34fb)
	IEEE 11073-20601 Regulatory (00002a2a-0000-1000-8000-00805f9b34fb)
	PNPID (00002a50-0000-1000-8000-00805f9b34fb)


Unknown service (0000fff0-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff1-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff2-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff3-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff4-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff5-0000-1000-8000-00805f9b34fb)


Unknown service (f000ffc0-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc1-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc2-0451-4000-b000-000000000000)


-------------------------
[2Bluetooth LE Device GATT Results (Battery Monitor, 78_04_73_09_15_7C).txt](https://github.com/custom-components/ble_monitor/files/9066174/2Bluetooth.LE.Device.GATT.Results.Battery.Monitor.78_04_73_09_15_7C.txt)
-

**Comment by Next9999** [comment]
Create a new Case with all the data
