### ISSUE TITLE
BM2 Battery Monitor

### ISSUE THREAD

**Issue by Next9999** [custom-components/ble_monitor#935]
### Sensor Description

BM2 Battery Monitor

### Additional information

Used to monitor 12v battery, example car, motorhome

https://www.amazon.ca/QUICKLYNKS-Battery-Monitor-Bluetooth-Device/dp/B01MT4583U?th=1

[2Bluetooth LE Device GATT Results (Battery Monitor, 78_04_73_09_15_7C).txt](https://github.com/custom-components/ble_monitor/files/9067343/2Bluetooth.LE.Device.GATT.Results.Battery.Monitor.78_04_73_09_15_7C.txt)
[Bluetooth LE Device GATT Results (Battery Monitor, 44_EA_D8_31_07_AF).txt](https://github.com/custom-components/ble_monitor/files/9067344/Bluetooth.LE.Device.GATT.Results.Battery.Monitor.44_EA_D8_31_07_AF.txt)

### BLE advertisements

```shell
Device Name: Battery Monitor
Device Address: 44:EA:D8:31:07:AF

Services:--------------------------
GAP (00001800-0000-1000-8000-00805f9b34fb)
	Device Name (00002a00-0000-1000-8000-00805f9b34fb)
	Appearance (00002a01-0000-1000-8000-00805f9b34fb)
	Peripheral Privacy Flag (00002a02-0000-1000-8000-00805f9b34fb)
	Reconnection Address (00002a03-0000-1000-8000-00805f9b34fb)
	Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)
	Service Changed (00002a05-0000-1000-8000-00805f9b34fb)


Device Information (0000180a-0000-1000-8000-00805f9b34fb)
	System ID (00002a23-0000-1000-8000-00805f9b34fb)
	Model Number String (00002a24-0000-1000-8000-00805f9b34fb)
	Serial Number String (00002a25-0000-1000-8000-00805f9b34fb)
	Firmware Revision String (00002a26-0000-1000-8000-00805f9b34fb)
	Hardware Revision String (00002a27-0000-1000-8000-00805f9b34fb)
	Software Revision String (00002a28-0000-1000-8000-00805f9b34fb)
	Manufacturer Name String (00002a29-0000-1000-8000-00805f9b34fb)
	IEEE 11073-20601 Regulatory (00002a2a-0000-1000-8000-00805f9b34fb)
	PNPID (00002a50-0000-1000-8000-00805f9b34fb)


Unknown service (0000fff0-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff1-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff2-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff3-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff4-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff5-0000-1000-8000-00805f9b34fb)


Unknown service (f000ffc0-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc1-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc2-0451-4000-b000-000000000000)


--------------------------
Device Name: Battery Monitor
Device Address: 78:04:73:09:15:7C

Services:--------------------------
GAP (00001800-0000-1000-8000-00805f9b34fb)
	Device Name (00002a00-0000-1000-8000-00805f9b34fb)
	Appearance (00002a01-0000-1000-8000-00805f9b34fb)
	Peripheral Privacy Flag (00002a02-0000-1000-8000-00805f9b34fb)
	Reconnection Address (00002a03-0000-1000-8000-00805f9b34fb)
	Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)
	Service Changed (00002a05-0000-1000-8000-00805f9b34fb)


Device Information (0000180a-0000-1000-8000-00805f9b34fb)
	System ID (00002a23-0000-1000-8000-00805f9b34fb)
	Model Number String (00002a24-0000-1000-8000-00805f9b34fb)
	Serial Number String (00002a25-0000-1000-8000-00805f9b34fb)
	Firmware Revision String (00002a26-0000-1000-8000-00805f9b34fb)
	Hardware Revision String (00002a27-0000-1000-8000-00805f9b34fb)
	Software Revision String (00002a28-0000-1000-8000-00805f9b34fb)
	Manufacturer Name String (00002a29-0000-1000-8000-00805f9b34fb)
	IEEE 11073-20601 Regulatory (00002a2a-0000-1000-8000-00805f9b34fb)
	PNPID (00002a50-0000-1000-8000-00805f9b34fb)


Unknown service (0000fff0-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff1-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff2-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff3-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff4-0000-1000-8000-00805f9b34fb)
	Unknown characteristic (0000fff5-0000-1000-8000-00805f9b34fb)


Unknown service (f000ffc0-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc1-0451-4000-b000-000000000000)
	Unknown characteristic (f000ffc2-0451-4000-b000-000000000000)


--------------------------
```

**Comment by Ernst79** [comment]
Sorry, I didn't got back to this issue sooner. Unfortunately, the provided information isn't what I need, I need the RAW ble advertisement or the service data. 

Is it possible to get the BLE advertisement data from the HA logs or with a HCIdump?

For instructions, check https://custom-components.github.io/ble_monitor/sensor_request

**Comment by Next9999** [comment]
it is this?

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/UTILIS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/UTILIS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



mac | name | firstTimestamp | firstRssi | currentTimestamp | currentRssi | adRecord | iBeacon | uuid | major | minor | txPower | distance | accuracy
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
44:EA:D8:31:07:AF | Battery Monitor | 2022-07-20T13:11:32.125 UTC | -81 | 2022-07-20T13:11:32.125 UTC | -81 | [02, 01, 06, 1A, FF, 4C, 00, 02, 15, 65, 5F, 83, CA, AE, 16, A1, 0A, 70,   2E, 31, F3, 0D, 58, DD, 82, F6, 44, 52, C1, 64, 10, 09, 42, 61, 74, 74, 65,   72, 79, 20, 4D, 6F, 6E, 69, 74, 6F, 72, 05, 12, 0A, 00, 19, 00, 02, 0A, 00,   00, 00, 00, 00, 00, 00] | TRUE | 655f83ca-ae16-a10a-702e-31f30d58dd82 | 21185 | 63044 | 100 | immediate | 0.121576655
78:04:73:09:15:7C | Battery Monitor | 2022-07-20T13:11:33.117 UTC | -95 | 2022-07-20T13:11:55.993 UTC | -93 | [02, 01, 06, 03, 02, F0, FF, 11, FF, 70, 11, B7, 72, 1B, 06, DA, C3, FA,   0E, E4, FB, 17, 8A, 3A, DB, 10, 09, 42, 61, 74, 74, 65, 72, 79, 20, 4D, 6F,   6E, 69, 74, 6F, 72, 05, 12, 0A, 00, 19, 00, 02, 0A, 00, 00, 00, 00, 00, 00,   00, 00, 00, 00, 00, 00] | FALSE |   |   |   |   |   |  



</body>

</html>
[Book1.xlsx](https://github.com/custom-components/ble_monitor/files/9158889/Book1.xlsx)

**Comment by Ernst79** [comment]
Yes, I need the adRecord. I will have a look at the data

**Comment by Next9999** [comment]
This may also help

https://github.com/KrystianD/bm2-battery-monitor

**Comment by Ernst79** [comment]
I first checked the messages, the first one is sending a iBeacon message, as you already indicated. 

```
result  ({'type': 'iBeacon', 'packet': 'no packet id', 'firmware': 'iBeacon', 'data': True, 'rssi': -43, 'mac': '00:1B:DC:4B:11:AD', 'uuid': '655f83caae16a10a702e31f30d58dd82', 'tracker_id': b'e_\x83\xca\xae\x16\xa1\np.1\xf3\rX\xdd\x82', 'major': -2492, 'minor': 21185, 'measured power': 100, 'cypress temperature': 85.62640625, 'cypress humidity': 34.0390625}, None)
```

The second one is more promising, 

```
man spec data:  11ff7011b7721b06dac3fa0ee4fb178a3adb
local name:  Battery Monitor
```

Next, I checked your link. They explain that you will have to read the characteristics. This means that you will have to send data to the device and ask for data. This is not supported in BLE monitor unfortunately. This also means that we can't add this device, I'm afraid.

**Comment by Next9999** [comment]
Okay tks for your great support
