### ISSUE TITLE
Xiaomi Humidity Temperature LYWSD03MMC unavailable after last update ha 2022.7.1

### ISSUE THREAD

**Issue by antoweb** [custom-components/ble_monitor#936]
### What happened?

After last update HA 2022.7.1 my sensors are unavailable
![image](https://user-images.githubusercontent.com/32364871/177948198-ca3fbc09-ca48-45ed-b629-c3018ecd8676.png)

### Sensor type

Xiaomi LYWSD03MMC

**Comment by Ernst79** [comment]
Is there anything in the logs? 
Are other sensors working ok?
Battery still ok?

**Comment by antoweb** [comment]
sorry it's my fault because i had put two exclusions in yaml and it disabled me the configuration from ui.  I had to re-enter all the bind keys.  but I ask how to exclude devices that I do not need from the ui?

**Comment by Ernst79** [comment]
You can only include devices in the ui. After you have all the devices you need, disable `discovery`. After that, restart HA. Next, go to the ble_monitor options and select the device that you don't want to see anymore (in the devices pull down menu at the bottom. click submit, select "delete device" and click submit again. This should delete the device and it should not be added again, as `discovery` is disabled.

**Comment by antoweb** [comment]
Disabling discovery means this?
![image](https://user-images.githubusercontent.com/32364871/177960447-b7253057-b236-451c-b1aa-e405dea8281f.png)

**Comment by Ernst79** [comment]
yes, correct

**Comment by antoweb** [comment]
Thank you
