### ISSUE TITLE
[New Sensor]: XMZNMST02YD add door to supported please!

### ISSUE THREAD

**Issue by snkku** [custom-components/ble_monitor#938]
### Sensor Description

door

### Additional information

just edited array of supported methods, added "door" and its work well with XMZNMST02YD

        "new_state": {
            "entity_id": "binary_sensor.ble_door_xxxxx",
            "state": "off",
            "attributes": {
                "sensor_type": "XMZNMST02YD",
                "mac_address": "XXXXXX",
                "last_packet_id": 167,
                "rssi": -73,
                "firmware": "Xiaomi (MiBeacon V5 encrypted)",
                "uuid": "XXXXXX",
                "door_action": "close the door",
                "device_class": "door",
                "friendly_name": "ble door XXXXXXX"
            }

please add it in your const.py

**Comment by Ernst79** [comment]
Will be included in the next release, when #937 is merged.
