### ISSUE TITLE
[Bug]: Problem adding new device

### ISSUE THREAD

**Issue by antoweb** [custom-components/ble_monitor#939]
### What happened?

After added a new device via UI this is not added and appear in list with ":" the others doenst have ":"
![image](https://user-images.githubusercontent.com/32364871/177978848-0d18da54-3a81-4125-815f-21f9e3aae658.png)
4 devise

in integration page only 3 device
![image](https://user-images.githubusercontent.com/32364871/177978979-e05d72e7-6a27-4d0c-b108-e92fb8209152.png)

**Comment by Ernst79** [comment]
the sensor is only added to Home Assistant after it receives its first two BLE message. The reason is that it needs to know what kind of sensor it is, before it can create the sensor entities. Please wait at least 30 minutes for LYWSD03MMC sensors, as it only sends 1 message per 10 minutes. Just be patient.

**Comment by Ernst79** [comment]
The restore state in the first configuration window is the "global setting" for all devices. 

When you (de)select it in the **device** configuration UI, it will overwrite the global setting for that specific MAC address.

**Comment by antoweb** [comment]
So if a leave unchecked in that specifi MAC address but checked in global setting, the result is checked or not?

**Comment by Ernst79** [comment]
Looks like you have an old version. 

![image](https://user-images.githubusercontent.com/24375847/177993103-88180eb2-559a-4bce-8563-3dda9a8d839c.png)

On my system, I have three options, `default` means that it will use the global setting, `true/false` will overwrite the global setting. 

If you select true on global settings and false on device level, it will be turned off (not checked).

**Comment by antoweb** [comment]
Ok thank you
