### ISSUE TITLE
[Bug]: Deprecated async_get_registry

### ISSUE THREAD

**Issue by Szeryff** [custom-components/ble_monitor#940]
### What happened?

Hi,
with the latest core 2022.6.x update, I received this error. Can you update this registry change?
thank you
`Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for ble_monitor using this method at custom_components/ble_monitor/device_tracker.py, line 117: dev_registry = await device_registry.async_get_registry(hass)`

### Sensor type

ble_monitor

**Comment by Ernst79** [comment]
Ah, I missed that one. Will fix it

**Comment by Ernst79** [comment]
This is already fixed since 8.7.0. Please check for updates of ble monitor. I think you have an old version.
