### ISSUE TITLE
[Bug]: Cannot connect after a reboot system

### ISSUE THREAD

**Issue by Next9999** [custom-components/ble_monitor#941]
### What happened?

This error originated from a custom integration.

Logger: custom_components.elkbledom.elkbledom
Source: custom_components/elkbledom/elkbledom.py:196
Integration: Elkbledom (documentation, issues)
First occurred: 08:28:39 (19 occurrences)
Last logged: 08:39:57

Error getting status: [org.bluez.Error.Failed] Software caused connection abort
Error getting status: Device with address BE:FF:30:02:0C:D6 could not be found. Try increasing `timeout` value or moving the device closer.
Error getting status: [Errno 32] Broken pipe

### Sensor type

Elkbledom

### Relevant log output

```shell
This error originated from a custom integration.

Logger: custom_components.elkbledom.elkbledom
Source: custom_components/elkbledom/elkbledom.py:196
Integration: Elkbledom (documentation, issues)
First occurred: 08:28:39 (19 occurrences)
Last logged: 08:39:57

Error getting status: [org.bluez.Error.Failed] Software caused connection abort
Error getting status: Device with address BE:FF:30:02:0C:D6 could not be found. Try increasing `timeout` value or moving the device closer.
Error getting status: [Errno 32] Broken pipe
```

**Comment by Ernst79** [comment]
This error is not from BLE monitor, but from elkbledom. Please report the bug in that repository, not here. 

Btw, this error is probably related to the removal of pybluez in HA 2022.7
