### ISSUE TITLE
[Bug]: Deleting devices does not work

### ISSUE THREAD

**Issue by dingausmwald** [custom-components/ble_monitor#948]
### What happened?

Last time we talked you integrated the complete delete function quite fast. Well, it does not work anymore with newest integration and HA core. I already posted a bug in HA because renaming devices/entities is kind of broken too. Maybe this is related.

**Comment by Ernst79** [comment]
Can you give the steps you took to delete a device. I don't see the issue on my end.

**Comment by bencollinz** [comment]
I have a similar issue. I tell it NOT to "Discover devices and sensors automatically" and at the end of every day I have about 12 ibeacon devices added. I delete them, they come right back. Everything is updated. I only have one bluetooth temp connected through this add-on that is being used. I've rebooted numerous times. Removed, readded addon numerous times.

**Comment by Ernst79** [comment]
Sorry, I didn’t respond to you. I hope this issue is solved. If not, please open a new issue or reopen this one, and I’ll try to help you find out what is wrong.
