### ISSUE TITLE
[Bug]: No Bluetooth Interface/Adapter Available to Select

### ISSUE THREAD

**Issue by ItsJamesMurray** [custom-components/ble_monitor#957]
### What happened?

I have Home Assistant (Container) running on a Raspberry Pi 4.  I have both the built in bluetooth adapter AND an external bluetooth via USB port.

After installing via HACs and setting up the integration I am unable to select either of my bluetooths in the config window.  It is all blank and the "Don't use Bluetooth adapter" option is selected by default.  I have SSHed into the Raspberry Pi and ran `bluetoothctl list` I receive the following output:
```
Controller 00:19:86:00:1A:AE raspberrypi #2 [default]
Controller E4:5F:01:A0:78:DB raspberrypi 
```
so I know that both are working "properly".  Any thoughts on how to setup the add on?

**Comment by Ernst79** [comment]
Is the Bluetooth adapter also accessible from within the container, by the command line? I remember that you have to make the Bluetooth adapters available to the docker environment

**Comment by ItsJamesMurray** [comment]
Inside my docker container, when I run `lsusb` I get a list of all the USBs connected to my Raspberry Pi. That means it should be accessible, no?

**Comment by Ernst79** [comment]
Not necessarily I think. Do you see the Bluetooth adapter. Can you run commands like hcidump from the command line inside your docker environment

**Comment by ItsJamesMurray** [comment]
Ahhh... that is not working.  I get `Can't open HCI socket.: Address family not supported by protocol`.  Attempting a few of the top search results yielded no luck.

Any idea how I can get it working?  Even the built in bluetooth adapter is not working — so would that mean that this component would not work when running docker in bridge mode?

**Comment by Ernst79** [comment]
Not sure how, I don’t have docker, but it is possible, try googling for “ docker use host bluetooth”

**Comment by mb-software** [comment]
Hi, I have the same problem. I am using Homeassistant in Docker and an external BLE dongle. BUT: It has been working without any problem until I updated the ble_monitor integration yesterday. Nothing else has been changed in my system. So I believe there is a problem with one of the most recent updates of ble_monitor.

**Comment by Ernst79** [comment]
There hasnt been any changes on the Bluetooth end lately, so I dont know what happened in your case. Can you access Bluetooth from the command line in the decker environment ?

**Comment by Ernst79** [comment]
Also note that HA will start support Bluetooth in the next release, including some core passive Bluetooth integrations, like xiaomi, govee, and some more. This should improve Bluetooth support, as they use a different backend (bleak)

**Comment by ItsJamesMurray** [comment]
Hi @Ernst79  —  I got it setup using the native Bluetooth integration in the new release.  I'm going to close this issue now.
