### ISSUE TITLE
[New Sensor]: Thermopro TP357

### ISSUE THREAD

**Issue by capo-at-the-5th-fret** [custom-components/ble_monitor#961]
### Sensor Description

Indoor Hygrometer Thermometer

### Additional information

https://buythermopro.com/product/thermopro-tp357-bluetooth-digital-indoor-hygrometer-thermometer/

The advertisements occur every 2/3 seconds, yet the readings/screen only update every 30 seconds. Nothing I can see in the app allows you to change the refresh rate. Only the 3 bytes near the end of the message were changing.

545033353720283241303129 = "TP357 (2A01)" is the sensor name that appears in the thermopro app (2A01 = last two bytes of mac address)

16 bits for temp * 10 in the 4th last column
8 bits for humidity in the 3rd last column

I'll run a scan again in a couple weeks to see if I can detect a battery level change.

### BLE advertisements

```shell
Mac: 48:7e:48:98:2a:01

[ 27.9C / 39% ]
043e 25 02010000 012a98487e48 19 0d 09 545033353720283241303129 02 0105 07 ffc2 1701 27 022c bc

[ 32.2C / 86% ]
043e 25 02010000 012a98487e48 19 0d 09 545033353720283241303129 02 0105 07 ffc2 4201 56 022c b4

[ 29.5C / 87% ]
043e 25 02010000 012a98487e48 19 0d 09 545033353720283241303129 02 0105 07 ffc2 2701 57 022c ba

[ 28.9C / 88% ]
043e 25 02010000 012a98487e48 19 0d 09 545033353720283241303129 02 0105 07 ffc2 2101 58 022c bc

```

**Comment by Ernst79** [comment]
Thanks, I wish all people make such sensor requests. Normally I only get a brandname and type and a link to amazon and "good luck" 😄 

As a matter of fact, this one was as easy as adding the name TP357 to TP359, they use the same format.

**Comment by Ernst79** [comment]
Added in 9.0.4

**Comment by si458** [comment]
Thank you for this integration, much better than the built in one with HA 2024, can you possibly detect its battery life at all?
What do you need from me to add this?
Any docs you can provide so I can give u data from the device?

**Comment by Ernst79** [comment]
Just enable debug logging for BLE monitor for your sensor and post some logs here, together with the battery state. Please open a new issue for that
