### ISSUE TITLE
BLE dongle not found with Home Assistant 2022.7.x

### ISSUE THREAD

**Issue by lecrams** [custom-components/ble_monitor#971]
Hi, Since the last version of HA my Bluetooth LE dongle is seen but not used anymore so I can track my BLE devices anymore.
In the configuration UI the mac address (hci0) is displayed however the checkbox in front is empty. Checking it is not saved when I dismiss the UI.
Loggings wrt to Bluetooth are not reported (with "custom_components.ble_monitor: info" in my configuration).

Any idea what can be wrong?

**Comment by Ernst79** [comment]
Did you try a full system restart? Not only HA, but restart the entire system.

**Comment by Ernst79** [comment]
Closing this issue due to not activity. Feel free to reopen.
