### ISSUE TITLE
[New Sensor]: ZNMS17LM Add armed away lock aka Guard Mode (obj0008) 

### ISSUE THREAD

**Issue by dvdng** [custom-components/ble_monitor#973]
### Sensor Description

I have realized there is an addition of obj0008 (armed away) in the xiaomi.py file. Wanted to request if possible to add this object to the ZNMS17LM (Aqara N200 Door Lock). As this is the Guard Mode button for the N200. I have tested it by putting it as a lock device class in const.py and it works as intended.  

    BLEMonitorBinarySensorEntityDescription(
        key="armed away",
        sensor_class="BaseBinarySensor",
        update_behavior="Instantly",
        name="ble Armed Away",
        unique_id="armedaway_",
        device_class=BinarySensorDeviceClass.LOCK,
        force_update=True,
    ),    

    'ZNMS17LM'                : [["battery", "rssi"], [], ["lock", "door", "fingerprint", "antilock", "childlock", "armed away"]],

### Additional information

e.g. a link to product details, etc.

**Comment by Ernst79** [comment]
Yes, I will have a look and add it, but it can take a while due to holidays.

**Comment by borky** [comment]
Hi, can you please add this to the ZNMS16LM? i just tested it and works also on this lock. Thanks!

**Comment by Ernst79** [comment]
Yep, will do that

**Comment by Ernst79** [comment]
Done, in 9.1.1

**Comment by borky** [comment]
> Done, in 9.1.1

thanks:)

**Comment by dvdng** [comment]
Thank you!
