### ISSUE TITLE
[Bug]: Created configuration without scanning

### ISSUE THREAD

**Issue by lokaelmo** [custom-components/ble_monitor#975]
### What happened?

The integration used to work well, it automatically adds devices 
when I deleted and integrated again, now it says: Options successfully saved.
without scanning or showing my devices

### Relevant log output

```shell
This error originated from a custom integration.

Logger: custom_components.ble_monitor.bt_helpers
Source: custom_components/ble_monitor/bt_helpers.py:43
Integration: Passive BLE monitor (documentation, issues)
First occurred: 12:33:33 AM (1 occurrences)
Last logged: 12:33:33 AM

There are no BT controllers present in the system!
```

**Comment by Ernst79** [comment]
The log says that it cant find the Bluetooth dongle/adapter. Can you check that it can be found by HA. Also try a full system restart (not only HA, the entire system)

**Comment by Ernst79** [comment]
Did you solve the issue? If so, please close the issue.
