### ISSUE TITLE
Beta version 7.1 incompatibility with HA 0.113 

### ISSUE THREAD

**Issue by boesing** [custom-components/ble_monitor#98]
Hey there,

I am using this amazing custom-component but my `homeassistant-core` with v0.113 does not properly start up when this is within the `custom_components/` directory.

I am not sure if this is due to the fact that this sensor is overwriting the original one from homeassistant.

Would love if this will be investigated.

Thanks in advance.

**Comment by Ernst79** [comment]
Do you have any errors in your logs? Please enabled debug logging to help you further.

**Comment by boesing** [comment]
I'll provide these this weekend, currently rolled back to 0.112.4

After installing pip packages, home assistant does not finish starting up. 
It stays in startup mode and stops after 10 minutes or so due to some timeout.

**Comment by Ernst79** [comment]
Ok, let us know.

**Comment by shirou93** [comment]
When i updated to 0.113 ha stops update sensors. When i reboot device sensor Has unavaible.

**Comment by Ernst79** [comment]
Did you wait several minutes to see if the sensor comes back available? Please try to move it closer to see if you have connection issues

**Comment by Ernst79** [comment]
Does home assistant start up now without issues?

**Comment by arecdudek** [comment]
I have also a problem with thermometers. Addon see one of them but all states are unavailable.

**Comment by shirou93** [comment]
On logs no errors. Sensors is unavaible.

**Comment by snakuzzo** [comment]
Same here...no error on log (debug level)...
Consider that this problem is present on other custom components after 0.113 update.

This is the issue on ha project...
https://github.com/home-assistant/core/issues/38088#issuecomment-663786440

**Comment by Ernst79** [comment]
Strange thing is that I don’t have this issue. I’m running a supervised home assistant installation. How did you install HA?

**Comment by Ernst79** [comment]
If I understand correctly, 0.113.1 has now additional logging which component fails. Can you try again? Does is say that mitemp_bt is the problem?

**Comment by snakuzzo** [comment]
Nothing in logs. If you check my latest post on the HA issue...I explained that...
If I remove minitemp_bt from custom_components dir ... ha starts and value templates work
If I put minjtemp_bt in custom_components dir ... ha doesn't start (ha start event not happened) and value templates are not values.

**Comment by shirou93** [comment]
On Hassio i try reinstall integration on community. After restart ha show all time "home assistant startup..."
Ha startup info disappear when enter "ha core restart" in console.

Integration still not work.

Strange becasue value templates works for me.

**Comment by boesing** [comment]
I am on HassOS 4.11 with supervisor 229.

Will try 0.113.1 tomorrow. 👍🏻

**Comment by shirou93** [comment]
> I am on HassOS 4.11 with supervisor 229.
> 
> Will try 0.113.1 tomorrow. 👍🏻

0.113.1 same issues :/

**Comment by maxcanna** [comment]
I can confirm the issue using the latest beta version in HA core 0.113.1 running in docker

**Comment by Ernst79** [comment]
Hmm, very strange. Problem is that my installation works fine, so I don’t know where to start looking. Perhaps @Magalex2x14 has an idea, but I don’t know when he has time to look into this.

I see people with HA core and people with home assistant (hassOs), so it does not seem limited to one type of installation. Personally, I have a supervised installation on RasberryOs (previously known as raspbian)., which works fine.

One way to find out what is wrong is to manually add several debug messages in the code, to see where it fails. But this should be done by someone with a failing component.

**Comment by aqualx** [comment]
Maybe coinsedence, but I wasn't able upgrade HA to 0.113/0.113.1 untill disable sensor.mitemp_bt. Used latest beta of sensor.mitemp_bt untill upgrade. After upgrade installed stable version 0.6.10 and no problems so far.
So probably issue is with 0.7.1-beta...

**Comment by boesing** [comment]
I am on the beta aswell as I had issues with the Stäbe Version (it stopped updating my sensors). 

So probably just an issue with the 0.7.1 beta.

**Comment by Ernst79** [comment]
@boesing Can you confirm that it works with the latest stable version?

**Comment by Xitro01** [comment]
> @boesing Can you confirm that it works with the latest stable version?

Had the same issue, sensors update now, but seems to be quite slow after a restart before they show up. But it works for now, need to give it 10+ hours.

**Comment by timaseth** [comment]
Hi All! I can confirm the following:
I was on the Beta version of our app reason being that after the last change, I was not gerting readings from any of my 4 sensors).
This beta version has troubled me a lot with the latest HA update - HA kept automatocally rolling back to 112.4

So, I updated to v6.10 of our app, and after a restart of HA, updated to 113.1 - All good now!
Cherry on the cake, all sensors are working well too :-)

**Comment by Ernst79** [comment]
Good to hear. So to conclude stable versions 6.9 and 6.10 had some small changes that fixed that you didn’t get readings and works fine with home assistant 0.113. Beta version 7.1 has more significant changes, which seems not to work correctly with the latest home assistant 0.113. We will look into that, but for now, please use 6.10 stable version. I will add a warning for now.

**Comment by boesing** [comment]
Yes, can confirm that this is a beta issue as stable version does not block HA from starting up. 👍🏻

**Comment by xvolte** [comment]
Hello
Got same issue with the beta. Is it resolved yet?
