### ISSUE TITLE
about ble_monitor.parse_data

### ISSUE THREAD

**Issue by 50494554524F** [custom-components/ble_monitor#980]
i'm playing with ble_monitor advanced features, but i can't have ble_monitor.parse_data working...

i'm in developer tools > services, i fill the packet field (packet comes from esphome) but the sensor doesn't update

how it is supposed to work?! is there any output somewhere?!

thanks

**Comment by Ernst79** [comment]
If you send the same ble data every time, it probably wont update as e.g xiaomi ble data have a counter. If the counter is not changed, it assumes that the data is still the same (by definition). So, you will have to change the counter on the ble data to make it update.

**Comment by Ernst79** [comment]
Check this page to find out where the counter (called frame count) is located in Xiaomi data.

https://custom-components.github.io/ble_monitor/MiBeacon_protocol

**Comment by 50494554524F** [comment]
to be more precise... i'm using blegateway on esphome, i copy the packets live from the esphome log and then paste into homeassistant developer tools... nothing happens for the sensors

parse_date seems called reading the logs (debug mode) but i can't see the sensors updated

thanks

**Comment by 50494554524F** [comment]
ok, updated ble_monitor to latest version, deleted all the entities, restarted, entities are back... works now... sorry, the 3d can be deleted
