### ISSUE TITLE
[Bug]: feasycom ble beacon

### ISSUE THREAD

**Issue by RogerSero** [custom-components/ble_monitor#981]
### What happened?

hello, I have two feasycom ble beacons working with passive ble.  When everything is migrated to bluetooth from home assistant, will they continue to work for me or will there be any way for me to recognize them?

**Comment by Ernst79** [comment]
Sure, we will move everything. I assume it is recognized as an iBeacon. We will make device tracking and beacons available in a future release of HA. Device tracking based on mac address is already available, but iBeacons use the uuid.

**Comment by RogerSero** [comment]
The ones I use, feasycom, with only the mac address, recognizes them and tracks them.

**Comment by Ernst79** [comment]
I thought they had updated Bluetooth LE integration https://www.home-assistant.io/integrations/bluetooth_le_tracker/ to use the new Bluetooth integration (based on bleak) but the documentation looks to be somewhat outdated, so, not sure. But normally, i would say that you can use that integration.

**Comment by Ernst79** [comment]
Please close this issue if you managed to get it working

**Comment by RogerSero** [comment]
another problem I have is that when I restart home assistant the sensors remain unknown, they do not return to the state before the restart, and that I have activated the option to restore the state before the restart

**Comment by Ernst79** [comment]
How did you configure BLE monitor, in YAML or in the User Interface? It sometimes helps to open the BLE monitor options and make a change, save it and change it back.

**Comment by RogerSero** [comment]
I did it through the user interface, and checked the option to restore state after reboot in all the ibeacon that I link, but it does not do it for me.

**Comment by Ernst79** [comment]
Ill try to reproduce the issue when I'm back home

**Comment by Ernst79** [comment]
Restore state issues can be discussed further here #794 Closing this issue.
