### ISSUE TITLE
about ble_monitor going official in home assistant

### ISSUE THREAD

**Issue by 50494554524F** [custom-components/ble_monitor#983]
these changes is a great award for you but could be heavy for us hobbyist  :D

so i have a couple of questions for you, if you already know something about that...

- will we have to rewrite the code?! putting back all the devices/entities?! etc... (every month something new interesting in ha but i have to check all the compatibility again)

- will we be able to add devices modules by our own?! (my next step would be to learn how to add a device to ble_monitor)

- what about great companion like pvvx firmware or ble_gateway?!

thanks

**Comment by Ernst79** [comment]
1. Yes, if you install one of the new integrations, you will have to modify your automations, if you use these. Also your lovelace has to be updated with the new entities.
2. What do you mean by adding on your own? If you have a new device, that is not supported yet, open an issue on github of Home Assistant, or here. I will take care that new devices that are reported here will also be added to the new HA integrations  once they are available. Or is this not your question?
3. Pvvx fi support will be moved to a new official HA integration, like all other sensors. This will however take some time. Also out own HA BLE format will be moved to HA, the devs already have plans for it to improve it. But this all takes time.

**Comment by 50494554524F** [comment]
2. you answered my question... my doubt was about new devices on the market that i could like but not interests to add them in ha
