### ISSUE TITLE
[Bug]: LYWSDCGQ works only with this integration

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/ble_monitor#984]
### What happened?

LYWSDCGQ by Xiaomi works so well in this integration. but with HA's new bluetooth is doesn't update or only updates once and never updates again

### Sensor type

LYWSDCGQ by Xiaomi

**Comment by Ernst79** [comment]
Try to enable active scan in BLE monitor. The new HA integration uses this, so ble monitor should as well, as the BT dongle can only operate in one scanning mode

**Comment by oneseventhree** [comment]
> Try to enable active scan in BLE monitor. The new HA integration uses this, so ble monitor should as well, as the BT dongle can only operate in one scanning mode

I completely deleted this integration on HACS and only had the HA version and my sensors either showed up as unavailable or showed the first reading of the temp and humidity and never worked again (up to 3 days). 

I then went back and installed BLE monitor and it works great. 

Any tips to get the HA version working the same as BLE  monitor?

**Comment by Ernst79** [comment]
My advice, make an issue on the Home Assistant github, with the debug logs enabled. Also try a system restart to force the Bluetooth adapter into the active scanning mode

**Comment by oneseventhree** [comment]
> My advice, make an issue on the Home Assistant github, with some logs ( with the debug logs enabled). Also try a system restart to force the Bluetooth adapter into the active scanning mode

thanks - I've done it here: 
https://github.com/home-assistant/core/issues/76539#issuecomment-1209997303

Hopefully they can get it working as well as BLE Monitor

**Comment by Ernst79** [comment]
Ill close the issue here, ad the issue seems to be in the xiaomi ble integration.
