### ISSUE TITLE
[New Sensor]: Polar ECG/PPH/HEART RATE/RR INTERAL

### ISSUE THREAD

**Issue by ponvthc** [custom-components/ble_monitor#985]
### Sensor Description

Polar H10/OH1

### Additional information

https://github.com/polarofficial/polar-ble-sdk/blob/6a967212b116fc4cd4edc567026d3206b12f7ff1/technical_documentation/Polar_Measurement_Data_Specification.pdf

I would like to integrate the Polar H10 (strap ECG monitor) and OH1 (wrist based plethysmographic pulse monitor) into BLE monitor / Home Assistant. The BLE specification for these devices is above.

I have tried to capture data using the logger as described, but have not been successful. This is the output from a bluetooth scanning utility on my mac.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/61214383/183472032-1a06dae6-b259-421c-9159-bb82417a6daa.png">

**Comment by ponvthc** [comment]
Managed to get a little more info:

2022-08-08 09:43:12.953 INFO (Thread-9) [custom_components.ble_monitor.ble_parser] Unknown advertisement received for mac: F6:4D:73:53:49:6Eservice data: []manufacturer specific data: [b'\x07\xffk\x003\x00\x008']local name: Polar H10 9F6E5322UUID16: None,UUID128: None

**Comment by Ernst79** [comment]
I will have a look in a couple of days.

**Comment by Ernst79** [comment]
I had some time to look at the manufacture specific data

in hex, this is `07ff6b0033000038`

`07` = length
`ff` = manufacturer specific data
`6b00` = company id
`33000038` = data

Next, I followed the link you gave, but they talk about GATT. GATT is telling us that you need to set up a connection to read the characteristics. This is not possible with BLE monitor, as we only passively listen to data, not reading after setting up a connection. You can try e.g. with ESPHome BLE client to make a connection and read the characteristics. 

The above message is most likely just a message to say that it is online and needs a connection to further communicate. Unfortunately, this means that the device can't be added to BLE monitor
