### ISSUE TITLE
Ble_monitor native to Home Assistant using remote esp devices for bluetooth sensors

### ISSUE THREAD

**Issue by 74jtheriault** [custom-components/ble_monitor#986]
I currently use ble_monitor with several esp32s as remote bluetooth sensors for both govee ans xiaomi temp sensors.  Will this still work with this update?

**Comment by Ernst79** [comment]
Not yet, the HA devs will implement some replacement for ESPhome BLE gateway in the future. Dont know if it will make it to 2022.9, but it is coming.

**Comment by Ernst79** [comment]
Im closing this issue here, as it is something that has to be added in HA, not in BLE monitor.
