### ISSUE TITLE
[Bug]: HA BLE DIY format - not work two counters

### ISSUE THREAD

**Issue by slacky1965** [custom-components/ble_monitor#987]
### What happened?

Hello.

My advertsing payload

`0x02010615161C180200010201640509BE0000000509C8000100`

`0x020106` - LE only
`0x15` - size
`0x16` - 16-bit UUID
`0x1C18` - GAT service User Data
`0x020001` - incrementable Packet ID
`0x020164` - battery level
`0x0509BE000000` - first 32-bit counter
`0x0509C8000100` - second 32-bit counter

BLE Monitor finds 1 device and 3 entities.
1 entity - battery level
2 entity - last counter
3 entity - RSSI

How can I get two counters?

Thanks.

### Sensor type

HA BLE DIY format

**Comment by Ernst79** [comment]
Currently it is not possible to have two measurements of the same type. Its on the todo list, but might be that we add it when we move to a core HA integration.

**Comment by slacky1965** [comment]
It seems obvious to me. Hot water, cold water.

**Comment by Ernst79** [comment]
Yes, it is, but the code on the HA sensor side isnt easy adjustable to create multiple sensors of the same type. It requires some significant changes in the code. 

But multiple sensor support of the same type is on the planning, when we move HA BLE to a new official integration. In the meantime, I would use another measurement type as a dummy for the second counter

**Comment by slacky1965** [comment]
Which for example, if the counter has 32 bits?

**Comment by Ernst79** [comment]
Doesnt matter which one, the number of bits is flexibel. Just pick one with a factor of 1 (not a binary sensor of course) and create a template sensor in HA to remove the unit of measurement

**Comment by slacky1965** [comment]
Thanks.

**Comment by Ernst79** [comment]
For now, Im closing this issue, as it is a duplicaten of #854
