### ISSUE TITLE
[Bug]: Inkbird IBS-TH1 external probe

### ISSUE THREAD

**Issue by iivana** [custom-components/ble_monitor#989]
### What happened?

External probe temperature sensor is not available in HA.

In documentation you write "Notes:The BLE advertisements does contain three extra bytes. It is unknown what these bytes represent at the moment, possibly used for an extra probe of the plus versions. If you have such a device, please let us know, such that we can create support for the extra probe." https://custom-components.github.io/ble_monitor/by_brand#inkbird

So I can help on this. What should I do for you?

### Sensor type

Inkbird IBS-TH1 external probe

**Comment by iivana** [comment]
Logging has been running about an hour. 

No "BLE ADV from UNKNOWN" messages yet, only a lot of following lines:
2022-08-15 20:36:35.769 INFO (Thread-100) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 64694e9d13ce: service data: []manufacturer specific data: []local name: UUID16: 61695,UUID128: None

One line likes this: 
2022-08-15 20:39:47.726 INFO (Thread-100) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 64694e9d13ce: service data: []manufacturer specific data: [b'\n\xff;\n\xf8\x15\x01\x8c\xbcd\x08']local name: spsUUID16: None,UUID128: None

At Inkbird mobile app (called "Engbird") I can only see one temperature info at the time, with mark "external" when external probe is connected. It seems that connecting external probe disconnects (stops broadcasting of) internal temperature. I found also this info (https://github.com/sputnikdev/eclipse-smarthome-bluetooth-binding/issues/60) , where it says that extra 3 bytes are:
- 5 byte is "which temperature sensor is in used":
     00 - Internal Probe
     01 - External Probe 
- 6-7 bytes is crc16 (modbus).

I let the extra logging run over night.

**Comment by Ernst79** [comment]
so, in the message above, this is, after conversion from bytes to hex `0aff3b0af815018cbc6408`

temperature = `3b0a` = 2619 = 26.19°C
humidity = `f815` = 5624 = 56.24%
probe = `01` = external probe
`crc16` = `8cbc`
battery = `64 = 100%

So, this should be the external sensor

**Comment by iivana** [comment]
yes, confirm external.

**Comment by Ernst79** [comment]
Ok, I’ll add the external sensor asap.

**Comment by iivana** [comment]
Perfect. Note that external sensor is only for temperature. Humidity is always the same internal sensor. So "probe"-byte is about temperature sensor.

**Comment by Ernst79** [comment]
Added in 9.2.0
