### ISSUE TITLE
[New Sensor]:  BLE integration for INode senzors

### ISSUE THREAD

**Issue by GamerClassN7** [custom-components/ble_monitor#994]
### Sensor Description

BLE integration for INode senzors

### Additional information

[e.g. a link to product details, etc.](https://botland.cz/inode-android-bluetooth-senzory-a-moduly/9929-inode-energy-meter-monitor-spotreby-energie-fototranzistor-5904422376413.html)

**Comment by Ernst79** [comment]
Please post some ble advertisement data, such that we can add it. See the docs how.

https://custom-components.github.io/ble_monitor/sensor_request
