### ISSUE TITLE
about xiaomi window sensor 2

### ISSUE THREAD

**Issue by 50494554524F** [custom-components/ble_monitor#997]
reading the supported sensors list by ble_monitor i decided to purchase this sensor... a couple of questions, i couldn't find a solution in the manual

- is there a possibility to add a pairing pin?! or... is it sufficient pressing the button to enable the pairing process and prevent connections from other people!?
- is it possible to change the broadcasted name?!

can anyone clarify my doubts?!

thanks

**Comment by Ernst79** [comment]
You can't change the broadcasted name, but you can change the name in Home Assistant. 

the pairing pin can be set in the options of BLE monitor, Open the options and select the MAC address in the pull down menu "devices" at the bottom. Click submit and a new menu will open, where you can set the encryption key. 

Getting the encryption key from the device is explained in the FAQ
https://custom-components.github.io/ble_monitor/faq#how-to-get-the-mibeacon-v4v5-encryption-key

**Comment by 50494554524F** [comment]
i know about the encryption key, i'm talking about the pairing pin requested i.e. when i try to connect with a pc to a bt device... just to know if anyone around me could hijack the sensor

**Comment by gordio** [comment]
> i know about the encryption key, i'm talking about the pairing pin requested i.e. when i try to connect with a pc to a bt device... just to know if anyone around me could hijack the sensor

encryption key - is the pin, but very very long :)

**Comment by Ernst79** [comment]
I think this issue can be closed, if not, let me know by reopening it
